package junie

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

// `import junie` picks the legacy `.junie/rules` layout by existence, so
// an empty directory left behind by the sweep would hide current rules
// and agents from a later import.
func TestEmit_SweepRemovesALegacyRulesTreeWithNestedFolders(t *testing.T) {
	dir := testutil.TempCwd(t)
	for _, rel := range []string{"a/r1.md", "b/r2.md"} {
		path := filepath.Join(dir, ".junie", "rules", rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte("<!-- Generated by agnostic-ai -->\nold\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	entries := []spec.Entry{{Kind: spec.KindRule, Name: "r1", Body: "rule body"}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".junie", "rules")); !os.IsNotExist(err) {
		t.Errorf("legacy .junie/rules survived the sweep: %v", err)
	}
}
