package cline

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

// TestEmit_AgentFileIsYAMLWithFrontmatter pins the three conditions
// loadConfiguredAgentConfigs imposes on a file in `.cline/agents/`
// (cline/cline@2755adf,
// sdk/packages/core/src/extensions/tools/team/configured-agent-config.ts):
// the extension must be `.yml` or `.yaml` (L113-115, L176-178), the
// first line must match /^(---)[^\S\r\n]*(?:\r?\n|$)/ (L49-52), and the
// frontmatter must carry a non-empty `name` and `description` (L8-10).
func TestEmit_AgentFileIsYAMLWithFrontmatter(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{{
		Kind: spec.KindAgent, Name: "reviewer", Path: "agents/reviewer.md",
		Meta: map[string]any{"description": "Reviews diffs"},
		Body: "Review the diff.",
	}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Join(dir, ".cline/agents/reviewer.md")); !os.IsNotExist(err) {
		t.Errorf("no Cline surface reads .md in the agents dir, err=%v", err)
	}
	got := readFileString(t, filepath.Join(dir, ".cline/agents/reviewer.yml"))
	if !strings.HasPrefix(got, "---\n") {
		t.Fatalf("file must open with the frontmatter delimiter, got:\n%s", got)
	}
	for _, want := range []string{"name: reviewer\n", "description: Reviews diffs\n", "Review the diff."} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in:\n%s", want, got)
		}
	}
	if !strings.Contains(got, "Generated by agnostic-ai") {
		t.Errorf("provenance header lost:\n%s", got)
	}
}

// TestEmit_AgentFileFallsBackToNameForDescription covers a spec with no
// description. `description` is `z.string().trim().min(1)`, so an empty
// one throws and the agent drops out of the load result entirely.
func TestEmit_AgentFileFallsBackToNameForDescription(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{{Kind: spec.KindAgent, Name: "alpha", Body: "alpha body"}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFileString(t, filepath.Join(dir, ".cline/agents/alpha.yml"))
	if !strings.Contains(got, "description: alpha\n") {
		t.Errorf("expected the name as the description fallback:\n%s", got)
	}
}

// TestEmit_AgentFileCarriesXClineKeys confirms the five optional
// frontmatter fields the vendor schema accepts (tools, skills,
// providerId, modelId, maxIterations) reach the file through `x-cline`.
func TestEmit_AgentFileCarriesXClineKeys(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{{
		Kind: spec.KindAgent, Name: "alpha", Body: "alpha body",
		Meta: map[string]any{
			"description": "Does alpha things",
			"x-cline": map[string]any{
				"tools":         []any{"read", "edit"},
				"skills":        "review",
				"providerId":    "anthropic",
				"modelId":       "claude-opus-4",
				"maxIterations": 12,
			},
		},
	}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFileString(t, filepath.Join(dir, ".cline/agents/alpha.yml"))
	for _, want := range []string{
		"maxIterations: 12", "modelId: claude-opus-4", "providerId: anthropic",
		"skills: review", "tools:", "- read", "- edit",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in:\n%s", want, got)
		}
	}
}

// TestEmit_SweepsStaleMarkdownAgentFiles covers the upgrade path from a
// release that wrote `<name>.md` there. The stale file carries the
// provenance marker, so it is ours to remove; a hand-authored sibling
// is not.
func TestEmit_SweepsStaleMarkdownAgentFiles(t *testing.T) {
	dir := testutil.TempCwd(t)

	agents := filepath.Join(dir, ".cline", "agents")
	if err := os.MkdirAll(agents, 0o755); err != nil {
		t.Fatal(err)
	}
	stale := filepath.Join(agents, "alpha.md")
	if err := os.WriteFile(stale, []byte(emit.WithHeader("alpha body\n", emit.FormatMarkdown)), 0o644); err != nil {
		t.Fatal(err)
	}
	mine := filepath.Join(agents, "mine.md")
	if err := os.WriteFile(mine, []byte("hand written\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := []spec.Entry{{Kind: spec.KindAgent, Name: "alpha", Body: "alpha body"}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Errorf("stale generated .md must be swept, err=%v", err)
	}
	if _, err := os.Stat(mine); err != nil {
		t.Errorf("hand-authored file must survive: %v", err)
	}
	if _, err := os.Stat(filepath.Join(agents, "alpha.yml")); err != nil {
		t.Errorf("new agent file missing: %v", err)
	}
}

func readFileString(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}
