package cline

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func swapNoteWarner(t *testing.T) *strings.Builder {
	t.Helper()
	buf := &strings.Builder{}
	prev := emit.Warner
	emit.Warner = buf
	t.Cleanup(func() { emit.Warner = prev })
	emit.ResetCoverageNotes()
	t.Cleanup(emit.ResetCoverageNotes)
	return buf
}

// Cline discovers a hook by file name: `toHookConfigFileName` strips
// the extension, lowercases the stem and looks it up in
// HOOK_CONFIG_FILE_LOOKUP (hook-file-config.ts). So the event has to be
// the file name, `.sh` has to be in SUPPORTED_HOOK_FILE_EXTENSIONS, and
// the script has to be executable.
func TestEmit_Hook_WritesOneExecutableScriptPerEvent(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindHook, Name: "fmt-go",
			Meta: map[string]any{"event": "PostToolUse", "command": "gofmt -w ."},
		},
		{
			Kind: spec.KindHook, Name: "greet",
			Meta: map[string]any{"event": "TaskStart", "command": "echo start"},
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}

	for path, want := range map[string]string{
		".cline/hooks/PostToolUse.sh": "gofmt -w .",
		".cline/hooks/TaskStart.sh":   "echo start",
	} {
		full := filepath.Join(dir, path)
		got, err := os.ReadFile(full)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		if !strings.Contains(string(got), want) {
			t.Errorf("%s missing %q:\n%s", path, want, got)
		}
		if !strings.HasPrefix(string(got), "# Generated by agnostic-ai") {
			t.Errorf("%s must open with the provenance comment, got:\n%s", path, got)
		}
		// A shebang would have to sit above the provenance line, which
		// would stop sync recognizing the file as managed. `.sh` runs
		// under bash through inferHookCommand without one.
		if strings.Contains(string(got), "#!") {
			t.Errorf("%s must carry no shebang:\n%s", path, got)
		}
		info, err := os.Stat(full)
		if err != nil {
			t.Fatalf("stat %s: %v", path, err)
		}
		// Windows has no POSIX execute bit: Go reports 0o666 for every
		// file it writes there, so this assertion can only hold on
		// unix. Emission still chmods, and Cline runs a `.sh` hook as
		// `bash <path>` via inferHookCommand, which needs no exec bit
		// on any platform.
		if runtime.GOOS != "windows" && info.Mode().Perm()&0o100 == 0 {
			t.Errorf("%s must be executable, mode = %v", path, info.Mode().Perm())
		}
	}
}

// HOOK_CONFIG_FILE_LOOKUP is keyed by the lowercased enum value, so
// Cline itself accepts any casing of a file name. Fold the spec's
// `event:` the same way instead of dropping a spelling Cline reads.
func TestEmit_Hook_EventNameFoldsCase(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindHook, Name: "h", Meta: map[string]any{"event": "pretooluse", "command": "echo one"}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".cline/hooks/PreToolUse.sh")); err != nil {
		t.Errorf("expected canonical .cline/hooks/PreToolUse.sh: %v", err)
	}
}

// The file name is the event, so two specs on one event have no second
// slot. They share one script, in spec order, under `set -e` so the
// first failure is the exit status a blocking event reads.
func TestEmit_Hook_SameEventSharesOneScript(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindHook, Name: "first", Meta: map[string]any{"event": "PostToolUse", "command": "echo one"}},
		{Kind: spec.KindHook, Name: "second", Meta: map[string]any{"event": "PostToolUse", "command": "echo two"}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".cline/hooks/PostToolUse.sh"))
	if err != nil {
		t.Fatalf("read script: %v", err)
	}
	body := string(got)
	if !strings.Contains(body, "set -e") {
		t.Errorf("script missing set -e:\n%s", body)
	}
	one, two := strings.Index(body, "echo one"), strings.Index(body, "echo two")
	if one < 0 || two < 0 {
		t.Fatalf("script missing a command:\n%s", body)
	}
	if one > two {
		t.Errorf("commands out of spec order:\n%s", body)
	}
}

// A hook command pointing at a sibling tool's hooks directory rewrites
// onto `.cline/hooks/` so the script the event file calls is the one
// materialized next to it.
func TestEmit_Hook_RewritesSiblingToolHookPath(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindHook, Name: "fmt", Meta: map[string]any{
			"event": "PreToolUse", "command": ".claude/hooks/fmt.sh",
		}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".cline/hooks/PreToolUse.sh"))
	if err != nil {
		t.Fatalf("read script: %v", err)
	}
	if !strings.Contains(string(got), ".cline/hooks/fmt.sh") {
		t.Errorf("expected rewritten .cline/hooks/fmt.sh:\n%s", got)
	}
}

// outputs.cline.hooks-dir redirects the scripts to the other directory
// resolveHooksConfigSearchPaths returns.
func TestEmit_Hook_HooksDirOverride(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"cline": {HooksDir: ".clinerules/hooks"}},
	}
	entries := []spec.Entry{
		{Kind: spec.KindHook, Name: "h", Meta: map[string]any{"event": "PostToolUse", "command": "echo hi"}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".clinerules/hooks/PostToolUse.sh")); err != nil {
		t.Errorf("expected .clinerules/hooks/PostToolUse.sh: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".cline/hooks/PostToolUse.sh")); !os.IsNotExist(err) {
		t.Errorf("expected no script at the default dir; err=%v", err)
	}
}

// An event Cline has no file name for is a note, not a file: nothing
// scans for a name outside HookConfigFileName, so writing one would be
// a silent drop.
func TestEmit_Hook_UnknownEventNotesInsteadOfWriting(t *testing.T) {
	dir := testutil.TempCwd(t)
	buf := swapNoteWarner(t)

	entries := []spec.Entry{
		{Kind: spec.KindHook, Name: "h", Meta: map[string]any{"event": "SessionStart", "command": "echo hi"}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	emit.FlushCoverageNotes()

	if _, err := os.Stat(filepath.Join(dir, ".cline/hooks")); !os.IsNotExist(err) {
		t.Errorf("expected no hooks dir for an unreadable event; err=%v", err)
	}
	if !strings.Contains(buf.String(), "Cline reads a hook by file name") {
		t.Errorf("expected an unknown-event note, got: %q", buf.String())
	}
}

// `matcher` and `timeout` have nowhere to land: the file is per event
// and the timeout is a runtime setting. Both stay notes so the drop is
// never silent.
func TestEmit_Hook_MatcherAndTimeoutNoteAsInert(t *testing.T) {
	testutil.TempCwd(t)
	buf := swapNoteWarner(t)

	entries := []spec.Entry{
		{Kind: spec.KindHook, Name: "h", Meta: map[string]any{
			"event": "PreToolUse", "matcher": "Edit", "command": "echo hi", "timeout": 30,
		}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	emit.FlushCoverageNotes()

	out := buf.String()
	for _, want := range []string{"`matcher`", "`timeout`"} {
		if !strings.Contains(out, want) {
			t.Errorf("expected a note for %s, got: %q", want, out)
		}
	}
}

// PreCompact is a name Cline lists and maps to no runtime event
// (HOOK_CONFIG_FILE_EVENT_MAP), so createHookCommandMap skips it. Write
// the script at the vendor's own name and report the gap.
func TestEmit_Hook_PreCompactWritesAndNotesTheInertEvent(t *testing.T) {
	dir := testutil.TempCwd(t)
	buf := swapNoteWarner(t)

	entries := []spec.Entry{
		{Kind: spec.KindHook, Name: "h", Meta: map[string]any{"event": "PreCompact", "command": "echo hi"}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	emit.FlushCoverageNotes()

	if _, err := os.Stat(filepath.Join(dir, ".cline/hooks/PreCompact.sh")); err != nil {
		t.Errorf("expected .cline/hooks/PreCompact.sh: %v", err)
	}
	if !strings.Contains(buf.String(), "PreCompact") {
		t.Errorf("expected a PreCompact surface note, got: %q", buf.String())
	}
}

// A bundle with no hook spec writes no hooks directory.
func TestEmit_Hook_NoHooksNoDirectory(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{{Kind: spec.KindRule, Name: "r1", Body: "rule"}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".cline/hooks")); !os.IsNotExist(err) {
		t.Errorf("expected no hooks dir; err=%v", err)
	}
}

// `.cline/workflows` resolves in the CLI and the SDK, never in the VS
// Code extension, which reads GlobalFileNames.workflows
// (`.clinerules/workflows`) alone. Emit there on request, and say so.
func TestEmit_Workflows_CLIOnlyPathNotesTheSurfaceGap(t *testing.T) {
	testutil.TempCwd(t)
	buf := swapNoteWarner(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"cline": {WorkflowsDir: ".cline/workflows"}},
	}
	entries := []spec.Entry{{Kind: spec.KindAgent, Name: "ship-it", Body: "Run the release."}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	emit.FlushCoverageNotes()

	if !strings.Contains(buf.String(), "Cline VS Code extension") {
		t.Errorf("expected a VS Code surface note, got: %q", buf.String())
	}
}

// The recommended path reaches both hosts, so it must stay quiet.
func TestEmit_Workflows_RecommendedPathIsQuiet(t *testing.T) {
	testutil.TempCwd(t)
	buf := swapNoteWarner(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"cline": {WorkflowsDir: recommendedWorkflowsDir}},
	}
	entries := []spec.Entry{{Kind: spec.KindAgent, Name: "ship-it", Body: "Run the release."}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	emit.FlushCoverageNotes()

	if strings.Contains(buf.String(), "Cline VS Code extension") {
		t.Errorf("expected no surface note at %s, got: %q", recommendedWorkflowsDir, buf.String())
	}
}
