#!/bin/sh
# Generated by agnostic-ai. Do not edit this file directly; edit specs under .agnostic-ai/ and run `agnostic-ai sync`.

# Blocks Codex apply_patch edits to the protected paths in settings specs.
# Needs only a POSIX shell and awk. Exit 2 blocks the edit; stderr says why.
# Codex lets an edit through when a hook fails, so every failure exits 2.
LC_ALL=C
export LC_ALL
fail() {
  printf 'agnostic-ai: %s, so the protect hook blocked this edit.\n' "$1" >&2
  exit 2
}
command -v awk >/dev/null 2>&1 || fail "awk is not on PATH"
case $0 in
*/*) hooks_dir=${0%/*} ;;
*) hooks_dir=. ;;
esac
AGNOSTIC_AI_ROOT=$(cd -- "$hooks_dir/../.." && pwd -P) || fail "the project root is not readable"
AGNOSTIC_AI_LOGICAL_ROOT=$(cd -- "$hooks_dir/../.." && pwd -L) || fail "the project root is not readable"
AGNOSTIC_AI_CWD=$(pwd -P) || fail "the working directory is not readable"
AGNOSTIC_AI_LOGICAL_CWD=$(pwd -L) || fail "the working directory is not readable"
export AGNOSTIC_AI_ROOT AGNOSTIC_AI_LOGICAL_ROOT AGNOSTIC_AI_CWD AGNOSTIC_AI_LOGICAL_CWD
awk 'function clean(p,    n, parts, i, k, out, stack) {
  n = split(p, parts, "/")
  k = 0
  for (i = 1; i <= n; i++) {
    if (parts[i] == "" || parts[i] == ".") continue
    if (parts[i] == "..") { if (k > 0) k--; continue }
    stack[++k] = parts[i]
  }
  out = ""
  for (i = 1; i <= k; i++) out = out "/" stack[i]
  return out
}
function drive(p) {
  if (p ~ /^[A-Za-z]:\//) return "/" tolower(substr(p, 1, 1)) substr(p, 3)
  return p
}
function under(abs,    lower) {
  lower = tolower(abs)
  if (index(lower, tolower(root) "/") == 1) return substr(abs, length(root) + 2)
  if (index(lower, tolower(lroot) "/") == 1) return substr(abs, length(lroot) + 2)
  return ""
}
function relative(p,    abs, rel, i) {
  p = drive(p)
  if (substr(p, 1, 1) == "/") abs = clean(p); else abs = clean(cwd "/" p)
  rel = under(abs)
  for (i = 1; rel == "" && i <= nalias; i++) {
    if (index(tolower(abs), tolower(alias[i]) "/") == 1) rel = under(clean(cwd "/" substr(abs, length(alias[i]) + 2)))
  }
  return rel
}
function check(p,    rel, cand, i) {
  rel = relative(p)
  if (rel == "" || (rel in seen)) return
  seen[rel] = 1
  cand = tolower(rel)
  while (1) {
    for (i = 1; i <= npat; i++) {
      if (cand ~ pat[i]) {
        block(rel " is protected (" txt[i] "). " why[grp[i]])
        return
      }
    }
    if (index(cand, "/") == 0) return
    sub(/\/[^\/]*$/, "", cand)
  }
}
function block(message) {
  blocked[++nblocked] = "agnostic-ai: " message
}
function addAlias(p) {
  p = drive(p)
  if (substr(p, 1, 1) != "/") return
  p = clean(p)
  if (p != "" && p != cwd) alias[++nalias] = p
}
function restore(p, code, text,    parts, n, i, out) {
  if (index(p, code) == 0) return p
  n = split(p, parts, code)
  out = parts[1]
  for (i = 2; i <= n; i++) out = out text parts[i]
  return out
}
function unicode(h,    v, i, d) {
  v = 0
  for (i = 1; i <= 4; i++) {
    d = index("0123456789abcdef", tolower(substr(h, i, 1)))
    if (d == 0) return "\003"
    v = v * 16 + d - 1
  }
  if (v == 0) return "\003"
  if (v == 34) return "\002"
  if (v == 92) return "\001"
  if (v >= 128) return "\200"
  return sprintf("%c", v)
}
function trimmed(c) {
  return c != "" && (index(" \t\v\f\r", c) > 0 || c >= "\200")
}
function control(c) {
  return c != "" && (c < " " || c == "\177") && !trimmed(c)
}
function header(l, marker,    at, before, p, c, odd) {
  at = index(l, marker)
  if (at == 0) return
  before = substr(l, 1, at - 1)
  odd = 0
  sub(/[ \t]+$/, "", before)
  while (before != "") {
    c = substr(before, length(before), 1)
    if (control(c)) odd = 1
    else if (!trimmed(c)) break
    before = substr(before, 1, length(before) - 1)
  }
  if (before != "" && c != "\"") return
  p = restore(stringAt(l, at + length(marker)), "\001", "/")
  sub(/[ \t]+$/, "", p)
  while (p != "") {
    c = substr(p, length(p), 1)
    if (control(c)) odd = 1
    else if (!trimmed(c)) break
    p = substr(p, 1, length(p) - 1)
  }
  if (control(substr(p, 1, 1))) odd = 1
  if (odd) {
    block("the header for " p " has control characters the hook cannot check. Write the header without them.")
    return
  }
  if (p != "") paths[++npaths] = p
}
function stringAt(s, from,    p, end) {
  p = substr(s, from)
  end = index(p, "\"")
  if (end > 0) p = substr(p, 1, end - 1)
  return restore(p, "\002", "\"")
}
function start() {
  first = 1
  fresh = 1
}
function text(s,    i) {
  while ((i = index(s, "\n")) > 0) {
    piece(substr(s, 1, i - 1))
    newline()
    s = substr(s, i + 1)
  }
  piece(s)
}
function piece(s,    t, c) {
  if (skip) return
  if (fresh) {
    t = s
    sub(/^[ \t]+/, "", t)
    while (t != "" && trimmed(substr(t, 1, 1))) t = substr(t, 2)
    if (t != "") {
      fresh = 0
      c = substr(t, 1, 1)
      if (!first && c != "*" && c != "\"" && !control(c)) {
        skip = 1
        cur = ""
        return
      }
    }
  }
  cur = cur s
}
function newline() {
  if (!skip) line(cur)
  cur = ""
  skip = 0
  fresh = 1
  first = 0
}
function finish() {
  newline()
}
function line(l) {
  if (!havecwd && match(l, /"cwd"[ \t]*:[ \t]*"/)) {
    havecwd = 1
    addAlias(restore(stringAt(l, RSTART + RLENGTH), "\001", "/"))
  }
  header(l, "*** Add File: ")
  header(l, "*** Update File: ")
  header(l, "*** Delete File: ")
  header(l, "*** Move to: ")
}
BEGIN {
  RS = "\\"
  esc["\""] = "\002"; esc["/"] = "/"; esc["t"] = "\t"; esc["r"] = "\r"; esc["f"] = "\f"; esc["b"] = "\b"; esc["n"] = "\n"
  root = drive(ENVIRON["AGNOSTIC_AI_ROOT"])
  lroot = drive(ENVIRON["AGNOSTIC_AI_LOGICAL_ROOT"])
  cwd = drive(ENVIRON["AGNOSTIC_AI_CWD"])
  addAlias(ENVIRON["AGNOSTIC_AI_LOGICAL_CWD"])
  why[1] = "CI and the lock file change only on purpose. Ask the user before editing it. This hook blocks the edit either way, so the user makes the change or removes the path from the protected list."
  pat[1] = "^\\.github/.+$"; txt[1] = ".github/**"; grp[1] = 1
  pat[2] = "^composer\\.lock$"; txt[2] = "composer.lock"; grp[2] = 1
  npat = 2
  start()
}
NR == 1 { text($0); next }
plain { plain = 0; text($0); next }
$0 == "" { text("\001"); plain = 1; next }
{
  c = substr($0, 1, 1)
  r = substr($0, 2)
  if (c == "u") text(unicode(substr(r, 1, 4)) substr(r, 5))
  else if (c in esc) text(esc[c] r)
  else text(c r)
}
END {
  finish()
  for (i = 1; i <= npaths; i++) check(paths[i])
  for (i = 1; i <= nblocked; i++) print blocked[i]
  if (nblocked > 0) exit 2
}
' 1>&2
status=$?
case $status in
0) exit 0 ;;
2) exit 2 ;;
esac
fail "awk stopped with status $status"
