package amp

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestEmit_Environment_WritesSetupAndServices(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindEnvironment,
			Name: "development",
			Meta: map[string]any{
				"install": "go mod download",
				"terminals": []any{
					map[string]any{"name": "dev", "command": "go run ./cmd/agnostic-ai"},
					map[string]any{"name": "docs", "command": "zola serve", "cwd": "docs/site", "agent": "observe"},
				},
			},
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}

	setupPath := filepath.Join(dir, ".agents", "setup")
	setup := readFile(t, setupPath)
	for _, want := range []string{"#!/usr/bin/env bash", "Generated by agnostic-ai", "go mod download"} {
		if !strings.Contains(setup, want) {
			t.Errorf("setup script missing %q:\n%s", want, setup)
		}
	}
	if runtime.GOOS != "windows" {
		info, err := os.Stat(setupPath)
		if err != nil {
			t.Fatal(err)
		}
		if info.Mode().Perm()&0o111 == 0 {
			t.Errorf("setup script is not executable: mode=%o", info.Mode().Perm())
		}
	}

	services := readFile(t, filepath.Join(dir, ".amp", "services.yaml"))
	for _, want := range []string{
		"# Generated by agnostic-ai",
		"services:",
		"dev:",
		"command: go run ./cmd/agnostic-ai",
		"docs:",
		"command: zola serve",
		"cwd: docs/site",
		"agent: observe",
	} {
		if !strings.Contains(services, want) {
			t.Errorf("services file missing %q:\n%s", want, services)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, ".agents", "resume")); !os.IsNotExist(err) {
		t.Errorf("environment must not invent resume semantics, err=%v", err)
	}
}

func TestEmit_Environment_UsesOutputOverridesAndLastValues(t *testing.T) {
	dir := testutil.TempCwd(t)
	cfg := &config.Config{Outputs: map[string]config.Output{
		"amp": {SetupFile: "orb/setup.sh", EnvironmentFile: "orb/services.yml"},
	}}
	entries := []spec.Entry{
		{Kind: spec.KindEnvironment, Name: "first", Meta: map[string]any{
			"install":   "first install",
			"terminals": []any{map[string]any{"name": "first", "command": "first command"}},
		}},
		{Kind: spec.KindEnvironment, Name: "second", Meta: map[string]any{
			"install":   "second install",
			"terminals": []any{map[string]any{"name": "second", "command": "second command"}},
		}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}

	setup := readFile(t, filepath.Join(dir, "orb", "setup.sh"))
	if !strings.Contains(setup, "second install") || strings.Contains(setup, "first install") {
		t.Errorf("expected last install value to win:\n%s", setup)
	}
	services := readFile(t, filepath.Join(dir, "orb", "services.yml"))
	if !strings.Contains(services, "second:") || strings.Contains(services, "first:") {
		t.Errorf("expected last terminals value to win:\n%s", services)
	}
}

func TestEmit_Environment_RejectsInvalidServices(t *testing.T) {
	cases := []struct {
		name string
		meta map[string]any
		want string
	}{
		{name: "install is not text", meta: map[string]any{"install": []any{"go mod download"}}, want: "install must be a string"},
		{name: "terminals is not a list", meta: map[string]any{"terminals": "go run ."}, want: "terminals must be a list"},
		{name: "terminal is not a mapping", meta: map[string]any{"terminals": []any{"go run ."}}, want: "must be a mapping"},
		{name: "invalid name", meta: map[string]any{"terminals": []any{map[string]any{"name": "Dev Server", "command": "go run ."}}}, want: "must match"},
		{name: "missing command", meta: map[string]any{"terminals": []any{map[string]any{"name": "dev"}}}, want: "requires command"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := testutil.TempCwd(t)
			if _, exists := tc.meta["install"]; !exists {
				tc.meta["install"] = "echo setup"
			}
			entry := spec.Entry{Kind: spec.KindEnvironment, Name: "development", Meta: tc.meta}
			err := New().Emit(emit.NewSession(), spec.NewBundle([]spec.Entry{entry}), &config.Config{}, false)
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("error = %v, want text %q", err, tc.want)
			}
			if _, statErr := os.Stat(filepath.Join(dir, ".agents", "setup")); !os.IsNotExist(statErr) {
				t.Errorf("invalid environment wrote setup before validation, err=%v", statErr)
			}
		})
	}
}
