// Package header centralizes the agnostic-ai provenance header that
// every generated file should carry. Adapters use it to render the
// comment line; importers use it to detect and strip the same line
// during round-trips so source specs do not carry the marker back.
//
// The package is intentionally split from `internal/adapters/internal/emit`
// so the cli package (which lives outside `internal/adapters/`) can
// reuse it for import-side stripping without crossing the emit
// package's `internal/` boundary.
package header

import (
	"strings"
)

// Format is the file-format hint for Line. Adapters pass the format
// matching the file they are about to write so the returned comment
// line is syntactically valid.
type Format int

const (
	// FormatMarkdown selects an HTML comment so the header stays
	// invisible to readers but is still discoverable in the raw source.
	// Use for .md / .mdc files, including those with YAML frontmatter.
	FormatMarkdown Format = iota
	// FormatTOML selects a `#` line comment. Use for .toml files.
	FormatTOML
	// FormatYAML selects a `#` line comment. Use for .yaml / .yml files.
	FormatYAML
	// FormatShell selects a `#` line comment. Use for shell scripts.
	FormatShell
	// FormatJSON returns empty from Line (JSON has no comment syntax).
	// Adapters writing JSON should skip the header.
	FormatJSON
)

// Marker is the substring agnostic-ai writes into every generated
// document. Importers detect it to distinguish a previously generated
// file from a user-authored one. The constant moved here from
// `internal/adapters/internal/emit/migrate.go` so both adapters and
// the cli can reuse the same canonical string.
const Marker = "Generated by agnostic-ai"

// payloadText is the human-facing portion of the header. It MUST
// contain Marker so substring detection keeps working. Kept short
// to minimize visual weight in generated files.
const payloadText = Marker

// Line returns the comment line that marks a generated file in the
// given format, terminated by a newline. Returns "" for FormatJSON
// because JSON has no comment syntax.
//
// The returned string contains Marker as a substring so legacy-file
// detection and any other importer-side checks keep working.
func Line(format Format) string {
	switch format {
	case FormatMarkdown:
		return "<!-- " + payloadText + " -->\n"
	case FormatTOML, FormatYAML, FormatShell:
		return "# " + payloadText + "\n"
	default:
		return ""
	}
}

// With prepends Line(format) to content. For Markdown content that
// starts with a YAML frontmatter block (`---\n...\n---\n`), the header
// is inserted right after the closing delimiter so the frontmatter
// parser is not broken. Empty content is returned unchanged.
// FormatJSON returns content unchanged.
func With(content string, format Format) string {
	if content == "" {
		return content
	}
	line := Line(format)
	if line == "" {
		return content
	}
	if format == FormatMarkdown {
		if strings.HasPrefix(content, "---\n") {
			if end := findFrontmatterEnd(content); end > 0 {
				rest := strings.TrimLeft(content[end:], "\n")
				return content[:end] + "\n" + line + "\n" + rest
			}
		}
		// For non-frontmatter markdown, separate the header from the
		// body with a blank line so visual reading stays clean.
		return line + "\n" + content
	}
	return line + content
}

// findFrontmatterEnd returns the byte offset right after the closing
// `\n---\n` delimiter of a YAML frontmatter block at the start of
// content. Returns -1 when no closing delimiter is found. Caller must
// have already verified that content starts with "---\n".
func findFrontmatterEnd(content string) int {
	const close = "\n---"
	idx := strings.Index(content[len("---\n"):], close)
	if idx < 0 {
		return -1
	}
	end := len("---\n") + idx + len(close)
	if end >= len(content) {
		return end
	}
	if content[end] != '\n' {
		return -1
	}
	return end + 1
}

// Has reports whether content carries the provenance marker. Used by
// importers and the legacy-file rename path to decide whether the file
// was agnostic-ai-generated.
func Has(content string) bool {
	return strings.Contains(content, Marker)
}

// Strip removes a leading agnostic-ai header line from content so
// importers do not capture it into source specs. Supports the two
// header forms emitted by Line: the HTML comment for Markdown and the
// `# ...` line comment for TOML/YAML/Shell. Trailing blank lines after
// the header are also trimmed so the body starts clean.
//
// For Markdown files with YAML frontmatter, the header lives below the
// frontmatter; Strip locates and removes that header line while
// preserving the frontmatter untouched.
//
// Content without a header is returned unchanged.
func Strip(content string) string {
	if !Has(content) {
		return content
	}
	if strings.HasPrefix(content, "---\n") {
		end := findFrontmatterEnd(content)
		if end > 0 {
			return content[:end] + stripHeaderLine(content[end:])
		}
	}
	return stripHeaderLine(content)
}

// stripHeaderLine removes a leading provenance header line plus its
// trailing blank line(s) from s. Returns s unchanged when the first
// non-blank line does not look like a header.
func stripHeaderLine(s string) string {
	trimmed := strings.TrimLeft(s, "\n")
	leading := len(s) - len(trimmed)
	nl := strings.IndexByte(trimmed, '\n')
	if nl < 0 {
		return s
	}
	first := trimmed[:nl]
	if !strings.Contains(first, Marker) {
		return s
	}
	if !looksLikeHeaderLine(first) {
		return s
	}
	rest := strings.TrimLeft(trimmed[nl+1:], "\n")
	if leading > 0 {
		return s[:leading] + rest
	}
	return rest
}

// looksLikeHeaderLine returns true when line matches one of the comment
// shapes Line emits. Keeps Strip from eating user-authored lines that
// happen to mention "Generated by agnostic-ai" in prose.
func looksLikeHeaderLine(line string) bool {
	t := strings.TrimSpace(line)
	if strings.HasPrefix(t, "<!--") && strings.HasSuffix(t, "-->") {
		return true
	}
	if strings.HasPrefix(t, "#") {
		return true
	}
	return false
}
