package header

import (
	"strings"
	"testing"
)

func TestLine_FormatsCarryMarker(t *testing.T) {
	for _, tc := range []struct {
		name   string
		format Format
		prefix string
	}{
		{"markdown", FormatMarkdown, "<!--"},
		{"toml", FormatTOML, "#"},
		{"yaml", FormatYAML, "#"},
		{"shell", FormatShell, "#"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := Line(tc.format)
			if !strings.HasPrefix(got, tc.prefix) {
				t.Errorf("expected prefix %q, got %q", tc.prefix, got)
			}
			if !strings.Contains(got, Marker) {
				t.Errorf("header missing marker: %q", got)
			}
			if !strings.HasSuffix(got, "\n") {
				t.Errorf("header must end with newline: %q", got)
			}
		})
	}
}

func TestLine_JSONReturnsEmpty(t *testing.T) {
	if got := Line(FormatJSON); got != "" {
		t.Errorf("FormatJSON header should be empty, got %q", got)
	}
}

func TestWith_PlainMarkdownPrepends(t *testing.T) {
	got := With("# Title\n\nbody\n", FormatMarkdown)
	if !strings.HasPrefix(got, "<!-- "+Marker) {
		t.Errorf("expected header at top, got:\n%s", got)
	}
	if !strings.Contains(got, "# Title") {
		t.Errorf("body lost: %s", got)
	}
}

func TestWith_MarkdownFrontmatterInsertsBelow(t *testing.T) {
	in := "---\nname: foo\n---\n\nbody text\n"
	got := With(in, FormatMarkdown)
	if !strings.HasPrefix(got, "---\nname: foo\n---\n") {
		t.Errorf("frontmatter mangled: %q", got)
	}
	idxFM := strings.Index(got, "---\nname: foo\n---\n")
	idxHeader := strings.Index(got, "<!-- "+Marker)
	if idxHeader < idxFM {
		t.Errorf("header must appear after frontmatter:\n%s", got)
	}
	if !strings.Contains(got, "body text") {
		t.Errorf("body lost: %s", got)
	}
}

func TestWith_TOMLPrepends(t *testing.T) {
	got := With("key = \"value\"\n", FormatTOML)
	if !strings.HasPrefix(got, "# "+Marker) {
		t.Errorf("expected toml header, got:\n%s", got)
	}
}

func TestWith_EmptyContentUnchanged(t *testing.T) {
	if got := With("", FormatMarkdown); got != "" {
		t.Errorf("empty content must stay empty, got %q", got)
	}
}

func TestWith_JSONUnchanged(t *testing.T) {
	in := "{\"k\":1}\n"
	if got := With(in, FormatJSON); got != in {
		t.Errorf("FormatJSON must not modify content, got %q", got)
	}
}

func TestStrip_RemovesMarkdownHeader(t *testing.T) {
	in := With("# Title\n\nbody\n", FormatMarkdown)
	got := Strip(in)
	if got != "# Title\n\nbody\n" {
		t.Errorf("expected stripped body, got %q", got)
	}
}

func TestStrip_RemovesTOMLHeader(t *testing.T) {
	in := With("k = 1\n", FormatTOML)
	got := Strip(in)
	if got != "k = 1\n" {
		t.Errorf("expected stripped body, got %q", got)
	}
}

func TestStrip_PreservesFrontmatter(t *testing.T) {
	in := With("---\nname: foo\n---\n\nbody\n", FormatMarkdown)
	got := Strip(in)
	want := "---\nname: foo\n---\n\nbody\n"
	if got != want {
		t.Errorf("expected %q, got %q", want, got)
	}
}

func TestStrip_LeavesUserContentAlone(t *testing.T) {
	in := "# My doc\n\nUnrelated text.\n"
	if got := Strip(in); got != in {
		t.Errorf("user content modified: got %q want %q", got, in)
	}
}

func TestStrip_NoMarkerNoOp(t *testing.T) {
	in := "# heading\n\nbody.\n"
	if got := Strip(in); got != in {
		t.Errorf("expected no-op, got %q", got)
	}
}

func TestRoundTrip_FrontmatterStaysIntact(t *testing.T) {
	original := "---\nname: foo\ndescription: bar\n---\n\nbody\n"
	round := Strip(With(original, FormatMarkdown))
	if round != original {
		t.Errorf("roundtrip changed content:\noriginal=%q\nround=%q", original, round)
	}
}

func TestLeads_AcceptsTheHeaderWhereEmittersWriteIt(t *testing.T) {
	for _, tc := range []struct {
		name, path, content string
	}{
		{"markdown", "AGENTS.md", With("body\n", FormatMarkdown)},
		{"markdown after frontmatter", ".claude/agents/a.md", With("---\nname: a\n---\nbody\n", FormatMarkdown)},
		{"mdc after frontmatter", ".cursor/rules/r.mdc", With("---\nalwaysApply: true\n---\nbody\n", FormatMarkdown)},
		{"toml", ".codex/agents/a.toml", With("name = \"a\"\n", FormatTOML)},
		{"yaml", ".continue/rules/r.yaml", With("name: r\n", FormatYAML)},
		{"ignore file", ".cursorignore", With("secrets/\n", FormatShell)},
		{"shell after shebang", ".openhands/setup.sh", "#!/bin/bash\n" + Line(FormatShell) + "\necho hi\n"},
		{"javascript", ".opencode/plugins/p.ts", With("export {}\n", FormatJavaScript)},
		{"crlf checkout", "AGENTS.md", strings.ReplaceAll(With("---\nname: a\n---\nbody\n", FormatMarkdown), "\n", "\r\n")},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if !Leads(tc.path, tc.content) {
				t.Errorf("Leads(%q) = false for:\n%s", tc.path, tc.content)
			}
		})
	}
}

// A file that only mentions the marker, like this package's own source or
// a docs page quoting the header, is not a generated file.
func TestLeads_RejectsTheMarkerAnywhereElse(t *testing.T) {
	for _, tc := range []struct {
		name, path, content string
	}{
		{"go source defining the marker", "internal/adapters/header/header.go", "// Package header\npackage header\n\nconst Marker = \"Generated by agnostic-ai\"\n"},
		{"docs page quoting the header", "docs/targets/claude.md", "---\ntitle: Claude\n---\n\nEvery file starts with `<!-- Generated by agnostic-ai. -->`.\n"},
		{"header below the first line", "AGENTS.md", "# Notes\n" + Line(FormatMarkdown)},
		{"prose line naming the marker", "AGENTS.md", "Generated by agnostic-ai, then edited.\n"},
		{"markdown with a shell comment", "AGENTS.md", Line(FormatShell) + "body\n"},
		{"toml with an html comment", "a.toml", Line(FormatMarkdown) + "name = \"a\"\n"},
		{"json", "settings.json", Line(FormatShell) + "{}\n"},
		{"shebang in markdown", "AGENTS.md", "#!/bin/bash\n" + Line(FormatMarkdown)},
		{"empty", "AGENTS.md", ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if Leads(tc.path, tc.content) {
				t.Errorf("Leads(%q) = true for:\n%s", tc.path, tc.content)
			}
		})
	}
}
