# Round-trip issues, Part 2 — deeper audit (v0.17.0)

Follow-up to `MANUSCRIPT_ROUND_TRIP_ISSUES.md` (issues #190–#198 filed). Same fixture: [manuscript](https://github.com/JesusValeraDev/manuscript). Additional issues surfaced from deeper testing: doctor/sync interaction, capability warnings, import scope, docs accuracy.

Ordered by severity. Each item ready to file as a separate issue. Cross-references to related closed issues are called out where the existing work covered part of the problem space but left gaps.

> **Dropped from this batch**: "Spec name collision detection" — duplicate of closed #171 (Deeper spec linting), which already lists `"Output collision: two specs would write the same path on disk"` as a planned check.

---

## Issue 10 — `doctor` and `sync` disagree on `.claude/settings.json` (drift loop) 🔴

**Severity**: high (false-positive drift reports break CI gating)
**Reproducible**: yes, every run

### Repro

```bash
agnostic-ai sync                   # exit 0, "synced"
agnostic-ai doctor                 # ✗ claude: drift
agnostic-ai doctor --fix           # → reconciled 1 file(s)
agnostic-ai doctor                 # ✓ clean
agnostic-ai sync                   # re-introduces the drift
agnostic-ai doctor                 # ✗ claude: drift  (loop)
```

### Diff between `sync` output and `doctor --fix` output

```diff
--- after sync
+++ after doctor --fix
@@ -46,7 +46,6 @@
       }
     ]
-
   },
```

`sync` emits an extra blank line at L49 of `settings.json` that `doctor --fix` strips. Two emit paths produce different bytes from identical input.

### Impact

- README pitches `agnostic-ai doctor` as the drift detector for CI. With this bug it false-positives on every clean repo right after `sync`. CI gate becomes unusable.
- Linked to filed #195 (trailing newline) but not the same: this is a mid-file blank, not a trailing one.

### Suspected root cause

Two code paths emit `settings.json`:

- `internal/adapters/claude/claude.go:181` (sync emit) — calls `emit.MarshalJSONIndent(doc) + "\n"`.
- Some doctor/check path that normalizes the same map with subtly different whitespace.

Find the doctor-side emitter and unify both call sites on the exact same byte-writer.

### Fix

- (a) Route both sync and doctor through one shared `emitClaudeSettings(doc) ([]byte, error)` helper.
- (b) Add a regression test: `sync → doctor` should report clean exit on a freshly synced repo, no exceptions.

---

## Issue 11 — README "byte-identical" claim is overstated 🟡

**Severity**: medium (docs accuracy / user trust)

### Quote from README

> `import claude` prefers `.claude/rules/*.md` (each file → one rule, byte-identical) and falls back to slicing `CLAUDE.md` on `## headings`...

### Reality

After a single import-then-sync round trip, every output file differs from the source by at least:

1. Two prepended lines: `<!-- Generated by agnostic-ai -->` + blank.
2. One appended trailing blank line.
3. Frontmatter keys re-ordered (#190) and indent changed (#191).
4. Quote style flipped (#193).

So "byte-identical" is false for any file that survives a sync. The promise holds only for the import direction in isolation. Sync clobbers it.

### Fix

- (a) Reword README to "content-preserving round trip — provenance marker and canonical formatting are applied on emit".
- (b) Once #190/191/195 land, the only remaining delta is the marker. Then claim becomes accurate modulo the marker, which is acceptable.

---

## Issue 12 — Target table in README misleads on native-path support 🟡

**Severity**: medium (user expectation management)

### Concrete cases

| Adapter output | Tool that actually reads it natively |
|---|---|
| `.claude/rules/*.md` | None. Claude Code requires `@.claude/rules/*` references inside `CLAUDE.md` to load these. |
| `.claude/settings.json` | Yes, Claude Code. ✅ |
| `.claude/agents/*.md` | Yes, Claude Code. ✅ |
| `.codex/config.toml` | No. OpenAI Codex CLI reads `~/.codex/config.toml` (user-home, not per-project). |
| `.codex/prompts/*.md` | No. Not in upstream Codex CLI spec. |
| `.agents/agents/*.toml` | No. Speculative community AGENTS.md spec; no shipped consumer reads it. |

The current ✅ column conflates "we emit a file" with "the tool loads it". A user enabling `codex` expects their hooks to fire in OpenAI Codex CLI; they will not.

### Fix

Add a "native | convention" column to the target table:

| Target | Skills | Native path? |
|---|---|---|
| Claude Code agents | `.claude/agents/` | native |
| Claude Code rules | `.claude/rules/` | convention (loaded via `@…` reference in CLAUDE.md) |
| Codex hooks | `.codex/config.toml` | convention (Codex CLI does not read project-local config) |

Or strike the ✅ for non-native paths until the upstream tool supports them.

---

## Issue 13 — `settings.json` has two sources of truth (split overlay) 🟡

**Severity**: medium (mental model / authoring confusion)
**Related**: closed #177 ("Claude + Codex adapter excellence") proposes promoting `enabledPlugins` / `outputStyle` / `statusLine` to first-class fields. This issue is the docs/UX counterpart — even before those promotions ship, the overlay path needs documentation.

### Observation

For Claude target, hooks come from `.agnostic-ai/hooks/*.md`. All other `settings.json` keys (`statusLine`, `enabledPlugins`, etc.) live in `.agnostic-ai/overlays/claude.settings.json`. Output is the merge of both.

### Why it's confusing

- A new user opens `.agnostic-ai/` and sees `hooks/`, `agents/`, `rules/`, etc. Logical model: one spec dir per concept.
- They do not expect `overlays/`. It's not in the README's "Where the specs live" list (`CLAUDE.md` says: agents, skills, rules, hooks, mcps, commands — no mention of overlays).
- Editing `statusLine` requires knowing to open `.agnostic-ai/overlays/claude.settings.json`, which is target-specific (defeats the "write once for every CLI" pitch).

### Fix options

- (a) Document `overlays/` prominently in README and `AGNOSTIC_AI.md` template.
- (b) Add a `.agnostic-ai/statuslines/` (or similar) abstraction that emits to Claude's `statusLine` and to whatever Codex/Gemini equivalent exists. Round-trippable like hooks.
- (c) Long-term: model status line and plugin config as first-class agnostic concepts if any other adapter has equivalents.

Short-term: at minimum add an entry under "Where the specs live" in the AGNOSTIC_AI.md template.

---

## Issue 14 — Capability warnings are noisy and unactionable (sync emit path) 🟡

**Severity**: low-medium (UX)
**Related**: closed #114 added a per-kind summary at *validate* time. This issue is about the *sync* emit path, which still prints one warning line per spec with no dedup and no suppression hint.

### Repro

Enable `aider` (which doesn't support hooks or commands) alongside claude+codex. Sync stderr:

```
! aider: hook not supported, skipped
! aider: command not supported, skipped
! aider: hook not supported, skipped
! aider: command not supported, skipped
```

Two issues:

- Duplicated: one line per hook spec and per command spec is emitted, not one per (target, kind) tuple. With 4 hooks and 10 commands × 1 target → 14 lines that say the same two things. With three unsupported targets and dozens of specs, this drowns the rest of sync output.
- No action: warning doesn't say `set on-unsupported: silent in agnostic-ai.yaml to suppress` or which spec file triggered it.

### Fix

```
! aider: 4 hooks skipped (target does not support hooks)
! aider: 10 commands skipped (target does not support commands)
  fix: set `on-unsupported: silent` in agnostic-ai.yaml to hide these
```

Group by (target, kind) tuple. Include suppression hint.

---

## Issue 15 — `import --dry-run` dumps full file contents (11939 lines for manuscript) 🟡

**Severity**: medium (UX, unreviewable output)
**Related**: closed #161 shipped `sync --plan` (per-target counts) and `sync --json`. Sync side is now fine. `import --dry-run` was not part of that PR and still dumps every file body.

### Repro

```bash
agnostic-ai import claude --dry-run | wc -l   # 11939
```

Output is every importable file's body separated by `--- path ---` headers. Equivalent to `cat`-ing all 75 files. Useless for "what will change?" review; user can just look at source files directly.

For comparison: `sync --plan` already produces the right shape —

```
[claude]  no changes
[codex]   no changes
```

`import` needs the equivalent.

### Useful import dry-run output (proposed)

```
Would import 75 specs into .agnostic-ai/:
  17 rules from .claude/rules/*.md
   9 agents from .claude/agents/*.md
  30 skills from .claude/skills/*/
   4 hooks from .claude/settings.json (PreToolUse:1, PostToolUse:3)
  10 commands from .claude/commands/*.md
   1 AGNOSTIC_AI.md seeded from CLAUDE.md
   1 overlay captured: claude.settings.json (statusLine, enabledPlugins)

Files that would be written (paths only):
  .agnostic-ai/AGNOSTIC_AI.md
  .agnostic-ai/agents/changelog-keeper.md
  .agnostic-ai/agents/clean-code-reviewer.md
  ...

Pass --verbose to see full content.
```

### Fix

- Default `import --dry-run`: summary + path list (mirror `sync --plan` shape).
- `--verbose`: full content.
- Optional `--diff`: only specs where output ≠ existing on-disk content under `.agnostic-ai/`.
- Match `import` to `sync` flag set: `--plan`, `--json`.

---

## Issue 16 — Hooks → multi-target schema mapping is undocumented 🟡

**Severity**: low (docs)

### What's missing

`.agnostic-ai/hooks/<name>.md` is a Markdown file with frontmatter. It renders to:

- `.claude/settings.json` under `hooks.{PreToolUse|PostToolUse|...}` with `matcher` + nested `hooks[].{type,command}` schema.
- `.codex/config.toml` under `[[hooks.PostToolUse]]` with TOML `matcher = "..."` + `command = "..."`.

Mapping is non-obvious. `docs/user/spec-format.md` covers the agnostic frontmatter but not how `event:`, `matcher:`, `command:` fields land in each target's native shape. Users authoring a new hook spec can't predict what `.claude/settings.json` and `.codex/config.toml` will end up containing.

### Fix

Add a per-spec-kind "what gets emitted" table to `docs/user/targets.md`. Example for hooks:

```
agnostic-ai frontmatter:
  event: PostToolUse
  matcher: Bash(git commit*)
  command: echo "tests please"

→ .claude/settings.json:
  hooks.PostToolUse[] = {
    matcher: "Bash(git commit*)",
    hooks: [{type: "command", command: "echo \"tests please\""}]
  }

→ .codex/config.toml:
  [[hooks.PostToolUse]]
  matcher = "Bash(git commit*)"
  command = "echo \"tests please\""
```

Document for every spec kind × every target.

---

## Issue 17 — `doctor` drift message conflates source-drift with user-edited-generated-file 🟡

**Severity**: low (existing detection works; message clarity gap)
**Related**: closed #159 extended `doctor` into the unified diagnostic. Detection works correctly.

### Observation

`doctor` DOES catch the case where a user edits `CLAUDE.md` directly:

```bash
echo "EDITED" >> CLAUDE.md
agnostic-ai doctor
# Sync drift:
# ✗ agnostic-ai: drift
# drift detected. run `agnostic-ai sync` to reconcile, or `agnostic-ai doctor --fix`
```

But the message lumps every cause under one label:

- Spec edit in `.agnostic-ai/` (legitimate, sync emits new files).
- Output file edited by user (footgun, sync silently clobbers).
- Sync state stale (sync never ran for current spec).
- Per-target adapter bug (#10 above).

User sees `✗ agnostic-ai: drift` and runs `sync`. If the cause was case 2 (footgun), their edits vanish silently.

### Fix

Split the doctor drift section into causes:

```
Sync drift:
  ✗ Local edits to generated files:
      CLAUDE.md (10 lines added since last sync)
      .claude/agents/reviewer.md (3 lines changed)
    Move these edits into .agnostic-ai/ before re-syncing.
  ✓ Source specs vs last sync: clean
  ✓ Adapter consistency: clean
```

Each cause gets a different remediation hint. Optional `doctor --explain` prints a diff for each drifted file so the user knows what they would lose.

### Bonus

Cross-target body drift detection — verify that root entry-point files (`CLAUDE.md`, `AGENTS.md`, `GEMINI.md`, ...) share the body in `AGNOSTIC_AI.md`. Currently checked transitively (any drift gets flagged), but not surfaced as its own category.

---

## Issue 18 — `globs:` patterns not validated against repo paths 🟡

**Severity**: low (silent failure mode)
**Related**: closed #171 (Deeper spec linting) covers dead-spec, hook-collision, output-collision, unreachable-rule, stale-reference. It does not include "glob matches no files in working tree" — this issue adds that check to the planned lint set.

### Scenario

Source rule has `globs: backend/modules/*/Domain/**/*.php`. Repo restructured — `backend/` becomes `apps/backend/`. Glob now matches nothing. Adapter still emits rule, target silently never applies it. No error, no warning.

### Fix

`doctor` could optionally check each rule's `globs:` patterns against the working tree:

```
! Rules with no matching files in repo:
    backend-domain-layer.md (globs: backend/modules/*/Domain/**/*.php — no matches)
  Either fix the glob or the rule will never load.
```

Off by default (some monorepos have intentionally unmatched globs for future features). Opt-in via `agnostic-ai doctor --check-globs`.

---

## Issue 19 — `import` doesn't capture arbitrary `.claude/*.sh` or sidecar files 🟡

**Severity**: low (scope clarification)

### Scenario

Manuscript's `.claude/settings.json` references `.claude/statusline.sh`. The shell script is part of the Claude Code config but is not modelled by agnostic-ai. After `import claude` + `agnostic-ai revert`, if the user then deletes their `.claude/` dir intending to fully regenerate from spec, the statusline shell script is lost.

### Mitigation options

- (a) Document scope: import captures rules, agents, skills, hooks, commands, settings overlay. Anything else under `.claude/` is your responsibility — git-track those files yourself.
- (b) Capture arbitrary referenced files: detect `.sh` / asset paths referenced from `settings.json` and stash them under `.agnostic-ai/overlays/claude.assets/`. Heavy; probably not worth it.
- (c) Add a `.agnostic-ai/assets/<target>/` opt-in mirror for arbitrary files. Sync copies them through verbatim.

Recommendation: (a) — document the scope boundary in `docs/user/getting-started.md` so users know to git-track helper files alongside their `.agnostic-ai/` source.

---

## Issue 20 — `.agnostic-ai/.sync-state` purpose, format, and lifecycle undocumented 🟢

**Severity**: low (docs)

### Observation

After `sync`, `.agnostic-ai/.sync-state` appears with `{"synced_at": ..., "files_changed": 125}`. Not documented in README, `spec-format.md`, or `configuration.md`. Users will see it in `git status`, wonder if it should be committed, what triggers its update, what its absence means.

Issue #136 (closed) added it to managed `.gitignore`. But there's still no docs on what it is and what consumes it.

### Fix

One short page in `docs/internal/` or a section in `docs/user/configuration.md`:

- What it stores (last sync timestamp, file count).
- What reads it (doctor uses it to detect "sync was run vs never run").
- Whether to commit it (no — already gitignored).
- Whether to delete it (safe — sync regenerates).

---

## Issue 21 — Skill helper file preservation is undocumented (positive finding) 🟢

**Severity**: low (docs gap, but works correctly)
**Related**: closed #177 mentions "Nested skill assets ... keep file-mode bits both directions" — implementation depth. This issue is the docs counterpart: the feature works, but no user-facing documentation announces it.

### What works

Manuscript has:

```
.claude/skills/i18n-parity/check.mjs            (JS helper)
.claude/skills/tiptap-extension/templates/      (template files)
```

Both round-trip byte-identically through import → sync. This is the right behaviour and probably non-trivial to get right. But it's not advertised anywhere in the README.

### Fix

Add a one-paragraph note in `docs/user/spec-format.md` under "Skills":

> Skills may contain helper files (scripts, templates, fixtures) alongside `SKILL.md`. Any non-`.md` file under `.agnostic-ai/skills/<name>/` (and any nested directory) is copied verbatim to the same relative location under each target's skills dir. Useful for shipping check scripts that the skill references.

Tells users this is a supported feature instead of an accident.

---

## Summary

12 issues total (one dropped — see top of file).

| # | Severity | Type | Title | Related |
|---|---|---|---|---|
| 10 | 🔴 high | bug | `doctor` and `sync` disagree on `.claude/settings.json` (drift loop) | — |
| 11 | 🟡 med | docs | README "byte-identical" claim is overstated | — |
| 12 | 🟡 med | docs | Target table misleads on native-path support | — |
| 13 | 🟡 med | design | `settings.json` has two sources of truth | #177 |
| 14 | 🟡 low-med | UX | Capability warnings noisy/unactionable at sync emit | #114 |
| 15 | 🟡 med | UX | `import --dry-run` dumps full file contents | #161 |
| 16 | 🟡 low | docs | Hooks → multi-target schema mapping undocumented | — |
| 17 | 🟡 low | UX | `doctor` drift message lumps all causes together | #159 |
| 18 | 🟡 low | validate | `globs:` patterns not validated against repo paths | #171 |
| 19 | 🟡 low | scope | `import` doesn't capture arbitrary sidecar files | — |
| 20 | 🟢 low | docs | `.agnostic-ai/.sync-state` undocumented | — |
| 21 | 🟢 low | docs | Skill helper file preservation undocumented | #177 |

### Recommended fix order

1. **#10** — high severity, makes `doctor` unusable as a CI gate. Fix first.
2. **#11, #12** — docs correctness. Low effort, high trust impact.
3. **#15** — every user who runs `import --dry-run` hits this. Mirror `sync --plan` shape.
4. **#14** — sync-time capability warning dedup, complements closed #114.
5. **#13, #16** — docs for power users.
6. **#17, #18** — `doctor` / lint enhancements building on closed #159, #171.
7. **#19, #20, #21** — docs / scope cleanup pass.

### Reproduction (still valid from Part 1)

```bash
cd /Users/chema/Code/JesusValeraDev/manuscript
git restore .claude CLAUDE.md
rm -rf .agents .codex AGENTS.md CLAUDE.md.bak .agnostic-ai agnostic-ai.yaml \
       .claude/**/*.bak
echo "claude,codex" | agnostic-ai init
agnostic-ai import claude
agnostic-ai sync --backup

# Issue 10 repro:
agnostic-ai doctor                  # expect ✓, see ✗ claude: drift
agnostic-ai doctor --fix
agnostic-ai sync
agnostic-ai doctor                  # drift returns

# Issue 14 repro:
sed -i '' '/^targets:/a\
  - aider
' agnostic-ai.yaml
agnostic-ai sync --dry-run 2>&1 | grep -c "aider:"
```
