package trae

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestName(t *testing.T) {
	if got := New().Name(); got != "trae" {
		t.Errorf("expected trae, got %s", got)
	}
}

func TestEmit_WritesRulesAgentsAndSkills(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "rule"},
		{Kind: spec.KindAgent, Name: "ag1", Body: "agent"},
		{Kind: spec.KindSkill, Name: "sk1", Path: "skills/sk1/SKILL.md", Body: "skill"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}

	cases := map[string]string{
		".trae/rules/r1.md":         "rule",
		".trae/rules/agent-ag1.md":  "agent",
		".trae/skills/sk1/SKILL.md": "skill",
	}
	for p, want := range cases {
		got, err := os.ReadFile(filepath.Join(dir, p))
		if err != nil {
			t.Fatalf("missing %s: %v", p, err)
		}
		body := string(got)
		if !strings.Contains(body, "Generated by agnostic-ai") {
			t.Errorf("%s missing provenance header:\n%s", p, body)
		}
		if !strings.Contains(body, want) {
			t.Errorf("%s missing body %q:\n%s", p, want, body)
		}
	}

	// The pre-fix flat form must not be written; Trae only loads
	// SKILL.md from a folder (docs.trae.ai/ide/skills), so a skill
	// shipping sibling assets would lose them silently to a rule-form
	// file that was never a skill.
	if _, err := os.Stat(filepath.Join(dir, ".trae/rules/skill-sk1.md")); !os.IsNotExist(err) {
		t.Errorf("expected no flat .trae/rules/skill-sk1.md, err=%v", err)
	}
}

// TestEmit_SkillsDirOverride_WritesToCustomDir confirms
// outputs.trae.skills-dir redirects the folder-per-skill output,
// consistent with every other emit.OutputSkillsDir consumer.
func TestEmit_SkillsDirOverride_WritesToCustomDir(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"trae": {SkillsDir: "custom/skills"}},
	}
	entries := []spec.Entry{{Kind: spec.KindSkill, Name: "sk1", Body: "skill body"}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "custom/skills/sk1/SKILL.md")); err != nil {
		t.Errorf("expected custom/skills/sk1/SKILL.md: %v", err)
	}
}

func TestEmit_WritesCommands(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindCommand, Name: "deploy", Meta: map[string]any{"description": "Ship it"}, Body: "Run the deploy steps."},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".trae/commands/deploy.md"))
	for _, want := range []string{"name: deploy", "description: Ship it", "Run the deploy steps.", "Generated by agnostic-ai"} {
		if !strings.Contains(got, want) {
			t.Errorf("command file missing %q:\n%s", want, got)
		}
	}
}

// TestEmit_CommandDescriptionFallsBackToName mirrors SkillMarkdown's
// convention: a command with no description still gets a non-empty one
// so the required frontmatter key is never written empty.
func TestEmit_CommandDescriptionFallsBackToName(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{{Kind: spec.KindCommand, Name: "deploy", Body: "Run the deploy steps."}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".trae/commands/deploy.md"))
	if !strings.Contains(got, "description: deploy") {
		t.Errorf("expected description to fall back to the command name:\n%s", got)
	}
}

// TestEmit_CommandFrontmatterOmitsUnconfirmedKeys locks the evidence
// this adapter is built on: only `name` and `description` are confirmed
// native to a Trae command file (239 real .trae/commands/*.md files via
// GitHub code search, cross-tool-generated files excluded). A spec that
// sets tools/model/argument-hint (Claude Code's own command vocabulary)
// must not leak them into the Trae file.
func TestEmit_CommandFrontmatterOmitsUnconfirmedKeys(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{
			Kind: spec.KindCommand,
			Name: "deploy",
			Meta: map[string]any{
				"description":   "Ship it",
				"tools":         []any{"Bash"},
				"model":         "opus",
				"argument-hint": "[env]",
			},
			Body: "Run the deploy steps.",
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".trae/commands/deploy.md"))
	for _, leaked := range []string{"tools:", "model:", "argument-hint:"} {
		if strings.Contains(got, leaked) {
			t.Errorf("unexpected leaked frontmatter %q in %s", leaked, got)
		}
	}
}

// TestEmit_CommandXTraeKeyReachesFrontmatter confirms the standard
// x-<target> escape hatch still works for commands: an author-declared
// custom key is an explicit per-spec opt-in, not a key inferred from the
// vendor's default format, so it is not covered by the "only name and
// description" evidence restriction. See #367.
func TestEmit_CommandXTraeKeyReachesFrontmatter(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{
			Kind: spec.KindCommand,
			Name: "deploy",
			Meta: map[string]any{
				"description": "Ship it",
				"x-trae":      map[string]any{"some-trae-key": "value"},
			},
			Body: "Run the deploy steps.",
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".trae/commands/deploy.md"))
	if !strings.Contains(got, "some-trae-key: value") {
		t.Errorf("expected x-trae custom key to reach frontmatter:\n%s", got)
	}
	if strings.Contains(got, "x-trae:") {
		t.Errorf("x-trae wrapper key itself must not leak:\n%s", got)
	}
}

// TestEmit_CommandsDirOverride_WritesToCustomDir confirms
// outputs.trae.commands-dir redirects the per-command output.
func TestEmit_CommandsDirOverride_WritesToCustomDir(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"trae": {CommandsDir: "custom/commands"}},
	}
	entries := []spec.Entry{{Kind: spec.KindCommand, Name: "deploy", Body: "Run the deploy steps."}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "custom/commands/deploy.md")); err != nil {
		t.Errorf("expected custom/commands/deploy.md: %v", err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}

func TestEmit_RulesDirOverride(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"trae": {RulesDir: ".trae/custom-rules"}},
	}
	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "rule body"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".trae/custom-rules/r1.md")); err != nil {
		t.Errorf("override should write to the custom dir: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".trae/rules/r1.md")); !os.IsNotExist(err) {
		t.Errorf("override must not also write the default dir, err=%v", err)
	}
}

func TestEmit_NoRootAGENTSMd_ByDefault(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "rule"},
		{Kind: spec.KindAgent, Name: "ag1", Body: "agent"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("expected no root AGENTS.md written by the adapter, err=%v", err)
	}
}

func TestEmit_EmptyBundle_WritesNothing(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	if err := New().Emit(emit.NewSession(), spec.NewBundle(nil), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".trae")); !os.IsNotExist(err) {
		t.Errorf("expected no .trae dir for an empty bundle, err=%v", err)
	}
}
