package qoder

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestName(t *testing.T) {
	if got := New().Name(); got != "qoder" {
		t.Errorf("expected qoder, got %s", got)
	}
}

func TestEmit_WritesRules(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "rule"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(dir, ".qoder/rules/r1.md"))
	if err != nil {
		t.Fatalf("missing .qoder/rules/r1.md: %v", err)
	}
	body := string(got)
	if !strings.Contains(body, "Generated by agnostic-ai") {
		t.Errorf("missing provenance header:\n%s", body)
	}
	if !strings.Contains(body, "rule") {
		t.Errorf("missing body %q:\n%s", "rule", body)
	}
}

func TestEmit_RulesDirOverride(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"qoder": {RulesDir: ".qoder/custom-rules"}},
	}
	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "rule body"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/custom-rules/r1.md")); err != nil {
		t.Errorf("override should write to the custom dir: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/rules/r1.md")); !os.IsNotExist(err) {
		t.Errorf("override must not also write the default dir, err=%v", err)
	}
}

// Agents and skills have no native Qoder surface, so they must never
// leak into the rules directory even though RulesDirectory could
// flatten them there for other adapters.
func TestEmit_AgentsAndSkillsNotFlattenedIntoRules(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "rule"},
		{Kind: spec.KindAgent, Name: "ag1", Body: "agent"},
		{Kind: spec.KindSkill, Name: "sk1", Body: "skill"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{OnUnsupported: "silent"}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/rules/r1.md")); err != nil {
		t.Errorf("expected rule file written: %v", err)
	}
	for _, p := range []string{".qoder/rules/agent-ag1.md", ".qoder/rules/skill-sk1.md"} {
		if _, err := os.Stat(filepath.Join(dir, p)); !os.IsNotExist(err) {
			t.Errorf("expected %s not to be written, err=%v", p, err)
		}
	}
}

func TestEmit_NoRootAGENTSMd_ByDefault(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "rule"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("expected no root AGENTS.md written by the adapter, err=%v", err)
	}
}

func TestEmit_EmptyBundle_WritesNothing(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	if err := New().Emit(emit.NewSession(), spec.NewBundle(nil), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder")); !os.IsNotExist(err) {
		t.Errorf("expected no .qoder dir for an empty bundle, err=%v", err)
	}
}
