package qoder

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestName(t *testing.T) {
	if got := New().Name(); got != "qoder" {
		t.Errorf("expected qoder, got %s", got)
	}
}

// swapNoteWarner redirects emit.Warner to a buffer for the duration of
// the test and clears any buffered coverage notes before and after.
// Mirrors the identical helper in the claude package; adapter test
// packages cannot share helpers across a no-cross-adapter-imports
// boundary.
func swapNoteWarner(t *testing.T) *strings.Builder {
	t.Helper()
	buf := &strings.Builder{}
	prev := emit.Warner
	emit.Warner = buf
	t.Cleanup(func() { emit.Warner = prev })
	emit.ResetCoverageNotes()
	t.Cleanup(emit.ResetCoverageNotes)
	return buf
}

func TestEmit_WritesRules(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "rule"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(dir, ".qoder/rules/r1.md"))
	if err != nil {
		t.Fatalf("missing .qoder/rules/r1.md: %v", err)
	}
	body := string(got)
	if !strings.Contains(body, "Generated by agnostic-ai") {
		t.Errorf("missing provenance header:\n%s", body)
	}
	if !strings.Contains(body, "rule") {
		t.Errorf("missing body %q:\n%s", "rule", body)
	}
}

func TestEmit_RulesDirOverride(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"qoder": {RulesDir: ".qoder/custom-rules"}},
	}
	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "rule body"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/custom-rules/r1.md")); err != nil {
		t.Errorf("override should write to the custom dir: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/rules/r1.md")); !os.IsNotExist(err) {
		t.Errorf("override must not also write the default dir, err=%v", err)
	}
}

// Agents and skills both have their own native surface (`.qoder/agents/`
// and `.qoder/skills/`), so neither must ever leak into the rules
// directory even though RulesDirectory could flatten them there for
// other adapters.
func TestEmit_AgentsAndSkillsNotFlattenedIntoRules(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "rule"},
		{Kind: spec.KindAgent, Name: "ag1", Body: "agent"},
		{Kind: spec.KindSkill, Name: "sk1", Body: "skill"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{OnUnsupported: "silent"}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/rules/r1.md")); err != nil {
		t.Errorf("expected rule file written: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/agents/ag1.md")); err != nil {
		t.Errorf("expected native agent file written: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/skills/sk1/SKILL.md")); err != nil {
		t.Errorf("expected native skill folder written: %v", err)
	}
	for _, p := range []string{".qoder/rules/agent-ag1.md", ".qoder/rules/skill-sk1.md"} {
		if _, err := os.Stat(filepath.Join(dir, p)); !os.IsNotExist(err) {
			t.Errorf("expected %s not to be written, err=%v", p, err)
		}
	}
}

// Native Agent Skills is documented at `.qoder/skills/<name>/SKILL.md`
// (docs.qoder.com/extensions/skills, target-audit 2026-08-08, #558): "Each
// Skill contains a `SKILL.md` file. A folder without it never registers as
// a skill, so this must land as a folder, not a flattened
// `skill-<name>.md` file, and must carry any bundled sibling asset with
// it.
func TestEmit_Skill_WritesSkillFolder(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindSkill, Name: "reviewer-kit", Meta: map[string]any{"description": "Review helpers."}, Body: "Use these helpers."},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".qoder/skills/reviewer-kit/SKILL.md"))
	for _, want := range []string{"name: reviewer-kit", "description: Review helpers.", "Use these helpers."} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in:\n%s", want, got)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/rules/skill-reviewer-kit.md")); !os.IsNotExist(err) {
		t.Errorf("expected no flat .qoder/rules/skill-reviewer-kit.md, err=%v", err)
	}
}

// TestEmit_SkillsDirOverride_WritesToCustomDir confirms
// outputs.qoder.skills-dir redirects the folder-per-skill output,
// consistent with every other emit.OutputSkillsDir consumer.
func TestEmit_SkillsDirOverride_WritesToCustomDir(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"qoder": {SkillsDir: "custom/skills"}},
	}
	entries := []spec.Entry{{Kind: spec.KindSkill, Name: "sk1", Body: "skill body"}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "custom/skills/sk1/SKILL.md")); err != nil {
		t.Errorf("expected custom/skills/sk1/SKILL.md: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/skills/sk1/SKILL.md")); !os.IsNotExist(err) {
		t.Errorf("expected no output at the default skills dir once overridden, err=%v", err)
	}
}

// name and tools are confirmed safe on real Qoder (target-audit
// 2026-08-01, #529): docs.qoder.com/extensions/subagent documents both
// as agent frontmatter, and Qoder's built-in tool vocabulary is
// Claude-style, so agnostic-ai's generic tools list passes straight
// through (unlike kilo and augment, whose vendor vocabularies differ).
func TestEmit_Agent_WritesAgentFile(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent, Name: "reviewer",
			Meta: map[string]any{
				"description": "Reviews diffs.",
				"model":       "sonnet",
				"tools":       []any{"Read", "Grep", "Bash"},
			},
			Body: "Review the diff for correctness.",
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".qoder/agents/reviewer.md"))
	if !strings.HasPrefix(got, "---\n") {
		t.Fatalf("frontmatter must be first, got:\n%s", got)
	}
	for _, want := range []string{
		"name: reviewer",
		"description: Reviews diffs.",
		"model: sonnet",
		"tools: Read, Grep, Bash",
		"Review the diff for correctness.",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in:\n%s", want, got)
		}
	}
	if strings.Contains(got, "tools: [") || strings.Contains(got, "- Read") {
		t.Errorf("qoder tools must be a comma-separated string, not a list, got:\n%s", got)
	}
}

func TestEmit_Agent_DescriptionFallsBackToName(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{{Kind: spec.KindAgent, Name: "no-desc", Body: "body"}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".qoder/agents/no-desc.md"))
	if !strings.Contains(got, "description: no-desc") {
		t.Errorf("expected description fallback to agent name, got:\n%s", got)
	}
	if strings.Contains(got, "model:") || strings.Contains(got, "tools:") {
		t.Errorf("expected no model/tools keys when absent from meta, got:\n%s", got)
	}
}

// A spec author who already writes Qoder's own comma-separated string
// (typically via x-qoder.tools) must see it pass through unchanged, not
// re-joined or otherwise mangled.
func TestEmit_Agent_ToolsAlreadyStringPassesThroughUnchanged(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent, Name: "alpha",
			Meta: map[string]any{"description": "d", "tools": "Read, Grep, Glob, Bash"},
			Body: "body",
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".qoder/agents/alpha.md"))
	if !strings.Contains(got, "tools: Read, Grep, Glob, Bash") {
		t.Errorf("expected the pre-joined string to pass through unchanged, got:\n%s", got)
	}
}

// skills and mcpServers are documented optional Qoder agent frontmatter
// fields with no agnostic-ai-native shape of their own, so whatever the
// spec declares passes straight through.
func TestEmit_Agent_SkillsAndMCPServersPassThrough(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent, Name: "alpha",
			Meta: map[string]any{
				"description": "d",
				"skills":      []any{"yaml-validator"},
				"mcpServers":  []any{"filesystem"},
			},
			Body: "body",
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".qoder/agents/alpha.md"))
	for _, want := range []string{"skills:", "yaml-validator", "mcpServers:", "filesystem"} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in:\n%s", want, got)
		}
	}
}

// color (docs.qoder.com/cli/subagent field reference: one of eight
// named values, e.g. `cyan`, shown while the Subagent runs in the TUI)
// is a shared portable concept augment.go and kilo.go already promote;
// qoder must too (#588).
func TestEmit_Agent_ColorField(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent, Name: "reviewer",
			Meta: map[string]any{"description": "d", "color": "cyan"},
			Body: "body",
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".qoder/agents/reviewer.md"))
	if !strings.Contains(got, "color: cyan") {
		t.Errorf("missing color: cyan in:\n%s", got)
	}
}

// x-qoder.color overrides a plain top-level color, and must not also
// duplicate the key via the generic x-qoder passthrough below it:
// ResolveMeta already flattens x-qoder.color onto the top-level field
// agentMarkdown's loop reads, the same double-emission risk color, tools
// (see TestEmit_Agent_XQoderToolsOverridesGenericList).
func TestEmit_Agent_XQoderColorOverridesGenericColor(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent, Name: "alpha",
			Meta: map[string]any{
				"description": "d",
				"color":       "red",
				"x-qoder":     map[string]any{"color": "purple"},
			},
			Body: "body",
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".qoder/agents/alpha.md"))
	if !strings.Contains(got, "color: purple") {
		t.Errorf("expected x-qoder.color to win, got:\n%s", got)
	}
	if strings.Count(got, "color:") != 1 {
		t.Errorf("expected exactly one color: line, got:\n%s", got)
	}
}

// x-qoder cannot reintroduce name: the file identity always comes from
// the spec name, matching every other AGENTS.md-family target's
// per-file surface.
func TestEmit_Agent_XQoderCannotReintroduceName(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent, Name: "alpha",
			Meta: map[string]any{
				"description": "d",
				"x-qoder":     map[string]any{"name": "override"},
			},
			Body: "body",
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".qoder/agents/alpha.md"))
	if strings.Contains(got, "override") {
		t.Errorf("x-qoder must not override the spec-derived name, got:\n%s", got)
	}
	if !strings.Contains(got, "name: alpha") {
		t.Errorf("expected name: alpha, got:\n%s", got)
	}
}

// x-qoder.tools overrides a plain top-level tools list: ResolveMeta
// flattens the target-scoped block on top of the generic field before
// agentMarkdown ever sees it, so the escape hatch wins.
func TestEmit_Agent_XQoderToolsOverridesGenericList(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent, Name: "alpha",
			Meta: map[string]any{
				"description": "d",
				"tools":       []any{"Read"},
				"x-qoder":     map[string]any{"tools": "Bash, WebFetch"},
			},
			Body: "body",
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".qoder/agents/alpha.md"))
	if !strings.Contains(got, "tools: Bash, WebFetch") {
		t.Errorf("expected x-qoder.tools to win, got:\n%s", got)
	}
	if strings.Count(got, "tools:") != 1 {
		t.Errorf("expected exactly one tools: line, got:\n%s", got)
	}
}

// Arbitrary x-qoder keys pass through so the full agent schema is
// reachable without waiting on this adapter's allowlist.
func TestEmit_Agent_XQoderPassthrough(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent, Name: "alpha",
			Meta: map[string]any{"description": "d", "x-qoder": map[string]any{"temperature": "0.2"}},
			Body: "body",
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".qoder/agents/alpha.md"))
	if !strings.Contains(got, "temperature:") {
		t.Errorf("expected x-qoder key to pass through, got:\n%s", got)
	}
}

func TestEmit_AgentsDirOverride(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{Outputs: map[string]config.Output{"qoder": {AgentsDir: "custom/agents"}}}
	entries := []spec.Entry{{Kind: spec.KindAgent, Name: "a1", Body: "body"}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "custom/agents/a1.md")); err != nil {
		t.Errorf("expected override dir to hold the agent file: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/agents/a1.md")); !os.IsNotExist(err) {
		t.Errorf("expected no output at the default agents dir, err=%v", err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}

func TestEmit_NoRootAGENTSMd_ByDefault(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "rule"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("expected no root AGENTS.md written by the adapter, err=%v", err)
	}
}

func TestEmit_EmptyBundle_WritesNothing(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	if err := New().Emit(emit.NewSession(), spec.NewBundle(nil), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder")); !os.IsNotExist(err) {
		t.Errorf("expected no .qoder dir for an empty bundle, err=%v", err)
	}
}

// Stdio MCP merges into .qoder/settings.json under the standard
// mcpServers map, one of the two project-level locations
// docs.qoder.com/cli/mcp-reference's scope table documents (#641).
func TestEmit_MCP_StdioWritesQoderSettings(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "fs",
			Meta: map[string]any{
				"command": "npx",
				"args":    []any{"-y", "@modelcontextprotocol/server-filesystem", "."},
				"env":     map[string]any{"ALLOWED_PATHS": "."},
			},
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".qoder/settings.json"))
	if err != nil {
		t.Fatalf("missing .qoder/settings.json: %v", err)
	}
	body := string(got)
	for _, want := range []string{`"mcpServers"`, `"fs"`, `"command": "npx"`, `"ALLOWED_PATHS"`} {
		if !strings.Contains(body, want) {
			t.Errorf("missing %q in %s", want, body)
		}
	}
	if strings.Contains(body, `"type"`) {
		t.Errorf("stdio is the inferred default; type must stay unset, got:\n%s", body)
	}
}

func TestEmit_MCP_HTTPWritesTypeAndURL(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "linear",
			Meta: map[string]any{
				"type":    "http",
				"url":     "https://mcp.linear.app",
				"headers": map[string]any{"Authorization": "Bearer x"},
			},
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".qoder/settings.json"))
	if err != nil {
		t.Fatal(err)
	}
	body := string(got)
	for _, want := range []string{`"type": "http"`, `"url": "https://mcp.linear.app"`, `"Authorization"`} {
		if !strings.Contains(body, want) {
			t.Errorf("missing %q in %s", want, body)
		}
	}
}

// docs.qoder.com/cli/mcp-reference documents `disabled` as "Disables
// the server (keeps the configuration without deleting it)". It never
// emitted while qoder shared Claude Code's `.mcp.json`, where the key
// means nothing. Now that qoder writes its own file, the key is Qoder's
// own and lands as written, with no coverage note (#641).
func TestEmit_MCP_DisabledEmitsOnQoderSettings(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)
	buf := swapNoteWarner(t)

	entries := []spec.Entry{
		{Kind: spec.KindMCP, Name: "fs", Meta: map[string]any{"command": "npx", "disabled": true}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".qoder/settings.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), `"disabled": true`) {
		t.Errorf("expected disabled to reach .qoder/settings.json: %s", got)
	}

	emit.FlushCoverageNotes()
	if strings.Contains(buf.String(), "`disabled` on 1 mcp has no effect on qoder") {
		t.Errorf("disabled works on qoder now; the no-op note must be gone, got: %s", buf.String())
	}
}

// The nine "Common Optional Fields" plus the stdio table's `cwd`. None
// reached an emitted file before #641, top-level or namespaced.
func TestEmit_MCP_PassesThroughDocumentedOptionalFields(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "fs",
			Meta: map[string]any{
				"command":     "npx",
				"cwd":         "/srv/project",
				"timeout":     4500,
				"description": "Filesystem access",
				"trust":       true,
			},
		},
		{
			Kind: spec.KindMCP,
			Name: "linear",
			Meta: map[string]any{
				"type":         "http",
				"url":          "https://mcp.linear.app",
				"includeTools": []any{"list_issues"},
				"excludeTools": []any{"delete_issue"},
				"alwaysAllow":  []any{"list_issues"},
				"oauth":        map[string]any{"clientId": "abc", "callbackPort": 7778},
			},
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readSettings(t, filepath.Join(dir, ".qoder/settings.json"))
	for _, want := range []string{
		`"cwd": "/srv/project"`,
		`"timeout": 4500`,
		`"description": "Filesystem access"`,
		`"trust": true`,
		`"includeTools"`,
		`"list_issues"`,
		`"excludeTools"`,
		`"delete_issue"`,
		`"alwaysAllow"`,
		`"oauth"`,
		`"clientId": "abc"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

// MergeJSONFile, not WriteMCPFile: `.qoder/settings.json` is where
// Qoder also keeps `mcp.enableAllProjectMcpServers`, permissions, and
// custom models, so a sync must leave every key but `mcpServers` alone.
func TestEmit_MCP_PreservesUnrelatedSettingsKeys(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	if err := os.MkdirAll(filepath.Join(dir, ".qoder"), 0o755); err != nil {
		t.Fatal(err)
	}
	existing := `{"mcp":{"enableAllProjectMcpServers":true},"outputStyle":"concise"}`
	if err := os.WriteFile(filepath.Join(dir, ".qoder/settings.json"), []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := []spec.Entry{
		{Kind: spec.KindMCP, Name: "fs", Meta: map[string]any{"command": "npx"}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readSettings(t, filepath.Join(dir, ".qoder/settings.json"))
	for _, want := range []string{`"enableAllProjectMcpServers"`, `"outputStyle"`, `"mcpServers"`} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

func readSettings(t *testing.T, path string) string {
	t.Helper()
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(got)
}

func TestEmit_MCP_FileOverride(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"qoder": {MCPFile: "vendor/qoder-mcp.json"},
		},
	}
	entries := []spec.Entry{
		{Kind: spec.KindMCP, Name: "fs", Meta: map[string]any{"command": "npx"}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "vendor/qoder-mcp.json")); err != nil {
		t.Errorf("expected override path written: %v", err)
	}
}

func TestEmit_NoMCPJSONWhenNoMCPs(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{{Kind: spec.KindRule, Name: "r1", Body: "x"}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/settings.json")); !os.IsNotExist(err) {
		t.Errorf("expected no .qoder/settings.json when no MCP entries, err=%v", err)
	}
}

// TestEmit_MCP_NoLongerSharesClaudesFile pins the #641 split. Qoder and
// Claude Code both document a project-root `.mcp.json`, and this
// adapter wrote there while their emitted bytes stayed identical. They
// no longer can: Qoder documents `trust`, `includeTools`,
// `excludeTools`, `alwaysAllow` and a working `disabled`; Claude Code
// documents `headersHelper` and `alwaysLoad`. Two adapters writing
// different bytes to one path is a hard error in sync's collision
// check, on a pair of targets both in the default set, so qoder moved
// to its own documented project-level location.
func TestEmit_MCP_NoLongerSharesClaudesFile(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindMCP, Name: "fs", Meta: map[string]any{"command": "npx", "trust": true}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".mcp.json")); !os.IsNotExist(err) {
		t.Errorf("qoder must not write the project-root .mcp.json claude owns, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".qoder/settings.json")); err != nil {
		t.Errorf("expected .qoder/settings.json written: %v", err)
	}
}
