// Package copilot emits .github/copilot-instructions.md for GitHub Copilot.
package copilot

import (
	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

const (
	target         = "copilot"
	defaultOutFile = ".github/copilot-instructions.md"
)

var caps = emit.Capabilities{
	Target:   target,
	Supports: []spec.Kind{spec.KindAgent, spec.KindRule},
}

// Adapter emits GitHub Copilot configs.
type Adapter struct{}

// New returns a Copilot adapter.
func New() *Adapter { return &Adapter{} }

// Name returns the target identifier.
func (Adapter) Name() string { return target }

// Emit writes .github/copilot-instructions.md.
func (Adapter) Emit(b spec.Bundle, cfg *config.Config, dryRun bool) error {
	if err := emit.ReportUnsupported(caps, b, cfg.OnUnsupported); err != nil {
		return err
	}
	return emit.MergedDocument(b, emit.MergedOpts{
		OutFile:            outFile(cfg),
		Title:              "GitHub Copilot Instructions",
		Intro:              "Generated by agnostic-ai.",
		AgentSectionPrefix: "Agent: ",
	}, dryRun)
}

func outFile(cfg *config.Config) string {
	if o, ok := cfg.Outputs[target]; ok && o.File != "" {
		return o.File
	}
	return defaultOutFile
}
