// Package copilot emits .github/copilot-instructions.md for GitHub Copilot.
package copilot

import (
	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

const (
	target         = "copilot"
	defaultOutFile = ".github/copilot-instructions.md"
	defaultMCPFile = ".vscode/mcp.json"
)

var caps = emit.Capabilities{
	Target:   target,
	Supports: []spec.Kind{spec.KindAgent, spec.KindSkill, spec.KindRule, spec.KindMCP},
}

// Adapter emits GitHub Copilot configs.
type Adapter struct{}

// New returns a Copilot adapter.
func New() *Adapter { return &Adapter{} }

// Name returns the target identifier.
func (Adapter) Name() string { return target }

// Emit writes the Copilot instructions and, when MCP entries exist,
// a `.vscode/mcp.json` using the VS Code servers schema.
func (Adapter) Emit(b spec.Bundle, cfg *config.Config, dryRun bool) error {
	if err := emit.ReportUnsupported(caps, b, cfg.OnUnsupported); err != nil {
		return err
	}
	if err := emit.MergedDocument(b, emit.MergedOpts{
		OutFile:            emit.OutputFile(cfg, target, defaultOutFile),
		Title:              "GitHub Copilot Instructions",
		Intro:              "Generated by agnostic-ai. Do not edit by hand.",
		AgentSectionPrefix: "Agent: ",
	}, dryRun); err != nil {
		return err
	}
	return emit.WriteMCPFile(b.MCPs, emit.MCPSchemaVSCodeServers, emit.OutputMCPFile(cfg, target, defaultMCPFile), dryRun)
}
