package cli

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/chemaclass/agnostic-ai/internal/adapters"
)

// reduceToGeneratedRules returns the inner content of the sync-generated
// rules appendix when the sentinel markers are present, so importers
// reconstruct rule specs from the inlined block and discard the
// regenerable pointer body and target-overview. Returns body unchanged
// when no rules block is present: hand-authored entry-points and legacy
// concatenated rules-files slice in full.
func reduceToGeneratedRules(body string) string {
	start := strings.Index(body, adapters.RulesStartMarker)
	if start < 0 {
		return body
	}
	inner := body[start+len(adapters.RulesStartMarker):]
	if end := strings.Index(inner, adapters.RulesEndMarker); end >= 0 {
		inner = inner[:end]
	}
	return inner
}

// extractMarkedBlock returns the inner content between start and end
// sentinel markers in body, "" when start is absent. Unlike
// reduceToGeneratedRules (which falls back to the whole body so a
// hand-authored file still slices in full), callers here need to tell
// "block present but empty" apart from "no block at all", so an absent
// start marker reports as no content instead.
func extractMarkedBlock(body, start, end string) string {
	i := strings.Index(body, start)
	if i < 0 {
		return ""
	}
	inner := body[i+len(start):]
	if j := strings.Index(inner, end); j >= 0 {
		inner = inner[:j]
	}
	return inner
}

// extractLeadingItalic returns the inner text of a `_..._` paragraph
// at the start of body (no surrounding whitespace) and the body with
// that paragraph plus its trailing blank line stripped. ok is false
// when body does not begin with a single-line italic paragraph.
//
// Several adapters render `description:` as a leading italic paragraph
// in the emitted markdown. Importers use this helper to reverse that
// transformation so a description round-trips through frontmatter
// rather than accumulating as body content.
func extractLeadingItalic(body string) (desc, stripped string, ok bool) {
	trimmed := strings.TrimLeft(body, "\n")
	nl := strings.IndexByte(trimmed, '\n')
	var first string
	if nl < 0 {
		first = trimmed
	} else {
		first = trimmed[:nl]
	}
	first = strings.TrimSpace(first)
	if len(first) < 3 || !strings.HasPrefix(first, "_") || !strings.HasSuffix(first, "_") {
		return "", body, false
	}
	if strings.Count(first, "_") != 2 {
		return "", body, false
	}
	desc = first[1 : len(first)-1]
	rest := ""
	if nl >= 0 {
		rest = strings.TrimLeft(trimmed[nl+1:], "\n")
	}
	return desc, rest, true
}

// mergedDocWrapperHeadings are the H2 headings the central
// MergedDocument emitter writes (Rules / Agents / Skills) and whose
// H3 children are the actual specs. When the importer encounters one
// of these wrappers, it unwraps each H3 child into its own rule file
// so a sync -> import -> sync round-trip lands at a fixed point
// instead of nesting the wrapper deeper on every cycle (#340).
var mergedDocWrapperHeadings = map[string]bool{
	"rules":  true,
	"agents": true,
	"skills": true,
}

// mergedDocPreambleRE matches the central MergedDocument preamble
// ("Generated by agnostic-ai." sitting alone after the H1) so the
// importer can drop it instead of carrying it through as a `project`
// rule body. The header.Strip pipeline removes the provenance comment
// from emitted files; this regex removes the prose intro line that
// MergedDocument layers on top.
var mergedDocPreambleRE = regexp.MustCompile(`(?m)^Generated by agnostic-ai\.[ \t]*$`)

// mergedDocTitleRE matches a leading H1 (`# Title`) that the central
// MergedDocument emits as its document title. The importer drops it
// before the preamble survives as a rule body so a round-trip does not
// resurrect the title as a synthetic `project` rule.
var mergedDocTitleRE = regexp.MustCompile(`(?m)\A#[ \t]+[^\n]*\n?`)

// mergedDocSourceCommentRE matches the inline `<!-- source: ... -->`
// provenance comments WriteSection writes before each rule/agent
// body. Stripping them before the rule body lands in `.agnostic-ai/
// rules/*.md` avoids double-stamping the comment on the next sync.
var mergedDocSourceCommentRE = regexp.MustCompile(`(?m)^[ \t]*<!--\s*source:\s*[^\n]*-->[ \t]*\n?`)

// sliceMainFileByH2 splits <root>/<srcName> on `## ` headings into one
// rule per section in dstDir. Without headings it writes a single rule
// named after the project directory. No-op when the source file is
// absent or empty. Reused by every importer whose target keeps rules
// in a single concatenated markdown file (CONVENTIONS.md, AGENTS.md,
// GEMINI.md, .rules, .agent/AGENTS.md, etc.).
//
// Files emitted by the central MergedDocument helper (Rules / Agents /
// Skills wrapper H2s) get their H3 children unwrapped into one rule
// each and have provenance preamble + `<!-- source: ... -->` comments
// stripped from rule bodies so a sync -> import -> sync round-trip is
// byte-stable instead of nesting the wrapper deeper on every cycle.
func sliceMainFileByH2(root, srcName, dstDir string) (int, error) {
	src := filepath.Join(root, srcName)
	data, err := os.ReadFile(src)
	if errors.Is(err, fs.ErrNotExist) {
		return 0, nil
	}
	if err != nil {
		return 0, fmt.Errorf("read %s: %w", src, err)
	}

	// When sync inlined the rules into a sentinel block, reconstruct the
	// specs from that block alone and ignore the regenerable pointer
	// body (and target-overview). A no-op on hand-authored or legacy
	// concatenated files, which slice in full as before.
	body := reduceToGeneratedRules(string(data))

	preamble, sections := splitH2Sections(body)
	preamble = stripMergedDocPreamble(preamble)
	if len(sections) == 0 {
		flat := strings.TrimSpace(body)
		if flat == "" {
			return 0, nil
		}
		name := projectSlug(root)
		path := filepath.Join(dstDir, name+".md")
		if err := writeRule(path, name, flat); err != nil {
			return 0, err
		}
		return 1, nil
	}

	used := map[string]int{}
	for _, s := range sections {
		used[s.slug] = 1
	}
	count := 0
	if preamble != "" {
		slug := preambleSlug(preamble, used)
		path := filepath.Join(dstDir, slug+".md")
		if err := writeRule(path, slug, preamble); err != nil {
			return 0, err
		}
		count++
	}
	for _, s := range sections {
		if mergedDocWrapperHeadings[s.slug] {
			children, ok := unwrapMergedH3Children(s.body, used)
			if ok {
				for _, c := range children {
					path := filepath.Join(dstDir, c.slug+".md")
					if err := writeRule(path, c.slug, c.body); err != nil {
						return count, err
					}
					count++
				}
				continue
			}
		}
		body := stripMergedDocSourceComment(s.body)
		path := filepath.Join(dstDir, s.slug+".md")
		if err := writeRule(path, s.slug, body); err != nil {
			return count, err
		}
		count++
	}
	return count, nil
}

// stripMergedDocPreamble removes the central MergedDocument intro line
// ("Generated by agnostic-ai.") plus its companion H1 title so the
// preamble does not survive as a synthetic `project` rule body. The H1
// strip only fires when the intro line is present so hand-authored
// CLAUDE.md / CONVENTIONS.md files keep their leading H1 (which the
// importer maps to a preamble slug).
func stripMergedDocPreamble(s string) string {
	if s == "" {
		return s
	}
	if !mergedDocPreambleRE.MatchString(s) {
		return s
	}
	s = mergedDocTitleRE.ReplaceAllString(s, "")
	s = mergedDocPreambleRE.ReplaceAllString(s, "")
	return strings.TrimSpace(s)
}

// stripMergedDocSourceComment removes inline `<!-- source: ... -->`
// provenance comments so the rule body does not double-stamp itself on
// the next sync.
func stripMergedDocSourceComment(s string) string {
	return strings.TrimSpace(mergedDocSourceCommentRE.ReplaceAllString(s, ""))
}

// mergedH3Child holds one unwrapped H3 entry from a Rules / Agents /
// Skills wrapper H2 section.
type mergedH3Child struct{ slug, body string }

// unwrapMergedH3Children splits a wrapper H2's body by `### ` into one
// entry per child, dropping italic descriptions and `<!-- source -->`
// comments from each body. Returns (nil, false) when the wrapper has
// no H3 children so the caller can fall back to writing the wrapper as
// a single rule.
func unwrapMergedH3Children(body string, used map[string]int) ([]mergedH3Child, bool) {
	idx := h3HeadingRE.FindAllStringSubmatchIndex(body, -1)
	if len(idx) == 0 {
		return nil, false
	}
	out := make([]mergedH3Child, 0, len(idx))
	for i, m := range idx {
		title := body[m[2]:m[3]]
		slug := slugify(title)
		if slug == "" {
			slug = fmt.Sprintf("section-%d", i+1)
		}
		slug = dedupSlug(used, slug)
		bodyStart := m[1]
		bodyEnd := len(body)
		if i+1 < len(idx) {
			bodyEnd = idx[i+1][0]
		}
		secBody := strings.TrimSpace(body[bodyStart:bodyEnd])
		secBody = stripMergedDocSourceComment(secBody)
		_, secBody, _ = extractLeadingItalic(secBody)
		out = append(out, mergedH3Child{slug: slug, body: strings.TrimSpace(secBody)})
	}
	return out, true
}

// writeAgentMD writes an agent spec to path with a name + optional
// description and tags frontmatter, followed by body.
func writeAgentMD(path, name, description string, tags []string, body string) error {
	var sb strings.Builder
	sb.WriteString("---\nname: " + name + "\n")
	if description != "" {
		sb.WriteString(yamlFrontmatterLine("description", description))
	}
	if len(tags) > 0 {
		sb.WriteString("tags: [" + strings.Join(tags, ", ") + "]\n")
	}
	sb.WriteString("---\n\n")
	sb.WriteString(strings.TrimRight(body, "\n"))
	sb.WriteString("\n")
	if err := importWriteFile(path, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
