package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestImportFromCodex_NoAgentsMd(t *testing.T) {
	dir := t.TempDir()
	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}
	entries, _ := os.ReadDir(filepath.Join(dir, "rules"))
	if len(entries) != 0 {
		t.Errorf("expected empty rules/, got %d entries", len(entries))
	}
}

func TestImportFromCodex_HandWrittenSplitsByH2(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "AGENTS.md"), `# Project Conventions

Use semantic versioning.

## go-style

gofmt-clean. No init() in business code.

## commits

Conventional Commits, subject < 72 chars.
`)
	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"go-style", "commits"} {
		path := filepath.Join(dir, "rules", name+".md")
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("missing %s: %v", path, err)
		}
		if !strings.Contains(string(data), "name: "+name) {
			t.Errorf("expected name: %s in %s", name, data)
		}
	}
}

func TestImportFromCodex_MonolithicAgentsMd(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "AGENTS.md"), "Just a flat doc.\n")
	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir(filepath.Join(dir, "rules"))
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 {
		t.Fatalf("expected 1 rule, got %d", len(entries))
	}
}

func TestImportFromCodex_AgnosticEmittedFormat(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "AGENTS.md"), `# AGENTS.md

Generated by agnostic-ai. Do not edit by hand.

## Conventions

### conventional-commits

_Always use Conventional Commits._

Use feat:, fix:, etc.

### go-style

_gofmt-clean code._

No init() functions in business code.
`)
	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(dir, "rules", "conventional-commits.md"))
	if err != nil {
		t.Fatal(err)
	}
	out := string(got)
	for _, want := range []string{
		"name: conventional-commits",
		"description: Always use Conventional Commits.",
		"Use feat:, fix:, etc.",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in:\n%s", want, out)
		}
	}
	if strings.Contains(out, "_Always use Conventional Commits._") {
		t.Errorf("italic description leaked into body:\n%s", out)
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "agents-md.md")); err == nil {
		t.Error("did not expect a rule from the # AGENTS.md header")
	}
}

func TestImportFromCodex_AggressiveItalicExtraction(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "AGENTS.md"), `## rule-a

_Short desc._

Body of A.

## rule-b

_Multi
line italic._

Body of B.

## rule-c

Plain body, no italic.
`)
	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}

	a, _ := os.ReadFile(filepath.Join(dir, "rules", "rule-a.md"))
	if !strings.Contains(string(a), "description: Short desc.") {
		t.Errorf("rule-a missing description, got:\n%s", a)
	}
	if strings.Contains(string(a), "_Short desc._") {
		t.Errorf("rule-a italic leaked into body:\n%s", a)
	}

	b, _ := os.ReadFile(filepath.Join(dir, "rules", "rule-b.md"))
	if strings.Contains(string(b), "description:") {
		t.Errorf("rule-b should have no description (multi-line italic), got:\n%s", b)
	}

	c, _ := os.ReadFile(filepath.Join(dir, "rules", "rule-c.md"))
	if strings.Contains(string(c), "description:") {
		t.Errorf("rule-c should have no description, got:\n%s", c)
	}
}

func TestImportFromCodex_NestedAgentsMdInfersGlobs(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "AGENTS.md"), "## root-rule\n\nproject-wide.\n")
	writeFile(t, filepath.Join(dir, "src", "AGENTS.md"), "## src-rule\n\nscoped to src.\n")
	writeFile(t, filepath.Join(dir, "docs", "api", "AGENTS.md"), "## api-rule\n\nscoped to docs/api.\n")

	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}

	root, _ := os.ReadFile(filepath.Join(dir, "rules", "root-rule.md"))
	if strings.Contains(string(root), "globs:") {
		t.Errorf("root rule should not have globs, got:\n%s", root)
	}

	src, _ := os.ReadFile(filepath.Join(dir, "rules", "src-rule.md"))
	if !strings.Contains(string(src), "globs: src/**") {
		t.Errorf("src rule missing globs: src/**, got:\n%s", src)
	}

	api, _ := os.ReadFile(filepath.Join(dir, "rules", "api-rule.md"))
	if !strings.Contains(string(api), "globs: docs/api/**") {
		t.Errorf("api rule missing globs: docs/api/**, got:\n%s", api)
	}
}

func TestImportFromCodex_SlugCollisionAcrossFiles(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "AGENTS.md"), "## style\n\nroot style.\n")
	writeFile(t, filepath.Join(dir, "src", "AGENTS.md"), "## style\n\nsrc style.\n")

	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"style.md", "style-2.md"} {
		if _, err := os.Stat(filepath.Join(dir, "rules", want)); err != nil {
			t.Errorf("expected %s after collision, got: %v", want, err)
		}
	}
}

func TestImportFromCodex_SkipsConventionsWrapper(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "AGENTS.md"), `# AGENTS.md

## Conventions

### real-rule

body
`)
	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "conventions.md")); err == nil {
		t.Error("did not expect a 'conventions' rule from the wrapper section")
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "real-rule.md")); err != nil {
		t.Errorf("expected real-rule.md, got: %v", err)
	}
}

func TestImportCmd_CodexRoutes(t *testing.T) {
	dir := t.TempDir()
	writeMinimalConfig(t, dir, ".agnostic-ai")
	writeFile(t, filepath.Join(dir, "AGENTS.md"), "## routed\n\nbody\n")
	testutil.Chdir(t, dir)
	silence(t)

	root := NewRootCmd("test")
	root.SetArgs([]string{"import", "codex"})
	if err := root.Execute(); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".agnostic-ai", "rules", "routed.md")); err != nil {
		t.Error("expected .agnostic-ai/rules/routed.md after import codex")
	}
}
