package cli

import (
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters/header"
	"github.com/chemaclass/agnostic-ai/internal/errs"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestImportTrae_SharedSkillsPreserveAssetsAndFilterGeneratedFiles(t *testing.T) {
	testutil.Chdir(t, t.TempDir())
	silence(t)
	writeFile(t, "agnostic-ai.yaml", "version: 1\ntargets: [trae]\n")
	const skill = "---\nname: demo\ndescription: Demo skill.\n---\nRead references/checks.md.\n"
	writeFile(t, ".agents/skills/demo/SKILL.md", skill)
	const asset = "Example: `Generated by agnostic-ai`.\n"
	writeFile(t, ".agents/skills/demo/references/checks.md", asset)
	writeFile(t, ".agents/skills/demo/references/generated.md", header.Line(header.FormatMarkdown)+"Generated helper.\n")
	execCLI(t, "import", "trae")
	if got := readFile(t, ".agnostic-ai/skills/demo/SKILL.md"); got != skill {
		t.Errorf("skill = %q, want %q", got, skill)
	}
	if got := readFile(t, ".agnostic-ai/skills/demo/references/checks.md"); got != asset {
		t.Errorf("asset = %q, want %q", got, asset)
	}
	if _, err := os.Stat(".agnostic-ai/skills/demo/references/generated.md"); !errors.Is(err, os.ErrNotExist) {
		t.Errorf("generated file imported: %v", err)
	}
}

func TestImportTrae_NativeSkillWinsOverSharedDuplicate(t *testing.T) {
	testutil.Chdir(t, t.TempDir())
	silence(t)
	writeFile(t, "agnostic-ai.yaml", "version: 1\ntargets: [trae]\n")
	const skill = "---\nname: demo\ndescription: Demo skill.\n---\nNative guidance.\n"
	writeFile(t, ".trae/skills/demo/SKILL.md", skill)
	writeFile(t, ".trae/skills/demo/references/native.txt", "Native asset.\n")
	writeFile(t, ".agents/skills/demo/SKILL.md", strings.ReplaceAll(skill, "Native", "Shared"))
	writeFile(t, ".agents/skills/demo/references/shared.txt", "Shared asset.\n")
	execCLI(t, "import", "trae")
	if got := readFile(t, ".agnostic-ai/skills/demo/SKILL.md"); got != skill {
		t.Errorf("skill = %q, want native skill", got)
	}
	if got := readFile(t, ".agnostic-ai/skills/demo/references/native.txt"); got != "Native asset.\n" {
		t.Errorf("native asset = %q", got)
	}
	if _, err := os.Stat(".agnostic-ai/skills/demo/references/shared.txt"); !errors.Is(err, os.ErrNotExist) {
		t.Errorf("duplicate shared asset imported: %v", err)
	}
}

func TestImportTrae_SharedSkillRefusesLossyExistingSpecReplacement(t *testing.T) {
	testutil.Chdir(t, t.TempDir())
	silence(t)
	writeFile(t, "agnostic-ai.yaml", "version: 1\ntargets: [trae]\n")
	const source = "---\nname: demo\ndescription: Demo skill.\n---\nShared body.\n\n::target codex\nCodex-only step.\n::end\n"
	writeFile(t, ".agnostic-ai/skills/demo/SKILL.md", source)
	execCLI(t, "sync")
	writeFile(t, ".agents/skills/demo/SKILL.md", "---\nname: demo\ndescription: Demo skill.\n---\nEdited body.\n")
	writeFile(t, ".agents/skills/demo/references/new.txt", "Do not write on conflict.\n")
	if err := os.Rename(".trae/skills", ".trae/saved-skills"); err != nil {
		t.Fatal(err)
	}
	for _, args := range [][]string{{"import", "trae", "--dry-run", "--diff"}, {"import", "trae"}} {
		_, err := runCLI(t, args...)
		if errs.CodeOf(err) != errs.CodeImportWouldReplace {
			t.Errorf("%v = %v, want AAI-203", args, err)
		}
	}
	if _, err := os.Stat(".agnostic-ai/skills/demo/references/new.txt"); !errors.Is(err, os.ErrNotExist) {
		t.Errorf("asset written despite source conflict: %v", err)
	}
	if got := readFile(t, ".agnostic-ai/skills/demo/SKILL.md"); got != source {
		t.Errorf("source replaced:\n%s", got)
	}
}
