package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters"
	"github.com/chemaclass/agnostic-ai/internal/adapters/claude"
	"github.com/chemaclass/agnostic-ai/internal/adapters/header"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// rootSources returns a Sources value pointing at root-level kind dirs,
// matching the importer test fixtures.
func rootSources() config.Sources {
	return config.Sources{
		Agents:       "agents",
		Skills:       "skills",
		Rules:        "rules",
		Hooks:        "hooks",
		MCPs:         "mcps",
		Commands:     "commands",
		Settings:     "settings",
		Environments: "environments",
	}
}

func TestImportFromClaude_SplitsRulesByH2(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), generatedEntry(`# Project

## conventional-commits

Use feat:, fix:, etc.

## go-style

gofmt clean.
`))
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"conventional-commits", "go-style"} {
		path := filepath.Join(dir, "rules", name+".md")
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("missing %s: %v", path, err)
		}
		if !strings.Contains(string(data), "name: "+name) {
			t.Errorf("expected frontmatter name: %s in %s", name, data)
		}
	}
}

func TestImportFromClaude_MonolithicRules(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), generatedEntry("Just a flat doc with no headings.\n"))
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir(filepath.Join(dir, "rules"))
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 {
		t.Fatalf("expected 1 rule, got %d", len(entries))
	}
}

func TestImportFromClaude_PrefersClaudeRulesDir(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), "## sliced\n\nFrom CLAUDE.md\n")
	ruleBody := "---\nname: go-style\n---\n\ngofmt clean.\n"
	writeFile(t, filepath.Join(dir, ".claude", "rules", "go-style.md"), ruleBody)
	writeFile(t, filepath.Join(dir, ".claude", "rules", "tests.md"), "tests body\n")

	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(dir, "rules", "go-style.md"))
	if err != nil {
		t.Fatalf("missing rules/go-style.md: %v", err)
	}
	if string(got) != ruleBody {
		t.Errorf("rule not byte-identical. got %q", got)
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "tests.md")); err != nil {
		t.Errorf("missing rules/tests.md: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "sliced.md")); !os.IsNotExist(err) {
		t.Errorf("CLAUDE.md should not have been sliced when .claude/rules exists: %v", err)
	}
}

func TestImportFromClaude_EmptyClaudeRulesDirSkipsSlicing(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), "## sliced\n\nFrom CLAUDE.md\n")
	if err := os.MkdirAll(filepath.Join(dir, ".claude", "rules"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "sliced.md")); !os.IsNotExist(err) {
		t.Errorf("empty .claude/rules should still suppress slicing: %v", err)
	}
}

func TestImportFromClaude_WritesagnosticMainFile(t *testing.T) {
	dir := t.TempDir()
	body := "# Project\n\nTop-level instructions.\n\n## conventional-commits\n\nUse feat:.\n"
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), body)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, agnosticMainFile))
	if err != nil {
		t.Fatalf("missing %s: %v", agnosticMainFile, err)
	}
	if string(got) != body {
		t.Errorf("AGNOSTIC_AI.md not byte-identical to CLAUDE.md. got %q", got)
	}
}

func TestImportFromClaude_StripsProvenanceHeaderFromMainFile(t *testing.T) {
	dir := t.TempDir()
	body := "# Project\n\nTop-level instructions.\n"
	// A synced CLAUDE.md carries the provenance header on line 1.
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), header.With(body, header.FormatMarkdown))
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, agnosticMainFile))
	if err != nil {
		t.Fatalf("missing %s: %v", agnosticMainFile, err)
	}
	if strings.Contains(string(got), "Generated by agnostic-ai") {
		t.Errorf("provenance header leaked into %s: %s", agnosticMainFile, got)
	}
	if string(got) != body {
		t.Errorf("seed not byte-identical to header-stripped body.\nwant:\n%s\ngot:\n%s", body, got)
	}
}

func TestImportFromClaude_NoagnosticMainFileWhenClaudeMdMissing(t *testing.T) {
	dir := t.TempDir()
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, agnosticMainFile)); !os.IsNotExist(err) {
		t.Errorf("expected no AGNOSTIC_AI.md when CLAUDE.md absent: %v", err)
	}
}

func TestImportFromClaude_NoClaudeMd(t *testing.T) {
	dir := t.TempDir()
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	entries, _ := os.ReadDir(filepath.Join(dir, "rules"))
	if len(entries) != 0 {
		t.Errorf("expected empty rules/, got %d entries", len(entries))
	}
}

func TestImportFromClaude_FullSyncImportCycleIsMarkerStable(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)
	original := "---\nname: reviewer\ndescription: code review\n---\n\nReview diffs.\n"
	writeFile(t, filepath.Join(dir, ".claude", "agents", "reviewer.md"), original)

	srcs := rootSources()
	if err := importFromClaude(dir, srcs, defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	// Simulate sync: claude adapter re-emits .claude/agents/reviewer.md
	// with the agnostic-ai provenance marker.
	cfg := &config.Config{Sources: srcs}
	bundle, err := spec.LoadBundle(dir, cfg)
	if err != nil {
		t.Fatalf("LoadBundle: %v", err)
	}
	if err := (claude.Adapter{}).Emit(adapters.NewSession(), bundle, cfg, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	emitted, err := os.ReadFile(filepath.Join(dir, ".claude", "agents", "reviewer.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(emitted), "Generated by agnostic-ai") {
		t.Fatalf("emit did not write provenance marker: %s", emitted)
	}
	// Re-import: marker must NOT leak into the source spec.
	if err := importFromClaude(dir, srcs, defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, "agents", "reviewer.md"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(got), "Generated by agnostic-ai") {
		t.Errorf("marker leaked into source after sync/import cycle: %s", got)
	}
}

func TestImportFromClaude_RoundTripStripsGeneratedMarker(t *testing.T) {
	dir := t.TempDir()
	// Hand-authored agent placed in .claude/agents.
	original := "---\nname: reviewer\ndescription: code review\n---\n\nReview diffs.\n"
	writeFile(t, filepath.Join(dir, ".claude", "agents", "reviewer.md"), original)

	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	if data, _ := os.ReadFile(filepath.Join(dir, "agents", "reviewer.md")); strings.Contains(string(data), "Generated by agnostic-ai") {
		t.Fatalf("import 1 leaked marker into source: %s", data)
	}

	// Simulate a downstream sync that wrote the provenance header into
	// the Claude file. The marker MUST round-trip out on re-import so
	// repeated agnostic-ai sync ↔ import cycles do not accumulate
	// header lines in the source spec.
	withMarker := "---\nname: reviewer\ndescription: code review\n---\n\n<!-- Generated by agnostic-ai -->\n\nReview diffs.\n"
	writeFile(t, filepath.Join(dir, ".claude", "agents", "reviewer.md"), withMarker)

	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, "agents", "reviewer.md"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(got), "Generated by agnostic-ai") {
		t.Errorf("import 2 leaked marker into source: %s", got)
	}
	if string(got) != original {
		t.Errorf("re-import did not restore byte-identical source.\nwant:\n%s\ngot:\n%s", original, got)
	}
}

func TestImportFromClaude_CopiesAgents(t *testing.T) {
	dir := t.TempDir()
	body := "---\nname: reviewer\nmodel: gpt-5.5\n---\nReview diffs.\n"
	writeFile(t, filepath.Join(dir, ".claude", "agents", "reviewer.md"), body)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, "agents", "reviewer.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != body {
		t.Errorf("agent not byte-identical. got %q", got)
	}
}

func TestImportFromClaude_CopiesSkills(t *testing.T) {
	dir := t.TempDir()
	body := "---\nname: validator\n---\nValidate yaml.\n"
	writeFile(t, filepath.Join(dir, ".claude", "skills", "validator", "SKILL.md"), body)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, "skills", "validator", "SKILL.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != body {
		t.Errorf("skill not byte-identical. got %q", got)
	}
}

func TestImportFromClaude_CopiesSkillAssets(t *testing.T) {
	dir := t.TempDir()
	skillRoot := filepath.Join(dir, ".claude", "skills", "validator")
	writeFile(t, filepath.Join(skillRoot, "SKILL.md"), "---\nname: validator\n---\nbody\n")
	writeFile(t, filepath.Join(skillRoot, "scripts", "run.py"), "print('ok')\n")
	writeFile(t, filepath.Join(skillRoot, "fixtures", "data.json"), `{"k":1}`)

	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}

	for _, rel := range []string{"SKILL.md", "scripts/run.py", "fixtures/data.json"} {
		got, err := os.ReadFile(filepath.Join(dir, "skills", "validator", filepath.FromSlash(rel)))
		if err != nil {
			t.Errorf("missing imported skill asset %q: %v", rel, err)
			continue
		}
		want, _ := os.ReadFile(filepath.Join(skillRoot, filepath.FromSlash(rel)))
		if string(got) != string(want) {
			t.Errorf("skill asset %q not byte-identical: got %q want %q", rel, got, want)
		}
	}
}

func TestImportFromClaude_PreservesSkillScriptExecutableBit(t *testing.T) {
	dir := t.TempDir()
	skillRoot := filepath.Join(dir, ".claude", "skills", "build")
	writeFile(t, filepath.Join(skillRoot, "SKILL.md"), "---\nname: build\n---\nbody\n")
	scriptPath := filepath.Join(skillRoot, "run.sh")
	writeFile(t, scriptPath, "#!/bin/sh\necho hi\n")
	if err := os.Chmod(scriptPath, 0o755); err != nil {
		t.Fatal(err)
	}

	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}

	if runtime.GOOS != "windows" {
		info, err := os.Stat(filepath.Join(dir, "skills", "build", "run.sh"))
		if err != nil {
			t.Fatal(err)
		}
		if info.Mode().Perm()&0o111 == 0 {
			t.Errorf("executable bit dropped on import: mode=%v", info.Mode().Perm())
		}
	}
}

func TestImportFromClaude_ImportsHooks(t *testing.T) {
	dir := t.TempDir()
	settings := `{
  "hooks": {
    "PostToolUse": [
      {"matcher": "Edit|Write", "hooks": [{"type": "command", "command": "fmt"}]}
    ]
  }
}`
	writeFile(t, filepath.Join(dir, ".claude", "settings.json"), settings)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	path := findOneHookFile(t, filepath.Join(dir, "hooks"), "posttooluse")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("missing %s: %v", path, err)
	}
	for _, want := range []string{"event: PostToolUse", "matcher: Edit|Write", "command: fmt"} {
		if !strings.Contains(string(data), want) {
			t.Errorf("expected %q in %s", want, data)
		}
	}
}

func TestImportFromClaude_MultipleHookCommandsPerGroup(t *testing.T) {
	dir := t.TempDir()
	settings := `{
  "hooks": {
    "PostToolUse": [
      {"matcher": "Edit", "hooks": [
        {"type": "command", "command": "fmt"},
        {"type": "command", "command": "lint"}
      ]}
    ]
  }
}`
	writeFile(t, filepath.Join(dir, ".claude", "settings.json"), settings)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	path := findOneHookFile(t, filepath.Join(dir, "hooks"), "posttooluse")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"- fmt", "- lint", "matcher: Edit"} {
		if !strings.Contains(string(data), want) {
			t.Errorf("expected %q in %s", want, data)
		}
	}
}

// timeout and statusMessage are first-class Claude hook fields that
// must round-trip through the spec, not be silently dropped during
// import. Spec is the source of truth; on next sync the emit side
// re-populates the fields from these Meta keys.
func TestImportFromClaude_PreservesHookTimeoutAndStatusMessage(t *testing.T) {
	dir := t.TempDir()
	settings := `{
  "hooks": {
    "PostToolUse": [
      {"matcher": "Edit|Write", "hooks": [
        {"type": "command", "command": "fmt", "timeout": 30, "statusMessage": "Formatting"},
        {"type": "command", "command": "lint", "timeout": 30, "statusMessage": "Formatting"}
      ]}
    ]
  }
}`
	writeFile(t, filepath.Join(dir, ".claude", "settings.json"), settings)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	path := findOneHookFile(t, filepath.Join(dir, "hooks"), "posttooluse")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"timeout: 30", "statusMessage: Formatting"} {
		if !strings.Contains(string(data), want) {
			t.Errorf("expected %q in %s", want, data)
		}
	}
}

// async, asyncRewake, shell, and if are current command-hook schema
// fields. Import must capture them into the spec or the next sync
// silently strips them from settings.json.
func TestImportFromClaude_PreservesHookAsyncShellIf(t *testing.T) {
	dir := t.TempDir()
	settings := `{
  "hooks": {
    "PreToolUse": [
      {"matcher": "Bash", "hooks": [
        {"type": "command", "command": "check.sh", "async": true, "asyncRewake": true, "once": true, "shell": "bash", "if": "Bash(git *)"}
      ]}
    ]
  }
}`
	writeFile(t, filepath.Join(dir, ".claude", "settings.json"), settings)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	path := findOneHookFile(t, filepath.Join(dir, "hooks"), "pretooluse")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"async: true", "asyncRewake: true", "once: true", "shell: bash", "if: Bash(git *)"} {
		if !strings.Contains(string(data), want) {
			t.Errorf("expected %q in %s", want, data)
		}
	}
}

// Hook script bodies under `.claude/hooks/` are captured into
// `.agnostic-ai/scripts/claude/` so a gitignored .claude/ tree can be
// reconstructed by the next `sync`. Executable bit must survive the
// copy.
// The claude importer previously claimed "AGNOSTIC_AI.md seeded from
// CLAUDE.md" even when the project had no root CLAUDE.md (the common
// case when claude rules live entirely in `.claude/`). Verify the line
// only prints when the mirror actually wrote.
func TestImportFromClaude_SkipsMainFileSummaryWhenAbsent(t *testing.T) {
	dir := t.TempDir()
	// No root CLAUDE.md, but settings.json forces import to run.
	writeFile(t, filepath.Join(dir, ".claude", "settings.json"), `{"includeCoAuthoredBy": false}`)

	var buf bytes.Buffer
	prev := logOut
	logOut = &buf
	defer func() { logOut = prev }()

	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	if strings.Contains(buf.String(), "AGNOSTIC_AI.md seeded from CLAUDE.md") {
		t.Errorf("summary should not claim AGNOSTIC_AI.md was seeded when CLAUDE.md is absent:\n%s", buf.String())
	}
	if _, err := os.Stat(filepath.Join(dir, ".agnostic-ai", "AGNOSTIC_AI.md")); !os.IsNotExist(err) {
		t.Errorf("expected no AGNOSTIC_AI.md when no source existed, err=%v", err)
	}
}

func TestImportFromClaude_CapturesHookScriptBodies(t *testing.T) {
	dir := t.TempDir()
	body := "#!/usr/bin/env bash\necho protect\n"
	if err := os.MkdirAll(filepath.Join(dir, ".claude", "hooks"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".claude", "hooks", "protect-files.sh"), []byte(body), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	dst := filepath.Join(dir, ".agnostic-ai", "scripts", "claude", "protect-files.sh")
	got, err := os.ReadFile(dst)
	if err != nil {
		t.Fatalf("expected stashed script body: %v", err)
	}
	if string(got) != body {
		t.Errorf("body mismatch: %q vs %q", got, body)
	}
	if runtime.GOOS != "windows" {
		info, err := os.Stat(dst)
		if err != nil {
			t.Fatal(err)
		}
		if info.Mode().Perm()&0o100 == 0 {
			t.Errorf("expected executable bit preserved, got %v", info.Mode().Perm())
		}
	}
}

func TestImportFromClaude_WritesSettingsOverlay(t *testing.T) {
	dir := t.TempDir()
	settings := `{
  "statusLine": {"type": "command", "command": "echo status"},
  "enabledPlugins": ["foo", "bar"],
  "hooks": {
    "PostToolUse": [
      {"matcher": "Edit", "hooks": [{"type": "command", "command": "fmt"}]}
    ]
  }
}`
	writeFile(t, filepath.Join(dir, ".claude", "settings.json"), settings)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, ".agnostic-ai/overlays/claude.settings.json"))
	if err != nil {
		t.Fatalf("missing overlay: %v", err)
	}
	for _, want := range []string{"statusLine", "enabledPlugins"} {
		if !strings.Contains(string(raw), want) {
			t.Errorf("overlay missing %q: %s", want, raw)
		}
	}
	if strings.Contains(string(raw), `"hooks"`) {
		t.Errorf("hooks captured as specs must be absent from overlay: %s", raw)
	}
}

// TestImportFromClaude_OverlayPreservesKeyOrder regresses #215.
// importClaudeSettingsOverlay used to round-trip through map[string]any,
// which alpha-sorts every key on json.Marshal. The captured overlay
// therefore lost the user's authored key order, and downstream
// `doctor --fix` writes propagated the alpha-sorted form back.
// OrderedJSON adoption keeps statusLine before enabledPlugins, and
// inner statusLine fields type before command, byte-for-byte.
func TestImportFromClaude_OverlayPreservesKeyOrder(t *testing.T) {
	dir := t.TempDir()
	settings := `{
  "statusLine": {"type": "command", "command": "echo status"},
  "enabledPlugins": {"plugin-a": true},
  "hooks": {}
}`
	writeFile(t, filepath.Join(dir, ".claude", "settings.json"), settings)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, ".agnostic-ai/overlays/claude.settings.json"))
	if err != nil {
		t.Fatalf("missing overlay: %v", err)
	}
	s := string(raw)
	idxStatus := strings.Index(s, `"statusLine"`)
	idxPlugins := strings.Index(s, `"enabledPlugins"`)
	if idxStatus < 0 || idxPlugins <= idxStatus {
		t.Errorf("overlay re-ordered top-level keys (want statusLine before enabledPlugins):\n%s", s)
	}
	statusBlock := s
	if i := strings.Index(s, `"statusLine"`); i >= 0 {
		statusBlock = s[i:]
		if j := strings.Index(statusBlock, "}"); j >= 0 {
			statusBlock = statusBlock[:j+1]
		}
	}
	idxType := strings.Index(statusBlock, `"type"`)
	idxCmd := strings.Index(statusBlock, `"command"`)
	if idxType < 0 || idxCmd <= idxType {
		t.Errorf("statusLine inner keys re-ordered (want type before command):\n%s", statusBlock)
	}
}

// TestImportFromClaude_HooksFirstSurvivesRoundTrip regresses #227.
func TestImportFromClaude_HooksFirstSurvivesRoundTrip(t *testing.T) {
	s := syncImportedClaudeSettings(t, `{
  "hooks": {
    "PostToolUse": [
      {"matcher": "Edit", "hooks": [{"type": "command", "command": "fmt"}]}
    ]
  },
  "statusLine": {"type": "command", "command": "echo status"},
  "enabledPlugins": {"plugin-a": true}
}`)
	idxHooks := strings.Index(s, `"hooks"`)
	idxStatus := strings.Index(s, `"statusLine"`)
	idxPlugins := strings.Index(s, `"enabledPlugins"`)
	if idxHooks < 0 || idxStatus <= idxHooks || idxPlugins <= idxStatus {
		t.Errorf("expected hooks < statusLine < enabledPlugins (author order), got:\n%s", s)
	}
}

func TestImportFromClaude_HooksBetweenKeysSurviveRoundTrip(t *testing.T) {
	s := syncImportedClaudeSettings(t, `{
  "statusLine": {"type": "command", "command": "echo status"},
  "hooks": {
    "PostToolUse": [
      {"matcher": "Edit", "hooks": [{"type": "command", "command": "fmt"}]}
    ]
  },
  "enabledPlugins": {"plugin-a": true}
}`)
	idxStatus := strings.Index(s, `"statusLine"`)
	idxHooks := strings.Index(s, `"hooks"`)
	idxPlugins := strings.Index(s, `"enabledPlugins"`)
	if idxStatus < 0 || idxHooks <= idxStatus || idxPlugins <= idxHooks {
		t.Errorf("expected statusLine < hooks < enabledPlugins (author order), got:\n%s", s)
	}
	if !strings.Contains(s, `"command": "fmt"`) {
		t.Errorf("hook spec was not restored: %s", s)
	}
}

// syncImportedClaudeSettings imports settings into a fresh project,
// syncs Claude, and returns the settings.json sync wrote.
func syncImportedClaudeSettings(t *testing.T, settings string) string {
	t.Helper()
	dir := t.TempDir()
	testutil.Chdir(t, dir)
	writeFile(t, filepath.Join(dir, ".claude", "settings.json"), settings)
	srcs := rootSources()
	if err := importFromClaude(dir, srcs, defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	cfg := &config.Config{Sources: srcs}
	bundle, err := spec.LoadBundle(dir, cfg)
	if err != nil {
		t.Fatalf("LoadBundle: %v", err)
	}
	if err := (claude.Adapter{}).Emit(adapters.NewSession(), bundle, cfg, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, ".claude", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}
	return string(raw)
}

func TestImportFromClaude_OnlyHooks_NoOverlay(t *testing.T) {
	dir := t.TempDir()
	settings := `{
  "hooks": {
    "PostToolUse": [
      {"matcher": "Edit", "hooks": [{"type": "command", "command": "fmt"}]}
    ]
  }
}`
	writeFile(t, filepath.Join(dir, ".claude", "settings.json"), settings)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".agnostic-ai/overlays/claude.settings.json")); !os.IsNotExist(err) {
		t.Errorf("overlay should not exist when only hooks present: %v", err)
	}
}

func TestImportFromClaude_HookFilenamesStableAcrossReimport(t *testing.T) {
	dir := t.TempDir()
	settings := `{
  "hooks": {
    "PostToolUse": [
      {"matcher": "Edit", "hooks": [{"type": "command", "command": "cmd1"}]},
      {"matcher": "Edit", "hooks": [{"type": "command", "command": "cmd2"}]}
    ]
  }
}`
	writeFile(t, filepath.Join(dir, ".claude", "settings.json"), settings)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	first, err := filepath.Glob(filepath.Join(dir, "hooks", "*.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if len(first) != 2 {
		t.Fatalf("expected 2 hook files, got %d: %v", len(first), first)
	}
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	second, err := filepath.Glob(filepath.Join(dir, "hooks", "*.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if len(second) != 2 {
		t.Errorf("re-import created duplicates: %v", second)
	}
	for i := range first {
		if first[i] != second[i] {
			t.Errorf("filename changed across imports: %q vs %q", first[i], second[i])
		}
	}
}

func TestImportFromClaude_MalformedSettings(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".claude", "settings.json"), "{not json")
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err == nil {
		t.Error("expected parse error on malformed settings.json")
	}
}

func TestImportFromClaude_HonorsCustomSourceDirs(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), generatedEntry("## r1\n\nbody\n"))
	src := config.Sources{
		Agents: ".agnostic-ai/agents",
		Skills: ".agnostic-ai/skills",
		Rules:  ".agnostic-ai/rules",
		Hooks:  ".agnostic-ai/hooks",
		MCPs:   ".agnostic-ai/mcps",
	}
	if err := importFromClaude(dir, src, defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".agnostic-ai", "rules", "r1.md")); err != nil {
		t.Errorf("expected .agnostic-ai/rules/r1.md, got %v", err)
	}
}

func TestSlugify_Collisions(t *testing.T) {
	in := "## Go Style\n\nfoo\n\n## go-style\n\nbar\n"
	_, got := splitH2Sections(in)
	if len(got) != 2 {
		t.Fatalf("expected 2 sections, got %d", len(got))
	}
	if got[0].slug != "go-style" || got[1].slug != "go-style-2" {
		t.Errorf("expected go-style, go-style-2; got %s, %s", got[0].slug, got[1].slug)
	}
}

func TestImportFromClaude_PreservesPreamble(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), generatedEntry(`# Project Title

Preamble explaining the project before any H2.

## rule-one

Body one.
`))
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "rules", "project-title.md"))
	if err != nil {
		t.Fatalf("expected rules/project-title.md (preamble file), got %v", err)
	}
	if !strings.Contains(string(data), "Preamble explaining the project") {
		t.Errorf("preamble lost: %s", data)
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "rule-one.md")); err != nil {
		t.Errorf("missing rule-one.md: %v", err)
	}
}

func TestImportFromClaude_PreambleFallbackSlug(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), generatedEntry("Bare preamble, no H1.\n\n## rule-one\n\nBody.\n"))
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "intro.md")); err != nil {
		t.Errorf("expected rules/intro.md, got %v", err)
	}
}

func TestImportFromClaude_IgnoresH2InsideFencedBlocks(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), generatedEntry("## rule-one\n\nBody.\n\n"+
		"```markdown\n## not-a-real-rule\n\nExample inside fence.\n```\n\n"+
		"## rule-two\n\nBody two.\n"))
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "not-a-real-rule.md")); !os.IsNotExist(err) {
		t.Errorf("phantom rule from fenced block: %v", err)
	}
	for _, name := range []string{"rule-one", "rule-two"} {
		data, err := os.ReadFile(filepath.Join(dir, "rules", name+".md"))
		if err != nil {
			t.Fatalf("missing %s: %v", name, err)
		}
		if strings.Contains(string(data), "not-a-real-rule") && name == "rule-two" {
			t.Errorf("%s leaked fenced heading", name)
		}
	}
	one, _ := os.ReadFile(filepath.Join(dir, "rules", "rule-one.md"))
	if !strings.Contains(string(one), "Example inside fence.") {
		t.Errorf("rule-one missing fenced example body: %s", one)
	}
}

func TestImportCmd_UnknownSourceRejected(t *testing.T) {
	dir := t.TempDir()
	writeMinimalConfig(t, dir, ".agnostic-ai")
	testutil.Chdir(t, dir)
	silence(t)

	root := NewRootCmd("test")
	root.SetArgs([]string{"import", "nonesuch"})
	if err := root.Execute(); err == nil {
		t.Error("expected error for unknown source")
	}
}

func TestImportCmd_RequiresConfig(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)
	silence(t)

	root := NewRootCmd("test")
	root.SetArgs([]string{"import", "claude"})
	if err := root.Execute(); err == nil {
		t.Error("expected error when agnostic-ai.yaml missing")
	}
}

func TestImportCmd_ClaudeWritesIntoConfiguredSources(t *testing.T) {
	dir := t.TempDir()
	writeMinimalConfig(t, dir, ".agnostic-ai")
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), generatedEntry("## r1\n\nbody\n"))
	testutil.Chdir(t, dir)
	silence(t)

	root := NewRootCmd("test")
	root.SetArgs([]string{"import", "claude"})
	if err := root.Execute(); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".agnostic-ai", "rules", "r1.md")); err != nil {
		t.Errorf("expected .agnostic-ai/rules/r1.md, got %v", err)
	}
}

// findOneHookFile returns the single hook yaml whose stem starts with
// prefix. Tests use it so they do not have to compute hash filenames.
func findOneHookFile(t *testing.T, dir, prefix string) string {
	t.Helper()
	matches, err := filepath.Glob(filepath.Join(dir, prefix+"*.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if len(matches) != 1 {
		t.Fatalf("expected exactly one hook file with prefix %q in %s, got %v", prefix, dir, matches)
	}
	return matches[0]
}

func TestImportFromClaude_PreservesCommandFrontmatter(t *testing.T) {
	dir := t.TempDir()
	cmdBody := `---
description: Fix a bug
argument-hint: <bug-id>
model: claude-sonnet-4-6
allowed-tools: [Read, Edit]
disable-model-invocation: false
---

Fix the bug at $ARGUMENTS.
`
	writeFile(t, filepath.Join(dir, ".claude/commands/fix-bug.md"), cmdBody)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	out := filepath.Join(dir, "commands", "fix-bug.md")
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("missing %s: %v", out, err)
	}
	got := string(data)
	for _, want := range []string{
		"description: Fix a bug",
		"argument-hint: <bug-id>",
		"model: claude-sonnet-4-6",
		"allowed-tools:",
		"disable-model-invocation: false",
		"Fix the bug at $ARGUMENTS.",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in:\n%s", want, got)
		}
	}
}

func TestImportFromClaude_ImportsMCPServers(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, claudeMCPFile), `{
  "mcpServers": {
    "fs": {"command": "npx", "args": ["server-filesystem"]},
    "github": {"type": "http", "url": "https://api.githubcopilot.com/mcp/"}
  }
}`)
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	fs, err := os.ReadFile(filepath.Join(dir, "mcps", "fs.yaml"))
	if err != nil {
		t.Fatalf("missing mcps/fs.yaml: %v", err)
	}
	for _, want := range []string{"name: fs", "command: npx", "server-filesystem"} {
		if !strings.Contains(string(fs), want) {
			t.Errorf("missing %q in fs.yaml:\n%s", want, fs)
		}
	}
	gh, err := os.ReadFile(filepath.Join(dir, "mcps", "github.yaml"))
	if err != nil {
		t.Fatalf("missing mcps/github.yaml: %v", err)
	}
	for _, want := range []string{"name: github", "type: http", "url: https://api.githubcopilot.com/mcp/"} {
		if !strings.Contains(string(gh), want) {
			t.Errorf("missing %q in github.yaml:\n%s", want, gh)
		}
	}
}

func TestImportFromClaude_NoMCPFile(t *testing.T) {
	dir := t.TempDir()
	if err := importFromClaude(dir, rootSources(), defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	entries, _ := os.ReadDir(filepath.Join(dir, "mcps"))
	if len(entries) != 0 {
		t.Errorf("expected empty mcps/, got %d entries", len(entries))
	}
}

// A hand-edited CLAUDE.md that no longer matches the fenced view leaves
// AGNOSTIC_AI.md as it is: which ::target block the edit belongs to is
// unknown, and appending it unfenced would reach every tool (#1595).
func TestMirrorMainFile_LeavesAFencedSourceAndSaysSo(t *testing.T) {
	dir := t.TempDir()
	source := "Shared.\n\n::target claude\nClaude-only line.\n::end\n\n::target gemini\nGemini-only line.\n::end\n"
	writeFile(t, filepath.Join(dir, agnosticMainFile), source)
	writeFile(t, filepath.Join(dir, "CLAUDE.md"), "Hand-edited, no longer matches sync.\n")

	var buf bytes.Buffer
	prev := logOut
	logOut = &buf
	defer func() { logOut = prev }()

	result, err := mirrorMainFile(dir, "CLAUDE.md")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result != mirrorKept {
		t.Errorf("result = %v, want kept", result)
	}
	got, err := os.ReadFile(filepath.Join(dir, agnosticMainFile))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != source {
		t.Errorf("AGNOSTIC_AI.md changed:\n%s", got)
	}
	if !strings.Contains(buf.String(), "merge the edit into it by hand") {
		t.Errorf("expected the edit to be named, got:\n%s", buf.String())
	}
}

// writeMinimalConfig drops a config that points sources at base/<kind>.
func writeMinimalConfig(t *testing.T, dir, base string) {
	t.Helper()
	cfg := "version: 1\n"
	if base != "" {
		cfg += "sources:\n"
		for _, k := range []string{"agents", "skills", "rules", "hooks", "mcps"} {
			cfg += "  " + k + ": " + filepath.ToSlash(filepath.Join(base, k)) + "\n"
		}
	}
	writeFile(t, filepath.Join(dir, "agnostic-ai.yaml"), cfg)
}

func TestImportFromClaude_ReadonlyAgentRoundTripKeepsOtherTargetsReadOnly(t *testing.T) {
	dir := setupFixture(t)
	testutil.Chdir(t, dir)
	silence(t)
	writeFile(t, filepath.Join(dir, "agnostic-ai.yaml"), "version: 1\ntargets: [claude, cursor, codex]\n")
	agents := filepath.Join(dir, ".agnostic-ai", "agents")
	writeFile(t, filepath.Join(agents, "reviewer.md"), "---\nname: reviewer\ndescription: Reviews code.\nreadonly: true\n---\nReview code.\n")
	if err := runSync(t); err != nil {
		t.Fatal(err)
	}
	if _, err := importClaudeAgents(dir, agents, defaultClaudeLayout()); err != nil {
		t.Fatal(err)
	}
	if err := runSync(t); err != nil {
		t.Fatal(err)
	}
	for path, want := range map[string]string{
		filepath.Join(agents, "reviewer.md"):                    "disallowedTools: Write, Edit, NotebookEdit",
		filepath.Join(dir, ".cursor", "agents", "reviewer.md"):  "readonly: true",
		filepath.Join(dir, ".codex", "agents", "reviewer.toml"): `sandbox_mode = "read-only"`,
	} {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(data), want) {
			t.Errorf("%s lost %q after sync, import, sync:\n%s", path, want, data)
		}
	}
}

func TestImportFromClaude_ReadonlyOverridesSurviveSyncImportSync(t *testing.T) {
	cases := []struct {
		name, fields, edit, want, absent string
	}{
		{"target optout", "readonly: true\nx-claude: {readonly: false}\n", "", "readonly: false", "disallowedTools:"},
		{"merged target optout", "readonly: true\nx-cursor: &opts {readonly: false}\nx-claude: {<<: *opts}\n", "", "readonly: false", "disallowedTools:"},
		{"merged explicit readonly wins", "readonly: true\nx-cursor: &opts {readonly: false}\nx-claude: {<<: *opts, readonly: true}\n", "", "readonly: true", ""},
		{"merged sequence precedence", "readonly: true\nx-cursor: &first {readonly: false}\nx-codex: &second {readonly: true}\nx-claude: {<<: [*first, *second]}\n", "", "readonly: false", "disallowedTools:"},
		{"null optout", "readonly: true\nx-claude: {disallowedTools: null}\n", "", "disallowedTools: null", "disallowedTools:"},
		{"merged null optout", "readonly: false\nx-cursor: &opts {disallowedTools: null}\nx-claude: {<<: *opts}\n", "", "disallowedTools: null", "disallowedTools:"},
		{"aliased null optout", "readonly: true\nx-cursor: &opts {disallowedTools: null}\nx-claude: *opts\n", "", "disallowedTools: null", "disallowedTools:"},
		{"edited null optout", "readonly: true\nx-claude: {disallowedTools: null}\n", "disallowedTools: Bash\n", "disallowedTools: Bash", "disallowedTools: null"},
		{"target readonly", "x-claude: {readonly: true}\n", "", "readonly: true", ""},
		{"deleted target restrictions", "x-claude: {readonly: true}\n", "description: edited\n", "disallowedTools: null", "disallowedTools:"},
		{"edited fields", "readonly: true\nx-claude: {readonly: false, model: sonnet, tools: [Read]}\n", "model: haiku\ntools: [Bash]\ndisallowedTools: Edit\n", "readonly: false", "sonnet"},
		{"deleted translated tools", "readonly: true\n", "description: edited\n", "disallowedTools: null", "disallowedTools:"},
		{"deleted native fields", "x-claude: {model: sonnet, tools: [Read]}\n", "description: edited\n", "description: edited", "model:"},
		{"deleted native restrictions", "readonly: true\nx-claude: {disallowedTools: Bash}\n", "description: edited\n", "disallowedTools: null", "disallowedTools:"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			dir := setupFixture(t)
			testutil.Chdir(t, dir)
			silence(t)
			writeFile(t, "agnostic-ai.yaml", "version: 1\ntargets: [claude]\n")
			path := filepath.Join(dir, ".agnostic-ai/agents/reviewer.md")
			writeFile(t, path, "---\nname: reviewer\n"+c.fields+"---\nReview code.\n")
			execCLI(t, "sync")
			native := filepath.Join(dir, ".claude/agents/reviewer.md")
			before := readFile(t, native)
			if c.edit != "" {
				writeFile(t, native, "---\nname: reviewer\n"+c.edit+"---\nReview code.\n")
			}
			execCLI(t, "import", "claude", "--overwrite")
			if got := readFile(t, path); !strings.Contains(got, c.want) {
				t.Errorf("canonical translation intent lost:\n%s", got)
			}
			execCLI(t, "sync")
			got := readFile(t, native)
			if c.edit == "" && got != before {
				t.Errorf("native output changed after import:\nbefore:\n%s\nafter:\n%s", before, got)
			}
			if c.absent != "" && strings.Contains(got, c.absent) {
				t.Errorf("native output restored %q:\n%s", c.absent, got)
			}
			if c.name == "edited fields" && (!strings.Contains(got, "haiku") || !strings.Contains(got, "Bash") || !strings.Contains(got, "disallowedTools: Edit")) {
				t.Errorf("native edits lost:\n%s", got)
			}
			if c.name == "edited null optout" && !strings.Contains(got, "disallowedTools: Bash") {
				t.Errorf("native restriction edit lost:\n%s", got)
			}
		})
	}
}

func TestImportFromClaude_RemovingAgentFrontmatterKeepsOnlyTranslationIntent(t *testing.T) {
	dir := setupFixture(t)
	testutil.Chdir(t, dir)
	silence(t)
	writeFile(t, "agnostic-ai.yaml", "version: 1\ntargets: [claude]\n")
	writeFile(t, ".agnostic-ai/agents/reviewer.md", "---\nname: reviewer\nreadonly: true\nmodel: sonnet\ntools: [Read]\n---\nReview code.\n")
	execCLI(t, "sync")
	writeFile(t, ".claude/agents/reviewer.md", "Review code.\n")
	execCLI(t, "import", "claude", "--overwrite")
	canonical := readFile(t, ".agnostic-ai/agents/reviewer.md")
	if !strings.Contains(canonical, "readonly: true") || !strings.Contains(canonical, "disallowedTools: null") {
		t.Errorf("canonical translation intent lost:\n%s", canonical)
	}
	execCLI(t, "sync")
	got := readFile(t, ".claude/agents/reviewer.md")
	for _, key := range []string{"name:", "model:", "tools:", "disallowedTools:", "readonly:"} {
		if strings.Contains(got, key) {
			t.Errorf("removed native %q resurrected:\n%s", key, got)
		}
	}
}

func TestImportFromClaude_NativeRestrictionsDoNotInferReadonly(t *testing.T) {
	dir := setupFixture(t)
	testutil.Chdir(t, dir)
	silence(t)
	writeFile(t, "agnostic-ai.yaml", "version: 1\ntargets: [claude]\n")
	writeFile(t, ".claude/agents/reviewer.md", "---\nname: reviewer\ndisallowedTools: Write, Edit, NotebookEdit\n---\nReview code.\n")
	execCLI(t, "import", "claude")
	if got := readFile(t, ".agnostic-ai/agents/reviewer.md"); strings.Contains(got, "readonly:") {
		t.Errorf("native tools guessed portable readonly:\n%s", got)
	}
}

func TestImportFromClaude_AliasedReadonlyOptoutSurvivesSyncImportSync(t *testing.T) {
	dir := setupFixture(t)
	testutil.Chdir(t, dir)
	silence(t)
	writeFile(t, "agnostic-ai.yaml", "version: 1\ntargets: [claude]\n")
	writeFile(t, ".agnostic-ai/agents/reviewer.md", "---\nname: reviewer\nreadonly: true\nx-cursor: &opts {readonly: false, tools: [Read]}\nx-claude: *opts\n---\nReview code.\n")
	execCLI(t, "sync")
	before := readFile(t, ".claude/agents/reviewer.md")
	if strings.Contains(before, "disallowedTools:") {
		t.Fatalf("initial alias optout was not applied:\n%s", before)
	}
	execCLI(t, "import", "claude", "--overwrite")
	canonical := readFile(t, ".agnostic-ai/agents/reviewer.md")
	if !strings.Contains(canonical, "x-claude: {readonly: false}") || strings.Contains(canonical, "*opts") {
		t.Errorf("aliased override was not preserved independently:\n%s", canonical)
	}
	execCLI(t, "sync")
	if got := readFile(t, ".claude/agents/reviewer.md"); got != before {
		t.Errorf("native alias output changed after import:\nbefore:\n%s\nafter:\n%s", before, got)
	}
}

func TestPreserveClaudeReadonly_DetachesSharedAliasBeforeFiltering(t *testing.T) {
	existing, err := frontmatterMapping([]byte("readonly: true\nx-cursor: &opts {readonly: false, tools: [Read]}\nx-claude: *opts\n"))
	if err != nil {
		t.Fatal(err)
	}
	imported, err := frontmatterMapping([]byte("tools: [Read]\n"))
	if err != nil {
		t.Fatal(err)
	}
	preserveClaudeReadonly(existing, imported)
	var meta map[string]any
	if err := existing.Decode(&meta); err != nil {
		t.Fatal(err)
	}
	cursor, ok := meta["x-cursor"].(map[string]any)
	if !ok {
		t.Fatalf("Cursor mapping was lost: %#v", meta)
	}
	claude, ok := meta["x-claude"].(map[string]any)
	if !ok {
		t.Fatalf("Claude alias mapping was lost: %#v", meta)
	}
	if claude["readonly"] != false || claude["tools"] != nil {
		t.Errorf("Claude override was not filtered: %#v", claude)
	}
	if cursor["readonly"] != false || cursor["tools"] == nil {
		t.Errorf("shared Cursor mapping was mutated: %#v", cursor)
	}
}

// generatedEntry marks body as a document sync wrote, the only kind of
// entry point import still slices into rules: a hand-written one imports
// whole as the shared body.
func generatedEntry(body string) string {
	return header.Line(header.FormatMarkdown) + "\n" + body
}
