package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/config"
)

func TestImportFromAntigravity_RulesAndAgents(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".agent", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(rulesDir, "go-style.md"),
		"<!-- Generated by agnostic-ai. Do not edit. -->\n\n# go-style\n\ngofmt clean.\n")
	writeFile(t, filepath.Join(rulesDir, "agent-helper.md"),
		"<!-- Generated by agnostic-ai. Do not edit. -->\n\n# Agent: helper\n\nhelper body.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}

	ruleData, err := os.ReadFile(filepath.Join(dir, "rules", "go-style.md"))
	if err != nil {
		t.Fatalf("missing rules/go-style.md: %v", err)
	}
	if !strings.Contains(string(ruleData), "name: go-style") {
		t.Errorf("expected name: go-style frontmatter, got %s", ruleData)
	}
	if !strings.Contains(string(ruleData), "gofmt clean.") {
		t.Errorf("expected rule body, got %s", ruleData)
	}
	if strings.Contains(string(ruleData), "Generated by agnostic-ai") {
		t.Errorf("provenance header not stripped: %s", ruleData)
	}

	agentData, err := os.ReadFile(filepath.Join(dir, "agents", "helper.md"))
	if err != nil {
		t.Fatalf("missing agents/helper.md: %v", err)
	}
	if !strings.Contains(string(agentData), "name: helper") {
		t.Errorf("expected name: helper frontmatter, got %s", agentData)
	}
	if !strings.Contains(string(agentData), "helper body.") {
		t.Errorf("expected agent body, got %s", agentData)
	}
}

// TestImportFromAntigravity_ReadsPluralRulesDir is the round-trip half
// of the paths fix: sync now defaults to `.agents/rules`, so import
// must read from there too, not just the legacy `.agent/rules`.
func TestImportFromAntigravity_ReadsPluralRulesDir(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".agents", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(rulesDir, "go-style.md"),
		"<!-- Generated by agnostic-ai. Do not edit. -->\n\n# go-style\n\ngofmt clean.\n")
	writeFile(t, filepath.Join(rulesDir, "agent-helper.md"),
		"<!-- Generated by agnostic-ai. Do not edit. -->\n\n# Agent: helper\n\nhelper body.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}

	ruleData, err := os.ReadFile(filepath.Join(dir, "rules", "go-style.md"))
	if err != nil {
		t.Fatalf("missing rules/go-style.md: %v", err)
	}
	if !strings.Contains(string(ruleData), "gofmt clean.") {
		t.Errorf("expected rule body, got %s", ruleData)
	}
	if _, err := os.Stat(filepath.Join(dir, "agents", "helper.md")); err != nil {
		t.Errorf("missing agents/helper.md: %v", err)
	}
}

// TestImportFromAntigravity_ReadsScopedRulesDirs is the import half of
// the scoped-rules fix: sync writes a scoped rule to
// `<scope>/.agents/rules/<name>.md`, outside the project's own rules
// tree, so import has to scan the project for that layout too (#1114).
func TestImportFromAntigravity_ReadsScopedRulesDirs(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".agents", "rules", "root.md"), "# root\n\nroot body\n")
	writeFile(t, filepath.Join(dir, "backend", ".agents", "rules", "auth.md"), "# auth\n\nauth body\n")
	writeFile(t, filepath.Join(dir, "backend", "api", ".agents", "rules", "limits.md"), "# limits\n\nlimits body\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}

	for _, p := range []string{
		filepath.Join("rules", "root.md"),
		filepath.Join("rules", "backend", "auth.md"),
		filepath.Join("rules", "backend", "api", "limits.md"),
	} {
		if _, err := os.Stat(filepath.Join(dir, p)); err != nil {
			t.Errorf("missing imported spec %s: %v", p, err)
		}
	}
}

// TestImportFromAntigravity_ReadsHiddenAndVendorScopedRulesDirs pins
// #1114's import-side fix: `CheckScopePath` accepts a scope like
// `.github`, `vendor`, or `node_modules`, so emission can write a
// scoped rule under any of them, and import must round-trip it instead
// of pruning the directory before ever looking inside it.
func TestImportFromAntigravity_ReadsHiddenAndVendorScopedRulesDirs(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".github", ".agents", "rules", "release.md"), "# release\n\nrelease body\n")
	writeFile(t, filepath.Join(dir, "vendor", ".agents", "rules", "pkg.md"), "# pkg\n\npkg body\n")
	writeFile(t, filepath.Join(dir, "node_modules", ".agents", "rules", "pkg2.md"), "# pkg2\n\npkg2 body\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}

	for _, p := range []string{
		filepath.Join("rules", ".github", "release.md"),
		filepath.Join("rules", "vendor", "pkg.md"),
		filepath.Join("rules", "node_modules", "pkg2.md"),
	} {
		if _, err := os.Stat(filepath.Join(dir, p)); err != nil {
			t.Errorf("missing imported spec %s: %v", p, err)
		}
	}
}

// TestImportFromAntigravity_SkipsGitAndOwnOutputDirs confirms the scan
// still prunes `.git` (never a legitimate scope) and Antigravity's own
// output roots (`.agents`, `.agent`), which the non-scoped import call
// already reads; walking into them looking for a nested copy of
// themselves would either find nothing or misread the tool's own tree
// as a scope.
func TestImportFromAntigravity_SkipsGitAndOwnOutputDirs(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".git", ".agents", "rules", "ignored.md"), "# ignored\n\nignored body\n")
	writeFile(t, filepath.Join(dir, ".agents", "rules", "root.md"), "# root\n\nroot body\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Join(dir, "rules", "ignored.md")); !os.IsNotExist(err) {
		t.Errorf(".git must never be scanned for scopes, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "root.md")); err != nil {
		t.Errorf("missing imported spec rules/root.md: %v", err)
	}
}

func TestImportFromAntigravity_ImportsNestedAgentProfiles(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".agents/agents/reviewer/agent.md"),
		"---\nname: reviewer\ndescription: Reviews changes.\n---\n<!-- Generated by agnostic-ai. Do not edit. -->\nReview the diff.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "agents/reviewer.md"))
	if err != nil {
		t.Fatalf("missing imported agent: %v", err)
	}
	if !strings.Contains(string(data), "Review the diff.") || strings.Contains(string(data), "Generated by agnostic-ai") {
		t.Errorf("unexpected imported agent:\n%s", data)
	}
}

func TestImportFromAntigravity_NestedProfilesTakePrecedenceOverFlat(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".agents/agents/antigravity/agent.md"), "---\nname: antigravity\n---\nNested.\n")
	writeFile(t, filepath.Join(dir, ".agents/agents/goose.md"), "---\nname: goose\n---\nFlat.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "agents/antigravity.md")); err != nil {
		t.Errorf("missing nested agent import: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "agents/goose.md")); !os.IsNotExist(err) {
		t.Errorf("flat shared profile should not be imported when nested profiles exist, err=%v", err)
	}
}

func TestImportFromAntigravity_FallsBackToLegacyFlatAgents(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".agents/agents/reviewer.md"), "---\nname: reviewer\n---\nLegacy flat.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "agents/reviewer.md")); err != nil {
		t.Errorf("missing legacy flat agent import: %v", err)
	}
}

func TestImportFromAntigravity_UsesConfiguredAgentsDir(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "custom/agents/reviewer/agent.md"), "---\nname: reviewer\n---\nCustom path.\n")
	cfg := &config.Config{Outputs: map[string]config.Output{"antigravity": {AgentsDir: "custom/agents"}}}

	if err := importFromAntigravity(dir, rootSources(), cfg); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "agents/reviewer.md")); err != nil {
		t.Errorf("missing configured-path agent import: %v", err)
	}
}

// TestImportFromAntigravity_PrefersPluralOverLegacyRulesDir asserts the
// new `.agents/rules` wins when both it and the legacy `.agent/rules`
// exist, matching the preference order windsurf's importer already
// uses for its own post-rename / pre-rename pair.
func TestImportFromAntigravity_PrefersPluralOverLegacyRulesDir(t *testing.T) {
	dir := t.TempDir()
	pluralDir := filepath.Join(dir, ".agents", "rules")
	legacyDir := filepath.Join(dir, ".agent", "rules")
	if err := os.MkdirAll(pluralDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(legacyDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(pluralDir, "current.md"), "# current\n\nfrom the plural dir.\n")
	writeFile(t, filepath.Join(legacyDir, "stale.md"), "# stale\n\nfrom the legacy dir.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Join(dir, "rules", "current.md")); err != nil {
		t.Errorf("missing rules/current.md: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "stale.md")); !os.IsNotExist(err) {
		t.Errorf("rules/stale.md should not be imported when .agents/rules exists, err=%v", err)
	}
}

// import antigravity had no MCP reader at all (#589): a hand-authored
// or agnostic-ai-emitted .agents/mcp_config.json produced 0 MCP specs
// back, silently.
func TestImportFromAntigravity_ImportsMCPServers(t *testing.T) {
	dir := t.TempDir()
	config := `{
  "mcpServers": {
    "fs": {"command": "fs-server", "args": ["--root", "."], "cwd": "/workspace"}
  }
}`
	writeFile(t, filepath.Join(dir, antigravityMCPFile), config)
	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "mcps", "fs.yaml"))
	if err != nil {
		t.Fatalf("missing mcps/fs.yaml: %v", err)
	}
	for _, want := range []string{"name: fs", "command: fs-server", "--root", "cwd: /workspace"} {
		if !strings.Contains(string(data), want) {
			t.Errorf("expected %q in mcp file: %s", want, data)
		}
	}
}

// Antigravity's own field name for a remote server is `serverUrl`, not
// the generic spec's `url`: the vendor doc states the legacy `url` /
// `httpUrl` names "are not supported." Import must rename it back to
// `url` so a re-emit through buildMCPServer (which reads e.Meta["url"])
// reaches the same JSON again.
func TestImportFromAntigravity_MCPRemoteRenamesServerURLToURL(t *testing.T) {
	dir := t.TempDir()
	config := `{
  "mcpServers": {
    "github": {"serverUrl": "https://api.githubcopilot.com/mcp/", "headers": {"Authorization": "Bearer x"}}
  }
}`
	writeFile(t, filepath.Join(dir, antigravityMCPFile), config)
	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "mcps", "github.yaml"))
	if err != nil {
		t.Fatalf("missing mcps/github.yaml: %v", err)
	}
	got := string(data)
	if !strings.Contains(got, "url: https://api.githubcopilot.com/mcp/") {
		t.Errorf("expected serverUrl renamed to url, got: %s", got)
	}
	if strings.Contains(got, "serverUrl") {
		t.Errorf("serverUrl must not survive the import, got: %s", got)
	}
}

// A field beyond the ones this adapter maps explicitly (authProviderType,
// oauth, disabledTools: antigravity.google/docs/mcp?tab=ide) round-trips
// through x-antigravity, the same escape hatch mcp.go's buildMCPServer
// emits it through on the way out (#588, #589).
func TestImportFromAntigravity_MCPUnknownFieldRoundTripsUnderXAntigravity(t *testing.T) {
	dir := t.TempDir()
	config := `{
  "mcpServers": {
    "corp-tools": {"serverUrl": "https://mcp.corp.example/tools", "authProviderType": "google_credentials"}
  }
}`
	writeFile(t, filepath.Join(dir, antigravityMCPFile), config)
	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "mcps", "corp-tools.yaml"))
	if err != nil {
		t.Fatalf("missing mcps/corp-tools.yaml: %v", err)
	}
	got := string(data)
	if !strings.Contains(got, "x-antigravity") || !strings.Contains(got, "authProviderType: google_credentials") {
		t.Errorf("expected authProviderType preserved under x-antigravity, got: %s", got)
	}
}

// A rule with `trigger: glob` (post-#1113 emit) imports back with
// `globs` set and `alwaysApply: false`, and the exact native trigger
// preserved under `x-antigravity.trigger` too (#1117 review):
// collapsing straight to the generic fields and dropping the original
// value loses information a re-emit cannot always recover, so
// rule.go's ruleTrigger reads this override back first.
func TestImportFromAntigravity_RuleGlobTriggerBecomesGlobs(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".agents", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(rulesDir, "py-style.md"),
		"---\ntrigger: glob\nglobs: '**/*.py'\n---\n\n<!-- Generated by agnostic-ai. Do not edit. -->\n\n# py-style\n\ngofmt clean.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "rules", "py-style.md"))
	if err != nil {
		t.Fatalf("missing rules/py-style.md: %v", err)
	}
	got := string(data)
	for _, want := range []string{"globs: '**/*.py'", "alwaysApply: false", "x-antigravity:", "trigger: glob"} {
		if !strings.Contains(got, want) {
			t.Errorf("expected %q, got: %s", want, got)
		}
	}
}

// A rule with `trigger: model_decision` and a `description` imports
// back with `alwaysApply: false` and the description preserved.
func TestImportFromAntigravity_RuleModelDecisionTriggerBecomesAlwaysApplyFalse(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".agents", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(rulesDir, "migrations.md"),
		"---\ntrigger: model_decision\ndescription: Apply for migrations.\n---\n\n<!-- Generated by agnostic-ai. Do not edit. -->\n\n# migrations\n\nExpand and contract.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "rules", "migrations.md"))
	if err != nil {
		t.Fatalf("missing rules/migrations.md: %v", err)
	}
	got := string(data)
	for _, want := range []string{"alwaysApply: false", "description: Apply for migrations."} {
		if !strings.Contains(got, want) {
			t.Errorf("expected %q, got: %s", want, got)
		}
	}
}

// A `trigger: always_on` rule (an author-written one; sync never emits
// this key for the default case) imports with `alwaysApply: true`.
func TestImportFromAntigravity_RuleAlwaysOnTriggerBecomesAlwaysApplyTrue(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".agents", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(rulesDir, "house.md"),
		"---\ntrigger: always_on\n---\n\n<!-- Generated by agnostic-ai. Do not edit. -->\n\n# house\n\nUse tabs.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "rules", "house.md"))
	if err != nil {
		t.Fatalf("missing rules/house.md: %v", err)
	}
	if !strings.Contains(string(data), "alwaysApply: true") {
		t.Errorf("expected alwaysApply: true, got: %s", data)
	}
}

// A `trigger: manual` rule (the vendor's "load only on an @-mention"
// mode, needing no companion field) imports with `alwaysApply: false`
// and the native trigger preserved under `x-antigravity.trigger`.
func TestImportFromAntigravity_RuleManualTriggerBecomesAlwaysApplyFalse(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".agents", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(rulesDir, "checklist.md"),
		"---\ntrigger: manual\n---\n\n<!-- Generated by agnostic-ai. Do not edit. -->\n\n# checklist\n\nRelease checklist.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "rules", "checklist.md"))
	if err != nil {
		t.Fatalf("missing rules/checklist.md: %v", err)
	}
	got := string(data)
	for _, want := range []string{"alwaysApply: false", "x-antigravity:", "trigger: manual"} {
		if !strings.Contains(got, want) {
			t.Errorf("expected %q, got: %s", want, got)
		}
	}
	if strings.Contains(got, "globs:") || strings.Contains(got, "description:") {
		t.Errorf("did not expect globs or description in the imported spec, got: %s", got)
	}
}

// The regression this PR fixes (#1117 review): a `manual` rule that
// also carries a `description` (the vendor recommends one on every
// rule) must keep `x-antigravity.trigger: manual` on import. Without
// it, the generic fields alone (`alwaysApply: false` + a description,
// no globs) re-derive as `model_decision` on the next sync, silently
// turning an explicit @-mention-only rule into an automatically-loaded
// one.
func TestImportFromAntigravity_ManualTriggerWithDescriptionPreservesNativeOverride(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".agents", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(rulesDir, "checklist.md"),
		"---\ntrigger: manual\ndescription: Release checklist, read on demand.\n---\n\n<!-- Generated by agnostic-ai. Do not edit. -->\n\n# checklist\n\nConfirm the changelog.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "rules", "checklist.md"))
	if err != nil {
		t.Fatalf("missing rules/checklist.md: %v", err)
	}
	got := string(data)
	for _, want := range []string{"alwaysApply: false", "description: Release checklist, read on demand.", "x-antigravity:", "trigger: manual"} {
		if !strings.Contains(got, want) {
			t.Errorf("expected %q, got: %s", want, got)
		}
	}
}

// An unrecognized trigger value (a hand-edited typo, or a future
// vendor addition agnostic-ai does not know yet) gets no generic
// `alwaysApply` mapping, only the verbatim `x-antigravity.trigger`, and
// a warning, so it never silently re-derives as some default on the
// next sync (#1117 review).
func TestImportFromAntigravity_UnknownTriggerPreservedVerbatimAndWarns(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".agents", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(rulesDir, "typo.md"),
		"---\ntrigger: alwaysOn\n---\n\n<!-- Generated by agnostic-ai. Do not edit. -->\n\n# typo\n\nUse tabs.\n")

	var buf bytes.Buffer
	prev := logOut
	logOut = &buf
	defer func() { logOut = prev }()

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(buf.String(), `trigger "alwaysOn"`) {
		t.Errorf("expected a warning naming the unrecognized trigger, got: %s", buf.String())
	}

	data, err := os.ReadFile(filepath.Join(dir, "rules", "typo.md"))
	if err != nil {
		t.Fatalf("missing rules/typo.md: %v", err)
	}
	got := string(data)
	if !strings.Contains(got, "x-antigravity:") || !strings.Contains(got, "trigger: alwaysOn") {
		t.Errorf("expected the unrecognized trigger preserved verbatim under x-antigravity, got: %s", got)
	}
	if strings.Contains(got, "alwaysApply:") {
		t.Errorf("an unrecognized trigger must not get a generic alwaysApply mapping, got: %s", got)
	}
}

func TestImportFromAntigravity_MirrorsAgentsMD(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".agents"), 0o755); err != nil {
		t.Fatal(err)
	}
	body := "# Project\n\nTop-level instructions.\n"
	writeFile(t, filepath.Join(dir, ".agents", "AGENTS.md"), body)

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, agnosticMainFile))
	if err != nil {
		t.Fatalf("missing %s: %v", agnosticMainFile, err)
	}
	if string(got) != body {
		t.Errorf("%s not byte-identical to .agents/AGENTS.md. got %q", agnosticMainFile, got)
	}
}

// A project synced before #1114 only has the legacy `.agent/AGENTS.md`.
// Import falls back to it when the preferred `.agents/AGENTS.md` is
// absent.
func TestImportFromAntigravity_MirrorsLegacyAgentsMD(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".agent"), 0o755); err != nil {
		t.Fatal(err)
	}
	body := "# Project\n\nLegacy top-level instructions.\n"
	writeFile(t, filepath.Join(dir, ".agent", "AGENTS.md"), body)

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, agnosticMainFile))
	if err != nil {
		t.Fatalf("missing %s: %v", agnosticMainFile, err)
	}
	if string(got) != body {
		t.Errorf("%s not byte-identical to .agent/AGENTS.md. got %q", agnosticMainFile, got)
	}
}
