package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestImportFromContinue_RulesAndMCPs(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".continue", "rules")
	mcpDir := filepath.Join(dir, ".continue", "mcpServers")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(mcpDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(rulesDir, "go-style.md"),
		"<!-- Generated by agnostic-ai. Do not edit. -->\n\n# go-style\n\ngofmt clean.\n")
	writeFile(t, filepath.Join(mcpDir, "stdio-one.yaml"),
		"# Generated by agnostic-ai. Do not edit.\n\nname: stdio-one\ncommand: npx\nargs:\n  - server\n")
	writeFile(t, filepath.Join(mcpDir, "http-one.yaml"),
		"# Generated by agnostic-ai. Do not edit.\n\nname: http-one\ntype: http\nurl: https://example.test/mcp\n")

	if err := importFromContinue(dir, rootSources()); err != nil {
		t.Fatal(err)
	}

	ruleData, err := os.ReadFile(filepath.Join(dir, "rules", "go-style.md"))
	if err != nil {
		t.Fatalf("missing rules/go-style.md: %v", err)
	}
	if !strings.Contains(string(ruleData), "gofmt clean.") {
		t.Errorf("expected rule body, got %s", ruleData)
	}

	stdio, err := os.ReadFile(filepath.Join(dir, "mcps", "stdio-one.yaml"))
	if err != nil {
		t.Fatalf("missing mcps/stdio-one.yaml: %v", err)
	}
	if strings.Contains(string(stdio), "Generated by agnostic-ai") {
		t.Errorf("provenance header not stripped: %s", stdio)
	}
	if !strings.Contains(string(stdio), "name: stdio-one") {
		t.Errorf("name lost: %s", stdio)
	}
	if !strings.Contains(string(stdio), "command: npx") {
		t.Errorf("command lost: %s", stdio)
	}

	http, err := os.ReadFile(filepath.Join(dir, "mcps", "http-one.yaml"))
	if err != nil {
		t.Fatalf("missing mcps/http-one.yaml: %v", err)
	}
	if !strings.Contains(string(http), "type: http") {
		t.Errorf("transport lost: %s", http)
	}
	if !strings.Contains(string(http), "url: https://example.test/mcp") {
		t.Errorf("url lost: %s", http)
	}
}

// A Continue block file speaks Continue's dialect: `streamable-http`
// where the spec says `http`, and headers one level down under
// `requestOptions`. Both come back in the agnostic spelling, or the
// imported spec would emit headerless on the next sync and would be
// skipped by every target whose vendor accepts only `http`.
func TestImportFromContinue_MCPUnwrapsVendorSpellings(t *testing.T) {
	dir := t.TempDir()
	mcpDir := filepath.Join(dir, ".continue", "mcpServers")
	if err := os.MkdirAll(mcpDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(mcpDir, "linear.yaml"),
		"# Generated by agnostic-ai. Do not edit.\n\n"+
			"mcpServers:\n"+
			"    - name: linear\n"+
			"      requestOptions:\n"+
			"        headers:\n"+
			"            Authorization: Bearer x\n"+
			"      type: streamable-http\n"+
			"      url: https://mcp.linear.app\n"+
			"name: linear\nschema: v1\nversion: 0.0.1\n")

	if err := importFromContinue(dir, rootSources()); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(dir, "mcps", "linear.yaml"))
	if err != nil {
		t.Fatalf("missing mcps/linear.yaml: %v", err)
	}
	if !strings.Contains(string(got), "type: http\n") {
		t.Errorf("transport not normalized to the spec spelling: %s", got)
	}
	if strings.Contains(string(got), "requestOptions") {
		t.Errorf("requestOptions wrapper survived import: %s", got)
	}
	if !strings.Contains(string(got), "headers:\n    Authorization: Bearer x") {
		t.Errorf("headers not lifted to the top level: %s", got)
	}
}

func TestImportFromContinue_MCPDirMissingNoOp(t *testing.T) {
	dir := t.TempDir()
	if err := importFromContinue(dir, rootSources()); err != nil {
		t.Fatal(err)
	}
	entries, _ := os.ReadDir(filepath.Join(dir, "mcps"))
	if len(entries) != 0 {
		t.Errorf("expected empty mcps dir, got %d", len(entries))
	}
}
