package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestImportFromAntigravity_RulesAndAgents(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".agent", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(rulesDir, "go-style.md"),
		"<!-- Generated by agnostic-ai. Do not edit. -->\n\n# go-style\n\ngofmt clean.\n")
	writeFile(t, filepath.Join(rulesDir, "agent-helper.md"),
		"<!-- Generated by agnostic-ai. Do not edit. -->\n\n# Agent: helper\n\nhelper body.\n")

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}

	ruleData, err := os.ReadFile(filepath.Join(dir, "rules", "go-style.md"))
	if err != nil {
		t.Fatalf("missing rules/go-style.md: %v", err)
	}
	if !strings.Contains(string(ruleData), "name: go-style") {
		t.Errorf("expected name: go-style frontmatter, got %s", ruleData)
	}
	if !strings.Contains(string(ruleData), "gofmt clean.") {
		t.Errorf("expected rule body, got %s", ruleData)
	}
	if strings.Contains(string(ruleData), "Generated by agnostic-ai") {
		t.Errorf("provenance header not stripped: %s", ruleData)
	}

	agentData, err := os.ReadFile(filepath.Join(dir, "agents", "helper.md"))
	if err != nil {
		t.Fatalf("missing agents/helper.md: %v", err)
	}
	if !strings.Contains(string(agentData), "name: helper") {
		t.Errorf("expected name: helper frontmatter, got %s", agentData)
	}
	if !strings.Contains(string(agentData), "helper body.") {
		t.Errorf("expected agent body, got %s", agentData)
	}
}

func TestImportFromAntigravity_MirrorsAgentsMD(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".agent"), 0o755); err != nil {
		t.Fatal(err)
	}
	body := "# Project\n\nTop-level instructions.\n"
	writeFile(t, filepath.Join(dir, ".agent", "AGENTS.md"), body)

	if err := importFromAntigravity(dir, rootSources(), nil); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, agnosticMainFile))
	if err != nil {
		t.Fatalf("missing %s: %v", agnosticMainFile, err)
	}
	if string(got) != body {
		t.Errorf("%s not byte-identical to .agent/AGENTS.md. got %q", agnosticMainFile, got)
	}
}
