package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

const appEnvironmentTOML = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "Acme"

[setup]
script = "bash scripts/setup-worktree.bash"

[cleanup]
script = "bash scripts/stop-preview.bash"

[[actions]]
name = "Dashboard"
icon = "run"
command = "bash scripts/run-preview.bash"

[[actions]]
name = "Tests"
icon = "test"
command = '''
go test ./...
go vet ./...
'''
`

// A hand-written .codex/environments/environment.toml becomes an
// environment spec (#1393).
func TestImportFromCodex_ReadsEnvironmentTOML(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".codex", "environments", "environment.toml"), appEnvironmentTOML)
	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}
	got := readFileString(t, filepath.Join(dir, "environments", "codex.yaml"))
	want := `name: Acme
setup: bash scripts/setup-worktree.bash
cleanup: bash scripts/stop-preview.bash
dev-commands:
    - name: Dashboard
      command: bash scripts/run-preview.bash
    - name: Tests
      command: |-
        go test ./...
        go vet ./...
      icon: test
`
	if got != want {
		t.Errorf("environments/codex.yaml:\n%s\nwant:\n%s", got, want)
	}
}

func TestImportFromCodex_ReadsWindowsSetupScript(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".codex", "environments", "environment.toml"), `version = 1
name = "web"

[setup]
script = "npm ci"

[setup.win32]
script = "npm ci --no-audit"
`)
	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}
	got := readFileString(t, filepath.Join(dir, "environments", "codex.yaml"))
	want := "name: web\nsetup: npm ci\nsetup-windows: npm ci --no-audit\n"
	if got != want {
		t.Errorf("environments/codex.yaml:\n%s\nwant:\n%s", got, want)
	}
}

// import, then sync, writes an environment.toml with the same scripts and
// actions, and the other targets get their files from the same spec.
func TestImportFromCodex_EnvironmentTOMLSurvivesSync(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)
	silence(t)
	captureLogOut(t)
	writeFile(t, "agnostic-ai.yaml", "version: 1\ntargets: [codex, cursor, claude]\n")
	writeFile(t, filepath.Join(".codex", "environments", "environment.toml"), appEnvironmentTOML)

	for _, args := range [][]string{{"import", "codex"}, {"sync"}, {"sync", "--check"}} {
		root := NewRootCmd("test")
		root.SetArgs(args)
		if err := root.Execute(); err != nil {
			t.Fatalf("%v: %v", args, err)
		}
	}
	got := readFile(t, filepath.Join(".codex", "environments", "environment.toml"))
	for _, want := range []string{
		"name = \"Acme\"\n",
		"[setup]\nscript = \"bash scripts/setup-worktree.bash\"\n",
		"[cleanup]\nscript = \"bash scripts/stop-preview.bash\"\n",
		"[[actions]]\nname = \"Dashboard\"\nicon = \"run\"\ncommand = \"bash scripts/run-preview.bash\"\n",
		"name = \"Tests\"\nicon = \"test\"\ncommand = \"\"\"\ngo test ./...\ngo vet ./...\n\"\"\"\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("synced environment.toml misses %q:\n%s", want, got)
		}
	}
	if _, err := os.Stat(filepath.Join(".claude", "launch.json")); err != nil {
		t.Errorf("the same spec did not reach .claude/launch.json: %v", err)
	}
}

// A file sync wrote, an existing spec, and a key the spec cannot hold all
// leave the file alone.
func TestImportFromCodex_LeavesEnvironmentTOMLItCannotHold(t *testing.T) {
	cases := map[string]string{
		"a darwin script":    "version = 1\nname = \"a\"\n[setup]\nscript = \"x\"\n[setup.darwin]\nscript = \"y\"\n",
		"an action platform": "version = 1\nname = \"a\"\n[[actions]]\nname = \"Run\"\ncommand = \"x\"\nplatform = \"darwin\"\n",
		"a windows cleanup":  "version = 1\nname = \"a\"\n[cleanup]\nscript = \"x\"\n[cleanup.win32]\nscript = \"y\"\n",
		"an unknown key":     "version = 1\nname = \"a\"\nextra = 1\n",
		"a repeated action":  "version = 1\nname = \"a\"\n[[actions]]\nname = \"Run\"\ncommand = \"x\"\n[[actions]]\nname = \"Run\"\ncommand = \"y\"\n",
	}
	for name, body := range cases {
		dir := t.TempDir()
		writeFile(t, filepath.Join(dir, ".codex", "environments", "environment.toml"), body)
		if err := importFromCodex(dir, rootSources()); err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if _, err := os.Stat(filepath.Join(dir, "environments", "codex.yaml")); !os.IsNotExist(err) {
			t.Errorf("%s: the file was imported: %v", name, err)
		}
	}

	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".codex", "environments", "environment.toml"), appEnvironmentTOML)
	own := "name: mine\nsetup: make other\n"
	writeFile(t, filepath.Join(dir, "environments", "codex.yaml"), own)
	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}
	if got := readFileString(t, filepath.Join(dir, "environments", "codex.yaml")); got != own {
		t.Errorf("existing spec changed:\n%s", got)
	}

	synced := t.TempDir()
	writeFile(t, filepath.Join(synced, ".codex", "environments", "environment.toml"), appEnvironmentTOML)
	writeFile(t, filepath.Join(synced, ".agnostic-ai", ".sync-state"), `{"outputs":[".codex/environments/environment.toml"]}`)
	if err := importFromCodex(synced, rootSources()); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(synced, "environments", "codex.yaml")); !os.IsNotExist(err) {
		t.Errorf("a synced environment.toml was imported: %v", err)
	}
}

func TestImportFromCodex_ReportsInvalidEnvironmentTOML(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".codex", "environments", "environment.toml"), "version = ")
	if err := importFromCodex(dir, rootSources()); err == nil {
		t.Fatal("want a parse error")
	}
}

// The cd that sync writes for a dev command's cwd imports back as cwd.
func TestImportFromCodex_ReadsActionCwd(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".codex", "environments", "environment.toml"), `version = 1
name = "web"

[[actions]]
name = "Docs"
icon = "run"
command = "cd apps/docs && pnpm dev"

[[actions]]
name = "Site"
icon = "run"
command = "cd 'my site' && npm start"

[[actions]]
name = "Seed"
icon = "run"
command = """
cd api || exit 1
npm run seed
"""
`)
	if err := importFromCodex(dir, rootSources()); err != nil {
		t.Fatal(err)
	}
	got := readFileString(t, filepath.Join(dir, "environments", "codex.yaml"))
	want := `name: web
dev-commands:
    - name: Docs
      command: pnpm dev
      cwd: apps/docs
    - name: Site
      command: npm start
      cwd: my site
    - name: Seed
      command: npm run seed
      cwd: api
`
	if got != want {
		t.Errorf("environments/codex.yaml:\n%s\nwant:\n%s", got, want)
	}
}
