package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

// TestImportCline_RoundTripFixedPoint emits a bundle to cline, wipes the
// source specs, imports the emitted tree back, then re-emits. The
// second emit must byte-match the first: import reconstructs rules
// (from `.cline/rules/`), agents (from `.cline/agents/`, native
// per-file), and skills (from `.cline/skills/`, Cline's native
// SKILL.md folder tree).
func TestImportCline_RoundTripFixedPoint(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)
	silence(t)

	writeFile(t, filepath.Join(dir, "agnostic-ai.yaml"), "version: 1\ntargets: [cline]\n")
	writeFile(t, filepath.Join(dir, ".agnostic-ai", "rules", "r1.md"),
		"---\nname: r1\n---\n\nrule one body\n")
	writeFile(t, filepath.Join(dir, ".agnostic-ai", "agents", "reviewer.md"),
		"---\nname: reviewer\n---\n\nagent body\n")
	writeFile(t, filepath.Join(dir, ".agnostic-ai", "skills", "my-skill", "SKILL.md"),
		"---\nname: my-skill\ndescription: An example skill\n---\n\nSkill body here.\n")

	execCLI(t, "sync", "-t", "cline")
	first := snapshotEmitted(t, dir)
	if _, ok := first[".cline/skills/my-skill/SKILL.md"]; !ok {
		t.Fatalf("first emit produced no skill folder: %v", keys(first))
	}
	if _, ok := first[".cline/rules/r1.md"]; !ok {
		t.Fatalf("first emit produced no rule file: %v", keys(first))
	}
	if _, ok := first[".cline/agents/reviewer.md"]; !ok {
		t.Fatalf("first emit produced no agent file: %v", keys(first))
	}

	if err := os.RemoveAll(filepath.Join(dir, ".agnostic-ai")); err != nil {
		t.Fatalf("wipe source specs: %v", err)
	}
	execCLI(t, "import", "cline")

	rule := readFile(t, filepath.Join(dir, ".agnostic-ai", "rules", "r1.md"))
	if !strings.Contains(rule, "rule one body") {
		t.Errorf("rule not reconstructed:\n%s", rule)
	}
	agent := readFile(t, filepath.Join(dir, ".agnostic-ai", "agents", "reviewer.md"))
	if !strings.Contains(agent, "agent body") {
		t.Errorf("agent not reconstructed:\n%s", agent)
	}
	skill := readFile(t, filepath.Join(dir, ".agnostic-ai", "skills", "my-skill", "SKILL.md"))
	if !strings.Contains(skill, "description: An example skill") || !strings.Contains(skill, "Skill body here.") {
		t.Errorf("skill not reconstructed:\n%s", skill)
	}

	execCLI(t, "sync", "-t", "cline")
	second := snapshotEmitted(t, dir)
	assertEmittedEqual(t, first, second)
}

// TestImportCline_LegacyFlatSkillStillImports covers a project synced
// before skills moved to a native folder: a flat
// `.clinerules/skill-<name>.md` still round-trips as a skill.
func TestImportCline_LegacyFlatSkillStillImports(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)
	silence(t)

	writeFile(t, filepath.Join(dir, "agnostic-ai.yaml"), "version: 1\ntargets: [cline]\n")
	writeFile(t, filepath.Join(dir, ".clinerules", "skill-legacy.md"),
		"# Skill: legacy\n\nlegacy skill body\n")

	execCLI(t, "import", "cline")

	got := readFile(t, filepath.Join(dir, ".agnostic-ai", "skills", "legacy.md"))
	if !strings.Contains(got, "legacy skill body") {
		t.Errorf("legacy flat skill not imported:\n%s", got)
	}
}

// TestImportCline_KnownSourceWiredIn guards the wiring: cline moved off
// the generic rulesDirImporters map onto its own dedicated importer and
// must stay a known source.
func TestImportCline_KnownSourceWiredIn(t *testing.T) {
	if !isKnownImportSource("cline") {
		t.Error("cline should be a known import source")
	}
	sources := importSources()
	if !strings.Contains(sources, "cline") {
		t.Errorf("importSources() missing %q: %s", "cline", sources)
	}
}

// TestImportFromCline_ReadsLegacyClinerulesWhenNewAbsent covers a
// project synced before #534: rules and agents both lived combined
// under `.clinerules/`, agents reclassified by the `agent-<name>.md`
// filename prefix. Import must still reconstruct both when `.cline/
// rules/` does not exist yet.
func TestImportFromCline_ReadsLegacyClinerulesWhenNewAbsent(t *testing.T) {
	dir := t.TempDir()
	legacyDir := filepath.Join(dir, ".clinerules")
	if err := os.MkdirAll(legacyDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(legacyDir, "style.md"),
		"<!-- Generated by agnostic-ai. Do not edit. -->\n\n# style\n\nUse 2-space indent.\n")
	writeFile(t, filepath.Join(legacyDir, "agent-reviewer.md"),
		"<!-- Generated by agnostic-ai. Do not edit. -->\n\n# Agent: reviewer\n\nReview the diff.\n")

	if err := importFromCline(dir, rootSources()); err != nil {
		t.Fatal(err)
	}

	rule, err := os.ReadFile(filepath.Join(dir, "rules", "style.md"))
	if err != nil {
		t.Fatalf("missing rules/style.md: %v", err)
	}
	if !strings.Contains(string(rule), "Use 2-space indent.") {
		t.Errorf("expected rule body, got %s", rule)
	}
	agent, err := os.ReadFile(filepath.Join(dir, "agents", "reviewer.md"))
	if err != nil {
		t.Fatalf("missing agents/reviewer.md: %v", err)
	}
	if !strings.Contains(string(agent), "Review the diff.") {
		t.Errorf("expected agent body, got %s", agent)
	}
}

// TestImportFromCline_PrefersNewRulesDirOverLegacy asserts `.cline/
// rules/` wins when both it and the legacy `.clinerules/` exist,
// matching the preference order windsurf's and antigravity's importers
// already use for their own post-migration / pre-migration pairs.
func TestImportFromCline_PrefersNewRulesDirOverLegacy(t *testing.T) {
	dir := t.TempDir()
	newDir := filepath.Join(dir, ".cline", "rules")
	legacyDir := filepath.Join(dir, ".clinerules")
	if err := os.MkdirAll(newDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(legacyDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(newDir, "current.md"), "# current\n\nfrom the new dir.\n")
	writeFile(t, filepath.Join(legacyDir, "stale.md"), "# stale\n\nfrom the legacy dir.\n")

	if err := importFromCline(dir, rootSources()); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Join(dir, "rules", "current.md")); err != nil {
		t.Errorf("missing rules/current.md: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "rules", "stale.md")); !os.IsNotExist(err) {
		t.Errorf("rules/stale.md should not be imported when .cline/rules exists, err=%v", err)
	}
}

// TestImportFromCline_ReadsNativeAgentsDir covers the current default:
// agents live flat under `.cline/agents/`, no `agent-` prefix, no
// frontmatter (target-audit 2026-08-01, #534).
func TestImportFromCline_ReadsNativeAgentsDir(t *testing.T) {
	dir := t.TempDir()
	agentsDir := filepath.Join(dir, ".cline", "agents")
	if err := os.MkdirAll(agentsDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(agentsDir, "reviewer.md"),
		"<!-- Generated by agnostic-ai. Do not edit. -->\n\nReview the diff for correctness.\n")

	if err := importFromCline(dir, rootSources()); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(dir, "agents", "reviewer.md"))
	if err != nil {
		t.Fatalf("missing agents/reviewer.md: %v", err)
	}
	if !strings.Contains(string(got), "Review the diff for correctness.") {
		t.Errorf("expected agent body, got %s", got)
	}
	if strings.Contains(string(got), "Generated by agnostic-ai") {
		t.Errorf("provenance header not stripped: %s", got)
	}
}
