package cli

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters"
)

func TestRecordLedgerWrites_KeepsCreatesUpdatesAndSkips(t *testing.T) {
	writes := []adapters.WrittenFile{
		{Path: "a.md", Action: "create"},
		{Path: "b.md", Action: "update"},
		{Path: "c.md", Action: "skip"},
		{Path: "d.md", Action: "delete"},
	}
	var session []string
	recordLedgerWrites(writes, &session)
	want := []string{"a.md", "b.md", "c.md"}
	if len(session) != len(want) {
		t.Fatalf("session=%v, want %v", session, want)
	}
	for i, p := range want {
		if session[i] != p {
			t.Errorf("session[%d]=%q, want %q", i, session[i], p)
		}
	}
}

func TestFinalizeLedger_SortsAndDeduplicates(t *testing.T) {
	in := []string{"b/x.md", "a/y.md", "b/x.md", "a/y.md", "c/z.md"}
	got := finalizeLedger(in)
	want := []string{"a/y.md", "b/x.md", "c/z.md"}
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("[%d] got %q want %q", i, got[i], want[i])
		}
	}
}

func TestSweepLedgerOrphans_RemovesProvenanceFilesNotInCurrent(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	orphan := filepath.Join(".legacy", "old.toml")
	if err := os.MkdirAll(filepath.Dir(orphan), 0o755); err != nil {
		t.Fatal(err)
	}
	body := "# Generated by agnostic-ai\nkey = 1\n"
	if err := os.WriteFile(orphan, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}

	removed, err := sweepLedgerOrphans([]string{orphan}, []string{"active/new.toml"}, false)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 1 || removed[0] != orphan {
		t.Errorf("removed=%v, want [%q]", removed, orphan)
	}
	if _, err := os.Stat(orphan); !os.IsNotExist(err) {
		t.Errorf("orphan still on disk: %v", err)
	}
	if _, err := os.Stat(".legacy"); !os.IsNotExist(err) {
		t.Errorf("empty parent dir should have been pruned: %v", err)
	}
}

func TestSweepLedgerOrphans_LeavesUserFilesUntouched(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	userPath := "mine.toml"
	user := "# hand-authored\nkey = 1\n"
	if err := os.WriteFile(userPath, []byte(user), 0o644); err != nil {
		t.Fatal(err)
	}

	removed, err := sweepLedgerOrphans([]string{userPath}, nil, false)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 0 {
		t.Errorf("user file should not be reported as removed, got %v", removed)
	}
	got, err := os.ReadFile(userPath)
	if err != nil {
		t.Fatalf("user file removed: %v", err)
	}
	if string(got) != user {
		t.Errorf("user file changed: %q", got)
	}
}

func TestSweepLedgerOrphans_EmptyPriorIsNoOp(t *testing.T) {
	removed, err := sweepLedgerOrphans(nil, []string{"x"}, false)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 0 {
		t.Errorf("empty prior should produce no removals, got %v", removed)
	}
}

func TestSweepLedgerOrphans_KeepsPathStillInCurrent(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	path := "kept.toml"
	body := "# Generated by agnostic-ai\nkey = 1\n"
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}

	removed, err := sweepLedgerOrphans([]string{path}, []string{path}, false)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 0 {
		t.Errorf("path still in current must not be removed, got %v", removed)
	}
	if _, err := os.Stat(path); err != nil {
		t.Errorf("kept file unexpectedly removed: %v", err)
	}
}

func TestSweepLedgerOrphans_DryRunDoesNotTouchDisk(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	path := "stale.toml"
	body := "# Generated by agnostic-ai\nkey = 1\n"
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}

	removed, err := sweepLedgerOrphans([]string{path}, nil, true)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 1 || removed[0] != path {
		t.Errorf("dry-run should report intent, got %v", removed)
	}
	if _, err := os.Stat(path); err != nil {
		t.Errorf("dry-run touched disk: %v", err)
	}
}

func TestSweepLedgerOrphans_KeepsParentWhenSiblingsRemain(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	orphan := filepath.Join(".x", "gone.toml")
	keeper := filepath.Join(".x", "stay.toml")
	if err := os.MkdirAll(filepath.Dir(orphan), 0o755); err != nil {
		t.Fatal(err)
	}
	body := "# Generated by agnostic-ai\nkey = 1\n"
	if err := os.WriteFile(orphan, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(keeper, []byte("# user\nkey = 2\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	removed, err := sweepLedgerOrphans([]string{orphan}, nil, false)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 1 {
		t.Errorf("removed=%v", removed)
	}
	if _, err := os.Stat(".x"); err != nil {
		t.Errorf("parent dir must stay because sibling remains: %v", err)
	}
}

// chdir is a local helper because the cli package does not already
// import testutil. Switching cwd lets sweepLedgerOrphans resolve the
// relative paths from the temp dir without picking up the host repo.
func chdir(t *testing.T, dir string) {
	t.Helper()
	prev, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(prev) })
}
