package cli

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters"
)

func TestRecordLedgerWrites_KeepsCreatesUpdatesAndSkips(t *testing.T) {
	writes := []adapters.WrittenFile{
		{Path: "a.md", Action: "create"},
		{Path: "b.md", Action: "update"},
		{Path: "c.md", Action: "skip"},
		{Path: "d.md", Action: "delete"},
	}
	var session []string
	recordLedgerWrites(writes, &session, map[string]string{})
	want := []string{"a.md", "b.md", "c.md"}
	if len(session) != len(want) {
		t.Fatalf("session=%v, want %v", session, want)
	}
	for i, p := range want {
		if session[i] != p {
			t.Errorf("session[%d]=%q, want %q", i, session[i], p)
		}
	}
}

func TestFinalizeLedger_SortsAndDeduplicates(t *testing.T) {
	in := []string{"b/x.md", "a/y.md", "b/x.md", "a/y.md", "c/z.md"}
	got := finalizeLedger(in)
	want := []string{"a/y.md", "b/x.md", "c/z.md"}
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("[%d] got %q want %q", i, got[i], want[i])
		}
	}
}

func TestSweepLedgerOrphans_RemovesProvenanceFilesNotInCurrent(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	orphan := filepath.Join(".legacy", "old.toml")
	if err := os.MkdirAll(filepath.Dir(orphan), 0o755); err != nil {
		t.Fatal(err)
	}
	body := "# Generated by agnostic-ai\nkey = 1\n"
	if err := os.WriteFile(orphan, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}

	removed, _, err := sweepLedgerOrphans(adapters.NewSession(), []string{orphan}, nil, []string{"active/new.toml"})
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 1 || removed[0] != orphan {
		t.Errorf("removed=%v, want [%q]", removed, orphan)
	}
	if _, err := os.Stat(orphan); !os.IsNotExist(err) {
		t.Errorf("orphan still on disk: %v", err)
	}
	if _, err := os.Stat(".legacy"); !os.IsNotExist(err) {
		t.Errorf("empty parent dir should have been pruned: %v", err)
	}
}

func TestSweepLedgerOrphans_LeavesUserFilesUntouched(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	userPath := "mine.toml"
	user := "# hand-authored\nkey = 1\n"
	if err := os.WriteFile(userPath, []byte(user), 0o644); err != nil {
		t.Fatal(err)
	}

	removed, _, err := sweepLedgerOrphans(adapters.NewSession(), []string{userPath}, nil, nil)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 0 {
		t.Errorf("user file should not be reported as removed, got %v", removed)
	}
	got, err := os.ReadFile(userPath)
	if err != nil {
		t.Fatalf("user file removed: %v", err)
	}
	if string(got) != user {
		t.Errorf("user file changed: %q", got)
	}
}

func TestSweepLedgerOrphans_EmptyPriorIsNoOp(t *testing.T) {
	removed, _, err := sweepLedgerOrphans(adapters.NewSession(), nil, nil, []string{"x"})
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 0 {
		t.Errorf("empty prior should produce no removals, got %v", removed)
	}
}

func TestSweepLedgerOrphans_KeepsPathStillInCurrent(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	path := "kept.toml"
	body := "# Generated by agnostic-ai\nkey = 1\n"
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}

	removed, _, err := sweepLedgerOrphans(adapters.NewSession(), []string{path}, nil, []string{path})
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 0 {
		t.Errorf("path still in current must not be removed, got %v", removed)
	}
	if _, err := os.Stat(path); err != nil {
		t.Errorf("kept file unexpectedly removed: %v", err)
	}
}

func TestSweepLedgerOrphans_KeepsParentWhenSiblingsRemain(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	orphan := filepath.Join(".x", "gone.toml")
	keeper := filepath.Join(".x", "stay.toml")
	if err := os.MkdirAll(filepath.Dir(orphan), 0o755); err != nil {
		t.Fatal(err)
	}
	body := "# Generated by agnostic-ai\nkey = 1\n"
	if err := os.WriteFile(orphan, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(keeper, []byte("# user\nkey = 2\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	removed, _, err := sweepLedgerOrphans(adapters.NewSession(), []string{orphan}, nil, nil)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 1 {
		t.Errorf("removed=%v", removed)
	}
	if _, err := os.Stat(".x"); err != nil {
		t.Errorf("parent dir must stay because sibling remains: %v", err)
	}
}

func TestCoversAllConfiguredTargets(t *testing.T) {
	cases := []struct {
		name       string
		emitted    []string
		configured []string
		want       bool
	}{
		{"full run", []string{"claude", "codex"}, []string{"claude", "codex"}, true},
		{"order-independent", []string{"codex", "claude"}, []string{"claude", "codex"}, true},
		{"only subset", []string{"claude"}, []string{"claude", "codex"}, false},
		{"empty configured", []string{"claude"}, nil, true},
		{"superset still covers", []string{"claude", "codex", "cursor"}, []string{"claude", "codex"}, true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := coversAllConfiguredTargets(tc.emitted, tc.configured); got != tc.want {
				t.Errorf("coversAllConfiguredTargets(%v, %v)=%v, want %v", tc.emitted, tc.configured, got, tc.want)
			}
		})
	}
}

func TestReconcilePartialLedger_FullRunIsUnchanged(t *testing.T) {
	ledger := []string{"b.md", "a.md"}
	prior := []string{"a.md", "z.md"}
	got := reconcilePartialLedger(ledger, prior, true)
	if len(got) != 2 || got[0] != "b.md" || got[1] != "a.md" {
		t.Errorf("full run must return ledger unchanged, got %v", got)
	}
}

func TestReconcilePartialLedger_PartialRunPreservesPriorOutputs(t *testing.T) {
	// --only claude: ledger holds only claude's files; codex's AGENTS.md
	// lives in prior. The merge keeps it so the sweep cannot delete it.
	ledger := []string{".claude/CLAUDE.md"}
	prior := []string{".claude/CLAUDE.md", "AGENTS.md"}
	got := reconcilePartialLedger(ledger, prior, false)
	want := map[string]bool{".claude/CLAUDE.md": true, "AGENTS.md": true}
	if len(got) != len(want) {
		t.Fatalf("got %v, want keys %v", got, want)
	}
	for _, p := range got {
		if !want[p] {
			t.Errorf("unexpected path %q in merged ledger", p)
		}
	}
}

// TestSweepLedgerOrphans_PartialRunDoesNotDeleteOtherTargets is the
// end-to-end guard for the --only data-loss bug: an un-synced target's
// file must survive when its path is folded back into the current set.
func TestSweepLedgerOrphans_PartialRunDoesNotDeleteOtherTargets(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	other := "AGENTS.md" // owned by codex, not emitted this run
	body := "# Generated by agnostic-ai\nbody\n"
	if err := os.WriteFile(other, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}

	prior := []string{".claude/CLAUDE.md", other}
	ledger := reconcilePartialLedger([]string{".claude/CLAUDE.md"}, prior, false)
	removed, _, err := sweepLedgerOrphans(adapters.NewSession(), prior, nil, ledger)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 0 {
		t.Errorf("partial run must not remove other target files, got %v", removed)
	}
	if _, err := os.Stat(other); err != nil {
		t.Errorf("other target's file was deleted: %v", err)
	}
}

// chdir is a local helper because the cli package does not already
// import testutil. Switching cwd lets sweepLedgerOrphans resolve the
// relative paths from the temp dir without picking up the host repo.
func chdir(t *testing.T, dir string) {
	t.Helper()
	prev, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(prev) })
}

func TestSweepLedgerOrphans_KeepsUnmanagedPath(t *testing.T) {
	chdir(t, t.TempDir())
	const owned = ".cursor/rules/legacy.mdc"
	body := "<!-- Generated by agnostic-ai -->\nold\n"
	mustWriteFile(t, owned, body)
	sess := adapters.NewSession()
	sess.SetUnmanaged([]string{owned})

	removed, _, err := sweepLedgerOrphans(sess, []string{owned}, nil, nil)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}

	if len(removed) != 0 {
		t.Errorf("removed=%v, want none", removed)
	}
	if got := readFile(t, owned); got != body {
		t.Errorf("user-owned file removed or changed: %q", got)
	}
}

// A ledgered shared-skills link that became a real directory (the opt-in
// was turned off, or the folder now holds a user-owned file) is not an
// orphan file: its own files are ledgered separately. The sweep skips it
// instead of failing to read a directory and abandoning later orphans.
func TestSweepLedgerOrphans_SkipsFormerLinkNowDirectory(t *testing.T) {
	chdir(t, t.TempDir())
	const former, orphan = ".cursor/skills/greet", "z-old.md"
	mustWriteFile(t, former+"/SKILL.md", "mine\n")
	mustWriteFile(t, orphan, "<!-- Generated by agnostic-ai -->\nold\n")

	removed, _, err := sweepLedgerOrphans(adapters.NewSession(), []string{former, orphan}, nil, nil)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}

	if len(removed) != 1 || removed[0] != orphan {
		t.Errorf("removed=%v, want only %s", removed, orphan)
	}
	if got := readFile(t, former+"/SKILL.md"); got != "mine\n" {
		t.Errorf("directory content changed: %q", got)
	}
}

func TestRecordLedgerWrites_CollectsSumsForWrittenPaths(t *testing.T) {
	writes := []adapters.WrittenFile{
		{Path: "ref.md", Action: "create", Sum: "abc"},
		{Path: "SKILL.md", Action: "skip"},
		{Path: "gone.md", Action: "delete", Sum: "zzz"},
	}
	var session []string
	sums := map[string]string{}
	recordLedgerWrites(writes, &session, sums)

	if got, ok := sums["ref.md"]; !ok || got != "abc" {
		t.Errorf("sums[ref.md]=%q,%v, want abc", got, ok)
	}
	if got, ok := sums["SKILL.md"]; !ok || got != "" {
		t.Errorf("header file must be recorded as written with no sum, got %q,%v", got, ok)
	}
	if _, ok := sums["gone.md"]; ok {
		t.Error("deleted path must not be recorded")
	}
}

func TestLedgerSums_PrefersThisRunAndCarriesPriorForUnwrittenPaths(t *testing.T) {
	ledger := []string{"fresh.md", "regenerated.md", "carried.md", "headerful.md"}
	written := map[string]string{"fresh.md": "new", "regenerated.md": "", "headerful.md": ""}
	prior := map[string]string{"regenerated.md": "stale", "carried.md": "old", "dropped.md": "x"}

	got := ledgerSums(ledger, written, prior)

	want := map[string]string{"fresh.md": "new", "carried.md": "old"}
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for p, sum := range want {
		if got[p] != sum {
			t.Errorf("got[%s]=%q, want %q", p, got[p], sum)
		}
	}
}

func TestSweepLedgerOrphans_RemovesUneditedHeaderlessAssetAndPrunesSkillDir(t *testing.T) {
	chdir(t, t.TempDir())
	ref := ".claude/skills/gone/references/a.md"
	body := "ref\n"
	mustWriteFile(t, ref, body)

	removed, kept, err := sweepLedgerOrphans(adapters.NewSession(), []string{ref},
		map[string]string{ref: adapters.ContentSum(body)}, nil)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 1 || removed[0] != ref {
		t.Errorf("removed=%v, want [%s]", removed, ref)
	}
	if len(kept) != 0 {
		t.Errorf("kept=%v, want none", kept)
	}
	if _, err := os.Stat(".claude"); !os.IsNotExist(err) {
		t.Errorf("empty skill tree should be pruned: %v", err)
	}
}

func TestSweepLedgerOrphans_KeepsAndReportsEditedHeaderlessAsset(t *testing.T) {
	chdir(t, t.TempDir())
	ref := ".claude/skills/gone/references/a.md"
	mustWriteFile(t, ref, "edited by hand\n")

	removed, kept, err := sweepLedgerOrphans(adapters.NewSession(), []string{ref},
		map[string]string{ref: adapters.ContentSum("ref\n")}, nil)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 0 {
		t.Errorf("removed=%v, want none", removed)
	}
	if len(kept) != 1 || kept[0] != ref {
		t.Errorf("kept=%v, want [%s]", kept, ref)
	}
}

func TestSweepLedgerOrphans_UnmanagedOrphanIsNeitherRemovedNorKept(t *testing.T) {
	chdir(t, t.TempDir())
	const owned = ".claude/skills/gone/references/a.md"
	mustWriteFile(t, owned, "edited\n")
	sess := adapters.NewSession()
	sess.SetUnmanaged([]string{owned})

	removed, kept, err := sweepLedgerOrphans(sess, []string{owned}, nil, nil)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 0 || len(kept) != 0 {
		t.Errorf("removed=%v kept=%v, want both empty", removed, kept)
	}
}

func TestSweepLedgerOrphans_MissingOrphanIsNotKept(t *testing.T) {
	chdir(t, t.TempDir())
	removed, kept, err := sweepLedgerOrphans(adapters.NewSession(), []string{"gone.md"}, nil, nil)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 0 || len(kept) != 0 {
		t.Errorf("removed=%v kept=%v, want both empty", removed, kept)
	}
}

func TestLedgerOrphans_FullRunRecordsKept(t *testing.T) {
	got := ledgerOrphans([]string{"b.md"}, []string{"a.md"}, nil, true)
	if len(got) != 1 || got[0] != "b.md" {
		t.Errorf("got %v, want [b.md]", got)
	}
}

func TestLedgerOrphans_PartialRunCarriesPriorOrphansNotRewritten(t *testing.T) {
	written := map[string]string{"rewritten.md": ""}
	got := ledgerOrphans(nil, []string{"rewritten.md", "still.md"}, written, false)
	if len(got) != 1 || got[0] != "still.md" {
		t.Errorf("got %v, want [still.md]", got)
	}
}

func TestSweepLedgerOrphans_PrunesDirectoryOnceLastSiblingIsRemoved(t *testing.T) {
	chdir(t, t.TempDir())
	skill := ".claude/skills/gone/SKILL.md"
	refs := []string{".claude/skills/gone/references/a.md", ".claude/skills/gone/references/b.md"}
	mustWriteFile(t, skill, "<!-- Generated by agnostic-ai -->\nbody\n")
	sums := map[string]string{}
	for _, r := range refs {
		mustWriteFile(t, r, "ref\n")
		sums[r] = adapters.ContentSum("ref\n")
	}

	_, _, err := sweepLedgerOrphans(adapters.NewSession(), append([]string{skill}, refs...), sums, nil)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if _, err := os.Stat(".claude"); !os.IsNotExist(err) {
		t.Errorf("skill tree should be pruned once every file is gone: %v", err)
	}
}

func TestSweepAndFinalizeLedger_DryRunSweepsNothing(t *testing.T) {
	chdir(t, t.TempDir())
	const out = "CLAUDE.md"
	mustWriteFile(t, out, "<!-- Generated by agnostic-ai -->\nbody\n")
	prev := syncStateFile{Outputs: []string{out}}

	_, kept, removed, err := sweepAndFinalizeLedger(adapters.NewSession(), prev, nil, map[string]string{}, []string{"claude"}, []string{"claude"}, true)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if len(removed) != 0 || len(kept) != 0 {
		t.Errorf("dry run reported removed=%v kept=%v, want none", removed, kept)
	}
	if _, err := os.Stat(out); err != nil {
		t.Errorf("dry run touched disk: %v", err)
	}
}
