package cli

import (
	"bytes"
	"os"
	"os/exec"
	"slices"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestSync_KeepsLegacyOrphanIgnored(t *testing.T) {
	for _, tc := range []struct {
		name         string
		args         []string
		partial      bool
		unreconciled bool
	}{
		{"text", nil, false, false},
		{"json", []string{"--json"}, false, false},
		{"partial text", []string{"--only", "codex"}, true, false},
		{"partial json", []string{"--only", "codex", "--json"}, true, false},
		{"first partial text", []string{"--only", "codex"}, false, true},
		{"first partial json", []string{"--only", "codex", "--json"}, false, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir, _ := gitRepo(t)
			testutil.Chdir(t, dir)
			mustWriteFile(t, "agnostic-ai.yaml", "version: 1\ntargets: [codex, claude]\ngitignore:\n  enabled: true\nsync:\n  unmanaged: [.codex/skills/mine/reference.md]\n")
			const orphan = ".codex/skills/gone/reference.md"
			const unmanaged = ".codex/skills/mine/reference.md"
			mustWriteFile(t, unmanaged, "user-owned\n")
			mustWriteFile(t, orphan, "copied before checksums\n")
			mustWriteFile(t, ".agnostic-ai/.sync-state", `{"version":2,"outputs":["`+orphan+`","`+unmanaged+`"]}`)
			if tc.partial {
				if err := writeStateFile(".", 0, "", "", syncLedger{outputs: []string{orphan, unmanaged}, orphans: []string{orphan}}); err != nil {
					t.Fatal(err)
				}
			}
			var out bytes.Buffer
			prev := logOut
			logOut = &out
			defer func() { logOut = prev }()
			args := append([]string{"sync"}, tc.args...)
			printed, err := runCLI(t, args...)
			if err != nil {
				t.Fatalf("sync: %v\n%s", err, printed)
			}
			if !fileExists(orphan) {
				t.Error("legacy orphan was deleted")
			}
			if output, err := exec.Command("git", "check-ignore", "--no-index", orphan).CombinedOutput(); err != nil {
				data, _ := os.ReadFile(".gitignore")
				t.Errorf("kept orphan is exposed to git add: %v %s\n%s", err, output, data)
			}
			if tc.name == "text" {
				all := out.String() + printed
				if !strings.Contains(all, "the sync that wrote it recorded no checksum") || strings.Contains(all, "edited since sync") {
					t.Errorf("wrong orphan reason:\n%s", all)
				}
			}
			if gitIgnored(t, dir, unmanaged) {
				t.Error("retention ignored a path handed off through sync.unmanaged")
			}
			state := readStateFile(".")
			if tc.unreconciled {
				if len(state.Orphans) != 0 {
					t.Errorf("partial upgrade classified orphan before full reconciliation: %v", state.Orphans)
				}
			} else if len(state.Orphans) != 1 || state.Orphans[0] != orphan {
				t.Errorf("lost orphan record: %v", state.Orphans)
			}
		})
	}
}

func TestSync_KeptEditedOrphanSaysEdited(t *testing.T) {
	testutil.TempCwd(t)
	mustWriteFile(t, "agnostic-ai.yaml", "version: 1\ntargets: [codex]\n")
	const orphan = ".codex/skills/gone/reference.md"
	mustWriteFile(t, orphan, "edited\n")
	if err := writeStateFile(".", 0, "", "", syncLedger{outputs: []string{orphan}, sums: map[string]string{orphan: adapters.ContentSum("original\n")}}); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	prev := logOut
	logOut = &out
	defer func() { logOut = prev }()
	printed, err := runCLI(t, "sync")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String()+printed, "edited since sync") {
		t.Errorf("edited orphan reason missing: %s%s", out.String(), printed)
	}
}

func TestSync_SweepErrorKeepsUnsweptPathsIgnored(t *testing.T) {
	for _, args := range [][]string{{"sync"}, {"sync", "--json"}} {
		t.Run(strings.Join(args, " "), func(t *testing.T) {
			dir, _ := gitRepo(t)
			testutil.Chdir(t, dir)
			mustWriteFile(t, "agnostic-ai.yaml", "version: 1\ntargets: [codex]\ngitignore:\n  enabled: true\n")
			const blocked = ".legacy-blocked/ref.md"
			const unswept = ".legacy-unswept/ref.md"
			const swept = ".legacy-swept/ref.md"
			mustWriteFile(t, swept, "# Generated by agnostic-ai\nold\n")
			mustWriteFile(t, blocked, "inaccessible\n")
			mustWriteFile(t, unswept, "old\n")
			if err := os.Chmod(blocked, 0); err != nil {
				t.Fatal(err)
			}
			defer func() {
				if err := os.Chmod(blocked, 0o644); err != nil {
					t.Error(err)
				}
			}()
			if _, err := os.ReadFile(blocked); err == nil {
				t.Skip("filesystem permits reading mode-000 file")
			}
			if err := writeStateFile(".", 0, "", "", syncLedger{outputs: []string{swept, blocked, unswept}, orphans: []string{swept, unswept}}); err != nil {
				t.Fatal(err)
			}
			var out bytes.Buffer
			prev := logOut
			logOut = &out
			defer func() { logOut = prev }()
			_, _ = runCLI(t, args...)
			state := readStateFile(".")
			for _, path := range []string{blocked, unswept} {
				if !slices.Contains(state.Outputs, path) {
					t.Errorf("forgot unswept output %s: %v", path, state.Outputs)
				}
				if !gitIgnored(t, dir, path) {
					t.Errorf("exposed unswept path %s", path)
				}
			}
			if !slices.Contains(state.Orphans, unswept) {
				t.Errorf("forgot prior orphan: %v", state.Orphans)
			}
			if slices.Contains(state.Outputs, swept) || slices.Contains(state.Orphans, swept) || gitIgnored(t, dir, swept) {
				t.Errorf("kept removed path in ledger or ignores: %+v", state)
			}
		})
	}
}

func TestSync_PartialRetentionHonorsCommittedKinds(t *testing.T) {
	dir := commitKindsFixture(t, "claude, codex")
	if _, err := runCLI(t, "sync", "--only", "codex"); err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{"CLAUDE.md", ".claude/settings.json"} {
		if gitIgnored(t, dir, path) {
			t.Errorf("partial retention ignored committed output %s", path)
		}
	}
}
