package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

const (
	aiderConf       = ".aider.conf.yml"
	aiderConfig     = "version: 1\ntargets: [aider, cline]\noutputs:\n  aider:\n    conf-file: .aider.conf.yml\n    model: gpt-x\n    weak-model: gpt-mini\n"
	aiderUserConf   = "dark-mode: true\nread: [NOTES.md]\n"
	withoutAiderCfg = "version: 1\ntargets: [cline]\n"
)

func readYAMLMap(t *testing.T, path string) map[string]any {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%s: %v", path, err)
	}
	var got map[string]any
	if err := yaml.Unmarshal(data, &got); err != nil {
		t.Fatalf("%s: %v\n%s", path, err, data)
	}
	return got
}

func assertOnlyUserAiderConf(t *testing.T) {
	t.Helper()
	got := readYAMLMap(t, aiderConf)
	want := map[string]any{"dark-mode": true, "read": []any{"NOTES.md"}}
	if !reflect.DeepEqual(got, want) {
		data, _ := os.ReadFile(aiderConf)
		t.Errorf("%s holds keys other than the user's:\n%s", aiderConf, data)
	}
	if data, _ := os.ReadFile(aiderConf); strings.Contains(string(data), "Generated by agnostic-ai") {
		t.Errorf("%s kept the provenance header:\n%s", aiderConf, data)
	}
}

func syncedAiderConf(t *testing.T, seed string) {
	t.Helper()
	testutil.Chdir(t, t.TempDir())
	mustWriteFile(t, "agnostic-ai.yaml", aiderConfig)
	if seed != "" {
		mustWriteFile(t, aiderConf, seed)
	}
	runSyncOK(t)
	got := readYAMLMap(t, aiderConf)
	if got["model"] != "gpt-x" || got["weak-model"] != "gpt-mini" {
		t.Fatalf("sync did not merge into %s: %#v", aiderConf, got)
	}
}

// Dropping aider, or its conf-file, takes out only what sync merged into
// .aider.conf.yml and keeps the user's keys and read entries (#1550).
func TestSync_DroppingAiderKeepsUserKeysInConfFile(t *testing.T) {
	for _, tc := range []struct{ name, config string }{
		{"target", withoutAiderCfg},
		{"conf-file", "version: 1\ntargets: [aider, cline]\noutputs:\n  aider:\n    model: gpt-x\n"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			syncedAiderConf(t, aiderUserConf)
			mustWriteFile(t, "agnostic-ai.yaml", tc.config)
			runSyncOK(t)
			assertOnlyUserAiderConf(t)
			if _, ok := readStateFile(".").Merged[aiderConf]; ok {
				t.Error("released file still has a merged record")
			}
			runSyncOK(t, "--check")
		})
	}
}

// The conf file does not depend on specs, so removing the last one
// leaves it written, with the user's keys in it.
func TestSync_RemovingLastSpecKeepsAiderConf(t *testing.T) {
	testutil.Chdir(t, t.TempDir())
	mustWriteFile(t, "agnostic-ai.yaml", aiderConfig)
	mustWriteFile(t, aiderConf, aiderUserConf)
	mustWriteFile(t, ".agnostic-ai/rules/style.md", "---\nname: style\n---\nBe terse.\n")
	runSyncOK(t)
	removeSpecs(t, ".agnostic-ai/rules/style.md")
	runSyncOK(t)
	got := readYAMLMap(t, aiderConf)
	if got["dark-mode"] != true || got["model"] != "gpt-x" {
		t.Errorf("%s = %#v", aiderConf, got)
	}
	runSyncOK(t, "--check")
}

// A conf file sync created goes away with the target. A read entry the
// user listed before sync added it stays.
func TestSync_DroppingAiderRemovesConfOnlyWhenSyncCreatedIt(t *testing.T) {
	for _, tc := range []struct {
		name, seed string
		want       map[string]any
	}{
		{"created by sync", "", nil},
		{"user listed the entry", "read: [CONVENTIONS.md]\n", map[string]any{"read": []any{"CONVENTIONS.md"}}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			syncedAiderConf(t, tc.seed)
			mustWriteFile(t, "agnostic-ai.yaml", withoutAiderCfg)
			runSyncOK(t)
			if tc.want == nil {
				if fileExists(aiderConf) {
					data, _ := os.ReadFile(aiderConf)
					t.Errorf("%s stayed:\n%s", aiderConf, data)
				}
				return
			}
			if got := readYAMLMap(t, aiderConf); !reflect.DeepEqual(got, tc.want) {
				t.Errorf("%s = %#v, want %#v", aiderConf, got, tc.want)
			}
		})
	}
}

// The release keeps the order and the comments it finds in the file.
func TestSync_DroppingAiderKeepsCommentsAndOrder(t *testing.T) {
	syncedAiderConf(t, aiderUserConf)
	data, err := os.ReadFile(aiderConf)
	if err != nil {
		t.Fatal(err)
	}
	mustWriteFile(t, aiderConf, string(data)+"# keep me\nzebra: 1 # trailing\nalpha: 2\n")
	mustWriteFile(t, "agnostic-ai.yaml", withoutAiderCfg)
	runSyncOK(t)
	out, err := os.ReadFile(aiderConf)
	if err != nil {
		t.Fatal(err)
	}
	got := string(out)
	for _, want := range []string{"# keep me", "# trailing"} {
		if !strings.Contains(got, want) {
			t.Errorf("lost comment %q:\n%s", want, got)
		}
	}
	if strings.Index(got, "zebra") > strings.Index(got, "alpha") {
		t.Errorf("key order changed:\n%s", got)
	}
	if strings.Contains(got, "model") {
		t.Errorf("sync's keys stayed:\n%s", got)
	}
}

// doctor --fix releases the conf file the same way the sweep does.
func TestDoctorFix_KeepsUserKeysInAiderConf(t *testing.T) {
	syncedAiderConf(t, aiderUserConf)
	mustWriteFile(t, "agnostic-ai.yaml", withoutAiderCfg)
	_, _ = runCLI(t, "doctor", "--fix")
	assertOnlyUserAiderConf(t)
	runSyncOK(t, "--check")
}

// A model the user changed by hand is theirs: the release keeps it and
// reports the file as a kept orphan.
func TestSync_DroppingAiderKeepsEditedModel(t *testing.T) {
	syncedAiderConf(t, aiderUserConf)
	data, err := os.ReadFile(aiderConf)
	if err != nil {
		t.Fatal(err)
	}
	mustWriteFile(t, aiderConf, strings.Replace(string(data), "model: gpt-x", "model: mine", 1))
	mustWriteFile(t, "agnostic-ai.yaml", withoutAiderCfg)
	out := syncOutput(t)
	got := readYAMLMap(t, aiderConf)
	want := map[string]any{"dark-mode": true, "read": []any{"NOTES.md"}, "model": "mine"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("%s = %#v, want %#v", aiderConf, got, want)
	}
	if !strings.Contains(out, "kept orphan "+aiderConf) {
		t.Errorf("kept edit not reported:\n%s", out)
	}
	runSyncOK(t)
	if readYAMLMap(t, aiderConf)["model"] != "mine" {
		t.Error("a later sync removed the edited model")
	}

	cfg, err := config.Load(".")
	if err != nil {
		t.Fatal(err)
	}
	reports := []driftReport{{Target: "agnostic-ai", Orphaned: []string{aiderConf}}}
	if _, err := offerOrphanRemoval(cfg, reports, false, func(string) (bool, error) { return true, nil }); err != nil {
		t.Fatal(err)
	}
	assertOnlyUserAiderConf(t)
}

// A ledger from before sync recorded the conf file's keys cannot tell
// the user's apart, so the sweep keeps the file.
func TestSync_OldLedgerKeepsAiderConf(t *testing.T) {
	for _, version := range []int{5, 6} {
		t.Run(fmt.Sprintf("v%d", version), func(t *testing.T) {
			syncedAiderConf(t, aiderUserConf)
			dropMergedRecords(t)
			setLedgerVersion(t, version)
			mustWriteFile(t, "agnostic-ai.yaml", withoutAiderCfg)
			for range 2 {
				out := syncOutput(t)
				if got := readYAMLMap(t, aiderConf); got["dark-mode"] != true {
					t.Fatalf("user key lost: %#v", got)
				}
				if !strings.Contains(out, "kept orphan "+aiderConf) {
					t.Errorf("kept file not reported:\n%s", out)
				}
			}
		})
	}
}

// A conf file that no longer parses stays as it is and says why.
func TestSync_UnparseableAiderConfSaysWhy(t *testing.T) {
	syncedAiderConf(t, aiderUserConf)
	const broken = "dark-mode: [true\n"
	mustWriteFile(t, aiderConf, broken)
	mustWriteFile(t, "agnostic-ai.yaml", withoutAiderCfg)
	out := syncOutput(t)
	if !strings.Contains(out, "does not parse") {
		t.Errorf("no parse reason:\n%s", out)
	}
	if data, _ := os.ReadFile(aiderConf); string(data) != broken {
		t.Errorf("file changed: %s", data)
	}
}

func setLedgerVersion(t *testing.T, version int) {
	t.Helper()
	raw, err := os.ReadFile(stateFilePath("."))
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	doc["version"] = version
	writeJSONFile(t, stateFilePath("."), doc)
}

// A rules-file change takes the entry sync added for the old path out
// of read:, so dropping aider later leaves no stale entry (#1562). An
// entry the user listed stays.
func TestSync_AiderRulesFileChangeDropsTheOldReadEntry(t *testing.T) {
	const conf = "version: 1\ntargets: [aider, cline]\noutputs:\n  aider:\n    conf-file: .aider.conf.yml\n    rules-file: %s\n"
	for _, tc := range []struct {
		name, seed string
		afterMove  []any
	}{
		{"sync's entry", aiderUserConf, []any{"NOTES.md", "SECOND.md"}},
		{"user's entry", "dark-mode: true\nread: [NOTES.md, FIRST.md]\n", []any{"NOTES.md", "FIRST.md", "SECOND.md"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			testutil.Chdir(t, t.TempDir())
			mustWriteFile(t, aiderConf, tc.seed)
			mustWriteFile(t, ".agnostic-ai/rules/style.md", "---\nname: style\n---\nBe terse.\n")
			mustWriteFile(t, "agnostic-ai.yaml", fmt.Sprintf(conf, "FIRST.md"))
			runSyncOK(t)
			mustWriteFile(t, "agnostic-ai.yaml", fmt.Sprintf(conf, "SECOND.md"))
			runSyncOK(t)
			if got := readYAMLMap(t, aiderConf)["read"]; !reflect.DeepEqual(got, tc.afterMove) {
				t.Errorf("read = %#v, want %#v", got, tc.afterMove)
			}
			runSyncOK(t, "--check")
			mustWriteFile(t, "agnostic-ai.yaml", withoutAiderCfg)
			runSyncOK(t)
			got := readYAMLMap(t, aiderConf)
			want := map[string]any{"dark-mode": true, "read": tc.afterMove[:len(tc.afterMove)-1]}
			if !reflect.DeepEqual(got, want) {
				t.Errorf("%s = %#v, want %#v", aiderConf, got, want)
			}
		})
	}
}
