package integration

import (
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

// TestAmpRoundTrip_SyncImportSyncIsByteEqual is the amp audit's
// byte-stability gate from #325 acceptance criterion C:
//
//	sync amp -> snapshot .agents/skills/* + .amp/settings.json
//	         -> wipe source specs
//	         -> import amp
//	         -> wipe emit
//	         -> sync amp
//	         -> assert byte-for-byte identical
//
// Skills and MCPs are the round-trip surfaces. Agents left it when Amp
// removed custom commands (#727): they now emit no adapter-owned file, so
// the fixture keeps them only to pin that `.agents/commands/` stays empty.
// Rules flow through sync's project-root AGENTS.md entry-point — same
// caveat the codex audit (#329) noted — so they are intentionally
// excluded; the entry-point round-trip needs its own harness.
func TestAmpRoundTrip_SyncImportSyncIsByteEqual(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	seedAmpRoundTripFixture(t, dir)

	runCmd(t, "sync", "-t", "amp")
	first := snapshotAmpEmit(t, dir)
	if len(first) == 0 {
		t.Fatalf("first sync produced no amp output")
	}
	if _, err := os.Stat(filepath.Join(dir, ".agents", "commands")); !os.IsNotExist(err) {
		t.Errorf("sync wrote the retired commands dir Amp told users to delete, err=%v", err)
	}

	for _, sub := range []string{"skills", "mcps"} {
		if err := os.RemoveAll(filepath.Join(dir, ".agnostic-ai", sub)); err != nil {
			t.Fatal(err)
		}
	}

	runCmd(t, "import", "amp")

	// Wipe both adapter-owned trees so the second sync writes from
	// scratch and the comparison reflects emit output, not stale
	// bytes left behind by the first sync.
	for _, sub := range []string{".agents", ".amp"} {
		if err := os.RemoveAll(filepath.Join(dir, sub)); err != nil {
			t.Fatal(err)
		}
	}

	runCmd(t, "sync", "-t", "amp")
	second := snapshotAmpEmit(t, dir)

	firstPaths := sortedKeys(first)
	secondPaths := sortedKeys(second)
	if !equalStringSlice(firstPaths, secondPaths) {
		t.Fatalf("emit path set changed across round-trip\nfirst:  %v\nsecond: %v",
			firstPaths, secondPaths)
	}
	for _, p := range firstPaths {
		if first[p] != second[p] {
			t.Errorf("byte mismatch at %s (first=%d bytes, second=%d bytes)\n%s",
				p, len(first[p]), len(second[p]), unifiedDiffLines(first[p], second[p]))
		}
	}
}

// TestAmpRoundTrip_LegacyBackupSurvivesASecondFullSync is the amp half
// of the third-review regression for #1118 (found against antigravity's
// MigrateLegacyPath, which amp's own AGENT.md -> AGENTS.md migration
// shares via MigrateLegacyFile): the `.bak` this writes must not be
// recorded in the sync ledger as a generated output, or the next full
// sync -- which no longer touches the now-gone AGENT.md -- treats it as
// an orphan and deletes it. Two consecutive full syncs must leave
// AGENT.md.bak byte-identical.
func TestAmpRoundTrip_LegacyBackupSurvivesASecondFullSync(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	must(t, os.WriteFile(filepath.Join(dir, "agnostic-ai.yaml"), []byte(`version: 1
targets:
  - amp
gitignore:
  enabled: false
`), 0o644))
	const legacy = "# AGENT.md\n\nGenerated by agnostic-ai. Do not edit by hand.\n\nstale.\n"
	must(t, os.WriteFile(filepath.Join(dir, "AGENT.md"), []byte(legacy), 0o644))

	runCmd(t, "sync", "-t", "amp")

	bakPath := filepath.Join(dir, "AGENT.md.bak")
	first, err := os.ReadFile(bakPath)
	if err != nil {
		t.Fatalf("missing backup after first sync: %v", err)
	}
	if string(first) != legacy {
		t.Fatalf("backup does not match the original legacy content:\n%s", first)
	}

	runCmd(t, "sync", "-t", "amp")

	second, err := os.ReadFile(bakPath)
	if err != nil {
		t.Fatalf("backup did not survive a second full sync (orphan-swept?): %v", err)
	}
	if string(second) != string(first) {
		t.Errorf("backup changed across a second sync\nfirst:  %q\nsecond: %q", first, second)
	}
}

// TestAmpRoundTrip_LegacyContentSurvivesAnExistingBackup is the amp
// half of the fourth-review regression (found against antigravity's
// MigrateLegacyPath, shared with amp's AGENT.md -> AGENTS.md migration
// via MigrateLegacyFile): a legacy path already recorded in an older,
// already-persisted sync ledger reads as an orphan the moment this
// run's migration no longer declares it a managed output. An
// already-taken `.bak` name used to make migration leave AGENT.md in
// place "to be safe", so the orphan sweep deleted it on the strength
// of its own copied provenance marker. One sync must now end with both
// byte sets on disk.
func TestAmpRoundTrip_LegacyContentSurvivesAnExistingBackup(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	must(t, os.WriteFile(filepath.Join(dir, "agnostic-ai.yaml"), []byte(`version: 1
targets:
  - amp
gitignore:
  enabled: false
`), 0o644))
	must(t, os.MkdirAll(filepath.Join(dir, ".agnostic-ai"), 0o755))
	must(t, os.WriteFile(filepath.Join(dir, ".agnostic-ai", ".sync-state"),
		[]byte(`{"version":3,"synced_at":"2026-01-01T00:00:00Z","outputs":["AGENT.md"]}`), 0o644))
	const older = "Generated by agnostic-ai. Do not edit by hand.\n\nolder backup content.\n"
	must(t, os.WriteFile(filepath.Join(dir, "AGENT.md.bak"), []byte(older), 0o644))
	const current = "Generated by agnostic-ai. Do not edit by hand.\n\ncurrent legacy content, never backed up.\n"
	must(t, os.WriteFile(filepath.Join(dir, "AGENT.md"), []byte(current), 0o644))

	runCmd(t, "sync", "-t", "amp")

	if _, err := os.Stat(filepath.Join(dir, "AGENT.md")); !os.IsNotExist(err) {
		t.Errorf("legacy file should be removed once its bytes are backed up, err=%v", err)
	}
	gotOlder, err := os.ReadFile(filepath.Join(dir, "AGENT.md.bak"))
	if err != nil {
		t.Fatalf("existing backup must survive: %v", err)
	}
	if string(gotOlder) != older {
		t.Errorf("existing backup must not be overwritten\nwant: %q\ngot:  %q", older, gotOlder)
	}
	gotCurrent, err := os.ReadFile(filepath.Join(dir, "AGENT.md.bak.1"))
	if err != nil {
		t.Fatalf("current legacy content must land in a numbered backup: %v", err)
	}
	if string(gotCurrent) != current {
		t.Errorf("numbered backup should carry the legacy file's current bytes\nwant: %q\ngot:  %q", current, gotCurrent)
	}
}

func seedAmpRoundTripFixture(t *testing.T, dir string) {
	t.Helper()
	must(t, os.WriteFile(filepath.Join(dir, "agnostic-ai.yaml"),
		[]byte(`version: 1
sources:
  agents: .agnostic-ai/agents
  skills: .agnostic-ai/skills
  mcps: .agnostic-ai/mcps
targets:
  - amp
gitignore:
  enabled: false
`), 0o644))

	must(t, os.MkdirAll(filepath.Join(dir, ".agnostic-ai/agents"), 0o755))
	for _, n := range []string{"alpha", "beta", "gamma"} {
		must(t, os.WriteFile(filepath.Join(dir, ".agnostic-ai/agents", n+".md"),
			[]byte("---\nname: "+n+"\ndescription: agent "+n+"\n---\n\n"+n+" body\n"), 0o644))
	}

	must(t, os.MkdirAll(filepath.Join(dir, ".agnostic-ai/skills/uno"), 0o755))
	must(t, os.WriteFile(filepath.Join(dir, ".agnostic-ai/skills/uno/SKILL.md"),
		[]byte("---\nname: uno\ndescription: skill uno\n---\n\nuno body\n"), 0o644))
	must(t, os.MkdirAll(filepath.Join(dir, ".agnostic-ai/skills/uno/scripts"), 0o755))
	must(t, os.WriteFile(filepath.Join(dir, ".agnostic-ai/skills/uno/scripts/check.sh"),
		[]byte("#!/bin/sh\nexit 0\n"), 0o755))

	must(t, os.MkdirAll(filepath.Join(dir, ".agnostic-ai/mcps"), 0o755))
	must(t, os.WriteFile(filepath.Join(dir, ".agnostic-ai/mcps/stdio-server.yaml"),
		[]byte("name: stdio-server\ncommand: npx\nargs:\n  - \"-y\"\n  - \"@modelcontextprotocol/server-filesystem\"\n"), 0o644))
	must(t, os.WriteFile(filepath.Join(dir, ".agnostic-ai/mcps/http-server.yaml"),
		[]byte("name: http-server\ntype: http\nurl: https://example.test/mcp\n"), 0o644))
}

// snapshotAmpEmit reads every file the amp adapter actually owns
// (.agents/skills/* + .amp/settings.json). The project-root
// AGENTS.md is excluded because sync writes it centrally, not amp,
// so it is not part of the adapter's round-trip surface.
func snapshotAmpEmit(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	for _, r := range []string{".agents", ".amp"} {
		full := filepath.Join(root, r)
		info, err := os.Stat(full)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			t.Fatalf("stat %s: %v", full, err)
		}
		if !info.IsDir() {
			data, err := os.ReadFile(full)
			if err != nil {
				t.Fatalf("read %s: %v", full, err)
			}
			out[r] = string(data)
			continue
		}
		err = filepath.WalkDir(full, func(path string, d fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if d.IsDir() {
				return nil
			}
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			out[filepath.ToSlash(rel)] = string(data)
			return nil
		})
		if err != nil {
			t.Fatalf("walk %s: %v", full, err)
		}
	}
	return out
}
