package cursor

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters/header"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

// Command specs emit as Cursor Custom Commands when commands-dir is set,
// the same opt-in surface agents use.
func TestEmit_WritesCommandFileWhenCommandsDirSet(t *testing.T) {
	dir := testutil.TempCwd(t)
	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"cursor": {CommandsDir: ".cursor/commands"},
		},
	}
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindCommand, Name: "deploy", Path: "commands/deploy.md", Meta: map[string]any{"description": "Ship it"}, Body: "Run the deploy steps."},
	})
	if err := New().Emit(b, cfg, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(dir, ".cursor", "commands", "deploy.md"))
	if err != nil {
		t.Fatalf("read command file: %v", err)
	}
	got := string(data)
	for _, want := range []string{"description: Ship it", "Run the deploy steps.", "Generated by agnostic-ai"} {
		if !strings.Contains(got, want) {
			t.Errorf("command file missing %q:\n%s", want, got)
		}
	}
}

// Commands emit to Cursor's standard `.cursor/commands/` location by
// default; no opt-in is needed anymore.
func TestEmit_CommandEmitsToDefaultCommandsDir(t *testing.T) {
	dir := testutil.TempCwd(t)
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindCommand, Name: "deploy", Path: "commands/deploy.md", Body: "Run the deploy steps."},
	})
	if err := New().Emit(b, &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".cursor", "commands", "deploy.md")); err != nil {
		t.Errorf("expected command at default .cursor/commands: %v", err)
	}
}

// Hook specs emit Cursor's native .cursor/hooks.json: a numeric version
// and a hooks map keyed by the verbatim event name, each entry carrying
// the command and optional matcher (#438).
func TestEmit_WritesCursorHooksJSON(t *testing.T) {
	dir := testutil.TempCwd(t)
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindHook, Name: "audit-shell", Meta: map[string]any{"event": "beforeShellExecution", "matcher": "rm|dd", "command": "echo audit"}},
		{Kind: spec.KindHook, Name: "fmt-edit", Meta: map[string]any{"event": "afterFileEdit", "command": "echo fmt"}},
	})
	if err := New().Emit(b, &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(dir, ".cursor", "hooks.json"))
	if err != nil {
		t.Fatalf("read hooks file: %v", err)
	}
	var doc struct {
		Version int                         `json:"version"`
		Hooks   map[string][]map[string]any `json:"hooks"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatalf("parse hooks.json: %v\n%s", err, data)
	}
	if doc.Version != 1 {
		t.Errorf("version = %d, want 1", doc.Version)
	}
	shell := doc.Hooks["beforeShellExecution"]
	if len(shell) != 1 || shell[0]["command"] != "echo audit" || shell[0]["matcher"] != "rm|dd" {
		t.Errorf("beforeShellExecution = %#v, want one {command: echo audit, matcher: rm|dd}", shell)
	}
	edit := doc.Hooks["afterFileEdit"]
	if len(edit) != 1 || edit[0]["command"] != "echo fmt" {
		t.Errorf("afterFileEdit = %#v, want one {command: echo fmt}", edit)
	}
	if _, ok := edit[0]["matcher"]; ok {
		t.Errorf("afterFileEdit entry should omit matcher, got %#v", edit[0])
	}
}

// No hook specs means no .cursor/hooks.json is written (no surprise file).
func TestEmit_NoHooksFileWithoutHookSpecs(t *testing.T) {
	dir := testutil.TempCwd(t)
	if err := New().Emit(spec.NewBundle(nil), &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".cursor", "hooks.json")); !os.IsNotExist(err) {
		t.Errorf("expected no hooks.json, stat err = %v", err)
	}
}

// Review specs emit one scope-located BUGBOT.md: unscoped at the repo root,
// scoped under its directory, with same-scope specs concatenated (#433).
func TestEmit_ReviewWritesBugbotPerScope(t *testing.T) {
	cwd := t.TempDir()
	testutil.Chdir(t, cwd)
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindReview, Name: "root", Path: "reviews/root.md", Body: "root rule one"},
		{Kind: spec.KindReview, Name: "root2", Path: "reviews/root2.md", Body: "root rule two"},
		{Kind: spec.KindReview, Name: "be", Path: "reviews/backend/be.md", Scope: "backend", Body: "backend rule"},
	})
	if err := New().Emit(b, &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}

	root, err := os.ReadFile(filepath.Join(cwd, "BUGBOT.md"))
	if err != nil {
		t.Fatalf("read root BUGBOT.md: %v", err)
	}
	if !strings.Contains(string(root), "root rule one") || !strings.Contains(string(root), "root rule two") {
		t.Errorf("root BUGBOT.md missing concatenated specs:\n%s", root)
	}
	be, err := os.ReadFile(filepath.Join(cwd, "backend", "BUGBOT.md"))
	if err != nil {
		t.Fatalf("read backend BUGBOT.md: %v", err)
	}
	if !strings.Contains(string(be), "backend rule") {
		t.Errorf("backend BUGBOT.md wrong content:\n%s", be)
	}
	if strings.Contains(string(be), "root rule") {
		t.Errorf("scoped review leaked root content:\n%s", be)
	}
}

// The review output basename is overridable via outputs.cursor.review-file.
func TestEmit_ReviewFileOverride(t *testing.T) {
	cwd := t.TempDir()
	testutil.Chdir(t, cwd)
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindReview, Name: "root", Path: "reviews/root.md", Body: "guidance"},
	})
	cfg := &config.Config{Outputs: map[string]config.Output{"cursor": {ReviewFile: "REVIEW.md"}}}
	if err := New().Emit(b, cfg, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(cwd, "REVIEW.md"))
	if err != nil {
		t.Fatalf("expected REVIEW.md override: %v", err)
	}
	if !strings.Contains(string(got), "guidance") {
		t.Errorf("override file missing body: %s", got)
	}
	if !header.Has(string(got)) {
		t.Errorf("override file missing provenance header: %s", got)
	}
}

// A frontmatter scope that escapes the repo root must not write a file
// outside the project tree (#433 review).
func TestEmit_ReviewScopeEscapeIsBlocked(t *testing.T) {
	cwd := t.TempDir()
	testutil.Chdir(t, cwd)
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindReview, Name: "evil", Path: "reviews/evil.md", Meta: map[string]any{"scope": "../escape"}, Body: "x"},
	})
	if err := New().Emit(b, &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	if _, err := os.Stat(filepath.Join(filepath.Dir(cwd), "escape", "BUGBOT.md")); err == nil {
		t.Errorf("escaping scope wrote BUGBOT.md outside the repo root")
	}
}

// Environment specs pass through to .cursor/environment.json, merging
// top-level keys and stripping agnostic routing fields (#434).
func TestEmit_EnvironmentWritesCursorJSON(t *testing.T) {
	cwd := t.TempDir()
	testutil.Chdir(t, cwd)
	b := spec.NewBundle([]spec.Entry{
		{
			Kind: spec.KindEnvironment, Name: "default", Path: "environments/default.yaml",
			Meta: map[string]any{"name": "default", "scope": "ignored", "install": "go mod download"},
		},
		{
			Kind: spec.KindEnvironment, Name: "extra", Path: "environments/extra.yaml",
			Meta: map[string]any{"terminals": []any{map[string]any{"name": "dev", "command": "make run"}}},
		},
	})
	if err := New().Emit(b, &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(cwd, ".cursor", "environment.json"))
	if err != nil {
		t.Fatalf("read environment.json: %v", err)
	}
	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse: %v", err)
	}
	if doc["install"] != "go mod download" {
		t.Errorf("install passthrough wrong: %v", doc["install"])
	}
	if _, ok := doc["terminals"]; !ok {
		t.Errorf("second spec did not merge: %s", raw)
	}
	if _, leaked := doc["name"]; leaked {
		t.Errorf("routing key name leaked into environment.json: %s", raw)
	}
	if _, leaked := doc["scope"]; leaked {
		t.Errorf("routing key scope leaked into environment.json: %s", raw)
	}
}

// A later environment spec overrides an earlier one on a key collision,
// and the x-cursor namespace resolves (override wins, other targets drop).
func TestEmit_EnvironmentMergeLastWinsAndResolvesMeta(t *testing.T) {
	cwd := t.TempDir()
	testutil.Chdir(t, cwd)
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindEnvironment, Name: "a", Path: "environments/a.yaml", Meta: map[string]any{"install": "first"}},
		{
			Kind: spec.KindEnvironment, Name: "b", Path: "environments/b.yaml",
			Meta: map[string]any{
				"install":  "second",
				"x-cursor": map[string]any{"start": "make run"},
				"x-codex":  map[string]any{"setup": "pip install"},
			},
		},
	})
	if err := New().Emit(b, &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	doc := map[string]any{}
	raw, _ := os.ReadFile(filepath.Join(cwd, ".cursor", "environment.json"))
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse: %v", err)
	}
	if doc["install"] != "second" {
		t.Errorf("last-wins violated: install = %v, want second", doc["install"])
	}
	if doc["start"] != "make run" {
		t.Errorf("x-cursor override did not resolve: %s", raw)
	}
	if _, leaked := doc["x-cursor"]; leaked {
		t.Errorf("x-cursor namespace leaked: %s", raw)
	}
	if _, leaked := doc["x-codex"]; leaked {
		t.Errorf("x-codex namespace leaked into cursor output: %s", raw)
	}
	if _, leaked := doc["setup"]; leaked {
		t.Errorf("other target's key leaked: %s", raw)
	}
}

// The environment output path is overridable via outputs.cursor.environment-file.
func TestEmit_EnvironmentFileOverride(t *testing.T) {
	cwd := t.TempDir()
	testutil.Chdir(t, cwd)
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindEnvironment, Name: "default", Path: "environments/default.yaml", Meta: map[string]any{"install": "x"}},
	})
	cfg := &config.Config{Outputs: map[string]config.Output{"cursor": {EnvironmentFile: ".cursor/env.custom.json"}}}
	if err := New().Emit(b, cfg, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	if _, err := os.ReadFile(filepath.Join(cwd, ".cursor", "env.custom.json")); err != nil {
		t.Errorf("expected env.custom.json override: %v", err)
	}
}

// Ignore specs fan out to .cursorignore (gitignore syntax), concatenating
// multiple specs, overridable via outputs.cursor.ignore-file (#435).
func TestEmit_IgnoreWritesCursorignore(t *testing.T) {
	cwd := t.TempDir()
	testutil.Chdir(t, cwd)
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindIgnore, Name: "secrets", Path: "ignore/secrets.md", Body: "*.env"},
		{Kind: spec.KindIgnore, Name: "build", Path: "ignore/build.md", Body: "dist/"},
	})
	if err := New().Emit(b, &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(cwd, ".cursorignore"))
	if err != nil {
		t.Fatalf("read .cursorignore: %v", err)
	}
	if !strings.Contains(string(got), "*.env") || !strings.Contains(string(got), "dist/") {
		t.Errorf(".cursorignore missing concatenated patterns:\n%s", got)
	}
	if !header.Has(string(got)) {
		t.Errorf(".cursorignore missing provenance header:\n%s", got)
	}
}

// The ignore output path is overridable via outputs.cursor.ignore-file.
func TestEmit_IgnoreFileOverride(t *testing.T) {
	cwd := t.TempDir()
	testutil.Chdir(t, cwd)
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindIgnore, Name: "secrets", Path: "ignore/secrets.md", Body: "*.env"},
	})
	cfg := &config.Config{Outputs: map[string]config.Output{"cursor": {IgnoreFile: ".aiignore"}}}
	if err := New().Emit(b, cfg, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(cwd, ".aiignore"))
	if err != nil {
		t.Fatalf("expected .aiignore override: %v", err)
	}
	if !strings.Contains(string(got), "*.env") || !header.Has(string(got)) {
		t.Errorf("override file missing pattern or header:\n%s", got)
	}
}

// Cursor has no settings surface, so a settings spec is unsupported and
// reported (errors under on-unsupported: error). Confirms the settings
// kind flows through the generic capability path (#432).
func TestEmit_SettingsKindUnsupported(t *testing.T) {
	testutil.Chdir(t, t.TempDir())
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindSettings, Name: "defaults", Meta: map[string]any{"model": "x"}},
	})
	err := New().Emit(b, &config.Config{OnUnsupported: "error"}, false)
	if err == nil || !strings.Contains(err.Error(), "settings") {
		t.Fatalf("expected unsupported-settings error, got %v", err)
	}
}

func TestEmit_WritesMdcRule(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	a := New()
	entries := []spec.Entry{
		{
			Kind: spec.KindRule,
			Name: "my-rule",
			Meta: map[string]any{"description": "desc", "globs": "**/*.go"},
			Body: "rule body",
		},
	}
	if err := a.Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".cursor/rules/my-rule.mdc"))
	if err != nil {
		t.Fatal(err)
	}
	// `**/*.go` needs quoting (leading `*`), so YAML uses a single-quoted
	// scalar — not the gratuitous double-quoting the emitter used before.
	if !strings.Contains(string(got), `globs: '**/*.go'`) {
		t.Errorf("missing globs: %s", got)
	}
	if !strings.Contains(string(got), "alwaysApply: true") {
		t.Errorf("rule should default alwaysApply=true: %s", got)
	}
}

// A hand-authored rule with empty globs and alwaysApply:true must
// round-trip without the emitter synthesizing `globs: "**/*"`, re-quoting
// scalar globs, or leaving a trailing space on an empty description (#443).
func TestEmit_MdcRuleFrontmatterByteStable(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		// Empty description + empty globs + alwaysApply:true.
		{Kind: spec.KindRule, Name: "always", Meta: map[string]any{"alwaysApply": true}, Body: "body"},
		// Scalar globs that does not need quoting must stay unquoted.
		{Kind: spec.KindRule, Name: "scoped", Meta: map[string]any{"globs": "apps/foo/**", "alwaysApply": false}, Body: "body"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}

	always, err := os.ReadFile(filepath.Join(dir, ".cursor/rules/always.mdc"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(always), "globs:") {
		t.Errorf("alwaysApply:true rule should omit synthesized globs:\n%s", always)
	}
	if strings.Contains(string(always), "description: \n") {
		t.Errorf("empty description should not carry a trailing space:\n%s", always)
	}
	if !strings.Contains(string(always), "description:\n") {
		t.Errorf("expected bare `description:` key:\n%s", always)
	}

	scoped, err := os.ReadFile(filepath.Join(dir, ".cursor/rules/scoped.mdc"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(scoped), "globs: apps/foo/**\n") {
		t.Errorf("scalar globs should stay unquoted:\n%s", scoped)
	}
}

func TestEmit_AgentDefaultsAlwaysApplyFalse(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindAgent, Name: "agent1", Meta: map[string]any{}, Body: "x"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".cursor/rules/agent1.mdc"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "alwaysApply: false") {
		t.Errorf("agent should default alwaysApply=false: %s", got)
	}
}

func TestEmit_NestedScopeRoutesUnderSubdir(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "auth", Scope: "backend", Body: "rule"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".cursor/rules/backend/auth.mdc")); err != nil {
		t.Errorf("expected nested file under .cursor/rules/backend: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "backend/.cursor/rules/auth.mdc")); !os.IsNotExist(err) {
		t.Errorf("expected no stray scope dir at repo root, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".cursor/rules/auth.mdc")); !os.IsNotExist(err) {
		t.Errorf("expected no root file when scope set, err=%v", err)
	}
}

func TestEmit_WritesMCPFile(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "fs",
			Meta: map[string]any{
				"command": "npx",
				"args":    []any{"-y"},
			},
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".cursor/mcp.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), `"mcpServers"`) {
		t.Errorf("expected mcpServers key: %s", got)
	}
}

// Skills emit natively under `.cursor/skills/<name>/SKILL.md` (Cursor
// 2.4+ discovers the Agent Skills layout); no flattened skill-*.mdc
// copy is written, which would double-expose the skill.
func TestEmit_SkillWritesNativeSkillFolder(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindSkill, Name: "sk1", Meta: map[string]any{"description": "skill desc"}, Body: "skill body"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".cursor/skills/sk1/SKILL.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"name: sk1", "description: skill desc", "skill body"} {
		if !strings.Contains(string(got), want) {
			t.Errorf("missing %q in SKILL.md:\n%s", want, got)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, ".cursor/rules/skill-sk1.mdc")); !os.IsNotExist(err) {
		t.Errorf("flattened skill .mdc must not emit anymore, stat err=%v", err)
	}
}

// The documented optional skill frontmatter fields pass through, and a
// skills-dir override relocates the tree.
func TestEmit_SkillHonorsOptionalFieldsAndDirOverride(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	cfg := &config.Config{
		Outputs: map[string]config.Output{target: {SkillsDir: "vendor/skills"}},
	}
	entries := []spec.Entry{
		{Kind: spec.KindSkill, Name: "sk1", Meta: map[string]any{
			"description":              "d",
			"paths":                    []string{"src/**"},
			"disable-model-invocation": true,
		}, Body: "b"},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, "vendor/skills/sk1/SKILL.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"paths:", "src/**", "disable-model-invocation: true"} {
		if !strings.Contains(string(got), want) {
			t.Errorf("missing %q in SKILL.md:\n%s", want, got)
		}
	}
}

func TestEmit_CommandsDirEmitsAgentAsCommand(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			target: {CommandsDir: ".cursor/commands"},
		},
	}
	entries := []spec.Entry{
		{Kind: spec.KindAgent, Name: "code-reviewer", Meta: map[string]any{
			"description": "reviews code",
			"model":       "sonnet-4-6",
		}, Body: "Body of the prompt.\n"},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	commandPath := filepath.Join(dir, ".cursor/commands/code-reviewer.md")
	got, err := os.ReadFile(commandPath)
	if err != nil {
		t.Fatalf("expected command file at %s: %v", commandPath, err)
	}
	if !strings.Contains(string(got), "description: reviews code") {
		t.Errorf("missing description in command: %s", got)
	}
	if !strings.Contains(string(got), "model: sonnet-4-6") {
		t.Errorf("missing model in command: %s", got)
	}
	if !strings.Contains(string(got), "Body of the prompt.") {
		t.Errorf("missing body in command: %s", got)
	}
	// Rule-form emission must still happen (back-compat).
	if _, err := os.Stat(filepath.Join(dir, ".cursor/rules/code-reviewer.mdc")); err != nil {
		t.Errorf("rule-form emission must remain when commands-dir is set: %v", err)
	}
}

func TestEmit_RulesCarryProvenanceHeader(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Meta: map[string]any{"description": "d"}, Body: "body"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, ".cursor/rules/r1.mdc"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "Generated by agnostic-ai") {
		t.Errorf("cursor rule missing provenance header:\n%s", got)
	}
	// Frontmatter must still parse cleanly: the header must live below
	// the closing `---` delimiter.
	idxFM := strings.Index(string(got), "---\n")
	idxClose := strings.Index(string(got), "\n---\n")
	idxHeader := strings.Index(string(got), "<!-- Generated")
	if idxFM != 0 || idxHeader < idxClose {
		t.Errorf("header must follow frontmatter close:\n%s", got)
	}
}

// Agents emit as Custom Commands at the default commands dir so they
// stay invocable by name without extra configuration.
func TestEmit_AgentEmitsAsCommandByDefault(t *testing.T) {
	dir := t.TempDir()
	testutil.Chdir(t, dir)

	entries := []spec.Entry{
		{Kind: spec.KindAgent, Name: "agent1", Meta: map[string]any{}, Body: "x"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".cursor/commands/agent1.md")); err != nil {
		t.Errorf("expected agent command at default .cursor/commands: %v", err)
	}
}
