package cursor

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

func TestEmit_PortableBeforeToolHookRunsThroughTheWrapper(t *testing.T) {
	emitTargetHooks(t, &config.Config{}, spec.Entry{Kind: spec.KindHook, Name: "guard", Meta: map[string]any{
		"on": "before-tool", "match": "shell", "command": "./guard.sh", "args": []any{"--deny", "push --force"},
	}})
	assertContainsAll(t, readTargetFile(t, ".cursor/hooks.json"),
		`"preToolUse": [`,
		`"command": ".cursor/hooks/agnostic-ai-portable-hook.sh './guard.sh '\\''--deny'\\'' '\\''push --force'\\'''"`,
		`"matcher": "^Shell$"`,
	)
	info, err := os.Stat(decisionWrapperPath)
	if err != nil || info.Mode().Perm()&0o111 == 0 {
		t.Fatalf("wrapper = %v, %v; want an executable file", info, err)
	}
	if body := readTargetFile(t, decisionWrapperPath); !strings.HasPrefix(body, "#!/usr/bin/env bash\n# Generated by agnostic-ai.") {
		t.Errorf("wrapper must start with its shebang and the provenance header:\n%s", body)
	}
}

func TestEmit_NativeHookSyncsAsWrittenWithNoWrapper(t *testing.T) {
	emitTargetHooks(t, &config.Config{}, spec.Entry{Kind: spec.KindHook, Name: "guard", Meta: map[string]any{
		"event": "preToolUse", "matcher": "^Shell$", "command": "./guard.sh",
	}})
	if got := readTargetFile(t, ".cursor/hooks.json"); !strings.Contains(got, `"command": "./guard.sh"`) || strings.Contains(got, emit.DecisionWrapperName) {
		t.Errorf("native hook must keep its command:\n%s", got)
	}
	if _, err := os.Stat(decisionWrapperPath); !os.IsNotExist(err) {
		t.Errorf("no portable hook, so no wrapper: %v", err)
	}
}

// The wrapper gives the permission reply Cursor reads for each exit code
// a portable hook uses, and hands the payload to the command.
func TestDecisionWrapper_RepliesAsACursorPermissionHook(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("runs the wrapper with bash")
	}
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash is not on PATH")
	}
	wrapper := filepath.Join(t.TempDir(), emit.DecisionWrapperName)
	if err := os.WriteFile(wrapper, []byte(emit.DecisionWrapper(decisionReply)), 0o755); err != nil {
		t.Fatal(err)
	}
	run := func(command string) (string, string, int) {
		t.Helper()
		cmd := exec.Command(wrapper, command)
		cmd.Stdin = strings.NewReader(`{"tool_name":"Shell","tool_input":{"command":"git push --force"}}`)
		var stderr strings.Builder
		cmd.Stderr = &stderr
		out, err := cmd.Output()
		code := 0
		if exit, ok := err.(*exec.ExitError); ok {
			code = exit.ExitCode()
		} else if err != nil {
			t.Fatal(err)
		}
		return string(out), stderr.String(), code
	}

	out, stderr, code := run(`if grep -q "push --force"; then printf 'no "force"\n\tpush\n' >&2; exit 2; fi`)
	var reply map[string]string
	if err := json.Unmarshal([]byte(out), &reply); err != nil || code != 0 || reply["permission"] != "deny" ||
		reply["agent_message"] != "no \"force\"\n\tpush" || reply["user_message"] != reply["agent_message"] {
		t.Errorf("exit 2 = %d %q (%v)", code, out, err)
	}
	if stderr != "no \"force\"\n\tpush\n" {
		t.Errorf("stderr must pass through, got %q", stderr)
	}
	if out, _, code = run("exit 2"); code != 0 || !strings.Contains(out, `"agent_message":"blocked by a hook that exited 2"`) {
		t.Errorf("exit 2 without stderr = %d %q", code, out)
	}
	if out, _, code = run("cat >/dev/null"); code != 0 || out != "{\"permission\":\"allow\"}\n" {
		t.Errorf("exit 0 = %d %q", code, out)
	}
	if out, _, code = run("echo checked"); code != 0 || out != "{\"permission\":\"allow\"}\n" {
		t.Errorf("exit 0 with plain stdout = %d %q; Claude Code allows it", code, out)
	}
	if out, _, code = run(`echo '  {"permission":"deny","agent_message":"own reply"}'`); code != 0 || !strings.Contains(out, `"own reply"`) {
		t.Errorf("a JSON reply the command prints must pass = %d %q", code, out)
	}
	if out, _, code = run("echo partial; exit 1"); code != 1 || out != "" {
		t.Errorf("exit 1 = %d %q; Cursor fails open on it, as Claude Code reports an error", code, out)
	}
}
