// Package zed emits a `.rules` file plus `.zed/settings.json` for the
// Zed editor's assistant.
//
// Zed reads a project-root `.rules` file as additional system context
// for the inline assistant. MCP servers are configured in
// `.zed/settings.json` under the `context_servers` key (note: not
// `mcpServers`), with a nested `{path, args, env}` command shape. Zed
// only supports stdio transport natively; HTTP / SSE entries need a
// local `mcp-remote` bridge and are routed through it automatically.
package zed

import (
	"fmt"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

const (
	target         = "zed"
	defaultOutFile = ".rules"
	defaultMCPFile = ".zed/settings.json"
	zedMCPKey      = "context_servers"
)

var caps = emit.Capabilities{
	Target:   target,
	Supports: []spec.Kind{spec.KindAgent, spec.KindSkill, spec.KindRule, spec.KindMCP},
}

// Adapter emits Zed configs.
type Adapter struct{}

// New returns a Zed adapter.
func New() *Adapter { return &Adapter{} }

// Name returns the target identifier.
func (Adapter) Name() string { return target }

// Emit writes `.rules` (merged document) and, when MCP entries exist,
// `.zed/settings.json` with the `context_servers` map.
func (Adapter) Emit(b spec.Bundle, cfg *config.Config, dryRun bool) error {
	if err := emit.ReportUnsupported(caps, b, cfg.OnUnsupported); err != nil {
		return err
	}
	if err := emit.MergedDocument(b, emit.MergedOpts{
		OutFile:            emit.OutputFile(cfg, target, defaultOutFile),
		Title:              "Project rules",
		Intro:              "Generated by agnostic-ai. Do not edit by hand.",
		AgentSectionPrefix: "Agent: ",
	}, dryRun); err != nil {
		return err
	}
	return emitContextServers(b.MCPs, emit.OutputMCPFile(cfg, target, defaultMCPFile), dryRun)
}

// emitContextServers writes (or merges into) .zed/settings.json with
// the `context_servers` map. Routes through emit.MergeJSONFile so any
// pre-existing user-managed Zed settings survive the sync; only
// `context_servers` is overwritten.
func emitContextServers(mcps []spec.Entry, path string, dryRun bool) error {
	servers := buildContextServers(mcps)
	if len(servers) == 0 {
		return nil
	}
	return emit.MergeJSONFile(path, map[string]any{zedMCPKey: servers}, dryRun)
}

func buildContextServers(mcps []spec.Entry) map[string]any {
	out := map[string]any{}
	for _, e := range mcps {
		if e.Name == "" {
			continue
		}
		entry := buildContextServer(e)
		if entry == nil {
			continue
		}
		out[e.Name] = entry
	}
	return out
}

// buildContextServer renders one Zed context_server entry. Stdio specs
// produce a nested `command: {path, args, env}` block. HTTP / SSE specs
// fall back to launching the upstream MCP through the `mcp-remote`
// npx shim since Zed has no native HTTP MCP transport.
func buildContextServer(e spec.Entry) map[string]any {
	transport, _ := e.Meta["type"].(string)
	if transport == "" {
		transport = "stdio"
	}
	cmd := map[string]any{}

	switch transport {
	case "stdio":
		path, _ := e.Meta["command"].(string)
		if path == "" {
			return nil
		}
		cmd["path"] = path
		if args := emit.StringSlice(e.Meta["args"]); len(args) > 0 {
			cmd["args"] = args
		}
		if env := emit.StringMap(e.Meta["env"]); len(env) > 0 {
			cmd["env"] = env
		} else {
			cmd["env"] = map[string]string{}
		}
	case "http", "sse":
		url, _ := e.Meta["url"].(string)
		if url == "" {
			return nil
		}
		_, _ = fmt.Fprintf(emit.Warner,
			"zed: routing %q through `npx mcp-remote` shim (Zed has no native HTTP MCP transport)\n",
			e.Name)
		cmd["path"] = "npx"
		cmd["args"] = []string{"-y", "mcp-remote", url}
		if env := emit.StringMap(e.Meta["env"]); len(env) > 0 {
			cmd["env"] = env
		} else {
			cmd["env"] = map[string]string{}
		}
	default:
		return nil
	}

	return map[string]any{
		"command":  cmd,
		"settings": map[string]any{},
	}
}
