// Package zed emits a `.rules` file for the Zed editor's assistant.
//
// Zed reads a project-root `.rules` file as additional system context
// for the inline assistant. It is plain Markdown without frontmatter.
package zed

import (
	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

const (
	target         = "zed"
	defaultOutFile = ".rules"
)

var caps = emit.Capabilities{
	Target:   target,
	Supports: []spec.Kind{spec.KindAgent, spec.KindSkill, spec.KindRule},
}

// Adapter emits Zed configs.
type Adapter struct{}

// New returns a Zed adapter.
func New() *Adapter { return &Adapter{} }

// Name returns the target identifier.
func (Adapter) Name() string { return target }

// Emit writes .rules.
func (Adapter) Emit(b spec.Bundle, cfg *config.Config, dryRun bool) error {
	if err := emit.ReportUnsupported(caps, b, cfg.OnUnsupported); err != nil {
		return err
	}
	return emit.MergedDocument(b, emit.MergedOpts{
		OutFile:            outFile(cfg),
		Title:              "Project rules",
		Intro:              "Generated by agnostic-ai. Do not edit by hand.",
		AgentSectionPrefix: "Agent: ",
	}, dryRun)
}

func outFile(cfg *config.Config) string {
	if o, ok := cfg.Outputs[target]; ok && o.File != "" {
		return o.File
	}
	return defaultOutFile
}
