// Package antigravity emits configs for Google Antigravity IDE.
//
// Antigravity reads project instructions from a top-level AGENTS.md and
// per-rule files under .agent/rules/*.md. This adapter routes rules and
// agents into those locations.
//
// To avoid colliding with Codex / Amp / Warp (which also default to a
// root AGENTS.md), the default file is ".agent/AGENTS.md". Override via
// outputs.antigravity.file if your project uses only one AGENTS.md owner.
//
// MCP support is omitted in this first cut: Antigravity's MCP surface
// was not confirmed in the public preview docs. Add it here once the
// upstream spec is stable.
package antigravity

import (
	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

const (
	target          = "antigravity"
	defaultOutFile  = ".agent/AGENTS.md"
	defaultRulesDir = ".agent/rules"
)

var caps = emit.Capabilities{
	Target:   target,
	Supports: []spec.Kind{spec.KindAgent, spec.KindRule},
}

// Adapter emits Antigravity configs.
type Adapter struct{}

// New returns an Antigravity adapter.
func New() *Adapter { return &Adapter{} }

// Name returns the target identifier.
func (Adapter) Name() string { return target }

// Emit writes per-rule files under .agent/rules/ and a merged AGENTS.md
// at .agent/AGENTS.md (or the configured override path).
func (Adapter) Emit(b spec.Bundle, cfg *config.Config, dryRun bool) error {
	if err := emit.ReportUnsupported(caps, b, cfg.OnUnsupported); err != nil {
		return err
	}
	if err := emit.RulesDirectory(b, emit.RulesDirOpts{
		Dir:         emit.OutputRulesDir(cfg, target, defaultRulesDir),
		AgentPrefix: "agent-",
	}, dryRun); err != nil {
		return err
	}
	return emit.MergedDocument(b, emit.MergedOpts{
		OutFile: emit.OutputFile(cfg, target, defaultOutFile),
		Title:   "AGENTS.md",
		Intro:   "Generated by agnostic-ai.",
	}, dryRun)
}
