package antigravity

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestName(t *testing.T) {
	if got := New().Name(); got != "antigravity" {
		t.Errorf("Name() = %q, want %q", got, "antigravity")
	}
}

func TestEmit_WritesRulesDir(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "commits", Body: "Use conventional commits."},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}

	got := readFile(t, filepath.Join(dir, ".agent/rules/commits.md"))
	if !strings.Contains(got, "Use conventional commits.") {
		t.Errorf("missing rule body in %s", got)
	}
}

func TestEmit_WritesMergedAGENTSMd(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "security", Path: "rules/security.md", Body: "Never expose secrets."},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}

	got := readFile(t, filepath.Join(dir, ".agent/AGENTS.md"))
	for _, want := range []string{
		"# AGENTS.md",
		"Generated by agnostic-ai",
		"Never expose secrets.",
		"<!-- source: rules/security.md -->",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

func TestEmit_AgentAppearsInRulesDirAndAGENTSMd(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent,
			Name: "deployer",
			Meta: map[string]any{"description": "Run deployments."},
			Body: "Deploy to production.",
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}

	// Rule-form file.
	ruleFile := filepath.Join(dir, ".agent/rules/agent-deployer.md")
	if _, err := os.Stat(ruleFile); err != nil {
		t.Errorf("expected agent rule file at %s: %v", ruleFile, err)
	}

	// Merged AGENTS.md should list the agent.
	got := readFile(t, filepath.Join(dir, ".agent/AGENTS.md"))
	for _, want := range []string{"## Agents", "deployer", "Deploy to production."} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

func TestEmit_EmptyBundle_WritesNothing(t *testing.T) {
	dir := testutil.TempCwd(t)

	if err := New().Emit(spec.NewBundle(nil), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".agent")); !os.IsNotExist(err) {
		t.Errorf("expected no .agent/ dir for empty bundle, err=%v", err)
	}
}

func TestEmit_FileOverride_WritesAGENTSMdToCustomPath(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"antigravity": {File: "docs/AGENTS.md"},
		},
	}
	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "body"},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "docs/AGENTS.md")); err != nil {
		t.Errorf("expected docs/AGENTS.md: %v", err)
	}
}

func TestEmit_RulesDirOverride_WritesRulesToCustomDir(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"antigravity": {RulesDir: "custom/rules"},
		},
	}
	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "body"},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "custom/rules/r1.md")); err != nil {
		t.Errorf("expected custom/rules/r1.md: %v", err)
	}
}

func TestEmit_SkillUnsupported_WarnsAndContinues(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindSkill, Name: "sk1", Body: "skill body"},
		{Kind: spec.KindRule, Name: "r1", Body: "rule body"},
	}
	cfg := &config.Config{OnUnsupported: "warn"}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	// Rule still emitted even when skill is unsupported.
	if _, err := os.Stat(filepath.Join(dir, ".agent/rules/r1.md")); err != nil {
		t.Errorf("expected r1.md despite unsupported skill: %v", err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}
