package emit

import (
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/config"
)

func TestWithHeader_RespectsProvenanceToggle(t *testing.T) {
	const body = "---\nname: x\n---\nbody\n"

	prev := SetProvenanceEnabled(true)
	t.Cleanup(func() { SetProvenanceEnabled(prev) })

	on := WithHeader(body, FormatMarkdown)
	if !strings.Contains(on, "Generated by agnostic-ai") {
		t.Errorf("expected header when toggle on:\n%s", on)
	}

	SetProvenanceEnabled(false)
	off := WithHeader(body, FormatMarkdown)
	if strings.Contains(off, "Generated by agnostic-ai") {
		t.Errorf("expected no header when toggle off:\n%s", off)
	}
	if off != body {
		t.Errorf("WithHeader(off) should return content unchanged, got %q want %q", off, body)
	}
}

// ProvenanceFor installs the per-target flag and the returned cleanup
// restores the previous value, so concurrent adapter Emit calls do not
// leak a previously-disabled state across runs.
func TestProvenanceFor_RestoresPreviousValue(t *testing.T) {
	prev := SetProvenanceEnabled(true)
	t.Cleanup(func() { SetProvenanceEnabled(prev) })

	off := false
	cfg := &config.Config{Outputs: map[string]config.Output{
		"x": {ProvenanceHeader: &off},
	}}

	restore := ProvenanceFor(cfg, "x")
	if ProvenanceEnabled() {
		t.Error("expected toggle off inside ProvenanceFor for x")
	}
	restore()
	if !ProvenanceEnabled() {
		t.Error("expected toggle restored to on after restore")
	}

	// Target without explicit config falls back to true (default).
	restore = ProvenanceFor(cfg, "other")
	if !ProvenanceEnabled() {
		t.Error("expected toggle on for unconfigured target")
	}
	restore()
}
