package emit

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/spec"
)

func TestMergedDocument_SkipsWhenEmpty(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "OUT.md")
	if err := MergedDocument(spec.Bundle{}, MergedOpts{
		OutFile: path,
		Title:   "OUT.md",
		Intro:   "Generated by agnostic-ai. Do not edit by hand.",
	}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Errorf("MergedDocument wrote %s with an empty bundle; want skip", path)
	}
}

func TestMergedDocument_WritesWhenNonEmpty(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "OUT.md")
	b := spec.Bundle{
		Rules: []spec.Entry{{Kind: spec.KindRule, Name: "r1", Body: "be excellent"}},
	}
	if err := MergedDocument(b, MergedOpts{
		OutFile: path,
		Title:   "OUT.md",
	}, false); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("expected file to be written: %v", err)
	}
	if len(got) == 0 {
		t.Error("expected non-empty output")
	}
}
