package emit

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

// TestMergeJSONFile_CaptureReadsExistingUserKeys regresses #465. Capture
// mode (used by `sync --check`, `doctor`, and `status`) must read the
// existing file so the captured bytes carry the user's sibling keys, not
// the managed keys alone. Otherwise drift is reported falsely and
// `doctor --fix` writes the managed-only capture back, deleting the
// user's keys.
func TestMergeJSONFile_CaptureReadsExistingUserKeys(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "opencode.json")
	const existing = `{"theme": "dark"}`
	if err := os.WriteFile(path, []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	sess.StartCapture()
	err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{"fs": map[string]any{}}}, false)
	files := sess.StopCapture()
	if err != nil {
		t.Fatal(err)
	}

	if len(files) != 1 {
		t.Fatalf("want 1 captured file, got %d", len(files))
	}
	for _, want := range []string{`"theme"`, `"dark"`, `"mcp"`} {
		if !strings.Contains(files[0].Content, want) {
			t.Errorf("captured content missing %q:\n%s", want, files[0].Content)
		}
	}

	// Capture must not write through to disk.
	disk, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(disk) != existing {
		t.Errorf("capture mutated disk: %s", disk)
	}
}

func TestMergeJSONFileNested_PreservesNativeObjectSiblings(t *testing.T) {
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "settings.json")
	if err := os.WriteFile(path, []byte(`{"model":{"name":"old","temperature":0.2},"theme":"dark"}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := NewSession().MergeJSONFileNested(path, map[string]any{
		"model": map[string]any{"name": "new"},
	}, []string{"model"}, false); err != nil {
		t.Fatal(err)
	}
	var got map[string]any
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatal(err)
	}
	model := got["model"].(map[string]any)
	if model["name"] != "new" || model["temperature"] != 0.2 || got["theme"] != "dark" {
		t.Errorf("nested merge lost native settings: %#v", got)
	}
}

func TestMigrateLegacyFile_RenamesWhenAgnosticGenerated(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"),
		[]byte("Generated by agnostic-ai\nstale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var warner bytes.Buffer
	prev := Warner
	Warner = &warner
	t.Cleanup(func() { Warner = prev })

	sess.MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", false)

	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md")); !os.IsNotExist(err) {
		t.Errorf("legacy should be renamed, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md.bak")); err != nil {
		t.Errorf("backup should exist: %v", err)
	}
	got := warner.String()
	for _, want := range []string{"amp:", "LEGACY.md", "NEW.md"} {
		if !bytes.Contains([]byte(got), []byte(want)) {
			t.Errorf("warner missing %q: %q", want, got)
		}
	}
}

func TestMigrateLegacyFile_LeavesUserAuthoredAlone(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	content := "My notes — no marker.\n"
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	sess.MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", false)
	got, err := os.ReadFile(filepath.Join(dir, "LEGACY.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != content {
		t.Errorf("user file modified: %q", got)
	}
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md.bak")); !os.IsNotExist(err) {
		t.Errorf("backup should not be made, err=%v", err)
	}
}

func TestMigrateLegacyFile_SkippedOnDryRun(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"),
		[]byte("Generated by agnostic-ai\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	sess.MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", true)
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md")); err != nil {
		t.Errorf("legacy should be preserved on dryRun: %v", err)
	}
}

func TestMigrateLegacyFile_SkippedDuringCapture(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"),
		[]byte("Generated by agnostic-ai\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	sess.StartCapture()
	sess.MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", false)
	_ = sess.StopCapture()
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md")); err != nil {
		t.Errorf("legacy should be preserved during capture: %v", err)
	}
}

func TestMigrateLegacyFile_HonorsCustomOutputDir(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	if err := os.MkdirAll(filepath.Join(dir, "vendor"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "vendor", "LEGACY.md"),
		[]byte("Generated by agnostic-ai\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"amp": {File: "vendor/NEW.md"},
		},
	}
	sess.MigrateLegacyFile(cfg, "amp", "LEGACY.md", "NEW.md", false)
	if _, err := os.Stat(filepath.Join(dir, "vendor", "LEGACY.md.bak")); err != nil {
		t.Errorf("expected backup in vendor/: %v", err)
	}
}

// TestMigrateLegacyPath_CrossesDirectories pins #1114's motivating case:
// a legacy path in one directory and a new default in another, which
// legacyFilePath's same-directory join cannot express.
func TestMigrateLegacyPath_CrossesDirectories(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	if err := os.MkdirAll(filepath.Join(dir, ".agent"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".agent", "AGENTS.md"),
		[]byte("Generated by agnostic-ai\nstale\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := sess.MigrateLegacyPath("antigravity", ".agent/AGENTS.md", ".agents/AGENTS.md", false); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Join(dir, ".agent", "AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("legacy should be renamed, err=%v", err)
	}
	got := readFileString(t, filepath.Join(dir, ".agent", "AGENTS.md.bak"))
	if !strings.Contains(got, "stale") {
		t.Errorf("backup should preserve old content: %q", got)
	}
}

// An existing `.bak` is never clobbered: `os.Rename` would silently
// overwrite it on Unix, discarding whatever an earlier migration (or a
// hand-made copy) left there. Leaving the legacy file in place instead
// was itself a data-loss bug: a legacy path already recorded in an
// older, already-persisted sync ledger reads as an orphan to the next
// sync's sweep once this run stops declaring it a managed output, and
// the sweep deletes it on the strength of its own provenance marker,
// discarding bytes that were never backed up anywhere (#1114 review).
// The fix numbers past the taken name instead: both the earlier backup
// and the current legacy content end up on disk, and the legacy path
// itself is always removed.
func TestMigrateLegacyPath_PreservesExistingBackup(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"),
		[]byte("Generated by agnostic-ai\nnew stale content\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md.bak"),
		[]byte("earlier backup, must survive\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var warner bytes.Buffer
	prev := Warner
	Warner = &warner
	t.Cleanup(func() { Warner = prev })

	if err := sess.MigrateLegacyPath("amp", "LEGACY.md", "NEW.md", false); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md")); !os.IsNotExist(err) {
		t.Errorf("legacy file should be removed once its bytes are backed up, err=%v", err)
	}
	if got := readFileString(t, filepath.Join(dir, "LEGACY.md.bak")); got != "earlier backup, must survive\n" {
		t.Errorf("existing backup must not be overwritten, got: %q", got)
	}
	if got := readFileString(t, filepath.Join(dir, "LEGACY.md.bak.1")); !strings.Contains(got, "new stale content") {
		t.Errorf("current legacy content should land in a numbered backup, got: %q", got)
	}
	if !strings.Contains(warner.String(), "LEGACY.md.bak.1") {
		t.Errorf("expected a warning naming the numbered backup, got %q", warner.String())
	}
}

// Numbering keeps going past more than one taken name.
func TestMigrateLegacyPath_NumbersPastSeveralTakenBackups(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"),
		[]byte("Generated by agnostic-ai\nthird generation\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"LEGACY.md.bak", "LEGACY.md.bak.1"} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte("taken\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	if err := sess.MigrateLegacyPath("amp", "LEGACY.md", "NEW.md", false); err != nil {
		t.Fatal(err)
	}

	if got := readFileString(t, filepath.Join(dir, "LEGACY.md.bak.2")); !strings.Contains(got, "third generation") {
		t.Errorf("expected the next free numbered backup, got: %q", got)
	}
	for _, name := range []string{"LEGACY.md.bak", "LEGACY.md.bak.1"} {
		if got := readFileString(t, filepath.Join(dir, name)); got != "taken\n" {
			t.Errorf("existing numbered backup %s must not be overwritten, got: %q", name, got)
		}
	}
}

// A rollback in the same transaction restores the legacy file and
// removes the backup this move created, so a sync pass that fails
// after the migration leaves the working tree exactly as it found it.
func TestMigrateLegacyPath_RollbackRestoresLegacyFile(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	const original = "Generated by agnostic-ai\noriginal content\n"
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"), []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}

	sess.StartTransaction()
	if err := sess.MigrateLegacyPath("amp", "LEGACY.md", "NEW.md", false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md.bak")); err != nil {
		t.Fatalf("expected backup before rollback: %v", err)
	}

	if err := sess.Rollback(); err != nil {
		t.Fatal(err)
	}

	if got := readFileString(t, filepath.Join(dir, "LEGACY.md")); got != original {
		t.Errorf("rollback should restore the legacy file verbatim, got: %q", got)
	}
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md.bak")); !os.IsNotExist(err) {
		t.Errorf("rollback should remove the backup this move created, err=%v", err)
	}
}

// sync.unmanaged matching the conventional backup destination (not the
// legacy path itself) skips that one candidate name, not the whole
// migration: the numbering search moves on to the next free name
// instead of writing over a user-owned path.
func TestMigrateLegacyPath_SkipsUnmanagedBackupCandidate(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	body := "Generated by agnostic-ai\nstale\n"
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	sess.SetUnmanaged([]string{"LEGACY.md.bak"})

	if err := sess.MigrateLegacyPath("amp", "LEGACY.md", "NEW.md", false); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md")); !os.IsNotExist(err) {
		t.Errorf("legacy file should be removed once its bytes are backed up, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md.bak")); !os.IsNotExist(err) {
		t.Errorf("no backup should be written over an unmanaged path, err=%v", err)
	}
	if got := readFileString(t, filepath.Join(dir, "LEGACY.md.bak.1")); got != body {
		t.Errorf("expected the backup at the next non-unmanaged name, got: %q", got)
	}
}

// TestMergeJSONFile_KeepsUserKeysInJSONC regresses #725. kilo, qoder and
// augment each merge into a file their vendor documents as JSONC, and
// `encoding/json` rejects both `//` comments and trailing commas. The
// parse error was swallowed and readExistingJSON returned an empty
// document, so the write back dropped every user-authored key,
// credentials and permission settings included.
func TestMergeJSONFile_KeepsUserKeysInJSONC(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "settings.json")
	const existing = `{
  // Provider credentials, hand-authored.
  "provider": {
    "name": "anthropic",
    "apiKey": "sk-secret-value",
  },
  /* block form too */
  "endpoint": "https://example.com//v1",
  "experimental": { "autoApprove": false },
}
`
	if err := os.WriteFile(path, []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{"linear": map[string]any{}}}, false)
	if err != nil {
		t.Fatal(err)
	}

	got := readFileString(t, path)
	for _, want := range []string{
		`"provider"`, `"sk-secret-value"`, `"experimental"`, `"mcp"`,
		`"https://example.com//v1"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("merged file lost %s:\n%s", want, got)
		}
	}
}

// TestMergeJSONFile_FailsLoudlyOnUnparseableFile pins the other half of
// #725: a non-empty file that is neither JSON nor JSONC aborts the write
// instead of being silently replaced by the managed keys alone.
func TestMergeJSONFile_FailsLoudlyOnUnparseableFile(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "settings.json")
	const existing = "{ this is not json at all"
	if err := os.WriteFile(path, []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{}}, false)
	if err == nil {
		t.Fatal("expected an error on an unparseable existing file")
	}
	if !strings.Contains(err.Error(), "settings.json") {
		t.Errorf("error should name the file: %v", err)
	}
	if got := readFileString(t, path); got != existing {
		t.Errorf("unparseable file must stay untouched, got:\n%s", got)
	}
}

// An empty or whitespace-only file is not a parse failure: it is the
// same starting point as a missing file, so the merge proceeds.
func TestMergeJSONFile_EmptyFileStartsFresh(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "settings.json")
	if err := os.WriteFile(path, []byte("\n  \n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{}}, false); err != nil {
		t.Fatal(err)
	}
	if got := readFileString(t, path); !strings.Contains(got, `"mcp"`) {
		t.Errorf("expected managed key in:\n%s", got)
	}
}

func TestMergeJSONFile_WarnsWhenCommentsDropped(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "settings.json")
	if err := os.WriteFile(path, []byte("{\n  // keep me\n  \"theme\": \"dark\"\n}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var warner bytes.Buffer
	prev := Warner
	Warner = &warner
	t.Cleanup(func() { Warner = prev })

	if err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{}}, false); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(warner.String(), "settings.json") {
		t.Errorf("expected a dropped-comment warning, got %q", warner.String())
	}
}

// A file with no comments must not trigger the dropped-comment warning,
// or every sync of an ordinary JSON settings file would print it.
func TestMergeJSONFile_SilentOnPlainJSON(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "settings.json")
	if err := os.WriteFile(path, []byte(`{"theme": "dark"}`), 0o644); err != nil {
		t.Fatal(err)
	}
	var warner bytes.Buffer
	prev := Warner
	Warner = &warner
	t.Cleanup(func() { Warner = prev })

	if err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{}}, false); err != nil {
		t.Fatal(err)
	}
	if warner.Len() > 0 {
		t.Errorf("plain JSON should warn about nothing, got %q", warner.String())
	}
}

func readFileString(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
