package emit

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

// TestMergeJSONFile_CaptureReadsExistingUserKeys regresses #465. Capture
// mode (used by `sync --check`, `doctor`, and `status`) must read the
// existing file so the captured bytes carry the user's sibling keys, not
// the managed keys alone. Otherwise drift is reported falsely and
// `doctor --fix` writes the managed-only capture back, deleting the
// user's keys.
func TestMergeJSONFile_CaptureReadsExistingUserKeys(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "opencode.json")
	const existing = `{"theme": "dark"}`
	if err := os.WriteFile(path, []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	sess.StartCapture()
	err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{"fs": map[string]any{}}}, false)
	files := sess.StopCapture()
	if err != nil {
		t.Fatal(err)
	}

	if len(files) != 1 {
		t.Fatalf("want 1 captured file, got %d", len(files))
	}
	for _, want := range []string{`"theme"`, `"dark"`, `"mcp"`} {
		if !strings.Contains(files[0].Content, want) {
			t.Errorf("captured content missing %q:\n%s", want, files[0].Content)
		}
	}

	// Capture must not write through to disk.
	disk, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(disk) != existing {
		t.Errorf("capture mutated disk: %s", disk)
	}
}

func TestMigrateLegacyFile_RenamesWhenAgnosticGenerated(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"),
		[]byte("Generated by agnostic-ai\nstale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var warner bytes.Buffer
	prev := Warner
	Warner = &warner
	t.Cleanup(func() { Warner = prev })

	sess.MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", false)

	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md")); !os.IsNotExist(err) {
		t.Errorf("legacy should be renamed, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md.bak")); err != nil {
		t.Errorf("backup should exist: %v", err)
	}
	got := warner.String()
	for _, want := range []string{"amp:", "LEGACY.md", "NEW.md"} {
		if !bytes.Contains([]byte(got), []byte(want)) {
			t.Errorf("warner missing %q: %q", want, got)
		}
	}
}

func TestMigrateLegacyFile_LeavesUserAuthoredAlone(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	content := "My notes — no marker.\n"
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	sess.MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", false)
	got, err := os.ReadFile(filepath.Join(dir, "LEGACY.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != content {
		t.Errorf("user file modified: %q", got)
	}
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md.bak")); !os.IsNotExist(err) {
		t.Errorf("backup should not be made, err=%v", err)
	}
}

func TestMigrateLegacyFile_SkippedOnDryRun(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"),
		[]byte("Generated by agnostic-ai\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	sess.MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", true)
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md")); err != nil {
		t.Errorf("legacy should be preserved on dryRun: %v", err)
	}
}

func TestMigrateLegacyFile_SkippedDuringCapture(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"),
		[]byte("Generated by agnostic-ai\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	sess.StartCapture()
	sess.MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", false)
	_ = sess.StopCapture()
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md")); err != nil {
		t.Errorf("legacy should be preserved during capture: %v", err)
	}
}

func TestMigrateLegacyFile_HonorsCustomOutputDir(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	if err := os.MkdirAll(filepath.Join(dir, "vendor"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "vendor", "LEGACY.md"),
		[]byte("Generated by agnostic-ai\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"amp": {File: "vendor/NEW.md"},
		},
	}
	sess.MigrateLegacyFile(cfg, "amp", "LEGACY.md", "NEW.md", false)
	if _, err := os.Stat(filepath.Join(dir, "vendor", "LEGACY.md.bak")); err != nil {
		t.Errorf("expected backup in vendor/: %v", err)
	}
}

// TestMergeJSONFile_KeepsUserKeysInJSONC regresses #725. kilo, qoder and
// augment each merge into a file their vendor documents as JSONC, and
// `encoding/json` rejects both `//` comments and trailing commas. The
// parse error was swallowed and readExistingJSON returned an empty
// document, so the write back dropped every user-authored key,
// credentials and permission settings included.
func TestMergeJSONFile_KeepsUserKeysInJSONC(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "settings.json")
	const existing = `{
  // Provider credentials, hand-authored.
  "provider": {
    "name": "anthropic",
    "apiKey": "sk-secret-value",
  },
  /* block form too */
  "endpoint": "https://example.com//v1",
  "experimental": { "autoApprove": false },
}
`
	if err := os.WriteFile(path, []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{"linear": map[string]any{}}}, false)
	if err != nil {
		t.Fatal(err)
	}

	got := readFileString(t, path)
	for _, want := range []string{
		`"provider"`, `"sk-secret-value"`, `"experimental"`, `"mcp"`,
		`"https://example.com//v1"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("merged file lost %s:\n%s", want, got)
		}
	}
}

// TestMergeJSONFile_FailsLoudlyOnUnparseableFile pins the other half of
// #725: a non-empty file that is neither JSON nor JSONC aborts the write
// instead of being silently replaced by the managed keys alone.
func TestMergeJSONFile_FailsLoudlyOnUnparseableFile(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "settings.json")
	const existing = "{ this is not json at all"
	if err := os.WriteFile(path, []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{}}, false)
	if err == nil {
		t.Fatal("expected an error on an unparseable existing file")
	}
	if !strings.Contains(err.Error(), "settings.json") {
		t.Errorf("error should name the file: %v", err)
	}
	if got := readFileString(t, path); got != existing {
		t.Errorf("unparseable file must stay untouched, got:\n%s", got)
	}
}

// An empty or whitespace-only file is not a parse failure: it is the
// same starting point as a missing file, so the merge proceeds.
func TestMergeJSONFile_EmptyFileStartsFresh(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "settings.json")
	if err := os.WriteFile(path, []byte("\n  \n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{}}, false); err != nil {
		t.Fatal(err)
	}
	if got := readFileString(t, path); !strings.Contains(got, `"mcp"`) {
		t.Errorf("expected managed key in:\n%s", got)
	}
}

func TestMergeJSONFile_WarnsWhenCommentsDropped(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "settings.json")
	if err := os.WriteFile(path, []byte("{\n  // keep me\n  \"theme\": \"dark\"\n}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var warner bytes.Buffer
	prev := Warner
	Warner = &warner
	t.Cleanup(func() { Warner = prev })

	if err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{}}, false); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(warner.String(), "settings.json") {
		t.Errorf("expected a dropped-comment warning, got %q", warner.String())
	}
}

// A file with no comments must not trigger the dropped-comment warning,
// or every sync of an ordinary JSON settings file would print it.
func TestMergeJSONFile_SilentOnPlainJSON(t *testing.T) {
	sess := NewSession()
	dir := testutil.TempCwd(t)
	path := filepath.Join(dir, "settings.json")
	if err := os.WriteFile(path, []byte(`{"theme": "dark"}`), 0o644); err != nil {
		t.Fatal(err)
	}
	var warner bytes.Buffer
	prev := Warner
	Warner = &warner
	t.Cleanup(func() { Warner = prev })

	if err := sess.MergeJSONFile(path, map[string]any{"mcp": map[string]any{}}, false); err != nil {
		t.Fatal(err)
	}
	if warner.Len() > 0 {
		t.Errorf("plain JSON should warn about nothing, got %q", warner.String())
	}
}

func readFileString(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
