package emit

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/chemaclass/agnostic-ai/internal/config"
)

// MergeJSONFile reads the existing JSON at path (when not in capture or
// dry-run mode), sets every key in `keys` on the decoded document, and
// writes the merged result back to path. Missing or malformed files
// start from an empty document.
//
// Used by adapters that share a project-shared config file with other
// tooling (opencode.json `mcp`, `.amp/settings.json` `amp.mcpServers`)
// and need to overwrite only their managed keys without clobbering
// user-edited siblings. Capture mode skips the read so the captured
// output is deterministic from the bundle alone; this may surface
// unrelated user keys as drift under `sync --check`, which is the
// intended trade-off.
func MergeJSONFile(path string, keys map[string]any, dryRun bool) error {
	doc := readExistingJSON(path, dryRun)
	for k, v := range keys {
		doc[k] = v
	}
	raw, err := MarshalJSONIndent(doc)
	if err != nil {
		return fmt.Errorf("marshal %s: %w", path, err)
	}
	return WriteFile(path, string(raw)+"\n", dryRun)
}

func readExistingJSON(path string, dryRun bool) map[string]any {
	if dryRun || IsCapturing() {
		return map[string]any{}
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return map[string]any{}
	}
	var doc map[string]any
	if err := json.Unmarshal(data, &doc); err != nil || doc == nil {
		return map[string]any{}
	}
	return doc
}

// ProvenanceMarker is the substring agnostic-ai writes into every
// generated document's header (e.g. `Generated by agnostic-ai. Do not
// edit by hand.`). Adapters use it to distinguish a previously
// generated file from a user-authored one before performing migration
// renames.
const ProvenanceMarker = "Generated by agnostic-ai"

// MigrateLegacyFile renames a previously generated legacy file aside
// so the user notices the rename to a new default file name. Used by
// adapters whose default output filename changed across releases
// (`amp`: AGENT.md -> AGENTS.md, `warp`: WARP.md -> AGENTS.md).
//
// Behavior:
//   - Skipped when dryRun is true.
//   - Skipped while capture mode is active so `sync --check` and
//     `revert` do not mutate the working tree.
//   - Skipped when the legacy file is missing or does not carry the
//     agnostic-ai provenance marker (it is treated as user-authored
//     and left untouched).
//   - Looks for the legacy file alongside the configured output
//     directory derived from cfg.Outputs[target].File (or the default
//     output path), so a custom output location migrates correctly.
//
// On success, renames `<rootDir>/<legacyName>` to `<rootDir>/<legacyName>.bak`
// and prints a one-line warning to Warner.
func MigrateLegacyFile(cfg *config.Config, target, legacyName, defaultNewPath string, dryRun bool) {
	if dryRun || IsCapturing() {
		return
	}
	rootDir := filepath.Dir(OutputFile(cfg, target, defaultNewPath))
	legacyPath := legacyName
	if rootDir != "." && rootDir != "" {
		legacyPath = filepath.Join(rootDir, legacyName)
	}
	data, err := os.ReadFile(legacyPath)
	if err != nil || !bytes.Contains(data, []byte(ProvenanceMarker)) {
		return
	}
	if err := os.Rename(legacyPath, legacyPath+".bak"); err != nil {
		return
	}
	newName := filepath.Base(defaultNewPath)
	_, _ = fmt.Fprintf(Warner, "%s: renamed legacy %s to %s.bak; new layout writes %s\n",
		target, legacyPath, legacyPath, newName)
}
