package emit

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestMigrateLegacyFile_RenamesWhenAgnosticGenerated(t *testing.T) {
	dir := testutil.TempCwd(t)
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"),
		[]byte("Generated by agnostic-ai\nstale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var warner bytes.Buffer
	prev := Warner
	Warner = &warner
	t.Cleanup(func() { Warner = prev })

	MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", false)

	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md")); !os.IsNotExist(err) {
		t.Errorf("legacy should be renamed, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md.bak")); err != nil {
		t.Errorf("backup should exist: %v", err)
	}
	got := warner.String()
	for _, want := range []string{"amp:", "LEGACY.md", "NEW.md"} {
		if !bytes.Contains([]byte(got), []byte(want)) {
			t.Errorf("warner missing %q: %q", want, got)
		}
	}
}

func TestMigrateLegacyFile_LeavesUserAuthoredAlone(t *testing.T) {
	dir := testutil.TempCwd(t)
	content := "My notes — no marker.\n"
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", false)
	got, err := os.ReadFile(filepath.Join(dir, "LEGACY.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != content {
		t.Errorf("user file modified: %q", got)
	}
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md.bak")); !os.IsNotExist(err) {
		t.Errorf("backup should not be made, err=%v", err)
	}
}

func TestMigrateLegacyFile_SkippedOnDryRun(t *testing.T) {
	dir := testutil.TempCwd(t)
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"),
		[]byte("Generated by agnostic-ai\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", true)
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md")); err != nil {
		t.Errorf("legacy should be preserved on dryRun: %v", err)
	}
}

func TestMigrateLegacyFile_SkippedDuringCapture(t *testing.T) {
	dir := testutil.TempCwd(t)
	if err := os.WriteFile(filepath.Join(dir, "LEGACY.md"),
		[]byte("Generated by agnostic-ai\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	StartCapture()
	MigrateLegacyFile(&config.Config{}, "amp", "LEGACY.md", "NEW.md", false)
	_ = StopCapture()
	if _, err := os.Stat(filepath.Join(dir, "LEGACY.md")); err != nil {
		t.Errorf("legacy should be preserved during capture: %v", err)
	}
}

func TestMigrateLegacyFile_HonorsCustomOutputDir(t *testing.T) {
	dir := testutil.TempCwd(t)
	if err := os.MkdirAll(filepath.Join(dir, "vendor"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "vendor", "LEGACY.md"),
		[]byte("Generated by agnostic-ai\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"amp": {File: "vendor/NEW.md"},
		},
	}
	MigrateLegacyFile(cfg, "amp", "LEGACY.md", "NEW.md", false)
	if _, err := os.Stat(filepath.Join(dir, "vendor", "LEGACY.md.bak")); err != nil {
		t.Errorf("expected backup in vendor/: %v", err)
	}
}
