package emit

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/chemaclass/agnostic-ai/internal/adapters/header"
	"github.com/chemaclass/agnostic-ai/internal/config"
)

// MergeJSONFile reads the existing JSON or JSONC at path (when not in
// dry-run mode), sets every key in `keys` on the decoded document, and
// writes the merged result back to path. A missing or empty file starts
// from an empty document; a non-empty file that will not parse is an
// error, and nothing is written.
//
// Used by adapters that share a project-shared config file with other
// tooling (opencode.json `mcp`, `.amp/settings.json` `amp.mcpServers`)
// and need to overwrite only their managed keys without clobbering
// user-edited siblings. Capture mode (sync --check, doctor, status)
// still reads the existing file: the on-disk document is part input
// (the user's sibling keys), not a pure output, so the captured bytes
// must reflect what sync would write. Skipping the read reported false
// drift and let `doctor --fix` delete the user's keys (#465).
//
// Comments do not survive: the document is re-rendered from parsed
// values, so a JSONC input keeps every key and loses every comment.
// The user hears about that once, on the sync that drops them (#725).
func (s *Session) MergeJSONFile(path string, keys map[string]any, dryRun bool) error {
	doc, err := s.readExistingJSON(path, dryRun)
	if err != nil {
		return err
	}
	names := make([]string, 0, len(keys))
	for k := range keys {
		names = append(names, k)
	}
	sort.Strings(names)
	for _, k := range names {
		if err := doc.Set(k, keys[k]); err != nil {
			return fmt.Errorf("marshal %s key %s: %w", path, k, err)
		}
	}
	raw, err := MarshalJSONIndent(doc)
	if err != nil {
		return fmt.Errorf("marshal %s: %w", path, err)
	}
	return s.WriteFile(path, string(raw)+"\n", dryRun)
}

// readExistingJSON parses path as an OrderedJSON, accepting JSONC.
// Source key order is preserved on the round-trip via OrderedJSON.
// dryRun returns empty so `--dry-run` previews stay pure; capture mode
// still reads so drift detection and `doctor --fix` see the user's
// sibling keys (#465).
//
// An unreadable or empty file returns an empty document so callers can
// layer their managed keys unconditionally. Anything else that fails to
// parse returns an error: the caller's next move is to write the file,
// and returning empty there means writing the managed keys over the
// top of content nobody could read. That silent replacement is what
// deleted user keys from every JSONC config (#725).
func (s *Session) readExistingJSON(path string, dryRun bool) (*OrderedJSON, error) {
	if dryRun {
		return NewOrderedJSON(), nil
	}
	data, err := os.ReadFile(path)
	if err != nil || len(bytes.TrimSpace(data)) == 0 {
		return NewOrderedJSON(), nil
	}
	stripped, hadComments := StripJSONC(data)
	doc := NewOrderedJSON()
	if err := json.Unmarshal(stripped, doc); err != nil {
		return nil, fmt.Errorf("parse %s: %w (agnostic-ai will not overwrite a file it cannot read; fix it or move it aside)", path, err)
	}
	if hadComments && !s.IsCapturing() {
		_, _ = fmt.Fprintf(Warner,
			"%s: comments are not preserved across a sync; every key is kept, the comments are dropped\n", path)
	}
	return doc, nil
}

// ProvenanceMarker is the substring agnostic-ai writes into every
// generated document's header (e.g. `Generated by agnostic-ai`).
// Adapters use it to distinguish a previously generated file from a
// user-authored one before performing migration renames. Aliased to
// header.Marker so both packages share one source of truth.
const ProvenanceMarker = header.Marker

// MigrateLegacyFile renames a previously generated legacy file aside
// so the user notices the rename to a new default file name. Used by
// adapters whose default output filename changed across releases
// (`amp`: AGENT.md -> AGENTS.md, `warp`: WARP.md -> AGENTS.md).
//
// Behavior:
//   - Skipped when dryRun is true.
//   - Skipped while capture mode is active so `sync --check` and
//     `revert` do not mutate the working tree.
//   - Skipped when the legacy file is missing or does not carry the
//     agnostic-ai provenance marker (it is treated as user-authored
//     and left untouched).
//   - Looks for the legacy file alongside the configured output
//     directory derived from cfg.Outputs[target].File (or the default
//     output path), so a custom output location migrates correctly.
//
// On success, renames `<rootDir>/<legacyName>` to `<rootDir>/<legacyName>.bak`
// and prints a one-line warning to Warner.
func (s *Session) MigrateLegacyFile(cfg *config.Config, target, legacyName, defaultNewPath string, dryRun bool) {
	if dryRun || s.IsCapturing() {
		return
	}
	legacyPath := legacyFilePath(cfg, target, legacyName, defaultNewPath)
	data, err := os.ReadFile(legacyPath)
	if err != nil || !bytes.Contains(data, []byte(ProvenanceMarker)) {
		return
	}
	if err := os.Rename(legacyPath, legacyPath+".bak"); err != nil {
		return
	}
	newName := filepath.Base(defaultNewPath)
	_, _ = fmt.Fprintf(Warner, "%s: renamed legacy %s to %s.bak; new layout writes %s\n",
		target, legacyPath, legacyPath, newName)
}

// legacyFilePath resolves legacyName against the directory holding the
// target's current entry-point output, honoring an outputs.<target>.file
// override the same way MigrateLegacyFile's rename target does.
func legacyFilePath(cfg *config.Config, target, legacyName, defaultNewPath string) string {
	rootDir := filepath.Dir(OutputFile(cfg, target, defaultNewPath))
	if rootDir == "." || rootDir == "" {
		return legacyName
	}
	return filepath.Join(rootDir, legacyName)
}

// WarnIfLegacyFileOutranksEntryPoint fires when legacyName exists next to
// the resolved entry-point file without the agnostic-ai provenance marker.
// MigrateLegacyFile already leaves such a file untouched, since it reads
// as real user content, but for a vendor whose CLI reads the legacy
// filename ahead of the new default that silence hides a total delivery
// failure rather than a harmless leftover: every rule sync just wrote to
// defaultNewPath never reaches the tool.
//
// Warp is the motivating case: "If both WARP.md and AGENTS.md exist in
// the same directory, WARP.md takes priority"
// (docs.warp.dev/agents/capabilities/rules, target-audit 2026-09-08,
// #691). Callers opt in per target; amp's AGENT.md is a documented
// fallback read only when AGENTS.md is absent, so it never calls this.
//
// Skipped while capture mode is active: `sync` itself runs every
// adapter once in capture mode first (collision detection) and once for
// real, and only the real pass should print. `sync --check` / `status`
// / `revert` never leave capture mode, so this stays silent there too,
// the same tradeoff MigrateLegacyFile's own rename already makes.
func (s *Session) WarnIfLegacyFileOutranksEntryPoint(cfg *config.Config, target, legacyName, defaultNewPath string) {
	if s.IsCapturing() {
		return
	}
	legacyPath := legacyFilePath(cfg, target, legacyName, defaultNewPath)
	data, err := os.ReadFile(legacyPath)
	if err != nil || bytes.Contains(data, []byte(ProvenanceMarker)) {
		return
	}
	newName := filepath.Base(defaultNewPath)
	_, _ = fmt.Fprintf(Warner, "%s: %s takes priority over %s; it is not agnostic-ai-generated, so none of the synced rules reach %s until you rename or remove it\n",
		target, legacyPath, newName, target)
}
