package emit

import (
	"os"
	"path/filepath"
	"testing"
)

// Another target's worker creates its directory before writing into it.
// A sweep that removed nothing must not prune that directory: on Windows
// the other worker's write then fails with "Access is denied" (#1548).
func TestRemoveGeneratedTreeExt_LeavesADirectoryItDidNotEmpty(t *testing.T) {
	dir := t.TempDir()
	shared := filepath.Join(dir, ".agents", "agents")
	other := filepath.Join(shared, "agent-1")
	if err := os.MkdirAll(other, 0o755); err != nil {
		t.Fatal(err)
	}

	if err := NewSession().RemoveGeneratedTreeExt(shared, ".toml", false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(other); err != nil {
		t.Errorf("sweep pruned a directory it held no file in: %v", err)
	}
}

// The root holds two emptied children, so it is only empty once both
// are gone. A root left behind keeps a legacy layout alive, such as the
// `.junie/rules` directory `import junie` picks by existence.
func TestRemoveGeneratedTree_PrunesARootEmptiedThroughSiblingDirs(t *testing.T) {
	dir := t.TempDir()
	root := filepath.Join(dir, ".junie", "rules")
	for _, rel := range []string{filepath.Join("a", "r1.md"), filepath.Join("b", "r2.md")} {
		path := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte("<!-- Generated by agnostic-ai -->\nx\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	if err := NewSession().RemoveGeneratedTree(root, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(root); !os.IsNotExist(err) {
		t.Errorf("emptied legacy root survived: %v", err)
	}
}

func TestRemoveGeneratedTreeExt_PrunesOnlyWhereItRemovedFiles(t *testing.T) {
	dir := t.TempDir()
	shared := filepath.Join(dir, "agents")
	legacy := filepath.Join(shared, "old", "old.toml")
	other := filepath.Join(shared, "agent-1")
	for _, d := range []string{filepath.Dir(legacy), other} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(legacy, []byte("# Generated by agnostic-ai\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := NewSession().RemoveGeneratedTreeExt(shared, ".toml", false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Dir(legacy)); !os.IsNotExist(err) {
		t.Errorf("emptied legacy directory survived: %v", err)
	}
	if _, err := os.Stat(other); err != nil {
		t.Errorf("sweep pruned another target's empty directory: %v", err)
	}
}
