package emit

import (
	"os"
	"path/filepath"
	"testing"
)

func writeTestFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestRemoveOwned_RemovesHeaderlessFileWhoseBytesMatchSum(t *testing.T) {
	path := filepath.Join(t.TempDir(), "references", "a.md")
	body := "ref\n"
	writeTestFile(t, path, body)

	removed, err := NewSession().RemoveOwned(path, ContentSum(body), false)
	if err != nil {
		t.Fatalf("RemoveOwned: %v", err)
	}
	if !removed {
		t.Error("removed = false, want true")
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Errorf("file still on disk: %v", err)
	}
}

func TestRemoveOwned_KeepsHeaderlessFileEditedSinceSync(t *testing.T) {
	path := filepath.Join(t.TempDir(), "a.md")
	writeTestFile(t, path, "edited\n")

	removed, err := NewSession().RemoveOwned(path, ContentSum("ref\n"), false)
	if err != nil {
		t.Fatalf("RemoveOwned: %v", err)
	}
	if removed {
		t.Error("removed = true, want false")
	}
	if _, err := os.Stat(path); err != nil {
		t.Errorf("edited file removed: %v", err)
	}
}

func TestRemoveOwned_KeepsHeaderlessFileWithoutSum(t *testing.T) {
	path := filepath.Join(t.TempDir(), "a.md")
	writeTestFile(t, path, "ref\n")

	removed, err := NewSession().RemoveOwned(path, "", false)
	if err != nil {
		t.Fatalf("RemoveOwned: %v", err)
	}
	if removed {
		t.Error("removed = true, want false")
	}
}

func TestRemoveOwned_RemovesHeaderFileRegardlessOfSum(t *testing.T) {
	path := filepath.Join(t.TempDir(), "SKILL.md")
	writeTestFile(t, path, "<!-- Generated by agnostic-ai -->\nbody\n")

	removed, err := NewSession().RemoveOwned(path, "", false)
	if err != nil {
		t.Fatalf("RemoveOwned: %v", err)
	}
	if !removed {
		t.Error("removed = false, want true")
	}
}

func TestRemoveOwned_KeepsUnmanagedPath(t *testing.T) {
	testutilChdir(t, t.TempDir())
	const path = ".claude/skills/gone/references/a.md"
	body := "ref\n"
	writeTestFile(t, path, body)
	sess := NewSession()
	sess.SetUnmanaged([]string{path})

	removed, err := sess.RemoveOwned(path, ContentSum(body), false)
	if err != nil {
		t.Fatalf("RemoveOwned: %v", err)
	}
	if removed {
		t.Error("removed = true, want false")
	}
	if _, err := os.Stat(path); err != nil {
		t.Errorf("user-owned file removed: %v", err)
	}
}

func TestRemoveOwned_DryRunReportsWithoutTouchingDisk(t *testing.T) {
	path := filepath.Join(t.TempDir(), "a.md")
	body := "ref\n"
	writeTestFile(t, path, body)

	removed, err := NewSession().RemoveOwned(path, ContentSum(body), true)
	if err != nil {
		t.Fatalf("RemoveOwned: %v", err)
	}
	if !removed {
		t.Error("dry-run removed = false, want true")
	}
	if _, err := os.Stat(path); err != nil {
		t.Errorf("dry-run touched disk: %v", err)
	}
}

func TestRemoveOwned_MissingFileIsNotRemoved(t *testing.T) {
	removed, err := NewSession().RemoveOwned(filepath.Join(t.TempDir(), "absent.md"), "x", false)
	if err != nil {
		t.Fatalf("RemoveOwned: %v", err)
	}
	if removed {
		t.Error("removed = true for a missing file")
	}
}

func TestRemoveOwned_RollbackRestoresHeaderlessFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "a.md")
	body := "ref\n"
	writeTestFile(t, path, body)
	sess := NewSession()
	sess.StartTransaction()

	if _, err := sess.RemoveOwned(path, ContentSum(body), false); err != nil {
		t.Fatalf("RemoveOwned: %v", err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("Rollback: %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil || string(got) != body {
		t.Errorf("rollback did not restore file: %q, %v", got, err)
	}
}

func TestDetailedWrite_SumsOnlyHeaderlessContent(t *testing.T) {
	dir := t.TempDir()
	sess := NewSession()
	sess.StartDetailedRecording()
	plain := filepath.Join(dir, "a.md")
	generated := filepath.Join(dir, "SKILL.md")
	if err := sess.WriteFile(plain, "ref\n", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.WriteFile(generated, "<!-- Generated by agnostic-ai -->\nbody\n", false); err != nil {
		t.Fatal(err)
	}
	// A rerun with identical bytes is a skip and must still carry the sum.
	if err := sess.WriteFile(plain, "ref\n", false); err != nil {
		t.Fatal(err)
	}
	writes := sess.StopDetailedRecording()

	if len(writes) != 3 {
		t.Fatalf("writes = %+v, want 3", writes)
	}
	if writes[0].Sum != ContentSum("ref\n") {
		t.Errorf("create sum = %q, want content sum", writes[0].Sum)
	}
	if writes[1].Sum != "" {
		t.Errorf("header file sum = %q, want empty", writes[1].Sum)
	}
	if writes[2].Action != "skip" || writes[2].Sum != ContentSum("ref\n") {
		t.Errorf("skip write = %+v, want skip with content sum", writes[2])
	}
}

// A file removed so a directory can take its path (Cline's single-file
// `.clinerules`, #1060) comes back on rollback once the files written
// under it are undone.
func TestRemoveOwned_RollbackRestoresFileReplacedByDirectory(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".clinerules")
	body := "Use tabs.\n"
	writeTestFile(t, path, body)
	sess := NewSession()
	sess.StartTransaction()

	if _, err := sess.RemoveOwned(path, ContentSum(body), false); err != nil {
		t.Fatalf("RemoveOwned: %v", err)
	}
	if err := sess.WriteFile(filepath.Join(path, "nested", "r.md"), "rule", false); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("Rollback: %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil || string(got) != body {
		t.Errorf("rollback did not restore file: %q, %v", got, err)
	}
}
