package emit

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

const scopedRender = "<!-- Generated by agnostic-ai. -->\n\n## Rules\n\n### money\n\n_Money rules._\n\nUse integer minor units.\n"

func writeScoped(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

// Import moves a hand-authored file's text into specs: headings become
// rule names and a leading italic line a description, so sync may
// replace the file once every line of text is in what it writes (#1269).
func TestCheckScopedDestination_AdoptsFileWhoseTextSyncWrites(t *testing.T) {
	testutil.Chdir(t, t.TempDir())
	writeScoped(t, "services/api/AGENTS.md", "# API\r\n\r\n## Money\r\n\r\n*Money rules.*\r\n\r\nUse integer minor units.  \r\n")

	if err := CheckScopedDestination("services/api/AGENTS.md", scopedRender); err != nil {
		t.Fatalf("CheckScopedDestination() = %v, want the imported file adopted", err)
	}
}

func TestCheckScopedDestination_NamesTextNoSpecHolds(t *testing.T) {
	testutil.Chdir(t, t.TempDir())
	writeScoped(t, "services/api/AGENTS.md", "Use integer minor units.\n\n#123 tracks this.\n")

	err := CheckScopedDestination("services/api/AGENTS.md", scopedRender)
	if err == nil {
		t.Fatal("CheckScopedDestination() = nil, want an error for text no spec holds")
	}
	for _, want := range []string{`"#123 tracks this."`, "after import", "mv services/api/AGENTS.md services/api/AGENTS.md.before-agnostic"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q should contain %q", err, want)
		}
	}
}

// Text an import captured does not make an alternate file safe: sync
// never writes it, so the host would load both.
func TestCheckScopedDestination_RejectsAlternateFileEvenWhenCaptured(t *testing.T) {
	testutil.Chdir(t, t.TempDir())
	writeScoped(t, "services/api/AGENTS.override.md", "Use integer minor units.\n")

	if err := CheckScopedDestination("services/api/AGENTS.md", scopedRender); err == nil {
		t.Fatal("CheckScopedDestination() = nil, want the alternate file rejected")
	}
}
