package emit

import (
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

func TestTransaction_RollbackRestoresOverwrittenFile(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	path := filepath.Join(dir, "CLAUDE.md")
	if err := os.WriteFile(path, []byte("original"), 0o644); err != nil {
		t.Fatal(err)
	}

	sess.StartTransaction()
	if err := sess.WriteFile(path, "modified", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "original" {
		t.Errorf("expected original content after rollback, got %q", got)
	}
}

func TestTransaction_RollbackRestoresExecutableMode(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Windows does not support Unix executable mode bits")
	}
	t.Parallel()
	sess := NewSession()
	path := filepath.Join(t.TempDir(), "setup")
	if err := os.WriteFile(path, []byte("#!/bin/sh\n"), 0o755); err != nil {
		t.Fatal(err)
	}

	sess.StartTransaction()
	if err := sess.WriteFile(path, "replacement", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o755 {
		t.Errorf("mode = %o, want 755", info.Mode().Perm())
	}
}

func TestTransaction_RollbackDeletesNewFile(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	path := filepath.Join(dir, "newfile.md")

	sess.StartTransaction()
	if err := sess.WriteFile(path, "created", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}

	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Errorf("expected file to be removed after rollback, stat err=%v", err)
	}
}

func TestTransaction_CommitPreservesWrites(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	path := filepath.Join(dir, "CLAUDE.md")
	if err := os.WriteFile(path, []byte("old"), 0o644); err != nil {
		t.Fatal(err)
	}

	sess.StartTransaction()
	if err := sess.WriteFile(path, "new", false); err != nil {
		t.Fatal(err)
	}
	sess.Commit()

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "new\n" {
		t.Errorf("expected new content after commit (normalized newline), got %q", got)
	}
}

func TestTransaction_RollbackMultipleFilesInReverseOrder(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	fileA := filepath.Join(dir, "a.md")
	fileB := filepath.Join(dir, "b.md")
	if err := os.WriteFile(fileA, []byte("a-old"), 0o644); err != nil {
		t.Fatal(err)
	}

	sess.StartTransaction()
	if err := sess.WriteFile(fileA, "a-new", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.WriteFile(fileB, "b-created", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}

	gotA, err := os.ReadFile(fileA)
	if err != nil {
		t.Fatal(err)
	}
	if string(gotA) != "a-old" {
		t.Errorf("expected a-old after rollback, got %q", gotA)
	}
	if _, err := os.Stat(fileB); !os.IsNotExist(err) {
		t.Errorf("expected fileB removed after rollback, stat err=%v", err)
	}
}

func TestTransaction_RollbackRestoresFileInPrunedFolder(t *testing.T) {
	t.Parallel()
	dir := filepath.Join(t.TempDir(), ".codex", "skills")
	path := filepath.Join(dir, "gone", "SKILL.md")
	const body = "<!-- Generated by agnostic-ai -->\nold\n"
	writeTestFile(t, path, body)
	sess := NewSession()
	sess.StartTransaction()

	if err := sess.RemoveGeneratedTree(dir, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(dir); !os.IsNotExist(err) {
		t.Fatalf("sweep kept the emptied tree: %v", err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}
	if got, err := os.ReadFile(path); err != nil || string(got) != body {
		t.Errorf("rollback did not restore file: %q, %v", got, err)
	}
}

func TestTransaction_RollbackRestoresRemovedLinkAsLink(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	const body = "<!-- Generated by agnostic-ai -->\nbody\n"
	writeTestFile(t, filepath.Join(dir, "AGENTS.md"), body)
	link := filepath.Join(dir, "AGENT.md")
	if err := os.Symlink("AGENTS.md", link); err != nil {
		t.Skipf("symlinks unsupported: %v", err)
	}
	sess := NewSession()
	sess.StartTransaction()

	if removed, err := sess.RemoveOwned(link, "", false); err != nil || !removed {
		t.Fatalf("RemoveOwned = %v, %v; want the link removed", removed, err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}
	if fi, err := os.Lstat(link); err != nil || fi.Mode()&os.ModeSymlink == 0 {
		t.Fatalf("rollback did not restore the link: %v", err)
	}
	if got, err := os.ReadFile(link); err != nil || string(got) != body {
		t.Errorf("restored link reads %q, %v", got, err)
	}
}

func TestTransaction_RemoveLinkLeavesRegularFile(t *testing.T) {
	t.Parallel()
	path := filepath.Join(t.TempDir(), "SKILL.md")
	writeTestFile(t, path, "<!-- Generated by agnostic-ai -->\nbody\n")
	sess := NewSession()
	sess.StartTransaction()

	if removed, err := sess.RemoveLink(path, false); err != nil || removed {
		t.Fatalf("RemoveLink = %v, %v; want the file left alone", removed, err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}
	if _, err := os.Stat(path); err != nil {
		t.Errorf("regular file lost: %v", err)
	}
}

func TestTransaction_RollbackNoOpsWithoutStart(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	if err := sess.Rollback(); err != nil {
		t.Errorf("rollback with no transaction should be a no-op, got %v", err)
	}
}

func TestTransaction_CommitClearsLog(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	path := filepath.Join(dir, "file.md")

	sess.StartTransaction()
	if err := sess.WriteFile(path, "v1", false); err != nil {
		t.Fatal(err)
	}
	sess.Commit()

	// Second rollback should be a no-op (log was cleared by Commit).
	if err := sess.Rollback(); err != nil {
		t.Errorf("rollback after commit should be no-op, got %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "v1\n" {
		t.Errorf("file should still hold v1 after stale rollback (normalized newline), got %q", got)
	}
}

func TestTransaction_RollbackWithDetailedRecordingMode(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	existing := filepath.Join(dir, "existing.md")
	brand := filepath.Join(dir, "brand-new.md")
	if err := os.WriteFile(existing, []byte("before"), 0o644); err != nil {
		t.Fatal(err)
	}

	sess.StartDetailedRecording()
	sess.StartTransaction()
	if err := sess.WriteFile(existing, "after", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.WriteFile(brand, "fresh", false); err != nil {
		t.Fatal(err)
	}
	sess.StopDetailedRecording()
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}

	got, err := os.ReadFile(existing)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "before" {
		t.Errorf("expected before after rollback in detailing mode, got %q", got)
	}
	if _, err := os.Stat(brand); !os.IsNotExist(err) {
		t.Errorf("expected brand-new.md removed, stat err=%v", err)
	}
}
