package emit

import (
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestTransaction_RollbackRestoresOverwrittenFile(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	path := filepath.Join(dir, "CLAUDE.md")
	if err := os.WriteFile(path, []byte("original"), 0o644); err != nil {
		t.Fatal(err)
	}

	sess.StartTransaction()
	if err := sess.WriteFile(path, "modified", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "original" {
		t.Errorf("expected original content after rollback, got %q", got)
	}
}

func TestTransaction_RollbackRestoresExecutableMode(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Windows does not support Unix executable mode bits")
	}
	t.Parallel()
	sess := NewSession()
	path := filepath.Join(t.TempDir(), "setup")
	if err := os.WriteFile(path, []byte("#!/bin/sh\n"), 0o755); err != nil {
		t.Fatal(err)
	}

	sess.StartTransaction()
	if err := sess.WriteFile(path, "replacement", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o755 {
		t.Errorf("mode = %o, want 755", info.Mode().Perm())
	}
}

func TestTransaction_RollbackDeletesNewFile(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	path := filepath.Join(dir, "newfile.md")

	sess.StartTransaction()
	if err := sess.WriteFile(path, "created", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}

	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Errorf("expected file to be removed after rollback, stat err=%v", err)
	}
}

func TestTransaction_CommitPreservesWrites(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	path := filepath.Join(dir, "CLAUDE.md")
	if err := os.WriteFile(path, []byte("old"), 0o644); err != nil {
		t.Fatal(err)
	}

	sess.StartTransaction()
	if err := sess.WriteFile(path, "new", false); err != nil {
		t.Fatal(err)
	}
	sess.Commit()

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "new\n" {
		t.Errorf("expected new content after commit (normalized newline), got %q", got)
	}
}

func TestTransaction_RollbackMultipleFilesInReverseOrder(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	fileA := filepath.Join(dir, "a.md")
	fileB := filepath.Join(dir, "b.md")
	if err := os.WriteFile(fileA, []byte("a-old"), 0o644); err != nil {
		t.Fatal(err)
	}

	sess.StartTransaction()
	if err := sess.WriteFile(fileA, "a-new", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.WriteFile(fileB, "b-created", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}

	gotA, err := os.ReadFile(fileA)
	if err != nil {
		t.Fatal(err)
	}
	if string(gotA) != "a-old" {
		t.Errorf("expected a-old after rollback, got %q", gotA)
	}
	if _, err := os.Stat(fileB); !os.IsNotExist(err) {
		t.Errorf("expected fileB removed after rollback, stat err=%v", err)
	}
}

func TestTransaction_RollbackRestoresFileInPrunedFolder(t *testing.T) {
	t.Parallel()
	dir := filepath.Join(t.TempDir(), ".codex", "skills")
	path := filepath.Join(dir, "gone", "SKILL.md")
	const body = "<!-- Generated by agnostic-ai -->\nold\n"
	writeTestFile(t, path, body)
	sess := NewSession()
	sess.StartTransaction()

	if err := sess.RemoveGeneratedTree(dir, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(dir); !os.IsNotExist(err) {
		t.Fatalf("sweep kept the emptied tree: %v", err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}
	if got, err := os.ReadFile(path); err != nil || string(got) != body {
		t.Errorf("rollback did not restore file: %q, %v", got, err)
	}
}

func TestTransaction_RollbackRestoresRemovedLinkAsLink(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	const body = "<!-- Generated by agnostic-ai -->\nbody\n"
	writeTestFile(t, filepath.Join(dir, "AGENTS.md"), body)
	link := filepath.Join(dir, "AGENT.md")
	if err := os.Symlink("AGENTS.md", link); err != nil {
		t.Skipf("symlinks unsupported: %v", err)
	}
	sess := NewSession()
	sess.StartTransaction()

	if removed, err := sess.RemoveOwned(link, "", false); err != nil || !removed {
		t.Fatalf("RemoveOwned = %v, %v; want the link removed", removed, err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}
	if fi, err := os.Lstat(link); err != nil || fi.Mode()&os.ModeSymlink == 0 {
		t.Fatalf("rollback did not restore the link: %v", err)
	}
	if got, err := os.ReadFile(link); err != nil || string(got) != body {
		t.Errorf("restored link reads %q, %v", got, err)
	}
}

// Windows fixes a link's file or directory type when it creates the
// link, so a swept link comes back after the folder it points at.
func TestTransaction_RollbackRestoresLinkToPrunedFolderAsDirectory(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	canonical := filepath.Join(dir, ".agents")
	const body = "<!-- Generated by agnostic-ai -->\nbody\n"
	writeTestFile(t, filepath.Join(canonical, "skills", "gone", "SKILL.md"), body)
	link := filepath.Join(dir, ".cursor", "skills", "gone")
	if err := os.MkdirAll(filepath.Dir(link), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join("..", "..", ".agents", "skills", "gone"), link); err != nil {
		t.Skipf("symlinks unsupported: %v", err)
	}
	sess := NewSession()
	sess.StartTransaction()

	if err := sess.RemoveGeneratedTree(canonical, false); err != nil {
		t.Fatal(err)
	}
	if removed, err := sess.RemoveLink(link, false); err != nil || !removed {
		t.Fatalf("RemoveLink = %v, %v; want the link removed", removed, err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}
	if fi, err := os.Stat(link); err != nil || !fi.IsDir() {
		t.Fatalf("restored link does not resolve to a directory: %v", err)
	}
	if got, err := os.ReadFile(filepath.Join(link, "SKILL.md")); err != nil || string(got) != body {
		t.Errorf("restored link does not reach the canonical folder: %q, %v", got, err)
	}
}

// Unix restores a link the same way whatever its target holds, so two
// blocked restores show the order in the errors Rollback joins.
func TestTransaction_RollbackRestoresLinksAfterFiles(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	folder := filepath.Join(dir, "canonical")
	file := filepath.Join(folder, "SKILL.md")
	writeTestFile(t, file, "<!-- Generated by agnostic-ai -->\nbody\n")
	link := filepath.Join(dir, "link")
	if err := os.Symlink("canonical", link); err != nil {
		t.Skipf("symlinks unsupported: %v", err)
	}
	sess := NewSession()
	sess.StartTransaction()

	if err := sess.RemoveGeneratedTree(folder, false); err != nil {
		t.Fatal(err)
	}
	if removed, err := sess.RemoveLink(link, false); err != nil || !removed {
		t.Fatalf("RemoveLink = %v, %v; want the link removed", removed, err)
	}
	writeTestFile(t, folder, "blocks the folder\n")
	writeTestFile(t, link, "blocks the link\n")

	err := sess.Rollback()
	var joined interface{ Unwrap() []error }
	if !errors.As(err, &joined) || len(joined.Unwrap()) != 2 {
		t.Fatalf("rollback = %v; want both restores to fail", err)
	}
	if first := joined.Unwrap()[0].Error(); !strings.Contains(first, file) {
		t.Errorf("rollback restored the link before the file it points into:\n%v", err)
	}
}

// A write that went through a link needs the link back before its bytes.
func TestTransaction_RollbackRestoresLinkBeforeWriteThroughIt(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	file := filepath.Join(dir, "canonical", "SKILL.md")
	writeTestFile(t, file, "old\n")
	link := filepath.Join(dir, "link")
	if err := os.Symlink("canonical", link); err != nil {
		t.Skipf("symlinks unsupported: %v", err)
	}
	sess := NewSession()
	sess.StartTransaction()

	if err := sess.WriteFile(filepath.Join(link, "SKILL.md"), "new", false); err != nil {
		t.Fatal(err)
	}
	if removed, err := sess.RemoveLink(link, false); err != nil || !removed {
		t.Fatalf("RemoveLink = %v, %v; want the link removed", removed, err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}
	if fi, err := os.Lstat(link); err != nil || fi.Mode()&os.ModeSymlink == 0 {
		t.Fatalf("rollback did not restore the link: %v", err)
	}
	if got, err := os.ReadFile(file); err != nil || string(got) != "old\n" {
		t.Errorf("rollback did not restore the file written through the link: %q, %v", got, err)
	}
}

// A write logged inside a folder before it became a link must be undone
// in the folder, never through the link into the files it points at.
func TestTransaction_RollbackPutsBackFolderReplacedWithLink(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "canonical", "SKILL.md"), "body\n")
	probe := filepath.Join(dir, "probe")
	if err := os.Symlink("canonical", probe); err != nil {
		t.Skipf("symlinks unsupported: %v", err)
	}
	folder := filepath.Join(dir, "copy")
	writeTestFile(t, filepath.Join(folder, "references", "a.md"), "kept\n")
	sess := NewSession()
	sess.StartTransaction()
	if err := sess.WriteFile(filepath.Join(folder, "SKILL.md"), "body", false); err != nil {
		t.Fatal(err)
	}

	err := sess.ReplaceFolderWithLink(folder, func() error {
		if err := os.RemoveAll(folder); err != nil {
			return err
		}
		return os.Symlink("canonical", folder)
	})
	if err != nil {
		t.Fatal(err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}

	if got, err := os.ReadFile(filepath.Join(dir, "canonical", "SKILL.md")); err != nil || string(got) != "body\n" {
		t.Errorf("canonical file = %q, %v", got, err)
	}
	if fi, err := os.Lstat(folder); err != nil || !fi.IsDir() {
		t.Fatalf("folder not put back: %v", err)
	}
	if _, err := os.Lstat(filepath.Join(folder, "SKILL.md")); !os.IsNotExist(err) {
		t.Errorf("write logged before the swap not undone: %v", err)
	}
	if got, err := os.ReadFile(filepath.Join(folder, "references", "a.md")); err != nil || string(got) != "kept\n" {
		t.Errorf("file the session never wrote = %q, %v", got, err)
	}
}

func TestTransaction_RollbackRestoresLinkOverLinkLeftInItsPlace(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "old", "SKILL.md"), "old\n")
	writeTestFile(t, filepath.Join(dir, "new", "SKILL.md"), "new\n")
	link := filepath.Join(dir, "link")
	if err := os.Symlink("old", link); err != nil {
		t.Skipf("symlinks unsupported: %v", err)
	}
	sess := NewSession()
	sess.StartTransaction()
	if removed, err := sess.RemoveLink(link, false); err != nil || !removed {
		t.Fatalf("RemoveLink = %v, %v; want the link removed", removed, err)
	}
	if err := os.Symlink("new", link); err != nil {
		t.Fatal(err)
	}

	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}
	if got, err := os.Readlink(link); err != nil || got != "old" {
		t.Errorf("link = %q, %v; want old", got, err)
	}
	if got, err := os.ReadFile(filepath.Join(dir, "new", "SKILL.md")); err != nil || string(got) != "new\n" {
		t.Errorf("folder behind the replaced link = %q, %v", got, err)
	}
}

func TestTransaction_RemoveLinkLeavesRegularFile(t *testing.T) {
	t.Parallel()
	path := filepath.Join(t.TempDir(), "SKILL.md")
	writeTestFile(t, path, "<!-- Generated by agnostic-ai -->\nbody\n")
	sess := NewSession()
	sess.StartTransaction()

	if removed, err := sess.RemoveLink(path, false); err != nil || removed {
		t.Fatalf("RemoveLink = %v, %v; want the file left alone", removed, err)
	}
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}
	if _, err := os.Stat(path); err != nil {
		t.Errorf("regular file lost: %v", err)
	}
}

func TestTransaction_RollbackNoOpsWithoutStart(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	if err := sess.Rollback(); err != nil {
		t.Errorf("rollback with no transaction should be a no-op, got %v", err)
	}
}

func TestTransaction_CommitClearsLog(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	path := filepath.Join(dir, "file.md")

	sess.StartTransaction()
	if err := sess.WriteFile(path, "v1", false); err != nil {
		t.Fatal(err)
	}
	sess.Commit()

	// Second rollback should be a no-op (log was cleared by Commit).
	if err := sess.Rollback(); err != nil {
		t.Errorf("rollback after commit should be no-op, got %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "v1\n" {
		t.Errorf("file should still hold v1 after stale rollback (normalized newline), got %q", got)
	}
}

func TestTransaction_RollbackWithDetailedRecordingMode(t *testing.T) {
	t.Parallel()
	sess := NewSession()
	dir := t.TempDir()
	existing := filepath.Join(dir, "existing.md")
	brand := filepath.Join(dir, "brand-new.md")
	if err := os.WriteFile(existing, []byte("before"), 0o644); err != nil {
		t.Fatal(err)
	}

	sess.StartDetailedRecording()
	sess.StartTransaction()
	if err := sess.WriteFile(existing, "after", false); err != nil {
		t.Fatal(err)
	}
	if err := sess.WriteFile(brand, "fresh", false); err != nil {
		t.Fatal(err)
	}
	sess.StopDetailedRecording()
	if err := sess.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}

	got, err := os.ReadFile(existing)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "before" {
		t.Errorf("expected before after rollback in detailing mode, got %q", got)
	}
	if _, err := os.Stat(brand); !os.IsNotExist(err) {
		t.Errorf("expected brand-new.md removed, stat err=%v", err)
	}
}
