// Package goose emits configs for Block's Goose CLI.
//
// Goose reads project instructions from the root `AGENTS.md` file,
// written centrally by `sync` as a slim pointer to the source specs
// with rule bodies inlined by default (one body shared with every
// other AGENTS.md-family target). Goose also reads a second, older
// file, `.goosehints`: a single concatenated document of project
// hints. This adapter writes that document only when the user opts in
// via `outputs.goose.rules-file`, so a fresh `init` followed by `sync`
// never surprises a project with an extra root file.
//
// goose-docs.ai/docs/guides/context-engineering/using-goosehints/
// documents nested discovery: "As goose reads or modifies files in
// nested subdirectories, it can also discover and load additional hint
// files from those directories automatically", checking each directory
// for one of `CONTEXT_FILE_NAMES` (default `AGENTS.md`, `.goosehints`).
// A rule carrying a source-layout or frontmatter scope (e.g.
// `backend/`) therefore routes into a nested `<scope>/.goosehints`
// instead of flattening into the root document (#608): once the
// rules-file opt-in is set, every rule still routes through it, scoped
// or not, so the gate stays a single on/off switch rather than an
// inconsistent one for the root file only.
//
// `.goosehints` reuses the same generic legacy-rules-file mechanism the
// zed, aider, warp, and antigravity adapters use for their own opt-in
// merged documents (`Session.EmitLegacyRulesFile`) for the root
// document; there is no dedicated `hints-file` config key. Only rule
// bodies go into the document: Goose has no per-agent or per-skill file
// surface, so caps.Supports declares KindRule only.
package goose

import (
	"path/filepath"
	"sort"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

const target = "goose"

var caps = emit.Capabilities{
	Target:   target,
	Supports: []spec.Kind{spec.KindRule},
}

// Adapter emits Goose configs.
type Adapter struct{}

// New returns a Goose adapter.
func New() *Adapter { return &Adapter{} }

// Name returns the target identifier.
func (Adapter) Name() string { return target }

// Emit writes the legacy concatenated `.goosehints`-style document only
// when `outputs.goose.rules-file` is set, scoped to rules so an agent
// or skill spec targeted at goose (which has no native surface for
// either) never leaks into the document. Root-scoped rules concatenate
// into that path unchanged; a rule carrying a source-layout or
// frontmatter scope concatenates into a sibling `<scope>/<basename>`
// file instead, matching Goose's own nested-discovery mechanism (see
// the package doc). The root AGENTS.md entry-point (with rule bodies
// inlined) is written centrally by `sync`, not here.
func (Adapter) Emit(sess *emit.Session, b spec.Bundle, cfg *config.Config, dryRun bool) error {
	if err := emit.ReportUnsupported(caps, b, cfg.OnUnsupported); err != nil {
		return err
	}
	root, scoped := splitRulesByScope(b.Rules)
	if err := sess.EmitLegacyRulesFile(spec.Bundle{Rules: root}, cfg, target, emit.MergedOpts{
		Title: "Project rules",
	}, dryRun); err != nil {
		return err
	}
	return emitScopedRulesFiles(sess, scoped, cfg, dryRun)
}

// splitRulesByScope buckets rules into root-scoped (EffectiveScope() ==
// "") and a map keyed by every other scope, each preserving the rules'
// original relative order.
func splitRulesByScope(rules []spec.Entry) (root []spec.Entry, scoped map[string][]spec.Entry) {
	scoped = map[string][]spec.Entry{}
	for _, r := range rules {
		if s := r.EffectiveScope(); s != "" {
			scoped[s] = append(scoped[s], r)
			continue
		}
		root = append(root, r)
	}
	return root, scoped
}

// emitScopedRulesFiles writes one merged `.goosehints`-style document
// per non-root scope, into `<scope>/<basename>` where `<basename>` is
// the last path element of the configured (or default) rules-file, so
// a custom `outputs.goose.rules-file` still nests under the same name
// Goose looks for automatically. No-op when the rules-file opt-in is
// unset, so a scoped rule produces no output until the same opt-in
// EmitLegacyRulesFile itself requires for the root document (#608): the
// gate stays one on/off switch, not two.
func emitScopedRulesFiles(sess *emit.Session, byScope map[string][]spec.Entry, cfg *config.Config, dryRun bool) error {
	rulesFile := emit.OutputRulesFile(cfg, target, "")
	if rulesFile == "" || len(byScope) == 0 {
		return nil
	}
	base := filepath.Base(rulesFile)
	for _, scope := range sortedScopeKeys(byScope) {
		opts := emit.MergedOpts{
			OutFile: filepath.Join(scope, base),
			Title:   "Project rules",
			Intro:   "Generated by agnostic-ai.",
		}
		if err := sess.MergedDocument(spec.Bundle{Rules: byScope[scope]}, opts, dryRun); err != nil {
			return err
		}
	}
	return nil
}

// sortedScopeKeys returns byScope's keys sorted for stable output order
// across runs.
func sortedScopeKeys(byScope map[string][]spec.Entry) []string {
	out := make([]string, 0, len(byScope))
	for k := range byScope {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
