// Generated by agnostic-ai. Do not edit this file directly; edit specs under .agnostic-ai/ and run `agnostic-ai sync`.
import type { Plugin } from "@kilocode/plugin"

const NeutralHookPlugin: Plugin = async ({ $ }) => {
  const run = async (cmd: string) => {
    try {
      const r = await $`${{ raw: cmd }}`.env({ ...process.env, AGNOSTIC_AI_TARGET: "kilo" }).nothrow()
      if (r.exitCode !== 0) console.error("agnostic-ai hook neutral-hook:", cmd, "exited", r.exitCode)
      return r
    } catch (err) {
      console.error("agnostic-ai hook neutral-hook:", cmd, err)
      return undefined
    }
  }

  return {
    "tool.execute.before": async () => {
      const r1 = await run(".kilo/hooks/shared-guard.sh")
      if (r1?.exitCode === 2) throw new Error(r1.stderr.toString() || "blocked by hook neutral-hook")
    },
  }
}

export default { id: "neutral-hook", server: NeutralHookPlugin }
