// Generated by agnostic-ai. Do not edit this file directly; edit specs under .agnostic-ai/ and run `agnostic-ai sync`.
import type { Plugin } from "@kilocode/plugin"

const SampleHookPlugin: Plugin = async ({ $ }) => {
  return {
    "tool.execute.after": async (input) => {
      if (!new RegExp("Edit").test(input.tool)) return
      await $`echo edited`
    },
  }
}

export default { id: "sample-hook", server: SampleHookPlugin }
