package gemini

import (
	"fmt"
	"os"
	"strings"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

type Adapter struct{}

func New() *Adapter { return &Adapter{} }

func (a *Adapter) Name() string { return "gemini" }

func (a *Adapter) Emit(entries []spec.Entry, cfg *config.Config, dryRun bool) error {
	var b strings.Builder
	b.WriteString("# GEMINI.md\n\nGenerated by agnostic-ai.\n\n")

	for _, r := range spec.Filter(entries, spec.KindRule) {
		b.WriteString("## " + r.Name + "\n\n" + r.Body + "\n\n")
	}
	for _, ag := range spec.Filter(entries, spec.KindAgent) {
		b.WriteString("## Agent: " + ag.Name + "\n\n" + ag.Body + "\n\n")
	}

	if len(spec.Filter(entries, spec.KindHook)) > 0 {
		fmt.Fprintln(os.Stderr, "  ! gemini: hooks not supported, skipped")
	}

	out := "GEMINI.md"
	if o, ok := cfg.Outputs["gemini"]; ok && o.File != "" {
		out = o.File
	}
	return emit.WriteFile(out, b.String(), dryRun)
}
