package warp

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestName(t *testing.T) {
	if got := New().Name(); got != "warp" {
		t.Errorf("Name() = %q, want %q", got, "warp")
	}
}

// Default emission writes AGENTS.md, replacing the legacy WARP.md filename.
func TestEmit_WritesAGENTSMd_NotWarpMd(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Path: "rules/r1.md", Body: "rule body"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, "AGENTS.md"))
	for _, want := range []string{"# AGENTS.md", "rule body", "<!-- source: rules/r1.md -->"} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "WARP.md")); !os.IsNotExist(err) {
		t.Errorf("legacy WARP.md should not be written, err=%v", err)
	}
}

func TestEmit_ScopedRule_RoutesToNestedAGENTSMd(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "auth", Scope: "backend", Body: "Validate at boundary."},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	nested := readFile(t, filepath.Join(dir, "backend/AGENTS.md"))
	if !strings.Contains(nested, "Validate at boundary.") {
		t.Errorf("missing scoped body: %s", nested)
	}
	if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("no root AGENTS.md when only scoped rules exist, err=%v", err)
	}
}

// Warp has no separate slash-command surface, so agents inline their
// bodies into the root AGENTS.md.
func TestEmit_Agent_InlinedIntoRootAGENTSMd(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent,
			Name: "pr-reviewer",
			Meta: map[string]any{"description": "Review PRs."},
			Body: "Open the PR. Read it. Comment.",
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	agents := readFile(t, filepath.Join(dir, "AGENTS.md"))
	for _, want := range []string{
		"## Agents",
		"Agent: pr-reviewer",
		"Review PRs.",
		"Open the PR. Read it. Comment.",
	} {
		if !strings.Contains(agents, want) {
			t.Errorf("missing %q in %s", want, agents)
		}
	}
}

// Skills appear as reference listings (description + source path) since
// Warp has no skill-execution model. Bodies are NOT inlined to keep the
// document scannable; users open the source spec to read the skill.
func TestEmit_Skill_ReferenceOnly(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindSkill,
			Name: "yaml-validator",
			Path: "skills/yaml-validator.md",
			Meta: map[string]any{"description": "Validate YAML."},
			Body: "Body content - should NOT inline.",
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	agents := readFile(t, filepath.Join(dir, "AGENTS.md"))
	for _, want := range []string{"## Skills", "yaml-validator", "Validate YAML.", "skills/yaml-validator.md"} {
		if !strings.Contains(agents, want) {
			t.Errorf("missing %q in %s", want, agents)
		}
	}
	if strings.Contains(agents, "should NOT inline") {
		t.Errorf("skill body should not be inlined: %s", agents)
	}
}

// A previously generated WARP.md is migrated to WARP.md.bak.
func TestEmit_MigratesLegacyWarpMd_WhenAgnosticGenerated(t *testing.T) {
	dir := testutil.TempCwd(t)

	legacy := "# WARP.md\n\nGenerated by agnostic-ai. Do not edit by hand.\n\nstale.\n"
	if err := os.WriteFile(filepath.Join(dir, "WARP.md"), []byte(legacy), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r", Body: "new rule"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "WARP.md")); !os.IsNotExist(err) {
		t.Errorf("legacy WARP.md should be removed, err=%v", err)
	}
	bak := readFile(t, filepath.Join(dir, "WARP.md.bak"))
	if !strings.Contains(bak, "stale.") {
		t.Errorf("backup should preserve old content: %s", bak)
	}
}

// A WARP.md without our provenance marker is user-authored and left alone.
func TestEmit_KeepsLegacyWarpMd_WhenUserAuthored(t *testing.T) {
	dir := testutil.TempCwd(t)

	userContent := "# WARP.md\n\nMy own notes.\n"
	if err := os.WriteFile(filepath.Join(dir, "WARP.md"), []byte(userContent), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r", Body: "new"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, "WARP.md"))
	if got != userContent {
		t.Errorf("user-authored WARP.md should be preserved verbatim: %q", got)
	}
	if _, err := os.Stat(filepath.Join(dir, "WARP.md.bak")); !os.IsNotExist(err) {
		t.Errorf("no backup should be made for user-authored file, err=%v", err)
	}
}

func TestEmit_FileOverride(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"warp": {File: "docs/AGENTS.md"},
		},
	}
	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "x"},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "docs/AGENTS.md")); err != nil {
		t.Errorf("expected docs/AGENTS.md: %v", err)
	}
}

// Stdio MCP entry emits to .warp/.mcp.json with the standard mcpServers schema.
func TestEmit_MCP_WritesStdioServer(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "fs",
			Meta: map[string]any{
				"command": "npx",
				"args":    []any{"-y", "@modelcontextprotocol/server-filesystem", "."},
				"env":     map[string]any{"ALLOWED_PATHS": "."},
			},
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".warp/.mcp.json"))
	for _, want := range []string{
		`"mcpServers"`,
		`"fs"`,
		`"command": "npx"`,
		`"ALLOWED_PATHS"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

func TestEmit_MCP_WritesHTTPServer(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "linear",
			Meta: map[string]any{
				"type":    "http",
				"url":     "https://mcp.linear.app",
				"headers": map[string]any{"Authorization": "Bearer x"},
			},
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".warp/.mcp.json"))
	for _, want := range []string{
		`"linear"`,
		`"url": "https://mcp.linear.app"`,
		`"Authorization"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

func TestEmit_MCP_FileOverride(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"warp": {MCPFile: "vendor/mcp.json"},
		},
	}
	entries := []spec.Entry{
		{Kind: spec.KindMCP, Name: "fs", Meta: map[string]any{"command": "x"}},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "vendor/mcp.json")); err != nil {
		t.Errorf("expected override path written: %v", err)
	}
}

func TestEmit_MCP_NoFileWhenNoEntries(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "x"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".warp/.mcp.json")); !os.IsNotExist(err) {
		t.Errorf("expected no MCP file when no entries, err=%v", err)
	}
}

func TestEmit_EmptyBundle_WritesNothing(t *testing.T) {
	dir := testutil.TempCwd(t)
	if err := New().Emit(spec.NewBundle(nil), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("expected no AGENTS.md for empty bundle, err=%v", err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}
