// Package warp emits configs for the Warp terminal AI.
//
// Warp's current Rules docs specify `AGENTS.md` (per the open AGENTS.md
// standard) plus optional subtree `AGENTS.md` files that scope rules to
// their directory. Previous releases of this adapter wrote `WARP.md`
// (the legacy name), which newer Warp versions no longer read.
//
// Warp has no separate slash-command surface, so agents inline their
// bodies into the root AGENTS.md and skills list as reference pointers
// to their source spec.
package warp

import (
	"bytes"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

const (
	target           = "warp"
	defaultOutFile   = "AGENTS.md"
	legacyOutFile    = "WARP.md"
	provenanceMarker = "Generated by agnostic-ai"
)

var caps = emit.Capabilities{
	Target:   target,
	Supports: []spec.Kind{spec.KindAgent, spec.KindSkill, spec.KindRule},
}

// Adapter emits Warp configs.
type Adapter struct{}

// New returns a Warp adapter.
func New() *Adapter { return &Adapter{} }

// Name returns the target identifier.
func (Adapter) Name() string { return target }

// Emit writes hierarchical AGENTS.md files and migrates any legacy
// agnostic-generated WARP.md to WARP.md.bak.
func (Adapter) Emit(b spec.Bundle, cfg *config.Config, dryRun bool) error {
	if err := emit.ReportUnsupported(caps, b, cfg.OnUnsupported); err != nil {
		return err
	}

	migrateLegacyWarpMd(cfg, dryRun)

	return emitAgentsTree(b, cfg, dryRun)
}

// emitAgentsTree writes one AGENTS.md per scope. Root document holds
// all rules at the root scope plus the agent (full bodies) and skill
// (reference) sections; scoped documents hold only their own rules.
func emitAgentsTree(b spec.Bundle, cfg *config.Config, dryRun bool) error {
	if len(b.Rules) == 0 && len(b.Agents) == 0 && len(b.Skills) == 0 {
		return nil
	}
	rootFile := emit.OutputFile(cfg, target, defaultOutFile)
	rootDir := filepath.Dir(rootFile)
	rootBase := filepath.Base(rootFile)

	byScope := emit.GroupRulesByScope(b.Rules)
	scopes := slices.Sorted(maps.Keys(byScope))
	if !slices.Contains(scopes, "") && (len(b.Agents) > 0 || len(b.Skills) > 0) {
		scopes = append([]string{""}, scopes...)
	}

	for _, scope := range scopes {
		var sb strings.Builder
		writeHeader(&sb, scope)
		writeRulesSection(&sb, byScope[scope])
		if scope == "" {
			writeAgentsSection(&sb, b.Agents)
			writeSkillsSection(&sb, b.Skills)
		}
		path := filepath.Join(rootDir, scope, rootBase)
		if err := emit.WriteFile(path, sb.String(), dryRun); err != nil {
			return err
		}
	}
	return nil
}

// migrateLegacyWarpMd moves a previously-generated WARP.md aside so
// the user notices the rename to AGENTS.md. Skipped during dry-run
// and capture mode so `sync --check` and `revert` do not mutate the
// working tree. User-authored WARP.md (no provenance marker) is left
// untouched.
func migrateLegacyWarpMd(cfg *config.Config, dryRun bool) {
	if dryRun || emit.IsCapturing() {
		return
	}
	legacyPath := legacyOutFile
	if root := filepath.Dir(emit.OutputFile(cfg, target, defaultOutFile)); root != "." && root != "" {
		legacyPath = filepath.Join(root, legacyOutFile)
	}
	data, err := os.ReadFile(legacyPath)
	if err != nil || !bytes.Contains(data, []byte(provenanceMarker)) {
		return
	}
	if err := os.Rename(legacyPath, legacyPath+".bak"); err != nil {
		return
	}
	_, _ = fmt.Fprintf(emit.Warner, "warp: renamed legacy %s to %s.bak; new layout writes AGENTS.md\n", legacyPath, legacyPath)
}

func writeHeader(sb *strings.Builder, scope string) {
	if scope == "" {
		sb.WriteString("# AGENTS.md\n\n")
	} else {
		sb.WriteString("# AGENTS.md (" + scope + ")\n\n")
		sb.WriteString("Scoped to `" + scope + "/**`. Inherits root rules.\n\n")
	}
	sb.WriteString("Generated by agnostic-ai. Do not edit by hand.\n\n")
}

func writeRulesSection(sb *strings.Builder, rules []spec.Entry) {
	if len(rules) == 0 {
		return
	}
	sb.WriteString("## Rules\n\n")
	for _, r := range rules {
		emit.WriteSection(sb, r.Name, r)
	}
}

// writeAgentsSection inlines each agent body (Warp has no separate
// command surface to point at).
func writeAgentsSection(sb *strings.Builder, agents []spec.Entry) {
	if len(agents) == 0 {
		return
	}
	sb.WriteString("## Agents\n\n")
	for _, a := range agents {
		emit.WriteSection(sb, "Agent: "+a.Name, a)
	}
}

// writeSkillsSection lists skills as reference pointers (no execution
// model in Warp) so the file stays scannable.
func writeSkillsSection(sb *strings.Builder, skills []spec.Entry) {
	if len(skills) == 0 {
		return
	}
	sb.WriteString("## Skills\n\n")
	sb.WriteString("Reference material. Read the source file to use a skill.\n\n")
	for _, s := range skills {
		emit.WriteReference(sb, s, s.Path)
	}
}
