package warp

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestName(t *testing.T) {
	if got := New().Name(); got != "warp" {
		t.Errorf("Name() = %q, want %q", got, "warp")
	}
}

// Default emission no longer writes AGENTS.md; sync owns the entry-point
// write so codex + amp + warp can coexist at the same path. Legacy
// WARP.md is never written.
func TestEmit_NoRootAGENTSMd_ByDefault(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Path: "rules/r1.md", Body: "rule body"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("adapter should not write AGENTS.md by default, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "WARP.md")); !os.IsNotExist(err) {
		t.Errorf("legacy WARP.md should not be written, err=%v", err)
	}
}

func TestEmit_LegacyRulesFile_WritesConcatenated(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"warp": {RulesFile: "AGENTS.md"}},
	}
	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Path: "rules/r1.md", Body: "rule body"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, "AGENTS.md"))
	if !strings.Contains(got, "rule body") {
		t.Errorf("legacy rules-file should contain concatenated rule body:\n%s", got)
	}
}

// A previously generated WARP.md is migrated to WARP.md.bak.
func TestEmit_MigratesLegacyWarpMd_WhenAgnosticGenerated(t *testing.T) {
	dir := testutil.TempCwd(t)

	legacy := "# WARP.md\n\nGenerated by agnostic-ai. Do not edit by hand.\n\nstale.\n"
	if err := os.WriteFile(filepath.Join(dir, "WARP.md"), []byte(legacy), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r", Body: "new rule"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "WARP.md")); !os.IsNotExist(err) {
		t.Errorf("legacy WARP.md should be removed, err=%v", err)
	}
	bak := readFile(t, filepath.Join(dir, "WARP.md.bak"))
	if !strings.Contains(bak, "stale.") {
		t.Errorf("backup should preserve old content: %s", bak)
	}
}

// A WARP.md without our provenance marker is user-authored and left alone.
func TestEmit_KeepsLegacyWarpMd_WhenUserAuthored(t *testing.T) {
	dir := testutil.TempCwd(t)

	userContent := "# WARP.md\n\nMy own notes.\n"
	if err := os.WriteFile(filepath.Join(dir, "WARP.md"), []byte(userContent), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r", Body: "new"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, "WARP.md"))
	if got != userContent {
		t.Errorf("user-authored WARP.md should be preserved verbatim: %q", got)
	}
	if _, err := os.Stat(filepath.Join(dir, "WARP.md.bak")); !os.IsNotExist(err) {
		t.Errorf("no backup should be made for user-authored file, err=%v", err)
	}
}

// Stdio MCP entry emits to .warp/.mcp.json with the standard mcpServers schema.
func TestEmit_MCP_WritesStdioServer(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "fs",
			Meta: map[string]any{
				"command": "npx",
				"args":    []any{"-y", "@modelcontextprotocol/server-filesystem", "."},
				"env":     map[string]any{"ALLOWED_PATHS": "."},
			},
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".warp/.mcp.json"))
	for _, want := range []string{
		`"mcpServers"`,
		`"fs"`,
		`"command": "npx"`,
		`"ALLOWED_PATHS"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

func TestEmit_MCP_WritesHTTPServer(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "linear",
			Meta: map[string]any{
				"type":    "http",
				"url":     "https://mcp.linear.app",
				"headers": map[string]any{"Authorization": "Bearer x"},
			},
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".warp/.mcp.json"))
	for _, want := range []string{
		`"linear"`,
		`"url": "https://mcp.linear.app"`,
		`"Authorization"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

func TestEmit_MCP_FileOverride(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"warp": {MCPFile: "vendor/mcp.json"},
		},
	}
	entries := []spec.Entry{
		{Kind: spec.KindMCP, Name: "fs", Meta: map[string]any{"command": "x"}},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "vendor/mcp.json")); err != nil {
		t.Errorf("expected override path written: %v", err)
	}
}

func TestEmit_MCP_NoFileWhenNoEntries(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "x"},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".warp/.mcp.json")); !os.IsNotExist(err) {
		t.Errorf("expected no MCP file when no entries, err=%v", err)
	}
}

func TestEmit_EmptyBundle_WritesNothing(t *testing.T) {
	dir := testutil.TempCwd(t)
	if err := New().Emit(emit.NewSession(), spec.NewBundle(nil), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("expected no AGENTS.md for empty bundle, err=%v", err)
	}
}

func TestEmit_WorkflowsDirEmitsAgentsAsWorkflows(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent,
			Name: "deploy",
			Path: "agents/deploy.md",
			Meta: map[string]any{
				"description": "Run the deploy script.",
				"tags":        []any{"release", "ops"},
			},
			Body: "./scripts/deploy.sh prod",
		},
	}
	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"warp": {WorkflowsDir: ".warp/workflows"},
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}

	wf := readFile(t, filepath.Join(dir, ".warp/workflows/deploy.yaml"))
	for _, want := range []string{
		"name: deploy",
		"command:",
		"./scripts/deploy.sh prod",
		"description: Run the deploy script.",
		"tags:",
		"- release",
		"- ops",
	} {
		if !strings.Contains(wf, want) {
			t.Errorf("missing %q in %s", want, wf)
		}
	}
}

// docs.warp.dev/terminal/entry/yaml-workflows documents optional
// `shells`, `arguments`, `source_url`, `author`, `author_url`. None of
// them are cross-tool spec fields, so they pass through under `x-warp`,
// the pattern opencode.go:195 already uses. See #538.
func TestEmit_WorkflowsDirEmitsXWarpFields(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent,
			Name: "deploy",
			Path: "agents/deploy.md",
			Meta: map[string]any{
				"description": "Run the deploy script.",
				"x-warp": map[string]any{
					"shells":     []any{"zsh", "bash"},
					"source_url": "https://example.com/deploy",
					"author":     "chema",
					"author_url": "https://github.com/chema",
					"arguments": []any{
						map[string]any{"name": "branch", "description": "target branch", "default_value": "main"},
					},
				},
			},
			Body: "./scripts/deploy.sh {{branch}}",
		},
	}
	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"warp": {WorkflowsDir: ".warp/workflows"},
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}

	wf := readFile(t, filepath.Join(dir, ".warp/workflows/deploy.yaml"))
	for _, want := range []string{
		"shells:",
		"- zsh",
		"- bash",
		"source_url: https://example.com/deploy",
		"author: chema",
		"author_url: https://github.com/chema",
		"arguments:",
		"name: branch",
		"default_value: main",
	} {
		if !strings.Contains(wf, want) {
			t.Errorf("missing %q in %s", want, wf)
		}
	}
}

// Skills emit natively as one folder per skill under .agents/skills/,
// the project-local path Warp's own docs recommend
// (docs.warp.dev/agents/capabilities/skills). The renderer matches the
// codex/amp/zed output byte-for-byte so the shared tree dedupes. See #557.
func TestEmit_Skill_WritesNativeSkillFolder(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindSkill,
			Name: "deploy",
			Meta: map[string]any{"description": "Run deployments."},
			Body: "Deploy to production.",
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".agents/skills/deploy/SKILL.md"))
	for _, want := range []string{"name: deploy", "description: Run deployments.", "Deploy to production."} {
		if !strings.Contains(got, want) {
			t.Errorf("SKILL.md missing %q:\n%s", want, got)
		}
	}
}

func TestEmit_Skill_SkillsDirOverride(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"warp": {SkillsDir: "custom/skills"}},
	}
	entries := []spec.Entry{{Kind: spec.KindSkill, Name: "deploy", Body: "body"}}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "custom/skills/deploy/SKILL.md")); err != nil {
		t.Errorf("expected custom/skills/deploy/SKILL.md: %v", err)
	}
}

// A plain workflow with no x-warp block must not gain the block.
func TestEmit_WorkflowsDirNoXWarpBlockWhenUnset(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent,
			Name: "deploy",
			Path: "agents/deploy.md",
			Body: "./scripts/deploy.sh",
		},
	}
	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"warp": {WorkflowsDir: ".warp/workflows"},
		},
	}
	if err := New().Emit(emit.NewSession(), spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	wf := readFile(t, filepath.Join(dir, ".warp/workflows/deploy.yaml"))
	if strings.Contains(wf, "shells") || strings.Contains(wf, "author") {
		t.Errorf("unexpected x-warp fields with no x-warp block set:\n%s", wf)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}
