package warp

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestName(t *testing.T) {
	if got := New().Name(); got != "warp" {
		t.Errorf("Name() = %q, want %q", got, "warp")
	}
}

// Default emission no longer writes AGENTS.md; sync owns the entry-point
// write so codex + amp + warp can coexist at the same path. Legacy
// WARP.md is never written.
func TestEmit_NoRootAGENTSMd_ByDefault(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Path: "rules/r1.md", Body: "rule body"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("adapter should not write AGENTS.md by default, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "WARP.md")); !os.IsNotExist(err) {
		t.Errorf("legacy WARP.md should not be written, err=%v", err)
	}
}

func TestEmit_LegacyRulesFile_WritesConcatenated(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"warp": {RulesFile: "AGENTS.md"}},
	}
	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Path: "rules/r1.md", Body: "rule body"},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, "AGENTS.md"))
	if !strings.Contains(got, "rule body") {
		t.Errorf("legacy rules-file should contain concatenated rule body:\n%s", got)
	}
}

// A previously generated WARP.md is migrated to WARP.md.bak.
func TestEmit_MigratesLegacyWarpMd_WhenAgnosticGenerated(t *testing.T) {
	dir := testutil.TempCwd(t)

	legacy := "# WARP.md\n\nGenerated by agnostic-ai. Do not edit by hand.\n\nstale.\n"
	if err := os.WriteFile(filepath.Join(dir, "WARP.md"), []byte(legacy), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r", Body: "new rule"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "WARP.md")); !os.IsNotExist(err) {
		t.Errorf("legacy WARP.md should be removed, err=%v", err)
	}
	bak := readFile(t, filepath.Join(dir, "WARP.md.bak"))
	if !strings.Contains(bak, "stale.") {
		t.Errorf("backup should preserve old content: %s", bak)
	}
}

// A WARP.md without our provenance marker is user-authored and left alone.
func TestEmit_KeepsLegacyWarpMd_WhenUserAuthored(t *testing.T) {
	dir := testutil.TempCwd(t)

	userContent := "# WARP.md\n\nMy own notes.\n"
	if err := os.WriteFile(filepath.Join(dir, "WARP.md"), []byte(userContent), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r", Body: "new"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, "WARP.md"))
	if got != userContent {
		t.Errorf("user-authored WARP.md should be preserved verbatim: %q", got)
	}
	if _, err := os.Stat(filepath.Join(dir, "WARP.md.bak")); !os.IsNotExist(err) {
		t.Errorf("no backup should be made for user-authored file, err=%v", err)
	}
}

// Stdio MCP entry emits to .warp/.mcp.json with the standard mcpServers schema.
func TestEmit_MCP_WritesStdioServer(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "fs",
			Meta: map[string]any{
				"command": "npx",
				"args":    []any{"-y", "@modelcontextprotocol/server-filesystem", "."},
				"env":     map[string]any{"ALLOWED_PATHS": "."},
			},
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".warp/.mcp.json"))
	for _, want := range []string{
		`"mcpServers"`,
		`"fs"`,
		`"command": "npx"`,
		`"ALLOWED_PATHS"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

func TestEmit_MCP_WritesHTTPServer(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "linear",
			Meta: map[string]any{
				"type":    "http",
				"url":     "https://mcp.linear.app",
				"headers": map[string]any{"Authorization": "Bearer x"},
			},
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".warp/.mcp.json"))
	for _, want := range []string{
		`"linear"`,
		`"url": "https://mcp.linear.app"`,
		`"Authorization"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

func TestEmit_MCP_FileOverride(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"warp": {MCPFile: "vendor/mcp.json"},
		},
	}
	entries := []spec.Entry{
		{Kind: spec.KindMCP, Name: "fs", Meta: map[string]any{"command": "x"}},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "vendor/mcp.json")); err != nil {
		t.Errorf("expected override path written: %v", err)
	}
}

func TestEmit_MCP_NoFileWhenNoEntries(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "x"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".warp/.mcp.json")); !os.IsNotExist(err) {
		t.Errorf("expected no MCP file when no entries, err=%v", err)
	}
}

func TestEmit_EmptyBundle_WritesNothing(t *testing.T) {
	dir := testutil.TempCwd(t)
	if err := New().Emit(spec.NewBundle(nil), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("expected no AGENTS.md for empty bundle, err=%v", err)
	}
}

func TestEmit_WorkflowsDirEmitsAgentsAsWorkflows(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent,
			Name: "deploy",
			Path: "agents/deploy.md",
			Meta: map[string]any{
				"description": "Run the deploy script.",
				"tags":        []any{"release", "ops"},
			},
			Body: "./scripts/deploy.sh prod",
		},
	}
	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"warp": {WorkflowsDir: ".warp/workflows"},
		},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}

	wf := readFile(t, filepath.Join(dir, ".warp/workflows/deploy.yaml"))
	for _, want := range []string{
		"name: deploy",
		"command:",
		"./scripts/deploy.sh prod",
		"description: Run the deploy script.",
		"tags:",
		"- release",
		"- ops",
	} {
		if !strings.Contains(wf, want) {
			t.Errorf("missing %q in %s", want, wf)
		}
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}
