package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"gopkg.in/yaml.v3"

	"github.com/chemaclass/agnostic-ai/internal/errs"
)

// File names recognized by Load.
const (
	ConfigFileName        = "agnostic-ai.yaml"
	LegacyConfigFileName  = "agnostic.config.yaml"
	LocalOverrideFileName = "agnostic-ai.local.yaml"
)

type Config struct {
	Version       int               `yaml:"version"                  json:"version"`
	Sources       Sources           `yaml:"sources,omitempty"        json:"sources,omitempty"`
	Targets       []string          `yaml:"targets,omitempty"        json:"targets,omitempty"`
	Outputs       map[string]Output `yaml:"outputs,omitempty"        json:"outputs,omitempty"`
	OnUnsupported string            `yaml:"on-unsupported,omitempty" json:"on-unsupported,omitempty"`
	Gitignore     Gitignore         `yaml:"gitignore,omitempty"      json:"gitignore,omitempty"`
	Sync          SyncConfig        `yaml:"sync,omitempty"           json:"sync,omitempty"`
	Import        ImportConfig      `yaml:"import,omitempty"         json:"import,omitempty"`
}

// ImportConfig holds per-source knobs for the `import` command. Empty
// values fall back to per-source defaults documented under each substruct.
type ImportConfig struct {
	Codex ImportCodex `yaml:"codex,omitempty" json:"codex,omitempty"`
}

// ImportCodex tunes `agnostic-ai import codex`.
type ImportCodex struct {
	// Shred toggles AGENTS.md H2 sharding. Nil or true keeps the default
	// behavior (one rule spec per ## heading). False keeps each AGENTS.md
	// as a single rule spec, useful when codex AGENTS.md duplicates policy
	// already authored as standalone rules.
	Shred *bool `yaml:"shred,omitempty" json:"shred,omitempty"`
}

// SyncConfig holds declarative knobs for the sync command. Settings here
// are applied globally; per-target overrides live in outputs.<target>.
type SyncConfig struct {
	// CollisionPolicy controls what happens when two enabled targets would
	// emit to the same output path. Accepted values:
	//   prompt      (default) error with a resolution hint; refuses non-interactive stdin
	//   prefer-spec skip the collision pre-flight; let the last adapter win
	//   fail        hard error with no resolution hint
	CollisionPolicy string `yaml:"collision-policy,omitempty" json:"collision-policy,omitempty"`
}

// ProvenanceHeaderEnabled returns whether the named target should write
// the `<!-- Generated by agnostic-ai -->` (or `#` line equivalent)
// provenance header to its emitted files. Defaults to true so existing
// projects keep the comment that warns hand-editors. Set
// `outputs.<target>.provenance-header: false` to opt out for a
// byte-stable round-trip from a hand-authored source.
func (c *Config) ProvenanceHeaderEnabled(target string) bool {
	if c == nil {
		return true
	}
	if o, ok := c.Outputs[target]; ok && o.ProvenanceHeader != nil {
		return *o.ProvenanceHeader
	}
	return true
}

// EffectiveCollisionPolicy returns the resolved collision policy for the
// given target. The per-target outputs.<target>.collision-policy wins over
// sync.collision-policy when set; empty values fall back to "prompt".
func (c *Config) EffectiveCollisionPolicy(target string) string {
	if o, ok := c.Outputs[target]; ok && o.CollisionPolicy != "" {
		return o.CollisionPolicy
	}
	if c.Sync.CollisionPolicy != "" {
		return c.Sync.CollisionPolicy
	}
	return "prompt"
}

// Gitignore controls automatic management of .gitignore entries for the
// generated target files. When Enabled, every `sync` run rewrites a
// managed block in `.gitignore` (created if missing) listing every path
// the configured adapters would emit.
type Gitignore struct {
	Enabled bool `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	// Path overrides the .gitignore location relative to the project root.
	Path string `yaml:"path,omitempty"    json:"path,omitempty"`
}

type Sources struct {
	Agents   string `yaml:"agents,omitempty"   json:"agents,omitempty"`
	Skills   string `yaml:"skills,omitempty"   json:"skills,omitempty"`
	Rules    string `yaml:"rules,omitempty"    json:"rules,omitempty"`
	Hooks    string `yaml:"hooks,omitempty"    json:"hooks,omitempty"`
	MCPs     string `yaml:"mcps,omitempty"     json:"mcps,omitempty"`
	Commands string `yaml:"commands,omitempty" json:"commands,omitempty"`
}

// CodexExecPolicy describes one Skylark-flavored `prefix_rule(...)` entry
// emitted into `.codex/rules/default.rules`. Codex CLI consumes that file
// as an exec-policy DSL that allow- or forbid-lists shell command
// prefixes; agnostic-ai users declare the data declaratively in
// `agnostic-ai.yaml` and the codex adapter renders the file.
type CodexExecPolicy struct {
	// Pattern is the shell command prefix tokens, e.g. ["composer", "test"].
	Pattern []string `yaml:"pattern"                 json:"pattern"`
	// Decision is one of "allow", "forbidden", "ask".
	Decision string `yaml:"decision"                json:"decision"`
	// Justification is a free-form comment emitted alongside the rule.
	Justification string `yaml:"justification,omitempty" json:"justification,omitempty"`
	// Match enumerates example commands the rule applies to. Optional;
	// when present they appear as a `# match:` comment block.
	Match []string `yaml:"match,omitempty"         json:"match,omitempty"`
}

type Output struct {
	Dir                  string            `yaml:"dir,omitempty"                      json:"dir,omitempty"`
	File                 string            `yaml:"file,omitempty"                     json:"file,omitempty"`
	RulesFile            string            `yaml:"rules-file,omitempty"               json:"rules-file,omitempty"`
	RulesDir             string            `yaml:"rules-dir,omitempty"                json:"rules-dir,omitempty"`
	MCPFile              string            `yaml:"mcp-file,omitempty"                 json:"mcp-file,omitempty"`
	AgentsDir            string            `yaml:"agents-dir,omitempty"               json:"agents-dir,omitempty"`
	SkillsDir            string            `yaml:"skills-dir,omitempty"               json:"skills-dir,omitempty"`
	InstructionsDir      string            `yaml:"instructions-dir,omitempty"         json:"instructions-dir,omitempty"`
	CommandsDir          string            `yaml:"commands-dir,omitempty"             json:"commands-dir,omitempty"`
	ChatmodesDir         string            `yaml:"chatmodes-dir,omitempty"            json:"chatmodes-dir,omitempty"`
	WorkflowsDir         string            `yaml:"workflows-dir,omitempty"            json:"workflows-dir,omitempty"`
	AssistantsDir        string            `yaml:"assistants-dir,omitempty"           json:"assistants-dir,omitempty"`
	TasksFile            string            `yaml:"tasks-file,omitempty"               json:"tasks-file,omitempty"`
	ConfFile             string            `yaml:"conf-file,omitempty"                json:"conf-file,omitempty"`
	Model                string            `yaml:"model,omitempty"                    json:"model,omitempty"`
	WeakModel            string            `yaml:"weak-model,omitempty"               json:"weak-model,omitempty"`
	MCPDir               string            `yaml:"mcp-dir,omitempty"                  json:"mcp-dir,omitempty"`
	EmitSkillsAsCommands bool              `yaml:"emit-skills-as-commands,omitempty"  json:"emit-skills-as-commands,omitempty"`
	SharedSubagents      *bool             `yaml:"shared-subagents,omitempty"         json:"shared-subagents,omitempty"`
	Settings             *ClaudeSettings   `yaml:"settings,omitempty"                 json:"settings,omitempty"`
	Config               *CodexConfig      `yaml:"config,omitempty"                   json:"config,omitempty"`
	ExecPolicies         []CodexExecPolicy `yaml:"exec-policies,omitempty"            json:"exec-policies,omitempty"`
	ExecPoliciesFile     string            `yaml:"exec-policies-file,omitempty"       json:"exec-policies-file,omitempty"`
	HooksFile            string            `yaml:"hooks-file,omitempty"               json:"hooks-file,omitempty"`
	ProvenanceHeader     *bool             `yaml:"provenance-header,omitempty"        json:"provenance-header,omitempty"`
	CollisionPolicy      string            `yaml:"collision-policy,omitempty"         json:"collision-policy,omitempty"`
}

// ClaudeSettings is the first-class representation of `.claude/settings.json`
// keys that agnostic-ai understands schema-side, rather than treating every
// key as an opaque overlay passthrough. Only the Claude adapter consumes
// this struct today.
//
// Layering at emit time: overlay (captured during `import claude`) is the
// base; non-zero fields here are written on top; the spec-derived `hooks`
// block is written last. So a user can either pin a value declaratively in
// `agnostic-ai.yaml` or leave it inside `.claude/settings.json` and let the
// overlay carry it.
type ClaudeSettings struct {
	Model               string             `yaml:"model,omitempty"               json:"model,omitempty"`
	OutputStyle         string             `yaml:"outputStyle,omitempty"         json:"outputStyle,omitempty"`
	APIKeyHelper        string             `yaml:"apiKeyHelper,omitempty"        json:"apiKeyHelper,omitempty"`
	CleanupPeriodDays   *int               `yaml:"cleanupPeriodDays,omitempty"   json:"cleanupPeriodDays,omitempty"`
	IncludeCoAuthoredBy *bool              `yaml:"includeCoAuthoredBy,omitempty" json:"includeCoAuthoredBy,omitempty"`
	EnabledPlugins      []string           `yaml:"enabledPlugins,omitempty"      json:"enabledPlugins,omitempty"`
	Env                 map[string]string  `yaml:"env,omitempty"                 json:"env,omitempty"`
	StatusLine          *ClaudeStatusLine  `yaml:"statusLine,omitempty"          json:"statusLine,omitempty"`
	Permissions         *ClaudePermissions `yaml:"permissions,omitempty"         json:"permissions,omitempty"`
}

// ClaudeStatusLine mirrors the `statusLine` block of `.claude/settings.json`.
// Claude Code accepts a `type` (today only "command") and a `command`
// string; the optional `padding` field controls leading whitespace.
type ClaudeStatusLine struct {
	Type    string `yaml:"type,omitempty"    json:"type,omitempty"`
	Command string `yaml:"command,omitempty" json:"command,omitempty"`
	Padding *int   `yaml:"padding,omitempty" json:"padding,omitempty"`
}

// ClaudePermissions mirrors the `permissions` block. Each list contains
// tool-pattern strings such as `Read(*)` or `Shell(rm *)`. Claude Code
// silently drops malformed patterns; agnostic-ai passes through verbatim.
type ClaudePermissions struct {
	Allow []string `yaml:"allow,omitempty" json:"allow,omitempty"`
	Deny  []string `yaml:"deny,omitempty"  json:"deny,omitempty"`
	Ask   []string `yaml:"ask,omitempty"   json:"ask,omitempty"`
}

// CodexConfig is the first-class representation of `.codex/config.toml` keys
// that agnostic-ai manages. Only the Codex adapter reads this struct.
//
// These fields are written into the project-tier `.codex/config.toml` on each
// sync. Keys not listed here (e.g. user-specific overrides) belong in the
// user-global `~/.codex/config.toml` which Codex merges last.
type CodexConfig struct {
	Sandbox               string                        `yaml:"sandbox,omitempty"                 json:"sandbox,omitempty"`
	ApprovalPolicy        string                        `yaml:"approval-policy,omitempty"         json:"approval-policy,omitempty"`
	Model                 string                        `yaml:"model,omitempty"                   json:"model,omitempty"`
	ModelReasoningEffort  string                        `yaml:"model-reasoning-effort,omitempty"  json:"model-reasoning-effort,omitempty"`
	ModelReasoningSummary string                        `yaml:"model-reasoning-summary,omitempty" json:"model-reasoning-summary,omitempty"`
	HistoryPersistence    string                        `yaml:"history-persistence,omitempty"     json:"history-persistence,omitempty"`
	Notify                []string                      `yaml:"notify,omitempty"                  json:"notify,omitempty"`
	Profiles              map[string]CodexProfile       `yaml:"profiles,omitempty"                json:"profiles,omitempty"`
	ModelProviders        map[string]CodexModelProvider `yaml:"model-providers,omitempty"         json:"model-providers,omitempty"`
}

// CodexModelProvider mirrors a `[model_providers.<id>]` table in
// `.codex/config.toml`. Each provider declares how Codex talks to a model
// backend (OpenAI-compatible, Azure, Ollama, custom OSS endpoints, ...).
// `Name` and `BaseURL` are usually required; the other fields fill in
// transport details.
type CodexModelProvider struct {
	Name      string `yaml:"name,omitempty"        json:"name,omitempty"`
	BaseURL   string `yaml:"base-url,omitempty"    json:"base-url,omitempty"`
	WireAPI   string `yaml:"wire-api,omitempty"    json:"wire-api,omitempty"`
	APIKeyEnv string `yaml:"api-key-env,omitempty" json:"api-key-env,omitempty"`
	EnvKey    string `yaml:"env-key,omitempty"     json:"env-key,omitempty"`
}

// CodexProfile mirrors a `[profiles.<name>]` table in `.codex/config.toml`.
// Codex resolves a profile by name (`codex --profile work`) and overlays its
// fields on top of the top-level defaults. Empty fields fall through to the
// top-level config.
type CodexProfile struct {
	Model                 string `yaml:"model,omitempty"                   json:"model,omitempty"`
	Sandbox               string `yaml:"sandbox,omitempty"                 json:"sandbox,omitempty"`
	ApprovalPolicy        string `yaml:"approval-policy,omitempty"         json:"approval-policy,omitempty"`
	ModelReasoningEffort  string `yaml:"model-reasoning-effort,omitempty"  json:"model-reasoning-effort,omitempty"`
	ModelReasoningSummary string `yaml:"model-reasoning-summary,omitempty" json:"model-reasoning-summary,omitempty"`
	ModelProvider         string `yaml:"model-provider,omitempty"          json:"model-provider,omitempty"`
}

// Load reads the project config from root. It prefers
// `agnostic-ai.yaml` and falls back to the legacy
// `agnostic.config.yaml` (with a one-shot stderr deprecation warning
// per process). When `agnostic-ai.local.yaml` exists in the same
// directory, it is deep-merged over the base: scalars and slices in
// the local file replace the base, maps merge recursively.
func Load(root string) (*Config, error) {
	cfg, _, err := LoadWithSources(root)
	return cfg, err
}

// LoadWithSources is Load that also reports the files it parsed, in
// load order (base first, local last). Callers that want to surface
// which files were merged (e.g. `sync` summary) use this variant.
func LoadWithSources(root string) (*Config, []string, error) {
	basePath, legacy, err := ResolveConfigPath(root)
	if err != nil {
		return nil, nil, err
	}
	if legacy {
		warnLegacyOnce(basePath)
	}

	localPath := filepath.Join(root, LocalOverrideFileName)
	localExists := fileExists(localPath)

	cfg := defaults()
	if localExists {
		if err := loadAndMerge(cfg, basePath, localPath); err != nil {
			return nil, nil, err
		}
	} else {
		if err := loadInto(cfg, basePath); err != nil {
			return nil, nil, err
		}
	}
	cfg.applyDefaults()

	sources := []string{basePath}
	if localExists {
		sources = append(sources, localPath)
	}
	return cfg, sources, nil
}

// ResolveConfigPath returns the path of the base config file in root.
// It prefers ConfigFileName and falls back to LegacyConfigFileName;
// legacy is true when the fallback won.
func ResolveConfigPath(root string) (path string, legacy bool, err error) {
	primary := filepath.Join(root, ConfigFileName)
	if fileExists(primary) {
		return primary, false, nil
	}
	legacyPath := filepath.Join(root, LegacyConfigFileName)
	if fileExists(legacyPath) {
		return legacyPath, true, nil
	}
	return "", false, errs.Coded(errs.CodeConfigMissing,
		"read config: no %s or %s in %s",
		ConfigFileName, LegacyConfigFileName, root)
}

// loadInto unmarshals path directly into cfg. Used when no local
// override file is present and the map-merge round-trip is wasteful.
func loadInto(cfg *Config, path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if err := yaml.Unmarshal(data, cfg); err != nil {
		return errs.Coded(errs.CodeConfigDecode, "parse %s: %w", path, err)
	}
	return nil
}

// loadAndMerge parses base and local as untyped maps, deep-merges
// local over base, and decodes the result into cfg.
func loadAndMerge(cfg *Config, basePath, localPath string) error {
	base, err := readYAMLMap(basePath)
	if err != nil {
		return err
	}
	local, err := readYAMLMap(localPath)
	if err != nil {
		return err
	}
	deepMerge(base, local)
	data, err := yaml.Marshal(base)
	if err != nil {
		return fmt.Errorf("re-encode merged config: %w", err)
	}
	if err := yaml.Unmarshal(data, cfg); err != nil {
		return errs.Coded(errs.CodeConfigDecode, "parse merged config: %w", err)
	}
	return nil
}

func readYAMLMap(path string) (map[string]any, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	out := map[string]any{}
	if len(data) == 0 {
		return out, nil
	}
	if err := yaml.Unmarshal(data, &out); err != nil {
		return nil, errs.Coded(errs.CodeConfigDecode, "parse %s: %w", path, err)
	}
	return out, nil
}

// deepMerge folds src into dst. Maps merge recursively; scalars and
// slices in src replace dst entirely. Slice concat is intentionally
// not supported: targets and similar lists should be authoritative
// per-layer so override semantics stay obvious.
func deepMerge(dst, src map[string]any) {
	for k, sv := range src {
		if dv, ok := dst[k]; ok {
			dstMap, dstIsMap := dv.(map[string]any)
			srcMap, srcIsMap := sv.(map[string]any)
			if dstIsMap && srcIsMap {
				deepMerge(dstMap, srcMap)
				continue
			}
		}
		dst[k] = sv
	}
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// warnLegacyOnce prints the deprecation warning a single time per
// process per legacy path. Load is called several times in a typical
// sync flow; spamming the same warning is noise.
var legacyWarnedPaths sync.Map

func warnLegacyOnce(path string) {
	if _, loaded := legacyWarnedPaths.LoadOrStore(path, struct{}{}); loaded {
		return
	}
	fmt.Fprintf(os.Stderr,
		"! %s is deprecated. Rename to %s.\n",
		LegacyConfigFileName, ConfigFileName)
}

// DefaultTargets returns the safe out-of-the-box target list. Codex, Amp,
// and Warp all default to the root AGENTS.md per the community spec, but the
// entry-point pointer body is byte-identical across them, so sync writes it
// once (auto-dedup) and enabling more than one does not collide. The default
// still picks only Codex (which also emits .codex/config.toml) and leaves Amp
// and Warp out, since they add no new entry-point. A real collision needs two
// targets to set a conflicting `outputs.<target>.rules-file: AGENTS.md`.
func DefaultTargets() []string {
	return []string{
		"claude", "codex", "gemini", "cursor",
		"copilot", "aider", "cline", "windsurf", "continue",
		"zed", "opencode", "antigravity",
	}
}

func defaults() *Config {
	return &Config{
		Version: 1,
		Sources: Sources{
			Agents:   "agents",
			Skills:   "skills",
			Rules:    "rules",
			Hooks:    "hooks",
			MCPs:     "mcps",
			Commands: "commands",
		},
		Targets:       DefaultTargets(),
		OnUnsupported: "warn",
	}
}

func (c *Config) applyDefaults() {
	if c.Sources.Agents == "" {
		c.Sources.Agents = "agents"
	}
	if c.Sources.Skills == "" {
		c.Sources.Skills = "skills"
	}
	if c.Sources.Rules == "" {
		c.Sources.Rules = "rules"
	}
	if c.Sources.Hooks == "" {
		c.Sources.Hooks = "hooks"
	}
	if c.Sources.MCPs == "" {
		c.Sources.MCPs = "mcps"
	}
	if c.Sources.Commands == "" {
		c.Sources.Commands = "commands"
	}
	if c.OnUnsupported == "" {
		c.OnUnsupported = "warn"
	}
}
