// Generated by agnostic-ai. Do not edit this file directly; edit specs under .agnostic-ai/ and run `agnostic-ai sync`.
import type { Plugin } from "@opencode-ai/plugin"

const MATCHER = new RegExp("^(?:Edit)$")

export const SampleHookPlugin: Plugin = async ({ $ }) => {
  const run = async (cmd: string) => {
    try {
      const r = await $`${{ raw: cmd }}`.nothrow()
      if (r.exitCode !== 0) console.error("agnostic-ai hook sample-hook:", cmd, "exited", r.exitCode)
      return r
    } catch (err) {
      console.error("agnostic-ai hook sample-hook:", cmd, err)
      return undefined
    }
  }

  return {
    "tool.execute.after": async (input) => {
      if (!MATCHER.test(input.tool)) return
      await run("echo edited")
    },
  }
}
