// Package codex emits AGENTS.md hierarchies, .codex/agents/*.toml files,
// and .agents/skills/<name>/ skill folders for the Codex CLI.
//
// The Codex CLI reads AGENTS.md for project conventions and supports
// nested AGENTS.md files in subdirectories that scope to that subtree.
// This adapter routes rules by their globs frontmatter:
//
//   - "src/**"        -> src/AGENTS.md
//   - "docs/api/**"   -> docs/api/AGENTS.md
//   - "**/*"          -> root
//   - "**/*.go"       -> root (no fixed prefix)
//
// Agents emit as one TOML file per agent under .codex/agents/ (override
// via outputs.codex.agents-dir) following the Codex subagents schema.
// The root AGENTS.md keeps a `## Agents` reference section listing each
// agent name, description, and source TOML path so humans browsing the
// document still see what is available.
//
// Skills emit as a folder per skill under .agents/skills/<name>/ (override
// via outputs.codex.skills-dir) per the Codex skills layout. Each folder
// contains a SKILL.md with `name` + `description` frontmatter plus the
// skill body. When the spec provides `x-codex.interface`, `x-codex.policy`,
// or `x-codex.dependencies`, an additional `agents/openai.yaml` is written
// alongside SKILL.md for UI customization and policy declarations.
//
// Codex has no native hook system: hooks are skipped.
package codex

import (
	"path/filepath"
	"sort"
	"strings"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

const (
	target           = "codex"
	defaultOutFile   = "AGENTS.md"
	defaultAgentsDir = ".codex/agents"
	defaultSkillsDir = ".agents/skills"
)

var caps = emit.Capabilities{
	Target: target,
	// Codex consumes agents, rules, and skills (the latter as listings).
	Supports: []spec.Kind{spec.KindAgent, spec.KindRule, spec.KindSkill},
}

// Adapter emits Codex configs.
type Adapter struct{}

// New returns a Codex adapter.
func New() *Adapter { return &Adapter{} }

// Name returns the target identifier.
func (Adapter) Name() string { return target }

// Emit writes the root AGENTS.md, any nested AGENTS.md files implied by
// rule globs, and one .codex/agents/<name>.toml per agent.
func (Adapter) Emit(b spec.Bundle, cfg *config.Config, dryRun bool) error {
	if err := emit.ReportUnsupported(caps, b, cfg.OnUnsupported); err != nil {
		return err
	}

	rootFile := emit.OutputFile(cfg, target, defaultOutFile)
	rootDir := filepath.Dir(rootFile)
	rootBase := filepath.Base(rootFile)
	agentsDir := emit.OutputAgentsDir(cfg, target, defaultAgentsDir)
	skillsDir := emit.OutputSkillsDir(cfg, target, defaultSkillsDir)

	for _, a := range b.Agents {
		path := filepath.Join(agentsDir, a.Name+".toml")
		if err := emit.WriteFile(path, agentTOML(a), dryRun); err != nil {
			return err
		}
	}

	for _, s := range b.Skills {
		if err := emitSkill(s, skillsDir, dryRun); err != nil {
			return err
		}
	}

	byDir := emit.GroupRulesByScope(b.Rules)

	dirs := sortedKeys(byDir)
	if !contains(dirs, "") && (len(b.Agents) > 0 || len(b.Skills) > 0) {
		dirs = append([]string{""}, dirs...)
	}

	for _, dir := range dirs {
		var sb strings.Builder
		writeHeader(&sb, dir)
		writeRules(&sb, byDir[dir])
		if dir == "" {
			writeAgents(&sb, b.Agents, agentsDir)
			writeSkills(&sb, b.Skills, skillsDir)
		}
		path := filepath.Join(rootDir, dir, rootBase)
		if err := emit.WriteFile(path, sb.String(), dryRun); err != nil {
			return err
		}
	}
	return nil
}

func writeHeader(sb *strings.Builder, dir string) {
	if dir == "" {
		sb.WriteString("# AGENTS.md\n\n")
	} else {
		sb.WriteString("# AGENTS.md (" + dir + ")\n\n")
		sb.WriteString("Scoped to `" + dir + "/**`. Inherits root rules.\n\n")
	}
	sb.WriteString("Generated by agnostic-ai. Do not edit by hand.\n\n")
}

func writeRules(sb *strings.Builder, rules []spec.Entry) {
	if len(rules) == 0 {
		return
	}
	sb.WriteString("## Conventions\n\n")
	for _, r := range rules {
		emit.WriteSection(sb, r.Name, r)
	}
}

// writeAgents renders a reference listing of agents in AGENTS.md. The
// real definitions live in <agentsDir>/<name>.toml; this section just
// helps humans see what is available without reading the TOML files.
func writeAgents(sb *strings.Builder, agents []spec.Entry, agentsDir string) {
	if len(agents) == 0 {
		return
	}
	sb.WriteString("## Agents\n\n")
	sb.WriteString("Custom Codex subagents. Definitions live in `" + agentsDir + "/`.\n\n")
	for _, a := range agents {
		sb.WriteString("### " + a.Name + "\n\n")
		sb.WriteString(emit.SourceComment(a.Path))
		if d := a.Description(); d != "" {
			sb.WriteString("_" + d + "_\n\n")
		}
		sb.WriteString("Source: `" + filepath.ToSlash(filepath.Join(agentsDir, a.Name+".toml")) + "`\n\n")
	}
}

// writeSkills renders a reference listing of skills in AGENTS.md. Each
// skill emits as its own folder under skillsDir per the Codex skills
// layout; this section just helps humans see what is available without
// browsing the directory.
func writeSkills(sb *strings.Builder, skills []spec.Entry, skillsDir string) {
	if len(skills) == 0 {
		return
	}
	sb.WriteString("## Skills\n\n")
	sb.WriteString("Codex skills. Definitions live in `" + skillsDir + "/<name>/SKILL.md`.\n\n")
	for _, s := range skills {
		sb.WriteString("### " + s.Name + "\n\n")
		sb.WriteString(emit.SourceComment(s.Path))
		if d := s.Description(); d != "" {
			sb.WriteString("_" + d + "_\n\n")
		}
		sb.WriteString("Source: `" + filepath.ToSlash(filepath.Join(skillsDir, s.Name, "SKILL.md")) + "`\n\n")
	}
}

func sortedKeys(m map[string][]spec.Entry) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func contains(ss []string, s string) bool {
	for _, x := range ss {
		if x == s {
			return true
		}
	}
	return false
}
