// Package codex emits AGENTS.md hierarchies and .codex/agents/*.toml
// files for the Codex CLI.
//
// The Codex CLI reads AGENTS.md for project conventions and supports
// nested AGENTS.md files in subdirectories that scope to that subtree.
// This adapter routes rules by their globs frontmatter:
//
//   - "src/**"        -> src/AGENTS.md
//   - "docs/api/**"   -> docs/api/AGENTS.md
//   - "**/*"          -> root
//   - "**/*.go"       -> root (no fixed prefix)
//
// Agents emit as one TOML file per agent under .codex/agents/ (override
// via outputs.codex.agents-dir) following the Codex subagents schema.
// The root AGENTS.md keeps a `## Agents` reference section listing each
// agent name, description, and source TOML path so humans browsing the
// document still see what is available.
//
// Codex has no native skill or hook systems: skills are listed by name +
// source path; hooks are skipped.
package codex

import (
	"path/filepath"
	"sort"
	"strings"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

const (
	target           = "codex"
	defaultOutFile   = "AGENTS.md"
	defaultAgentsDir = ".codex/agents"
)

var caps = emit.Capabilities{
	Target: target,
	// Codex consumes agents, rules, and skills (the latter as listings).
	Supports: []spec.Kind{spec.KindAgent, spec.KindRule, spec.KindSkill},
}

// Adapter emits Codex configs.
type Adapter struct{}

// New returns a Codex adapter.
func New() *Adapter { return &Adapter{} }

// Name returns the target identifier.
func (Adapter) Name() string { return target }

// Emit writes the root AGENTS.md, any nested AGENTS.md files implied by
// rule globs, and one .codex/agents/<name>.toml per agent.
func (Adapter) Emit(b spec.Bundle, cfg *config.Config, dryRun bool) error {
	if err := emit.ReportUnsupported(caps, b, cfg.OnUnsupported); err != nil {
		return err
	}

	rootFile := emit.OutputFile(cfg, target, defaultOutFile)
	rootDir := filepath.Dir(rootFile)
	rootBase := filepath.Base(rootFile)
	agentsDir := emit.OutputAgentsDir(cfg, target, defaultAgentsDir)

	for _, a := range b.Agents {
		path := filepath.Join(agentsDir, a.Name+".toml")
		if err := emit.WriteFile(path, agentTOML(a), dryRun); err != nil {
			return err
		}
	}

	byDir := groupRulesByDir(b.Rules)

	dirs := sortedKeys(byDir)
	if !contains(dirs, "") && (len(b.Agents) > 0 || len(b.Skills) > 0) {
		dirs = append([]string{""}, dirs...)
	}

	for _, dir := range dirs {
		var sb strings.Builder
		writeHeader(&sb, dir)
		writeRules(&sb, byDir[dir])
		if dir == "" {
			writeAgents(&sb, b.Agents, agentsDir)
			writeSkills(&sb, b.Skills)
		}
		path := filepath.Join(rootDir, dir, rootBase)
		if err := emit.WriteFile(path, sb.String(), dryRun); err != nil {
			return err
		}
	}
	return nil
}

func groupRulesByDir(rules []spec.Entry) map[string][]spec.Entry {
	out := map[string][]spec.Entry{}
	for _, r := range rules {
		out[routeDir(r)] = append(out[routeDir(r)], r)
	}
	return out
}

// routeDir returns the subdirectory to route a rule to. Source-layout
// scope (e.g. `rules/backend/auth.md` -> `backend`) wins over globs,
// since it is explicit. Globs are still parsed as a fallback for rules
// authored without nested layout.
func routeDir(r spec.Entry) string {
	if s := r.EffectiveScope(); s != "" {
		return s
	}
	g := strings.TrimPrefix(r.Globs(), "/")
	if g == "" || g == "**/*" || g == "*" {
		return ""
	}
	var prefix []string
	for _, p := range strings.Split(g, "/") {
		if strings.ContainsAny(p, "*?[") {
			break
		}
		prefix = append(prefix, p)
	}
	return strings.Join(prefix, "/")
}

func writeHeader(sb *strings.Builder, dir string) {
	if dir == "" {
		sb.WriteString("# AGENTS.md\n\n")
	} else {
		sb.WriteString("# AGENTS.md (" + dir + ")\n\n")
		sb.WriteString("Scoped to `" + dir + "/**`. Inherits root rules.\n\n")
	}
	sb.WriteString("Generated by agnostic-ai. Do not edit by hand.\n\n")
}

func writeRules(sb *strings.Builder, rules []spec.Entry) {
	if len(rules) == 0 {
		return
	}
	sb.WriteString("## Conventions\n\n")
	for _, r := range rules {
		emit.WriteSection(sb, r.Name, r)
	}
}

// writeAgents renders a reference listing of agents in AGENTS.md. The
// real definitions live in <agentsDir>/<name>.toml; this section just
// helps humans see what is available without reading the TOML files.
func writeAgents(sb *strings.Builder, agents []spec.Entry, agentsDir string) {
	if len(agents) == 0 {
		return
	}
	sb.WriteString("## Agents\n\n")
	sb.WriteString("Custom Codex subagents. Definitions live in `" + agentsDir + "/`.\n\n")
	for _, a := range agents {
		sb.WriteString("### " + a.Name + "\n\n")
		sb.WriteString(emit.SourceComment(a.Path))
		if d := a.Description(); d != "" {
			sb.WriteString("_" + d + "_\n\n")
		}
		sb.WriteString("Source: `" + filepath.ToSlash(filepath.Join(agentsDir, a.Name+".toml")) + "`\n\n")
	}
}

func writeSkills(sb *strings.Builder, skills []spec.Entry) {
	if len(skills) == 0 {
		return
	}
	sb.WriteString("## Skills\n\n")
	sb.WriteString("Codex has no native skills. The following are available as reference; invoke them by reading the source file.\n\n")
	for _, s := range skills {
		sb.WriteString("### " + s.Name + "\n\n")
		sb.WriteString(emit.SourceComment(s.Path))
		if d := s.Description(); d != "" {
			sb.WriteString("_" + d + "_\n\n")
		}
		sb.WriteString("Source: `" + s.Path + "`\n\n")
	}
}

func sortedKeys(m map[string][]spec.Entry) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func contains(ss []string, s string) bool {
	for _, x := range ss {
		if x == s {
			return true
		}
	}
	return false
}
