package codex

import (
	"maps"
	"slices"
	"strings"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

// renderConfigTOML builds the `.codex/config.toml` body from the bundle's
// hook and MCP entries. Each MCP entry emits as a `[mcp_servers.<name>]`
// table; each hook entry emits as an `[[hooks.<event>]]` array-of-tables
// element. Returns "" when there is no valid output to write (e.g. all
// hooks lack an `event` and no MCP entries).
func renderConfigTOML(hooks, mcps []spec.Entry) string {
	byEvent := groupHooksByEvent(hooks)
	if len(byEvent) == 0 && !anyNamedMCP(mcps) {
		return ""
	}
	var sb strings.Builder
	sb.WriteString("# Generated by agnostic-ai. Do not edit by hand.\n\n")

	writeMCPServers(&sb, mcps)
	writeHookSectionsFromMap(&sb, byEvent)
	return sb.String()
}

func anyNamedMCP(mcps []spec.Entry) bool {
	for _, m := range mcps {
		if m.Name != "" {
			return true
		}
	}
	return false
}

func writeMCPServers(sb *strings.Builder, mcps []spec.Entry) {
	// Sort by name for deterministic output.
	sorted := append([]spec.Entry(nil), mcps...)
	slices.SortFunc(sorted, func(a, b spec.Entry) int { return strings.Compare(a.Name, b.Name) })
	for _, m := range sorted {
		if m.Name == "" {
			continue
		}
		writeMCPServerTable(sb, m)
	}
}

// writeMCPServerTable emits one `[mcp_servers.<name>]` table with the
// transport-appropriate keys.
func writeMCPServerTable(sb *strings.Builder, m spec.Entry) {
	sb.WriteString("[mcp_servers." + m.Name + "]\n")

	transport, _ := m.Meta["type"].(string)
	if transport == "" {
		transport = "stdio"
	}
	switch transport {
	case "stdio":
		if cmd, _ := m.Meta["command"].(string); cmd != "" {
			emit.WriteTOMLString(sb, "command", cmd)
		}
		if args := emit.StringSlice(m.Meta["args"]); len(args) > 0 {
			emit.WriteTOMLStringArray(sb, "args", args)
		}
		emit.WriteTOMLInlineStringTable(sb, "env", emit.StringMap(m.Meta["env"]))
	case "http", "sse":
		if url, _ := m.Meta["url"].(string); url != "" {
			emit.WriteTOMLString(sb, "url", url)
		}
		if t, _ := m.Meta["bearer_token_env_var"].(string); t != "" {
			emit.WriteTOMLString(sb, "bearer_token_env_var", t)
		}
		emit.WriteTOMLInlineStringTable(sb, "http_headers", emit.StringMap(m.Meta["headers"]))
	}
	sb.WriteString("\n")
}

func writeHookSectionsFromMap(sb *strings.Builder, byEvent map[string][]spec.Entry) {
	for _, event := range slices.Sorted(maps.Keys(byEvent)) {
		for _, h := range byEvent[event] {
			writeHookSection(sb, event, h)
		}
	}
}

func groupHooksByEvent(hooks []spec.Entry) map[string][]spec.Entry {
	out := map[string][]spec.Entry{}
	for _, h := range hooks {
		event, _ := h.Meta["event"].(string)
		if event == "" {
			continue
		}
		out[event] = append(out[event], h)
	}
	return out
}

func writeHookSection(sb *strings.Builder, event string, h spec.Entry) {
	sb.WriteString("[[hooks." + event + "]]\n")
	if matcher, _ := h.Meta["matcher"].(string); matcher != "" {
		emit.WriteTOMLString(sb, "matcher", matcher)
	}
	if cmd, _ := h.Meta["command"].(string); cmd != "" {
		emit.WriteTOMLString(sb, "command", cmd)
	}
	sb.WriteString("\n")
}
