package codex

import (
	"fmt"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/chemaclass/agnostic-ai/internal/adapters/internal/emit"
	"github.com/chemaclass/agnostic-ai/internal/spec"
)

// openaiYAMLKeys are the top-level fields the Codex CLI reads from
// `<skill>/agents/openai.yaml`. Only these pass through; anything else
// under `x-codex` is ignored to keep the emitted file faithful to the
// documented schema.
var openaiYAMLKeys = []string{"interface", "policy", "dependencies"}

// emitSkill writes the per-skill folder layout for the Codex CLI:
//
//	<skillsDir>/<name>/
//	  SKILL.md           (required, frontmatter + body)
//	  agents/openai.yaml (optional, when x-codex provides UI/policy/deps)
//
// The SKILL.md frontmatter is reduced to the two fields Codex requires
// (`name`, `description`) so the file stays valid against the published
// schema regardless of what extra metadata the source spec carries.
func emitSkill(s spec.Entry, skillsDir string, dryRun bool) error {
	folder := filepath.Join(skillsDir, s.Name)

	if err := emit.WriteFile(filepath.Join(folder, "SKILL.md"), skillMarkdown(s), dryRun); err != nil {
		return err
	}

	if yamlBody := openaiYAML(s); yamlBody != "" {
		if err := emit.WriteFile(filepath.Join(folder, "agents", "openai.yaml"), yamlBody, dryRun); err != nil {
			return err
		}
	}
	return nil
}

func skillMarkdown(s spec.Entry) string {
	desc := s.Description()
	if desc == "" {
		desc = s.Name
	}
	front := emit.Frontmatter(map[string]any{
		"name":        s.Name,
		"description": desc,
	})
	body := strings.TrimSpace(s.Body)
	if body == "" {
		return front + "\n"
	}
	return front + "\n" + body + "\n"
}

// openaiYAML returns the YAML body for the optional agents/openai.yaml
// file, or "" when the spec carries no Codex-specific UI, policy, or
// dependency overrides.
func openaiYAML(s spec.Entry) string {
	x, ok := s.Meta["x-codex"].(map[string]any)
	if !ok || len(x) == 0 {
		return ""
	}
	out := map[string]any{}
	for _, k := range openaiYAMLKeys {
		if v, ok := x[k]; ok {
			out[k] = v
		}
	}
	if len(out) == 0 {
		return ""
	}
	data, err := yaml.Marshal(out)
	if err != nil {
		return ""
	}
	return fmt.Sprintf("# Generated by agnostic-ai. Do not edit by hand.\n%s", data)
}
