// Generated by agnostic-ai. Do not edit this file directly; edit specs under .agnostic-ai/ and run `agnostic-ai sync`.
import type { Plugin } from "@kilocode/plugin"

const FmtGoPlugin: Plugin = async ({ $ }) => {
  return {
    "tool.execute.after": async (input) => {
      if (!new RegExp("edit").test(input.tool)) return
      await $`gofmt -w .`
    },
  }
}

export default { id: "fmt-go", server: FmtGoPlugin }
