// Generated by agnostic-ai. Do not edit this file directly; edit specs under .agnostic-ai/ and run `agnostic-ai sync`.
import type { Plugin } from "@kilocode/plugin"

const MATCHER = new RegExp("^(?:edit)$")

const FmtGoPlugin: Plugin = async ({ $ }) => {
  return {
    "tool.execute.after": async (input) => {
      if (!MATCHER.test(input.tool)) return
      await $`${{ raw: "gofmt -w ." }}`.nothrow()
    },
  }
}

export default { id: "fmt-go", server: FmtGoPlugin }
