// Generated by agnostic-ai. Do not edit this file directly; edit specs under .agnostic-ai/ and run `agnostic-ai sync`.
import type { Plugin } from "@kilocode/plugin"

const NotifyIdlePlugin: Plugin = async ({ $ }) => {
  const run = async (cmd: string) => {
    try {
      const r = await $`${{ raw: cmd }}`.env({ ...process.env, AGNOSTIC_AI_TARGET: "kilo" }).nothrow()
      if (r.exitCode !== 0) console.error("agnostic-ai hook notify-idle:", cmd, "exited", r.exitCode)
      return r
    } catch (err) {
      console.error("agnostic-ai hook notify-idle:", cmd, err)
      return undefined
    }
  }

  return {
    event: async ({ event }) => {
      if (event.type !== "session.idle") return
      await run("echo done")
    },
  }
}

export default { id: "notify-idle", server: NotifyIdlePlugin }
