// Generated by agnostic-ai. Do not edit this file directly; edit specs under .agnostic-ai/ and run `agnostic-ai sync`.
import type { Plugin } from "@opencode-ai/plugin"

export const NotifyIdlePlugin: Plugin = async ({ $ }) => {
  return {
    event: async ({ event }) => {
      if (event.type !== "session.idle") return
      await $`${{ raw: "echo done" }}`.nothrow()
    },
  }
}
