package opencode

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chemaclass/agnostic-ai/internal/config"
	"github.com/chemaclass/agnostic-ai/internal/spec"
	"github.com/chemaclass/agnostic-ai/internal/testutil"
)

func TestName(t *testing.T) {
	if got := New().Name(); got != "opencode" {
		t.Errorf("Name() = %q, want %q", got, "opencode")
	}
}

// Command specs emit one markdown file per command under
// .opencode/commands/, the native slash-prompt surface.
func TestEmit_WritesCommandFile(t *testing.T) {
	dir := testutil.TempCwd(t)
	b := spec.NewBundle([]spec.Entry{
		{Kind: spec.KindCommand, Name: "deploy", Path: "commands/deploy.md", Meta: map[string]any{"description": "Ship it"}, Body: "Run the deploy steps."},
	})
	if err := New().Emit(b, &config.Config{}, false); err != nil {
		t.Fatalf("emit: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(dir, ".opencode", "commands", "deploy.md"))
	if err != nil {
		t.Fatalf("read command file: %v", err)
	}
	got := string(data)
	for _, want := range []string{"description: Ship it", "Run the deploy steps.", "Generated by agnostic-ai"} {
		if !strings.Contains(got, want) {
			t.Errorf("command file missing %q:\n%s", want, got)
		}
	}
}

func TestEmit_NoAgentsMd_ByDefault(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Path: "rules/r1.md", Body: "rule body"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".opencode/AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("adapter should not write .opencode/AGENTS.md by default; sync owns the entry-point, err=%v", err)
	}
}

func TestEmit_LegacyRulesFile_WritesConcatenated(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"opencode": {RulesFile: ".opencode/AGENTS.md"}},
	}
	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Path: "rules/r1.md", Body: "rule body"},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".opencode/AGENTS.md"))
	if !strings.Contains(got, "rule body") {
		t.Errorf("legacy rules-file should contain concatenated rule body:\n%s", got)
	}
}

// Each agent writes one command file under .opencode/commands/ with
// description frontmatter (required by OpenCode).
// Agents emit natively as one markdown per agent under .opencode/agents/,
// OpenCode's subagent surface, not as slash commands.
func TestEmit_Agent_WritesNativeAgentFile(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent,
			Name: "pr-reviewer",
			Meta: map[string]any{"description": "Review PRs like an owner."},
			Body: "Open the PR. Read it. Comment.",
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".opencode/agents/pr-reviewer.md"))
	for _, want := range []string{
		"---",
		"description: Review PRs like an owner.",
		"Open the PR. Read it. Comment.",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, ".opencode/commands/pr-reviewer.md")); !os.IsNotExist(err) {
		t.Errorf("agents must not emit as commands anymore, err=%v", err)
	}
}

// x-opencode.{mode,model,temperature,permission} pass through into the
// native agent frontmatter.
func TestEmit_Agent_XOpencodePassesThrough(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent,
			Name: "ag1",
			Meta: map[string]any{
				"description": "Do thing.",
				"x-opencode": map[string]any{
					"mode":        "subagent",
					"model":       "openai/gpt-5",
					"temperature": 0.2,
				},
			},
			Body: "body",
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".opencode/agents/ag1.md"))
	for _, want := range []string{
		"description: Do thing.",
		"mode: subagent",
		"model: openai/gpt-5",
		"temperature: 0.2",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

// Unrelated frontmatter keys (and the x- nested map itself) don't leak
// into the command frontmatter.
func TestEmit_Agent_OnlyAllowedFrontmatterKeys(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindAgent,
			Name: "ag",
			Meta: map[string]any{
				"description": "x",
				"name":        "ag",
				"globs":       "src/**",
				"tools":       []any{"Read"},
				"x-opencode":  map[string]any{"mode": "subagent"},
			},
			Body: "body",
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".opencode/agents/ag.md"))
	for _, leaked := range []string{"globs:", "tools:", "name:", "x-opencode:"} {
		if strings.Contains(got, leaked) {
			t.Errorf("unexpected leaked frontmatter %q in %s", leaked, got)
		}
	}
}

// Skills emit no command file by default.
func TestEmit_Skill_NoCommandByDefault(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindSkill,
			Name: "yaml-validator",
			Path: "skills/yaml-validator.md",
			Meta: map[string]any{"description": "Validate YAML."},
			Body: "Body content.",
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".opencode/commands/yaml-validator.md")); !os.IsNotExist(err) {
		t.Errorf("expected no skill command file by default, err=%v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".opencode/commands/skill-yaml-validator.md")); !os.IsNotExist(err) {
		t.Errorf("expected no prefixed skill command file by default, err=%v", err)
	}
}

// Skills emit as command files when emit-skills-as-commands is on.
func TestEmit_Skill_EmitsCommand_WhenOptIn(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"opencode": {EmitSkillsAsCommands: true},
		},
	}
	entries := []spec.Entry{
		{
			Kind: spec.KindSkill,
			Name: "yaml-validator",
			Meta: map[string]any{"description": "Validate YAML."},
			Body: "Validate against schema.",
		},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	cmd := readFile(t, filepath.Join(dir, ".opencode/commands/skill-yaml-validator.md"))
	for _, want := range []string{
		"description: Validate YAML.",
		"Validate against schema.",
	} {
		if !strings.Contains(cmd, want) {
			t.Errorf("missing %q in %s", want, cmd)
		}
	}
}

// A custom key under x-opencode beyond the documented allowlist reaches
// the command frontmatter; shared top-level keys stay stripped. See #367.
func TestEmit_Skill_CustomXOpencodeKeyReachesFrontmatter(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"opencode": {EmitSkillsAsCommands: true},
		},
	}
	entries := []spec.Entry{
		{
			Kind: spec.KindSkill,
			Name: "yaml-validator",
			Meta: map[string]any{
				"description": "Validate YAML.",
				"globs":       "src/**",
				"x-opencode":  map[string]any{"some-opencode-key": "manual"},
			},
			Body: "Validate against schema.",
		},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	cmd := readFile(t, filepath.Join(dir, ".opencode/commands/skill-yaml-validator.md"))
	if !strings.Contains(cmd, "some-opencode-key: manual") {
		t.Errorf("missing custom x-opencode key in %s", cmd)
	}
	if strings.Contains(cmd, "globs:") {
		t.Errorf("shared top-level key leaked into %s", cmd)
	}
}

func TestEmit_CommandsDirOverride(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"opencode": {CommandsDir: "vendor/oc/commands"},
		},
	}
	entries := []spec.Entry{
		{Kind: spec.KindCommand, Name: "deploy", Meta: map[string]any{"description": "x"}, Body: "x"},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "vendor/oc/commands/deploy.md")); err != nil {
		t.Errorf("expected override path written: %v", err)
	}
}

// Stdio MCP emits to opencode.json with type=local + command array.
func TestEmit_MCP_StdioWritesLocalCommand(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "fs",
			Meta: map[string]any{
				"command": "npx",
				"args":    []any{"-y", "@modelcontextprotocol/server-filesystem", "."},
				"env":     map[string]any{"ALLOWED_PATHS": "."},
			},
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, "opencode.json"))
	for _, want := range []string{
		`"$schema": "https://opencode.ai/config.json"`,
		`"mcp"`,
		`"fs"`,
		`"type": "local"`,
		`"npx"`,
		`"@modelcontextprotocol/server-filesystem"`,
		`"environment"`,
		`"ALLOWED_PATHS"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

func TestEmit_MCP_HTTPWritesRemoteURL(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindMCP,
			Name: "linear",
			Meta: map[string]any{
				"type":    "http",
				"url":     "https://mcp.linear.app",
				"headers": map[string]any{"Authorization": "Bearer x"},
			},
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, "opencode.json"))
	for _, want := range []string{
		`"type": "remote"`,
		`"url": "https://mcp.linear.app"`,
		`"Authorization"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

// User-managed keys in an existing opencode.json survive the sync.
func TestEmit_MCP_PreservesExistingUserKeys(t *testing.T) {
	dir := testutil.TempCwd(t)

	existing := `{"theme": "dark", "model": "claude-opus-4-7"}`
	if err := os.WriteFile(filepath.Join(dir, "opencode.json"), []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := []spec.Entry{
		{Kind: spec.KindMCP, Name: "fs", Meta: map[string]any{"command": "x"}},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, "opencode.json"))
	for _, want := range []string{
		`"theme": "dark"`,
		`"model": "claude-opus-4-7"`,
		`"mcp"`,
		`"fs"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in %s", want, got)
		}
	}
}

func TestEmit_MCP_FileOverride(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{
			"opencode": {MCPFile: "vendor/opencode.json"},
		},
	}
	entries := []spec.Entry{
		{Kind: spec.KindMCP, Name: "fs", Meta: map[string]any{"command": "x"}},
	}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "vendor/opencode.json")); err != nil {
		t.Errorf("expected override path written: %v", err)
	}
}

func TestEmit_MCP_NoFileWhenNoEntries(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{Kind: spec.KindRule, Name: "r1", Body: "x"},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "opencode.json")); !os.IsNotExist(err) {
		t.Errorf("expected no opencode.json when no MCP entries, err=%v", err)
	}
}

func TestEmit_EmptyBundle_WritesNothing(t *testing.T) {
	dir := testutil.TempCwd(t)

	if err := New().Emit(spec.NewBundle(nil), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, ".opencode/AGENTS.md")); !os.IsNotExist(err) {
		t.Errorf("expected no AGENTS.md for empty bundle, err=%v", err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}

// Skills emit natively as one folder per skill under .opencode/skills/,
// without any opt-in; the command form stays opt-in on top.
func TestEmit_Skill_WritesNativeSkillFolder(t *testing.T) {
	dir := testutil.TempCwd(t)

	entries := []spec.Entry{
		{
			Kind: spec.KindSkill,
			Name: "deploy",
			Meta: map[string]any{"description": "Run deployments."},
			Body: "Deploy to production.",
		},
	}
	if err := New().Emit(spec.NewBundle(entries), &config.Config{}, false); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, filepath.Join(dir, ".opencode/skills/deploy/SKILL.md"))
	for _, want := range []string{"name: deploy", "description: Run deployments.", "Deploy to production."} {
		if !strings.Contains(got, want) {
			t.Errorf("SKILL.md missing %q:\n%s", want, got)
		}
	}
}

func TestEmit_Skill_SkillsDirOverride(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"opencode": {SkillsDir: "custom/skills"}},
	}
	entries := []spec.Entry{{Kind: spec.KindSkill, Name: "deploy", Body: "body"}}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "custom/skills/deploy/SKILL.md")); err != nil {
		t.Errorf("expected custom/skills/deploy/SKILL.md: %v", err)
	}
}

func TestEmit_Agent_AgentsDirOverride(t *testing.T) {
	dir := testutil.TempCwd(t)

	cfg := &config.Config{
		Outputs: map[string]config.Output{"opencode": {AgentsDir: "custom/agents"}},
	}
	entries := []spec.Entry{{Kind: spec.KindAgent, Name: "ag", Body: "body"}}
	if err := New().Emit(spec.NewBundle(entries), cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "custom/agents/ag.md")); err != nil {
		t.Errorf("expected custom/agents/ag.md: %v", err)
	}
}
